### ISSUE TITLE
Monolog set timezone UTC to all logs

### ISSUE THREAD

**Issue by apoorva-shah** [Seldaek/monolog#1003]
I have changed timezone in processor.  (http://symfony.com/doc/2.8/logging/processors.html)

But it only change timezone for main handler. Even my extra data from here are not added in logs. Please guide.
Not for all handler defination. So what should i do?

**So i want to register my processor globally. Please guide.**
  
```
public function processRecord(array $record)
{
        if (null === $this->token) {
            try {
                $this->token = $this->session->getId();
            } catch (\RuntimeException $e) {
                $this->token = '????????';
            }
            $this->token .= '-' . substr(uniqid('log', true), -8);
        }
        $record['extra']['token'] = $this->token;

        $dateTimeObj = $record['datetime'];

        $dateTimeObj->setTimezone(new \DateTimeZone('UTC'));

        $record['datetime'] = $dateTimeObj;

        return $record;
}
```

**Comment by Seldaek** [comment]
I don't know how you configured it.. kind of lacking info to be able to help you.
