### ISSUE TITLE
RotatingFileHandler doesn't rotate files sometimes when wrapped with FingersCrossedHandler

### ISSUE THREAD

**Issue by m00t** [Seldaek/monolog#1004]
The problem is that `RotatingFileHandler::__destruct()` is called before `FingersCrossedHandler::__destruct()`, but it writes data only on `FingersCrossedHandler::__destruct()`. And it checks whether it should rotate or not on `write`. So it is basically this pseudocode in this sequence:
```
// RotatingFileHandler::__destruct()
if (shouldRotate) rotate() // shouldRotate === null

// FingersCrossedHandler::__destruct() -> RotatingFileHandler::handleBatch()
shouldRotate = !file_exists(newFile) // shouldRotate === true
```

**Comment by Seldaek** [comment]
Not sure what we can do about this tbh :/ Also not sure I quite understand from your pseudo code how it would go wrong, as far as I can tell from the code it would maybe rotate twice, but not fail to rotate?
