### ISSUE TITLE
LevelMap Override Problem with Exceptions

### ISSUE THREAD

**Issue by sfatula** [Seldaek/monolog#1005]
The default exception level map includes class "Throwable" and essentially combines the passed level map to method registerExceptionHandler with the default. This might otherwise work, but, the problem is Throwable. So, in this case, I wanted to override TypeError and make it critical. The array_replace adds the TypeError to the end of the list. The problem with that is Throwable matches TypeError or any other error type as far as I can tell. So, it never gets to the override since it's after Throwable in the array. Therefore, registerExceptionHandler is of no use as is.

**Comment by Seldaek** [comment]
Seems absolutely right.. Should be fixed now
