### ISSUE TITLE
Need throw Socket RuntimeException out

### ISSUE THREAD

**Issue by everCyan** [Seldaek/monolog#1007]
When I user monolog SocketHandler to send udp log, sometimes this error come..
`End-of-file reached, probably we got disconnected (sent $sent of $length)`

And I find it in /src/Monolog/Handler/SocketHandler.php
`    
protected function write(array $record)
    {
        $this->connectIfNotConnected();
        $data = $this->generateDataStream($record);
        $this->writeToSocket($data);
    }
`
I think if you can throw this error on $this->writeToSocket to outside, so I can catch and ignore it in my code.
Thank you!

**Comment by Seldaek** [comment]
You can use WhatFailureGroupHandler around your handler if you'd like to ignore errors like these.
