### ISSUE TITLE
Is there a way to return promise of logging?

### ISSUE THREAD

**Issue by PatchRanger** [Seldaek/monolog#1013]
### Problem
Everybody knows that file system operation could be quite slow.
In case if there is complex logic with plenty of "events" and "hooks" - there could be a lot of log writing operations, which as a whole could give significant performance decrease.

Is there a way to return promise instead of real logging? In order to keep the order of log items, we could chain them together using `then`.

**Comment by Seldaek** [comment]
The best way to do this is probably to use a BufferHandler so you can delay the writing to a later point (call flush manually or let it happen at the end of the request).
