### ISSUE TITLE
[doubt] Is 'string' an incorrect typehint of $message?

### ISSUE THREAD

**Issue by holtkamp** [Seldaek/monolog#1014]
Currently both the PSR-3 Log standard and this Monolog library use PHPDoc to 'typehint' the message variable as a string:

- [PSR-3](https://github.com/php-fig/log/blob/4ebe3a8bf773a19edfe0a84b6585ba3d401b724d/Psr/Log/LoggerInterface.php#L106)
- [Monolog](https://github.com/Seldaek/monolog/blob/7b992836275e09ed63c63fe33ca9993e515e6c5d/src/Monolog/Logger.php#L416)

While [the standard states](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#12-message):

> "Every method accepts a string as the message, or an object with a __toString() method. Implementors MAY have special handling for the passed objects. If that is not the case, implementors MUST cast it to a string."

[and](https://github.com/php-fig/log/blob/4ebe3a8bf773a19edfe0a84b6585ba3d401b724d/Psr/Log/LoggerInterface.php#L8)
> "The message MUST be a string or object implementing __toString()."

So I was wondering: should the PHPDoc typehint than not be:

- `@param string | object $message`
And maybe even to also suggest primitive types like `int` and `float` are not prohibited
- `@param mixed $message`

**Comment by Seldaek** [comment]
In PHP7 if you pass an object to a string arg it gets stringified actually so I think it's fine to say the arg is of type string, e.g. https://3v4l.org/o6UG4

**Comment by holtkamp** [comment]
>In PHP7 if you pass an object to a string arg it gets stringified

True, but still it is an object that is handed over to the function. So the function is "accepting" an object... And appartently it also accepts `int` and `float`..

Let's turn it around: why would we **not** change it to `@param mixed $message` ? The whole purpose of PHPDoc is to clarify right?

Just my 2 cents of course 😄

**Comment by Seldaek** [comment]
Well no the function accepts a string, php accepts other stuff as valid "string" arguments. The same can be told of all php internal functions for example that are documented as accepting strings.

**Comment by holtkamp** [comment]
Aah, ok, thanks for explaining. 

Apparently II have always "read" / understood it like "_must_ be a string"...

**Comment by Seldaek** [comment]
It must be a string if you enable strict_types, otherwise PHP's type juggling rules apply
