### ISSUE TITLE
Formatters: `format` signature incompatible with `normalize` signature

### ISSUE THREAD

**Issue by cutesquirrel** [Seldaek/monolog#1015]
The `format` wait for an array (it's mandatory)
The `normalize` signature is more permissive, and hopefully, because there are `instanceof` tests in it
But format method calls `normalize`, so the `$record` is converted everytime to an array, and the `instanceof` tests aren't used anymore.

I have a case in Drupal8, with an `Exception` and its huge stacktrace. As the exception is convert to an array, there is an infinite loop or something like that because the `normalize` tests aren't used, only the if `is_array($data)`. (By the way, it needs a protection system, as suggested by #924)

What could we do to change that ?
Many thanks !

Example on `LineFormatter.php`:
````
   /**
     * {@inheritdoc}
     */
    public function format(array $record)
    {
        $vars = parent::format($record);
        //...
    }
`````

**Comment by cutesquirrel** [comment]
Mmmmh, seems to be linked to #528 

In my case, Drupal generates a huge backtrace in an array (Drupal\Core\Utility::decodeException())
I tried to limit the backtrace array to 10 elements, and Monolog accept to display my message in a line, probably because the generated String isn't too big.

But if monolog will handle the $record type correctly, it could handle this kind of call, even if it's not its responsibility at first...

**Comment by stof** [comment]
`normalize` is more permissive, because it is called recursively.

`format` is called with a Monolog record array, i.e. the basic structure used by Monolog internally (which would be represented as a struct in C, or as a shape in Hack)

**Comment by cutesquirrel** [comment]
it makes sense :) I understand what you mean.
I gonna fix the issue in Drupal.
Thanks @stof
