### ISSUE TITLE
Rollerball Handler out of date

### ISSUE THREAD

**Issue by wshafer** [Seldaek/monolog#1021]
The Rollerbar Handler is out of date.  API changed awhile ago.  I'd fix this myself but I have no way to test the fixes since I don't use this service.   See api here:  https://github.com/rollbar/rollbar-php

**Comment by ArturMoczulski** [comment]
This is addressed in this PR: https://github.com/Seldaek/monolog/pull/1042

**Comment by Seldaek** [comment]
See https://github.com/Seldaek/monolog/pull/1042#issuecomment-397881987
