### ISSUE TITLE
RollbarNotifier class is missing.

### ISSUE THREAD

**Issue by jianzhong** [Seldaek/monolog#1036]
In src/Monolog/Handler/RollbarHandler.php, the class is trying to use a non-existing class 'RollbarNotifier' as the first parameter in the constructor. This causes PHP fatal error in my Symfony application when sending logging data to Rollbar. Please add this file back ASAP!

**Comment by jianzhong** [comment]
I've made a further investigation on the issue. The issue happened when I was trying to upgrade Rollbar from 0.18.2 to a later version by doing composer require ~1.1. The error was something like:

PHP Fatal error: Uncaught Error: Class 'RollbarNotifier' not found in ......
I noticed some changes in the autoload_psr4.php file under vendor\composer folder. The line

'Rollbar\' => array($vendorDir . '/rollbar/rollbar/src'),
becomes

'RollbarNotifier\' => array($vendorDir . '/rollbar/rollbar/src'),
If I changed RollbarNotifier to Rollbar, then I got another error in my Symfony application:

PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "RollbarNotifier" from the global namespace.

**Comment by jianzhong** [comment]
Resolved in [pull requests](https://github.com/Seldaek/monolog/pull/1042).

**Comment by jianzhong** [comment]
Have to reopen it as no release has been scheduled for it any time soon.

**Comment by Seldaek** [comment]
See https://github.com/Seldaek/monolog/pull/1042#issuecomment-397881987
