### ISSUE TITLE
Allow handler to decide it's fault tolerance

### ISSUE THREAD

**Issue by kristijorgji** [Seldaek/monolog#1043]
https://github.com/Seldaek/monolog/blob/7b992836275e09ed63c63fe33ca9993e515e6c5d/src/Monolog/Logger.php#L318

If one handler throws exception while processing the record the other ones won't process the record because of the exception.

I suggest you surround that part with a try catch, so all handlers will try to logg properly the record.
That way will be more fault tolerant the logging.

*Updated - allow each handler to decide it's own fault tolerance

**Comment by stof** [comment]
There is a WhatFailureGroupHandler which is precisely meant to wrap handlers to make them fault-tolerant. Use it in case it is the behavior you want.

**Comment by kristijorgji** [comment]
Ok good to know, but still would be good to have some property/method which decides how to handle each handler execution. 

That way I would not need to make a group just for making fault tolerant the execution of 1 single handler. Is increased complexity and bigger stack trace for nothing.

**Comment by Seldaek** [comment]
On top of the WhatFailureGroupHandler there is now https://github.com/Seldaek/monolog/pull/1012 as well which lets you customize error handling behavior.
