### ISSUE TITLE
Intended behavior to not allow overwriting some PushoverHandler properties via $context?

### ISSUE THREAD

**Issue by jk** [Seldaek/monolog#1048]
I want to set a custom title while using the PushoverHandler:

```php
$logger->info('some message', ['title'=>'myTitle']);
```

But because of this in [PushoverHandler.php:134](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/PushoverHandler.php#L134) I can't do this:

```php
$dataArray = [
  'token' => $this->token,
  'user' => $this->user,
  'message' => $message,
  'title' => $this->title,
  'timestamp' => $timestamp,
];
// ...
// Least important info should be merged with subsequent info
$dataArray = array_merge($extra, $context, $dataArray);
```

Is this the intended behavior that one can't overwrite `title` and even `timestamp` via the `$context` variable of the logging methods? If not, should I write a PR to fix this?

**Comment by Seldaek** [comment]
This is by design yes, you configure the title once and then give a message + additional data if needed in every record.
