### ISSUE TITLE
BufferHandler doesn't work on PHP-PM

### ISSUE THREAD

**Issue by rogeriolino** [Seldaek/monolog#1053]
I'm testing my Symfony 3.3 application using PHP-PM (HttpKernel bridge) and I'm getting a issue with deduplication handler as described in php-pm/php-pm-httpkernel#62. 

When start the application with `ppm` the `register_shutdown_function` callback is never called, and I cant figure out a solution for that.

Regards.

**Comment by Seldaek** [comment]
The way to go is to manually call close() on the BufferHandler instances, and in Monolog 2.x close is part of the HandlerInterface so such implementations should just close all monolog handlers at the end of every process lifecycle IMO.
