### ISSUE TITLE
StreamHandler: Set $useLocking to true by default

### ISSUE THREAD

**Issue by tomsommer** [Seldaek/monolog#1054]
Would it not make sense to set $useLocking to true by default? Otherwise you risk random concurrency/permission errors.

https://github.com/Seldaek/monolog/blob/7405bb5d673df9ee05698876843e85b0b8a599d4/src/Monolog/Handler/StreamHandler.php#L39

https://github.com/Seldaek/monolog/blob/07b6c1c4171a030787f2bc961272b1887032304e/src/Monolog/Handler/RotatingFileHandler.php#L45

**Comment by Seldaek** [comment]
As per https://github.com/Seldaek/monolog/issues/379 - this is only an issue if you log long lines or in very odd setups. For most use cases locking isn't needed even with high concurrency, so I don't think it's a good idea to enable by default.
