### ISSUE TITLE
Installation without Composer

### ISSUE THREAD

**Issue by emresaracoglu** [Seldaek/monolog#1060]
Hello

How I can Installation without Composer?

**Comment by HonzaMac** [comment]
Download button on main page https://github.com/Seldaek/monolog

**Comment by stof** [comment]
And then, take care of also downloading the code for psr/log (at https://github.com/php-fig/log) and to configure an autoloader able to load their classes (there are a bunch of autoloading packages available out there, even though most of them are becoming less maintained now that most frameworks and libraries expect their users to use Composer and so to rely on Composer's autoloader)

**Comment by Seldaek** [comment]
Yeah this isn't really supported..
