### ISSUE TITLE
Why is ruflin/elastica restricted to <3.0?

### ISSUE THREAD

**Issue by samimussbach** [Seldaek/monolog#1061]
At the moment composer.json restricts ruflin/elastica to <3.0. Why is this? This effectively mitigates any update to elasticsearch > 1.7.* in any project using monolog and elastica.
I cannot really believe that this is really the case, but I cannot spot my mistake. Could anyone help me please?

**Comment by stof** [comment]
There is no hard requirement on ruflin/elastica, so this won't prevent anything.

Whether the existing ElasticSearchHandler actually works with newer versions of Elastica is something to be checked. This handler was a community contribution.

**Comment by stof** [comment]
btw, why using Elastica to send logs directly to ES rather than using Logstash, which is Elastic's tool to send logs to an ES cluster (and probably with better performance than doing queries to ES inline)

**Comment by samimussbach** [comment]
I do not want to send logs via Elastica. I just use  symfony/monolog-bundle as well as friendsofsymfony/elastica-bundle. When I try to use friendsofsymfony/elastica-bundle 4.x I need ruflin/Elastica > 3.0 (which is what I want), but this could not be satisfiable as symfony/monolog-bundle restricts ruflin/elastica to <3.0

**Comment by xabbuh** [comment]
I do not see where you found that restriction in MonologBundle. Can you post the error message you get?

**Comment by stof** [comment]
MonologBundle does not have any requirement on Elastica. and Monolog only has a dev requirement on it, so it has no impact at all on the dependency resolution in your project.

**Comment by samimussbach** [comment]
require-dev section of monolog/monolog composer.json in v1.23.0

```json
{
    "name": "monolog/monolog",
    "description": "Sends your logs to files, sockets, inboxes, databases and various web services",
    "keywords": ["log", "logging", "psr-3"],
    "homepage": "http://github.com/Seldaek/monolog",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "Jordi Boggiano",
            "email": "j.boggiano@seld.be",
            "homepage": "http://seld.be"
        }
    ],
    "require": {
        "php": ">=5.3.0",
        "psr/log": "~1.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.5",
        "graylog2/gelf-php": "~1.0",
        "sentry/sentry": "^0.13",
        "ruflin/elastica": ">=0.90 <3.0",
        "doctrine/couchdb": "~1.0@dev",
        "aws/aws-sdk-php": "^2.4.9 || ^3.0",
        "php-amqplib/php-amqplib": "~2.4",
        "swiftmailer/swiftmailer": "^5.3|^6.0",
        "php-console/php-console": "^3.1.3",
        "phpunit/phpunit-mock-objects": "2.3.0",
        "jakub-onderka/php-parallel-lint": "0.9"
    },
    "_": "phpunit/phpunit-mock-objects required in 2.3.0 due to https://github.com/sebastianbergmann/phpunit-mock-objects/issues/223 - needs hhvm 3.8+ on travis",
    "suggest": {
        "graylog2/gelf-php": "Allow sending log messages to a GrayLog2 server",
        "sentry/sentry": "Allow sending log messages to a Sentry server",
        "doctrine/couchdb": "Allow sending log messages to a CouchDB server",
        "ruflin/elastica": "Allow sending log messages to an Elastic Search server",
        "php-amqplib/php-amqplib": "Allow sending log messages to an AMQP server using php-amqplib",
        "ext-amqp": "Allow sending log messages to an AMQP server (1.0+ required)",
        "ext-mongo": "Allow sending log messages to a MongoDB server",
        "mongodb/mongodb": "Allow sending log messages to a MongoDB server via PHP Driver",
        "aws/aws-sdk-php": "Allow sending log messages to AWS services like DynamoDB",
        "rollbar/rollbar": "Allow sending log messages to Rollbar",
        "php-console/php-console": "Allow sending log messages to Google Chrome"
    },
    "autoload": {
        "psr-4": {"Monolog\\": "src/Monolog"}
    },
    "autoload-dev": {
        "psr-4": {"Monolog\\": "tests/Monolog"}
    },
    "provide": {
        "psr/log-implementation": "1.0.0"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "2.0.x-dev"
        }
    },
    "scripts": {
        "test": [
            "parallel-lint . --exclude vendor",
            "phpunit"
        ]
    }
}
``` 

Error message is

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for demosplan dev-release_robob -> satisfiable by demosplan[dev-release_robob].
    - Conclusion: remove ruflin/elastica 2.3.1
    - Conclusion: don't install ruflin/elastica 2.3.1
    - demosplan dev-release_robob requires friendsofsymfony/elastica-bundle ~4.0 -> satisfiable by friendsofsymfony/elastica-bundle[v4.0.0, v4.0.1].
    - friendsofsymfony/elastica-bundle v4.0.0 requires ruflin/elastica 3.2.* -> satisfiable by ruflin/elastica[3.2, 3.2.1, 3.2.2, 3.2.3].
    - friendsofsymfony/elastica-bundle v4.0.1 requires ruflin/elastica 3.2.* -> satisfiable by ruflin/elastica[3.2, 3.2.1, 3.2.2, 3.2.3].
    - Can only install one of: ruflin/elastica[3.2, 2.3.1].
    - Can only install one of: ruflin/elastica[3.2.1, 2.3.1].
    - Can only install one of: ruflin/elastica[3.2.2, 2.3.1].
    - Can only install one of: ruflin/elastica[3.2.3, 2.3.1].
    - Installation request for ruflin/elastica (locked at 2.3.1) -> satisfiable by ruflin/elastica[2.3.1].

```

I agree that this is really strange but I cannot spot the error.

**Comment by stof** [comment]
`require-dev` of your dependency is **not** taken into account.

Here, the issue is a conflict of dependencies between `friendsofsymfony/elastica-bundle` (wanting 3.2) and your lock file (locking at 2.3.1 because you haven't included it in the upgrade whitelist).
Monolog has nothing to do with your error.

**Comment by samimussbach** [comment]
This is what I thought as well, but when I try to run composer with --no-dev I get the same error with
```
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems
``` 

But anyhow, it seems to be my problem, thanks for your time, I think I need to try to figure it out by myself

**Comment by stof** [comment]
@samimussbach `require-dev` is a *root-only* setting. The `--no-dev` option controls the installation of **your** dev requirements, not the one of your dependencies (which just **never** exist in the dependency solver)

**Comment by samimussbach** [comment]
This is how I understood it and why I was so baffled. Anyhow after several more composer updates the problem vanished, so it seemed to be a false alert. Thank you for your support, I appreciate it.
