### ISSUE TITLE
Annotation issue

### ISSUE THREAD

**Issue by AlexandreKhayrullin** [Seldaek/monolog#1063]
Hi.

There is an issue with @param and @return annotations in the class \Monolog\Handler\AbstractHandler that breaks compatibility with Magento 2: boolean values and parameters are referred to as "Boolean" instead of "bool", which causes Magento to look for a non-existing class \Monolog\Handler\Boolean and crashing upon not finding it.

Replacing "Boolean" with "bool" in annotations solves the problem.

Could you please correct at least this file?

**Comment by Seldaek** [comment]
Fixed by  #1077
