### ISSUE TITLE
Filter out some log messages based on runtime config?

### ISSUE THREAD

**Issue by howardjones** [Seldaek/monolog#1069]
In my app, I use error codes on warnings, and allow users to mute certain warnings (e.g. "--no-warn WARN22"). I plan to use monolog (1.23 for now, until I stop supporting php 5.6) and use the context data to tag the warning with the error code if it has one.

But, how can I implement the muting/filtering behaviour in monolog? They'll all be the same log level. Can a processor return null or an empty event, to indicate that the event shouldn't be logged? Internally I already have a list of currently-muted error codes to check against.

**Comment by howardjones** [comment]
Answering my own issue - you can't return null, but you can set the level to something non-existent...

```
class SuppressProcessor
{
    private $suppressed = array();

    public function addSuppressedCode($code)
    {
        $this->suppressed[$code] = true;
    }

    public function removeSuppressedCode($code)
    {
        unset($this->suppressed[$code]);
    }

    public function __invoke(array $record)
    {
        if (isset($record['context']['code']) && isset($this->suppressed[$record['context']['code']])) {
            $record['level'] = "SUPPRESS";
        }

        return $record;
    }
}
```

**Comment by Seldaek** [comment]
You could also use a wrapping handler instead of a processor, to filter what gets passed down to the other handlers. That'd be the more "monolog" way to do this.
