### ISSUE TITLE
Add ability to handle formatted message in PsrHandler

### ISSUE THREAD

**Issue by shouze** [Seldaek/monolog#1070]
This is just a proposal, I own this implementation inside of one of my own projects repo but maybe it would be useful for some other people? WDYT? Is it the way it should be implemented?

```php
class PsrHandler extends AbstractProcessingHandler
{
    protected $logger;
    public function __construct(LoggerInterface $logger, $level = Logger::DEBUG, $bubble = true)
    {
        parent::__construct($level, $bubble);
        $this->logger = $logger;
    }
    public function write(array $record)
    {
        if (!$this->isHandling($record)) {
            return false;
        }

        $message = isset($record['formatted']) ? $record['formatted'] : $record['message'];

        $this->logger->log(strtolower($record['level_name']), $message, $record['context']);

        return false === $this->bubble;
    }
}
```

**Comment by Seldaek** [comment]
Seems fine to me but I think this should be a 2.0 feature only as it can introduce some breakage. The question though is what should the default be? Should it format by default or rather pass-through by default but if you configure a formatter then it uses it to format?

**Comment by shouze** [comment]
> Seems fine to me but I think this should be a 2.0 feature only as it can introduce some breakage. The question though is what should the default be?

👍  for 2.0 of course. Should use the formatted message (if a formatted is configured of course) by default I guess, no?

> Should it format by default or rather pass-through by default but if you configure a formatter then it uses it to format?

Yes, only if you configure a formatter.

**Comment by Seldaek** [comment]
Ok then I guess go for a PR :)
