### ISSUE TITLE
Unable to send stacktrace using RavenHandler

### ISSUE THREAD

**Issue by phptek** [Seldaek/monolog#1074]
Using `Monolog\Handler\RavenHandler::write()` there is no option to send a stacktrace ala `Raven_Client::captureMessage()` (4th arg is not collected or passed).

Solution: Add an extra dimension to the `write()` method's `$record` param "trace" or "stack" and then pass `$record['some_param']` as the 4th arg to `$this->ravenClient->captureMessage($record['formatted'], array(), $options, $record['some_param']);`

**Comment by Seldaek** [comment]
The right way to capture the stack is to pass an exception instance in the log context's `exception` key (as defined in PSR-3), then Raven's captureException is used, which captures the stack.
