### ISSUE TITLE
NOTICE not logged when WordPress Debug mode OFF

### ISSUE THREAD

**Issue by burhandodhy** [Seldaek/monolog#1082]
Hi,

I'm integrating Monolog into WordPress plugin, but I'm facing the issue that when WordPress Debug mode is Off, the notices are not logged in log file.

**Comment by dnaber-de** [comment]
A bit of information about what you did and how would be great.

**Comment by burhandodhy** [comment]
WP_DEBUG is WordPress constant when its set to be "True" WordPress shows warnings and fatal errors,  plus all the warnings and errors are logged in Monolog file.

When I set the WP_DEBUG to "False", Monolog only logged fatal errors in log file not the Notices and Warnings.

**Comment by bueltge** [comment]
I think you can save your time if you need Monolog in the WP environment, see this solution https://github.com/inpsyde/wonolog

**Comment by gmazzap** [comment]
@burhandodhy Monolog is a tool that knownothing about WordPress, you can use it in WordPress but _you_ have to configure it.

Is it possible that you are using [Wonolog](https://github.com/inpsyde/Wonolog)? Because that's sound the default behavior of Wonolog, that is configurable by the way (see its docs).

**Comment by burhandodhy** [comment]
Thanks @bueltge  for the suggestion. 

@gmazzap Wonolog needs PHP 5.6+ whereas most of WordPress users are still using PHP 5.4 and PHP 5.5. This is the main reason i'm going with Monolog

**Comment by dnaber-de** [comment]
> Monolog is a tool that knownothing about WordPress, you can use it in WordPress but you have to configure it.

That's why I asked about what you did. Show some code! However, https://wordpress.stackexchange.com/ might be the better platform for your problem.
