### ISSUE TITLE
LineFormatter does not include stacktraces for "previous" exceptions

### ISSUE THREAD

**Issue by mpdude** [Seldaek/monolog#1086]
I am using the `LineFormatter` to log exceptions with stack traces.

However, `previous` exceptions are only logged with their class name, file, code and message, but no stack trace included. In many cases I have seen the stack trace of the "root" exception would be the interesting information I'd need.

So, short question: Would you support/merge a (probably trivial) PR to include stacktraces for all `previous` exceptions as well?

Should this be changed in `LineFormatter` only, or are there any other/better places?

**Comment by Seldaek** [comment]
LineFormatter is the only one with this issue it seems. So yes it's the only place to patch IMO. Feel free to send a PR targetting master branch, I think this is a bit too invasive to the log format to include in 1.x

**Comment by mpdude** [comment]
See #1170.
