### ISSUE TITLE
Is it possible to rotate a new log when exceeded 5M ? 

### ISSUE THREAD

**Issue by johnico** [Seldaek/monolog#1089]
I m using slim with monolog, and my log became bigger like 50MB per Day  , I would like to create a new log with index-like - > date-1, date-2.log   when it reach the limit of 5MB 
is it possible?  did not find option like that

**Comment by tomzx** [comment]
`RotatingFileHandler` does not support specifying a max size per file. If you would like to have such behavior, I suggest you extend/copy this class and add the necessary logic to make it work as you'd like.

**Comment by Seldaek** [comment]
IMO the best way to do this is to configure logrotate to rotate logs correctly. We are not going to reimplement all of it in Monolog, the RotatingFileHandler just offers very basic functionality.
