### ISSUE TITLE
Two Objects in log line confuses cloud watch

### ISSUE THREAD

**Issue by acinader** [Seldaek/monolog#1091]
The default line logger emits two objects: channel and extra.  Amazon Cloud Watch doesn't allow one to target these objects in metrics if more than one object exists in the logline.

JSON targetting works great if there is only one object, but when a log line has two, the JSON targetting doesn't work at all.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

My proposed solution is to make an option on the LineFormatter to combine extra and context objects.

**Comment by Seldaek** [comment]
Closing as per https://github.com/Seldaek/monolog/pull/1092#issuecomment-395973783
