### ISSUE TITLE
Ability to extend StreamHandler

### ISSUE THREAD

**Issue by bnowak** [Seldaek/monolog#1093]
Hi,

I would like to extend [StreamHandler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php) to handle multi urls where logs are saved. I need this because target url is resolve based on log context and the context can be dynamic.

I have problem when save logs to file and later to another file in different directory. When target directory aren't exist then in [createDir](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L159) method this directory is getting to be created. Unfortunately if directory were created the next time when we are logging something checking if directory is existed are missed because of [private dirCreated](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L162) flag.

```php
private $dirCreated;

[...]

private function createDir()
{
    // Do not try to create dir if it has already been tried.
    if ($this->dirCreated) {
        return;
    }

    [...]

    $this->dirCreated = true;
}
```

I would like to control this flag in a subclass but I can't if it's private. Can we make it protected?  
I'm wondering also why other methods and properties are private. It makes that this class is unextendable.

If I will make appropriate PR to make this class extendable will you consider a merge?

**Comment by tomzx** [comment]
Why not copy the code and do whatever you want instead of extending from `StreamHandler`. Furthermore, if you have custom requirements, those do not necessarily need to be part of monolog itself.

**Comment by bnowak** [comment]
> Why not copy the code and do whatever you want instead of extending from `StreamHandler`.

From the same reason that `RotatingFileHandler` extends `StreamHandler`. In OOP way it doesn't make sense to copy all class code to another and change only a few things. It's leads to make code more redundant.

> Furthermore, if you have custom requirements, those do not necessarily need to be part of monolog itself.

I agree with that but I didn't propose to add any of my custom requirments and change current code logic of monolog. I just want to extend that class. 

Right now I use `Reflection` in child class to dynamically change value of `dirCreated` in specified cases and handler works as expected. But this is bad and temporary solution.

**Comment by Seldaek** [comment]
Why not rather create a proxy handler that forwards to one of several StreamHandler instances depending on the record? That way every streamhandler can create it's own stream and you don't need to keep resetting them. That sounds like less hacky to me.
