### ISSUE TITLE
Mailgun Handler

### ISSUE THREAD

**Issue by Narrator** [Seldaek/monolog#1095]
Hello,

I've written a Mailgun (API v3) Handler after forking the repo. I'd like to contribute this to the master branch. Do I just directly create a pull request?

Also, I saw that that the 1.x branch is still using PHP 5.3 and since 1.23 is the latest stable version, should I push to the 1.x branch as well? The changes in this regard would obviously be different without strict types etc.

**Comment by Seldaek** [comment]
Thanks, however maintaining all handlers inside this repo is kinda unsustainable for me. Please instead publish such new handlers as individual packages on packagist.org and then add it to https://github.com/Seldaek/monolog/wiki/Third-Party-Packages so it's easily discoverable.
