### ISSUE TITLE
FriendsOfPHP Security advisory, can it be removed.

### ISSUE THREAD

**Issue by bweston92** [Seldaek/monolog#1097]
I went to use 1.9 and got a security advisory, is this still the case I would imagine a fix has been made within the 2 years?

PR: https://github.com/FriendsOfPHP/security-advisories/pull/44/files
Current Master: https://github.com/FriendsOfPHP/security-advisories/blob/master/monolog/monolog/2014-12-29-1.yaml

Composer logs.
```
  Problem 1
    - Conclusion: don't install monolog/monolog 1.9.1
    - monolog/monolog 1.9.0 conflicts with roave/security-advisories[dev-master].
    - monolog/monolog 1.9.0 conflicts with roave/security-advisories[dev-master].
    - Installation request for monolog/monolog 1.9.* -> satisfiable by monolog/monolog[1.9.0, 1.9.1].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].

```

**Comment by xabbuh** [comment]
There have been many updates. As you can see in the link advisories entry this security issue shouldn't affect you when using 1.12 or higher.

**Comment by bweston92** [comment]
You're right, no idea where I got the idea to use 1.9 from. Thanks!
