### ISSUE TITLE
Howto log all silent error

### ISSUE THREAD

**Issue by macintoshplus** [Seldaek/monolog#1103]
Hi,

If I have one line like `@trigger_error('error...' ...);` the message is not stored into the log.

Howto enable it ?

Thanks in advance and thanks for this great logger !

**Comment by tomzx** [comment]
You can make use of the [`ErrorHandler`](https://github.com/Seldaek/monolog/blob/1.23.0/src/Monolog/ErrorHandler.php) and register your logger.

```php
// Exception logger
$name = 'exception';
$logger = new Logger($name);

// Handlers
$streamHandler = new StreamHandler('php://stdout', MonologLogger::WARNING);
$logger->pushHandler($streamHandler);

Registry::addLogger($logger, $name);
self::$exceptionLogger = $logger;

ErrorHandler::register($logger);
```

You may have to change the error types you want to register for (see http://php.net/manual/en/function.trigger-error.php).
