### ISSUE TITLE
Request: move to somewhere the hardcoded swiftmailer formatter

### ISSUE THREAD

**Issue by Fewald** [Seldaek/monolog#1105]
We've got an issue with default monolog formatters which leads us to custom formatters everywhere. Unfortunately, this one is hardcoded
https://github.com/Seldaek/monolog/blob/7b992836275e09ed63c63fe33ca9993e515e6c5d/src/Monolog/Handler/SwiftMailerHandler.php#L73

Will it be ok for you to have a getter for that "subject" formatter? If so, I can do PR

**Comment by Seldaek** [comment]
Sure feel free to add a getter for it that takes the $message->getSubject() as argument or even the whole $message instance.
