### ISSUE TITLE
Is a new release planned?

### ISSUE THREAD

**Issue by MatTheCat** [Seldaek/monolog#1110]
I don't really understand commits and releases history but I wanted to test the Logmatic handler and it is not in v1.23.0. Will it be possible to have it?

**Comment by tomzx** [comment]
You could either depend on `dev-master` or `2.0.x-dev` until a release is published.

**Comment by MatTheCat** [comment]
Not using monolog-bundle :/

**Comment by Seldaek** [comment]
Yes, 1.24.0 is almost ready, just a few issues left in https://github.com/Seldaek/monolog/milestone/5 - LogmaticHandler is only in master branch though so it will come out with 2.0 which is a bit further out but hopefully coming soonish too.
