### ISSUE TITLE
Using set_error_handler() in StreamHandler

### ISSUE THREAD

**Issue by systemist** [Seldaek/monolog#1112]
Currently StreamHandler has:

    set_error_handler(array($this, 'customErrorHandler'));

and then:

    private function customErrorHandler($code, $msg)
    {
        $this->errorMessage = preg_replace('{^(fopen|mkdir)\(.*?\): }', '', $msg);
    }

Setting an error handler to a private method won't work, as the handler gets called from outside the object scope and the callback method needs to be public. Furthermore, when monolog is used to handle php errors,  `set_error_handler()` gets called from within the error handler callback itself, which can lead to pretty unexpected results. 

I have spent several hours trying to figure out why not all the messages are being logged using monolog, and it turned out that one of the error handlers was being popped from the stack when StreamHandler is used. 

Commenting out `set_error_handler()` and `restore_error_handler()` within `write()` method fixed the problem.

It seems that the problem only appears when there is more than one error handler stacked.

**Comment by Seldaek** [comment]
As per https://3v4l.org/D729B - this seems to all work as expected, and does not drop error handlers. If you can't provide more details I am afraid we can't do much here.
