### ISSUE TITLE
Why doesn't Predis need the same protection as Redis?

### ISSUE THREAD

**Issue by nacc** [Seldaek/monolog#1114]
Shouldn't

https://github.com/Seldaek/monolog/blob/7b992836275e09ed63c63fe33ca9993e515e6c5d/tests/Monolog/Handler/RedisHandlerTest.php#L30

and other lines be adjusted the same as

https://github.com/Seldaek/monolog/commit/b21b465cca4647d4ecae64795a8d6be6296fb15c

did for Redis?

**Comment by nacc** [comment]
Oh upon further reflection, this is because composer.json was also updated to require predis?

**Comment by Seldaek** [comment]
Exactly, we don't want to force anyone to have the redis extension installed to develop monolog though.
