### ISSUE TITLE
Ability for pretty JSON in NormalizerFormatter

### ISSUE THREAD

**Issue by dzhiryakov** [Seldaek/monolog#1139]
Now it is very difficult to make pretty formatting of the JSON. The toJson method is private and it not support JSON_PRETTY_PRINT option. 

How to optimally make the data in the extra processed using the JSON_PRETTY_PRINT option?

**Comment by tavlima** [comment]
Ideally, this should be configurable. If only `Monolog\Formatter\NormalizerFormatter::jsonEncode` was protected, it would be easier to introduce the behavior by subclassing.

**Comment by Seldaek** [comment]
IMO a config flag/setter could be added to NormalizerFormatter to let one enable that optionally.

**Comment by Olegf13** [comment]
@dzhiryakov, see https://github.com/tatocaster/monolog-json-unicode-pretty-formatter. Will it help?
