### ISSUE TITLE
getmypid() has been disabled for security reasons

### ISSUE THREAD

**Issue by wujekbogdan** [Seldaek/monolog#1143]
I can see the following error in logs:

```
getmypid() has been disabled for security reasons
```

I happen because of the `getmypid()` function call in `SyslogUdpHandler.php`

---
I've never seen such an error, it started to happen after migrating a site from HTTP to HTTPS. I don't know is it related. It might be a coincidence. 

The site is running on kinsta.com, PHP 7.1. Is there anything else I could share with you in order to help you with debugging?

**Comment by stof** [comment]
Well, SyslogUdpHandler relies on being able to get the pid to build the syslog header.
It looks like your host has disabled the `getmypid` function for security reasons (which is someone shared hosting often do).

so the best solution is to use a different Monolog handler to send your log, one which is compatible with the requirements set by your hosting.

**Comment by wujekbogdan** [comment]
@stof 
What do you use the `getmypid()` for? If you use it just to generate a random number then it could be replaced with `mt_rand()`. I know that `mt_rand()` will not generate a really unique (or a really random) number, but `getmypid()` isn't reliable either.  Eeven the PHP documentation says that:


> **Warning**
> Process IDs are not unique, thus they are a weak entropy source. We recommend against relying on pids in security-dependent contexts.
>

**Comment by stof** [comment]
it is used to put the pid itself in the appropriate place: https://github.com/Seldaek/monolog/blob/7b992836275e09ed63c63fe33ca9993e515e6c5d/src/Monolog/Handler/SyslogUdpHandler.php#L69-L89

**Comment by wujekbogdan** [comment]
@stof 
if  `getmypid()` is used to get the pid, not to generate a random number, then I guess that this problem can't be fixed. So this issue can be closed.

Thanks for your time.

---
PS
I've solved my problem by replacing the `SyslogUdpHandler` with the `SocketHandler`.
