### ISSUE TITLE
Error on Monolog\Handler\DynamoDbHandler::filterEmptyFields() when I try to use DynamoDbHandler

### ISSUE THREAD

**Issue by jonaselan** [Seldaek/monolog#1147]
Hi!

I'm building an application with **Laravel 5.6**  where the logs should be placed on DynamoDB. For this reason my `logging.php` stayed this way

```php
'channels' => [
        'stack' => [
            'driver' => 'stack',
            'tap' => [Freshbitsweb\LaravelLogEnhancer\LogEnhancer::class], // extra lib for get more information in my logs
            'channels' => ['single', 'log_dynamo'],
        ],
        'single' => [
            'driver' => 'single',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
        ],
        'log_dynamo' => [
            'driver'  => 'monolog',
            'handler' => Monolog\Handler\DynamoDbHandler::class,
            'with'    => [
                'client' => new \Aws\DynamoDb\DynamoDbClient([
                    'region' => env('AWS_REGION'),
                    'version'=> '2012-08-10',
                    'credentials' => array(
                        'key' => env('AWS_KEY'),
                        'secret'  => env('AWS_SECRET'),
                    )
                ]),
                'table' => 'Logs', # and yes, I already created a table 'Logs'
                'level' => 'debug'
            ],
        ],
    ],
``` 

The problem is: When my application get some error (like a misstype word), an error 500 is throw.  In my file `laravel.log` I see way:

```
local.ERROR: Type error: Argument 1 passed to Monolog\Handler\DynamoDbHandler::filterEmptyFields() must be of the type array, string given
```

I already try remove this extra lib, but the problem still

Thanks in advance!

**Comment by Seldaek** [comment]
If you don't override the default formatter of DynamoDbHandler (ScalarFormatter) I don't see how this error is possible. Your config doesn't look like you're doing this but I don't know what else happens in Laravel..

**Comment by jonaselan** [comment]
@Seldaek I see the problem. On DynamoDbHandler file, on line 76, the value expected of `$record['formatted']` is an array, but for some reason returns a string:

![error_dynamo](https://user-images.githubusercontent.com/5933907/41185983-2332bbf2-6b65-11e8-9b29-9fca99fe3b39.png)

The proof is if I put this way works:

![screenshot from 2018-06-08 21-45-13](https://user-images.githubusercontent.com/5933907/41185989-4020c47a-6b65-11e8-8506-f2947c3b860d.png)

**Comment by Seldaek** [comment]
Can you check what is the value of $this->formatter inside the handler? It should be an instance of ScalarFormatter, but maybe not.

**Comment by jonaselan** [comment]
I do a `dd($this->formatter)` and return this:
![dynamodb](https://user-images.githubusercontent.com/5933907/41207662-eb08c94c-6cef-11e8-86bb-d18361f45781.png)

**Comment by Seldaek** [comment]
Ok that's your problem then, the line formatter returns a string and not an array like the ScalarFormatter does. Make sure you don't overwrite the formatter for this handler.

**Comment by andrewminion-luminfire** [comment]
Note for others stumbling on this: I solved this by using `tap` to customize the formatter. See [Laravel documentation](https://laravel.com/docs/5.8/logging#advanced-monolog-channel-customization), and this `CustomizeFormatter.php` code:

```php
<?php

namespace App\Logging;

use Monolog\Formatter\ScalarFormatter;

class CustomizeFormatter
{
    /**
     * Customize the given logger instance.
     *
     * @param  \Illuminate\Log\Logger  $logger
     * @return void
     */
    public function __invoke($logger)
    {
        foreach ($logger->getHandlers() as $handler) {
            if (is_a($handler, '\Monolog\Handler\DynamoDbHandler')) {
                $handler->setFormatter(new ScalarFormatter());
            }
        }
    }
}
```
