### ISSUE TITLE
Get a list of processors attached to a Handler

### ISSUE THREAD

**Issue by gauravmak** [Seldaek/monolog#1154]
Hello,

Is it possible to add a method to fetch the list of processors that are attached to a handler?

[ProcessableHandlerTrait](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/ProcessableHandlerTrait.php) contains methods to push and pop a processor but not to get a list of them.

I do not have a complete idea of the flow I just wanted to ask the contributors before making a pull request.

**Comment by Seldaek** [comment]
I guess we could but I wonder what the need is?

**Comment by gauravmak** [comment]
Aah, can be done. Thanks.
