### ISSUE TITLE
What is the good practice to move to monolog

### ISSUE THREAD

**Issue by zomorod** [Seldaek/monolog#1158]
Hi there, 

I am trying to use monologs but I am confused to how to use it(I have checked the example on Github). I added my current structure for logging here. I am not good with coding, so I appreciate if you give me sample code example for better understanding.

Thank you for your help,

My current project has the flowing structure:

logs.inc 
```
/**
 * Logs a message to a external sites.
 */
function log_remote($group, $type, $message, $entity='entity_log') {
}
/**
 * Wraps log so that messages can be logged to a file.
 */
function log($message, $type = 'ok', $out = NULL) {
....
  // Write message to file.
    log_to_file($log_message . "\n");
}

/**
 * Wraps set_error so that errors can be logged to a file.
 */
function set_error($error, $message = null) {

 log("$error: $message", 'error');
}

/**
 * Logs a string to the current log file.
 */
function log_to_file($text) {
}
```
Then in my other php files I am calling the functions:
      log_remote('SITE', 'SITE_ERROR', $message);
      set_error('SITE', $message);
      log("message");

**Comment by stof** [comment]
Well, the readme describes basic usage: https://github.com/Seldaek/monolog#basic-usage

Monolog having an object-oriented API, its usage is different from our own procedural API using a global function.
