### ISSUE TITLE
Logging to an xUnit compatible format XML file.

### ISSUE THREAD

**Issue by rquadling** [Seldaek/monolog#1163]
I've got some Symfony console based apps that currently write to the console and/or to Monolog. All works fine.

I want to incorporate some of these apps into our pipeline and have error logs be processed by the pipeline tear down process.

The pipeline only understands jUnit format (it is primarily for using PHPUnit testing, but, for example, PHP Code Styling can generate appropriate jUnit logs, so you get to see what unit tests have failed as well as the code styling issues in the results page).

And so I was wondering if anyone knew of formatter for Monolog that would achieve a similar result. 

I suspect I'm going to have build my own and base it upon https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/HtmlFormatter.php

Suggestions/tips gratefully received.

**Comment by Seldaek** [comment]
Haven't heard of anything like that.. Indeed sounds like you might have to roll your own :)
