### ISSUE TITLE
How to categorize errors ?

### ISSUE THREAD

**Issue by zomorod** [Seldaek/monolog#1167]
Hi there,

I am trying to move to Monolog but I am wondering how I can categorize my errors with Monolog.
For example: I have several groups of errors that have different types and message and I need to save everything in one file. I can use channels instead of groups but how I can define my own types?

Group1 --> Type1, Message
             --> Type2, Message
             --> Type3, Message

Group2 --> Type4, Message
              --> Type5, Message
              --> Type6, Message

I appreciate your help in advance.

**Comment by Seldaek** [comment]
You could add the type in the context array when logging, and add %context.type% to the message format in the LineFormatter you use to log to the file, but I really have no idea what you're doing so maybe this is off.
