### ISSUE TITLE
Endpoint is no longer valid, should pass in as parameter

### ISSUE THREAD

**Issue by mundomatt** [Seldaek/monolog#1173]
https://github.com/Seldaek/monolog/blob/e5900c38147d13f0aa9072aaff7ff0f8dbb253f3/src/Monolog/Handler/LogEntriesHandler.php#L40

Logentries went under a structural change and is now called "InsightOps". The endpoint no longer works and has been replaced with something along the following format:
`[region].data.logs.insight.rapid7.com`

The endpoint should be passed in as a parameter for future-proofing.

**Comment by Seldaek** [comment]
Actually the correct way to do this is to migrate to the InsightOpsHandler
