### ISSUE TITLE
Weird behaviour of FingersCrossedHandler / RavenHandler in long-running process

### ISSUE THREAD

**Issue by Wirone** [Seldaek/monolog#1177]
Excuse me for rising this here, but I didn't get any response on Slack and Stackoverflow. The issue is described [here](https://stackoverflow.com/questions/51310575/monolog-send-errors-to-sentry-with-preserved-lower-level-log-records).

Whatever I do, I can't reproduce it locally. I run the same docker image of our app (more or less the same `docker-compose.yml`) and my local Sentry has only ERROR events while our production-bound Sentry gets many INFO events from logger used in long-running queue consumer containers (4 parallel workers). I don't understand why, since `RavenHandler` is wrapped inside `FingersCrossedHandler` with `action_level: error` and as far as I see it invokes `handleBatch`when activated, then Raven handler in its own `handleBatch` picks record with highest level and the rest as `logs` in context. So how INFO events get to our Sentry?

Maybe @Seldaek with his huge experience can give some hint why it behaves like this. Thanks in advance.

**Comment by Seldaek** [comment]
Fixed by https://stackoverflow.com/a/52399591

**Comment by Wirone** [comment]
Actually the solution was to configure `stop_buffering` for fingers crossed handler, which pass all records after first activation. MonologBundle has it enabled by default, so in long running processes after first error all logger records were sent to Sentry.
