### ISSUE TITLE
Question: why the LineFormatter doesn't try to recover json encoding errors?

### ISSUE THREAD

**Issue by mmenozzi** [Seldaek/monolog#1184]
Like stated in the subject: why the LineFormatter doesn't try to recover json encoding errors?
I mean something that has already been done with https://github.com/Seldaek/monolog/pull/683 for the NormalizerFormatter.

Is simply because anyone didn't have time to do such implementation or there are other reasons?

**Comment by Seldaek** [comment]
I think it's mostly because nobody did it yes.. Feel free to PR

**Comment by mmenozzi** [comment]
Ok I’ll do it

**Comment by mmenozzi** [comment]
Hi @Seldaek ,
sorry but what I said before it's not correct.

The `NormalizerFormatter` contains the logic to try to recover from json encoding errors but this logic isn't used in the `NormalizerFormatter` itself.

That logic is called from the `NormalizerFormatter::toJson` method but only if the `$ignoreErrors` parameters is `false`. Inside the `NormalizerFormatter` the `toJson` method is always called with `$ignoreErrors` set to `true`.

I found that the `NormalizerFormatter::toJson` method with `$ignoreErrors` set to `false` is called only in the `GelfMessageFormatter`, `LogstashFormatters` and `WildfireFormatter` formatters.

So the question now is: what we would like to do? Should the `LineFormatter` (or maybe also others) tries to recover json encoding errors or not?

**Comment by Seldaek** [comment]
Hmm I guess maybe yes. I think the whole formatter thing needs to be cleaned up in 2.0 but it's a rather complex task :/
