### ISSUE TITLE
Maybe LineFormatter shouldn't replace line breaks in the context values

### ISSUE THREAD

**Issue by nesk** [Seldaek/monolog#1185]
I need to log some ASCII tables, like this one:

```
┌─────────┬─────┬─────┐
│ (index) │  a  │  b  │
├─────────┼─────┼─────┤
│    0    │  1  │ 'Y' │
│    1    │ 'Z' │  2  │
└─────────┴─────┴─────┘
```

The default configuration of the `LineFormatter` is not really suitable to easily read these tables, so I've allowed inline line breaks, here's an example:

```php
define('ALLOW_INLINE_LINE_BREAKS', true);

use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use Monolog\Formatter\LineFormatter;
use Monolog\Processor\PsrLogMessageProcessor;

$formatter = new LineFormatter(null, null, ALLOW_INLINE_LINE_BREAKS);

$handler = new StreamHandler('php://stdout');
$handler->setFormatter($formatter);

$logger = new Logger('test');
$logger->pushHandler($handler);
$logger->pushProcessor(new PsrLogMessageProcessor);

$data = "
┌─────────┬─────┬─────┐
│ (index) │  a  │  b  │
├─────────┼─────┼─────┤
│    0    │  1  │ 'Y' │
│    1    │ 'Z' │  2  │
└─────────┴─────┴─────┘
";

$logger->debug("Here's the data: {data}", ['data' => $data]);
```

If you run this code, you will get the following output:

```
[2018-08-06 16:16:10] test.DEBUG: Here's the data: 
┌─────────┬─────┬─────┐
│ (index) │  a  │  b  │
├─────────┼─────┼─────┤
│    0    │  1  │ 'Y' │
│    1    │ 'Z' │  2  │
└─────────┴─────┴─────┘
 {"data":"
┌─────────┬─────┬─────┐
│ (index) │  a  │  b  │
├─────────┼─────┼─────┤
│    0    │  1  │ 'Y' │
│    1    │ 'Z' │  2  │
└─────────┴─────┴─────┘
"} []
```

However, I don't think it's relevant to replace `\n` and `\r` occurences in the log string with real line breaks because _it is no longer a valid JSON object_ (and it's hard to distinguish the message from the context), here's what I was expecting instead:

```
[2018-08-06 16:16:10] test.DEBUG: Here's the data: 
┌─────────┬─────┬─────┐
│ (index) │  a  │  b  │
├─────────┼─────┼─────┤
│    0    │  1  │ 'Y' │
│    1    │ 'Z' │  2  │
└─────────┴─────┴─────┘
{"data":"\n┌─────────┬─────┬─────┐\n│ (index) │  a  │  b  │\n├─────────┼─────┼─────┤\n│    0    │  1  │ 'Y' │\n│    1    │ 'Z' │  2  │\n└─────────┴─────┴─────┘\n"} []
```

This condition seems to be responsible of the additional line breaks:

https://github.com/Seldaek/monolog/blob/334b8d8783a1262c3b8311d6599889d82e9cc58c/src/Monolog/Formatter/LineFormatter.php#L159-L161

What do you think? Is this the wanted behavior?

**Comment by Seldaek** [comment]
I think maybe we could add another option in monolog 2 so that you can allow real line breaks, or optionally expand line breaks that have been inlined in json.

The way I use this, I never need the json to be actual json, and I don't wanna bother putting placeholders to get the expanded value in the message.. I just want to get whatever is in the context including line breaks.

**Comment by HenkPoley** [comment]
This also bites when parts of the path on Windows starts with an 'n' or an 'r' and you throw an exception. See the linked issue above.
