### ISSUE TITLE
New release for 1.x branch

### ISSUE THREAD

**Issue by xelan** [Seldaek/monolog#1196]
Hi @Seldaek!

First of all, thank you very much for creating and maintaining this awesome logging library. Just a quick question: What is the plan for a new 1.x release? The current release 1.23.0 is more than a year old, it would be great to have the recent fixes included in a stable release.

Thank you very much, best regards from Austria
Andreas

**Comment by gor-galaxy** [comment]
+1

**Comment by Seldaek** [comment]
https://github.com/Seldaek/monolog/releases/tag/1.24.0 is out!
