### ISSUE TITLE
Testing Monolog with vfsStream

### ISSUE THREAD

**Issue by babicaja** [Seldaek/monolog#1198]
I'm trying to test the log messages created with my app and I decided to do so with [vfsStream](https://github.com/mikey179/vfsStream)

To Whom It May Concern, vfsStream creates a virtual file system and replaces regular file/directory paths with urls of type _vfs://root/exampleDir/exampleFile.log_  

I am using a simple monolog isntance with a StreamHandler handler.
When i run my test with the vfsStream, at the moment when the StreamHandler writes the message, an error is thrown because of the StreamHandler->getDirFromStream() function.
```php
    /**
     * @param string $stream
     *
     * @return null|string
     */
    private function getDirFromStream($stream)
    {
        $pos = strpos($stream, '://');
        if ($pos === false) {
            return dirname($stream);
        }

        if ('file://' === substr($stream, 0, 7)) {
            return dirname(substr($stream, 7));
        }
        return;
     }
```

The null return at the end is triggered, and the code afterwards breaks, and an error is thrown.

There is a quick work-around, everything works like a charm if I add a new if clause in the  above function:

```php
    if ('vfs://' === substr($stream, 0, 6)) {
        return dirname($stream);
    }
```

Is there a better way of running monolog with vfsStream or is this something that qualifies for a pull request?

**Comment by stof** [comment]
Well, this method is only used to create the folder meant to contain the file in case it does not exist yet (if null is returned, the directory is not created, and may need to exist already depending on what the stream implementation supports).

I'm not sure making a special case for `vfs` makes sense here

**Comment by babicaja** [comment]
I do agree. Tell you what, I'll try to solve the problem is some other manner, if it is something useful or general I'll post a new issue or pull request.
Thank you for the quick answer @stof

**Comment by babicaja** [comment]
Ah, not really.. 
The **getDirFromSteam** will always fall to the last return, which is null, and that will make **$dir** null and an **UnexpectedValueException** in **StreamHandler->createDir()** regardless of the existence of the vfs:// folder.

**Comment by stof** [comment]
if the method returns null, the code throwing the exception is never reached

**Comment by babicaja** [comment]
Anyway, for the sake of anyone testing with vfsStream, the solution is - as you said - to pre-mock the directory structure and even the log files. This will help to avoid any problems we discussed above.
