### ISSUE TITLE
integration with telegram

### ISSUE THREAD

**Issue by eerison** [Seldaek/monolog#1201]
exists some way to do integration with **telegram**?
If There are not is a good idea to create a new Handler to it?

**Comment by xelan** [comment]
Should be quite easy, create a new handler similar to the `SlackWebhookHandler` but using the Telegram API [sendMessage](https://core.telegram.org/bots/api#sendmessage) endpoint. The Bot API token and the Telegram Chat ID of the recipient must be included in the request.

**Comment by xelan** [comment]
Maybe [this project](https://github.com/ide2/TelegramHandler) can already do what you want?

**Comment by Seldaek** [comment]
Yup, seems like the linked handler is already usable.
