### ISSUE TITLE
NormalizerFormatter treatment of broken encodings

### ISSUE THREAD

**Issue by UlrichEckhardt** [Seldaek/monolog#1203]
Just as a the background for this: We had issues writing to a database which caused an exception with "Incorrect string value: '\xFCnde' for column..." as message, i.e. a string with a byte value 0xFC in a UTF-8 environment. This message was successfully logged to file, but it didn't end up in our JSON logs that are aggregated centrally, so we almost missed that error.

Now, what did I find out:

- The data loss occurs in JsonFormatter. It simply invokes `json_encode()` on the record containing that string, which fails. To me, that's perfectly correct, because JSON is required to use UTF-8.
- In JsonFormatter is also a small bug: The documentation for `toJson()` is pretty explicit that it returns a string, which it doesn't in this case. That non-string gets appended a newline, which then causes an empty line in the logfiles which we also observed. Basically, the error handling here doesn't handle this case fully.
 - A possible fix needs to be applied before that though, in order to make the record JSON-encodable. I would have expected this to happen in `normalize()`, but here the code becomes really non-obvious to me. Firstly, it doesn't use `normalize()` from the NormalizerFormatter baseclass. Then, the differences between the two implementations are not clear either, e.g. that the baseclass specially handles SoapFaults (related to https://github.com/Seldaek/monolog/issues/1183?). That may be a completely separate issue though.
 - As a suggestion, I would check whether a string passed to normalize is encoded as UTF-8. If it isn't, just escape the invalid bytes within using the "\xFC" syntax.

Workaround:
```
use Monolog\Formatter\JsonFormatter as MonologJsonFormatter;

/**
 * Workaround for a bug in the JSON encoder when it encounters invalid encodings.
 * 
 * The problem is that JSON requires UTF-8, so when it encounters non-UTF-8,
 * it just returns false which results in an empty line in our JSON log. This
 * workaround replaces the faulty bytes with a question mark, which is still
 * better than nothing.
 */
class JsonFormatter extends MonologJsonFormatter
{
    /**
     * Normalizes given $data.
     *
     * @param mixed $data
     *
     * @return mixed
     */
    protected function normalize($data)
    {
        $res = parent::normalize($data);
        if (is_string($res)) {
            $res = mb_convert_encoding($res, null, 'UTF-8');
        }
        return $res;
    }
}
```

**Comment by crossjoin** [comment]
I had a similar problem. I always got NULL in the logs instead of the exception details.

The problem was that I got an error from the database with a localized message not in UTF-8 (SQL Server, connected via PDO, error in German, used charset unknown).

My work-around was a custom LineFormatter with a replaced formatException()-method:

```
private function formatException(\Throwable $e): string
{
    $message = \iconv('UTF-8', 'UTF-8//TRANSLIT//IGNORE', $e->getMessage());
    $str = '[object] (' . Utils::getClass($e) . '(code: ' . $e->getCode() . '): ' . $message . ' at ' . $e->getFile() . ':' . $e->getLine() . ')';
    if ($this->includeStacktraces) {
        $str .= "\n[stacktrace]\n" . $e->getTraceAsString() . "\n";
    }

    return $str;
}
```

I think this would also be useful for other formatters.

**Comment by Seldaek** [comment]
Yup the problem is solving this in a generic way means calling expensive charset conversion functions on every log record's value, which is in 99.99% of cases not needed, only to fix the few odd cases where people log non-UTF-8 text.. which IMO in 2020 should not happen anymore. So for that reason I think this is rather a won't-fix on our end sorry.

**Comment by Seldaek** [comment]
Actually coincidentally https://github.com/Seldaek/monolog/issues/1446 pointed out a solution to this which is much better, only for PHP 7.2 though and only for Monolog 2, but long term at least this can be considered fixed I believe.
