### ISSUE TITLE
Logger.php and PHP 7.0.27

### ISSUE THREAD

**Issue by NisSunPro** [Seldaek/monolog#1205]
simbol `?` before variable `DateTimeZone`.
My PHP version 7.0.27 returned `AH01215: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in path/to/src/Monolog/Logger.php on line 148`

**Comment by xabbuh** [comment]
Monolog 2 requires PHP 7.1: https://github.com/Seldaek/monolog/blob/master/composer.json#L16

**Comment by trickeyone** [comment]
@xabbuh Except there is no Monolog 2

**Comment by xabbuh** [comment]
There is no stable release yet, but you can of course already install it when allowing dev packages. How did you install Monolog?

**Comment by trickeyone** [comment]
With composer. I know the documentation says Monolog 2 for 7+, but since there isn't a Monolog 2 (yet), telling someone to use it seems unhelpful. And since PHP 5.6 loses support after December, PHP 7+ support is becoming more urgent. I opened my own question (#1206) asking about this.

**Comment by xabbuh** [comment]
If you are stuck on PHP 7.0, you can just stay on Monolog 1. It's fully compatible with PHP 7. For 2.x it's just the other way around: you are required to have PHP 7.1 or higher.

**Comment by trickeyone** [comment]
I'm not stuck on PHP 7.0, in fact I'm on 7.2. That's the reason I bring the lack of the Monolog 2 you keep mentioning. It hasn't been released.

**Comment by xabbuh** [comment]
Ah sorry, about that. I was a bit confused as the initial issue description was about PHP 7.0 and I didn't notice that you are not the reporter. :)
