### ISSUE TITLE
Monolog 2.0 ?

### ISSUE THREAD

**Issue by trickeyone** [Seldaek/monolog#1206]
More of a question than an issue. I see in the README.md that Monolog 2.x is compatible with PHP 7+, but I don't see a Monolog 2.x anywhere. All releases have been 1.x. To get 2.x, would we have to go "bleeding edge" and use dev-master? I see issues open since 2016 in regards to 2.0, so this is a little confusing as to when 2.0 will be released, especially in light of the deprecation and discontinued support for PHP 5.6 in December 2018.

**Comment by Seldaek** [comment]
Monolog 1.x does support PHP 7.3 and will be updated for 7.4/8 most likely if there is any need to. Monolog 2.x will be released whenever it's ready, which is hopefully not too far away, but that's all I can say.

**Comment by trickeyone** [comment]
Thanks for the reply, @Seldaek . It might be helpful to update the documentation to help alleviate confusion like I had.
