### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by LuizKrlz** [Seldaek/monolog#1207]
I'm trying to implement laravel + monolog + elasticsearch, and I'm having problems with memory allocation. "Maximum function nesting level of '256' reached, aborting!" and "Allowed memory size of 134217728 bytes" has configured the following:
```php
 'stderr' => [
             'driver' => 'monolog',
             'level' => 'error',
             'handler' => \ Monolog \ Handler \ ElasticSearchHandler :: class,
             'handler_with' => [
                 'host' => 'http://elasticsearch',
                 'port' => '9200'
             ],
             'formatter' => \ Monolog \ Formatter \ ElasticaFormatter :: class,
             'formatter_with' => [
                 'index' => 'test',
                 'type' => 'record'
             ]
         ],
```
Can anyone help me or instruct me if something I'm doing wrong?

**Comment by aivus** [comment]
Hi @LuizKrlz 

> Maximum function nesting level of '256' reached, aborting!

It caused by xdebug. Because it has default value 256 for `xdebug.max_nesting_level` property (https://xdebug.org/docs/basic). Try to disable xdebug at all or increase value for this property.

> Allowed memory size of 134217728 bytes

This is around 128 MB. Try to increase your `memory_limit` in `php.ini`

**Comment by akalongman** [comment]
@LuizKrlz which version of Monolog you use?
