### ISSUE TITLE
JsonSerializable implementation for DateTime

### ISSUE THREAD

**Issue by Olegf13** [Seldaek/monolog#1220]
Hello. Found next change in repo history committed in master but not yet included into any release - https://github.com/Seldaek/monolog/blob/6bb347c040bb29f42c2c249714aac8c0e36c2454/src/Monolog/DateTimeImmutable.php

Is there a way to include this change in one of nearest releases for the 1.x branch?

**Comment by Olegf13** [comment]
Sorry, forgot to describe the problem. At the moment in case of using `JsonFormatter` there is a problem with datetime to json serializing. Result log looks like the following:

```
"datetime":{"date":"2018-11-06 17:41:54.310231","timezone_type":3,"timezone":"Europe/Moscow"}
```

**Comment by moderndeveloperllc** [comment]
@Olegf13 That whole calls is part of the "2.x" release code in master. It won't be released until @Seldaek is happy with the state of `master` and creates that release. I've been using `dev-master` in my `composer.json` files for a couple of years now. He keeps a tight quality control over what gets in, so it's reasonable safe.

**Comment by Seldaek** [comment]
See https://github.com/Seldaek/monolog/milestone/1 - we're getting there.

**Comment by Olegf13** [comment]
@moderndeveloperllc, @Seldaek thank you for your answers!
