### ISSUE TITLE
Affiliation with Checkgit?

### ISSUE THREAD

**Issue by adlawson** [Seldaek/monolog#1224]
I'm assuming there's no affiliation between this project and CheckGit, but thought it was worth raising. No doubt they're just scraping source for emails 🤢 

![image](https://user-images.githubusercontent.com/200351/48470398-3822c880-e7e9-11e8-95ca-670a6df8a7ad.png)

**Comment by Seldaek** [comment]
I have never heard of CheckGit, sorry they're spamming you..
