### ISSUE TITLE
Documentation on https://seldaek.github.io/monolog

### ISSUE THREAD

**Issue by baiolo** [Seldaek/monolog#1226]
I've experienced a weid behavior on some links in the official documentation, clicking a link like [https://seldaek.github.io/monolog/src/Monolog/Handler/StreamHandler.php](https://seldaek.github.io/monolog/src/Monolog/Handler/StreamHandler.php), the browser is asking me to save the page rather than opening the page, any confirmation ?

**Comment by gmponos** [comment]
Github does not execute php... it's github issue not monolog.. it can happen to any github page that has php.

**Comment by Seldaek** [comment]
Interesting.. That's pretty silly though. Maybe I should link to https://github.com/Seldaek/monolog/blob/master/README.md instead then as doc URL, because this is kinda unusable.
