### ISSUE TITLE
Change the level numbers on 2.0

### ISSUE THREAD

**Issue by gmponos** [Seldaek/monolog#1233]
Hello.. I remember seeing at a specification that log level numbers are with an inverted order from the ones of monolog. So DEBUG = 600 and not 100..

I can try and find out but I was wondering if you already know about it... if you do is there any chance these levels could match the one of the specification?

**Comment by Seldaek** [comment]
That's part of the syslog spec AFAIK (https://en.wikipedia.org/wiki/Syslog#Severity_level), but I am not sure if it's worth breaking this in 2.0 or not to be honest. Not quite sure what the impact of this would be. Also these severities have no gap in between so you can't insert new levels between existing ones, which is possible with monolog's level. Again I am not sure if this is something people do or not.. The bottom line is this doesn't seem to be a real problem in practice as the numbers are mostly only used internally.

**Comment by gmponos** [comment]
OK.. I have no more feedback to give on this issue... Since you are aware of it and you feel that it will break a lot of stuff you can close it 👍  😄
