### ISSUE TITLE
Use SlackWebHookHandler in 1.17.2 version

### ISSUE THREAD

**Issue by imranbaloch** [Seldaek/monolog#1238]
I have old giant application where we need to use SlackWebHookHandler but for some reasons we can't update monolog version. We are using 1.17.2 version. Is it possible just grab some classes from source (like SlackWebHookHandler.php) and keep it inside the project. Is it possible possible to use it temporary?

**Comment by gmponos** [comment]
Maybe my package could help you if you have PHP 7.1.. 
https://github.com/gmponos/monolog-slack , v1.0.0. can be installed with all monolog versions.

Otherwise you could just copy-paste the class and initialize it your own.
