### ISSUE TITLE
SlackWebhookHandler ignores username and iconEmoji

### ISSUE THREAD

**Issue by scuben** [Seldaek/monolog#1247]
Despite sending the `username` and `iconEmoji` to the slack webhook it wont be considered by slack to write the message to the channel. In slack it will always use the username and icon of the slack app.

Is this the current normal behaviour? Should then the `username` and `iconEmoji` options be deprecated/removed? Or do I wrongly use the SlackWebhookHandler?

From the slack [documentation](https://api.slack.com/incoming-webhooks):

> You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.

**Comment by gmponos** [comment]
I haven't tried to override the channel but this image is from an application that I've been using my own custom slack implementation and I have successfully overridden `username` and `icon`

**Comment by gmponos** [comment]
example [here](https://monosnap.com/file/BCn6M48HDbNDWvGJCmNQxCRy7eZ1MG)

**Comment by matthewpoer** [comment]
I can confirm that I'm using `SlackWebhookHandler` and I can adjust both `$username` and `$iconEmoji`. I created my `$webhookUrl` in the Incoming Webhook section of my Slack settings @ `https://your-slack-app.slack.com/apps/A0F7XDUAZ-incoming-webhooks`

I have noticed that when I use Slack's app the icon doesn't show up (I don't use it often, and I don't recall if the username shows up as desired or not). Slack's MacOS app and web app both show the desired username and avatar settings.

Documentation on the Incoming Webhooks page notes the following:
> **Customized Appearance** You can customize the name and icon of your Incoming Webhook in the Integration Settings section below. However, you can override the displayed name by sending `"username": "new-bot-name"` in your JSON payload. You can also override the bot icon either with `"icon_url": "https://slack.com/img/icons/app-57.png"` or `"icon_emoji": ":ghost:"`.

My `composer.lock` shows me the `monolog` version in use:
```
            "name": "monolog/monolog",
            "version": "1.x-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/Seldaek/monolog.git",
                "reference": "4d5b7e6ba1127789c7ff59d6f762298eaa29787f"
            },
```
