### ISSUE TITLE
addRecord function on Logger still exists

### ISSUE THREAD

**Issue by gmponos** [Seldaek/monolog#1250]
Reading the upgrade guide:

> Removed non-PSR-3 methods to add records, all the add* (e.g. addWarning) methods as well as emerg, crit, err and warn.

I would've expect that `addRecord` [function](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php#L284) would have been removed as well since `log` function of PSR-3 exists... 

Is this by design or it was missed?

**Comment by Seldaek** [comment]
That one works with internal monolog levels only, that's why I kept it, it's kind of there to avoid calling toMonologLevel all the time.
