### ISSUE TITLE
What's this "?string"?

### ISSUE THREAD

**Issue by centurianii** [Seldaek/monolog#1262]
I loaded with my own loader module and I receive this:
```
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/test/server/Monolog/Registry.php on line 55
```
The line is this one:
```
public static function addLogger(Logger $logger, ?string $name = null, bool $overwrite = false)
```

Am I missing sth here?

**Comment by stof** [comment]
That's PHP 7.1+ code. That's a nullable typehint.

**Comment by centurianii** [comment]
Ok,
```
php -v
PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.32-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```
still don't get it!

**Comment by hkdobrev** [comment]
@centurianii You need to have at least PHP 7.1 to run this code. See http://php.net/manual/en/migration71.new-features.php Latest Monolog requires PHP 7.1+.

**Comment by centurianii** [comment]
Are there any older versions without superfluous php 7.1?

**Comment by xabbuh** [comment]
All Monolog 1.x releases support PHP 5.3 to 7.0 too.

**Comment by centurianii** [comment]
Thank you I'll have a look.
