### ISSUE TITLE
PHP Fatal error: Allowed memory size exhausted when log directory not writable

### ISSUE THREAD

**Issue by tonivdv** [Seldaek/monolog#1263]
Hi,

Following got me down the rabbit hole ... I've build a docker image for our php symfony web app in production. While everything worked perfectly in development (same base image), it didn't work in production. Immediately got following error:

```
[18-Dec-2018 09:09:26] WARNING: [pool www] child 16 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107"
```

Initially I thought it was related to a too low memory settings in php ini file, but after some hours of trial and error I realized I forgot to make the var/log directory writable ...

It seems, when the log directory is not writable a memory leak occurs ... 

Not sure if it's an issue in monolog per-se, but I wanted to share this as it could prevent others from wasting time on this.

Cheers

**Comment by tonivdv** [comment]
Is it not possible to throw an error saying the location to write the log
to is not writable?

**Comment by Seldaek** [comment]
We do at https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L107-L110 so I am not sure what issue you encountered.

**Comment by tonivdv** [comment]
I'm on the road today, but I'll try to figure it out. Thx

On 26 Dec 2018 15:42, "Jordi Boggiano" <notifications@github.com> wrote:

We do at
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L107-L110
so I am not sure what issue you encountered.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Seldaek/monolog/issues/1263#issuecomment-449975667>,
or mute
the thread
