### ISSUE TITLE
Duplication of Messages in Log

### ISSUE THREAD

**Issue by crayner** [Seldaek/monolog#1293]
I have been experiencing a duplication of messages in the log.  This may be because of a poor setup structure on my part, and eventually I will find some time to debug the setup structure.  In the meantime, I worked out that if I check the handler being pushed to the logger, and reject if already set, my duplication issue disappears.  
Hope this helps.  The PR is [#1292](https://github.com/Seldaek/monolog/pull/1292)

**Comment by Seldaek** [comment]
Closing as per https://github.com/Seldaek/monolog/pull/1292#issuecomment-507048805 - this can easily done by extending the Logger class if you really want though.
