### ISSUE TITLE
Proposal: RotationDetectionHandler

### ISSUE THREAD

**Issue by eightnoteight** [Seldaek/monolog#1294]
monolog already has `RotatingFileHandler`, which has worked for us greatly for a long time, but it doesn't offer as much customization as the logrotate does and the doc string mentions this.

our worker environment has php processes which run for more than 10 days a few running from 2-5 months, if we choose `StreamHandler`, over time the logrotate is rotating the files but unfortunately since the file is not closed, the rotation file doesn't have any affect and in somecases backfired on us when logrotate deletes the file and the php worker is still holding onto the file, our filebeat was not able to pick that file.

using `RotatingFileHandler` helped us a lot, but since it only supports daily rotation, a few workers are printing a lot of logs > 20G and our filebeat is able to push them to upstream but since its daily rotation we had to waste a lot of disk space. as a workaround I wrote a rotation detection handler which detects any rotation being done by the logrotate and the handler gracefully closes the file to be opened at the same by `StreamHandler` on the next write, and this solved our problems.

Please let me know if it sounds good, will make a PR

**Comment by Seldaek** [comment]
Sounds interesting to fix this problem in StreamHandler, if it's not too much code or too much slowdown I think it'd be good if it supports logrotate without problems.
