### ISSUE TITLE
Handlers using CURL

### ISSUE THREAD

**Issue by aquaticpond** [Seldaek/monolog#1295]
On some networks IPv6 resolution fails and falls back to IPv4 but it takes 10+ seconds for this to happen and complete the request.

`curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);`

Telling CURL to resolve to IPv4 with the above option solves this issue. Unfortunately it might not be feasible to default to IPv4 for everything though...

**Comment by Seldaek** [comment]
That sounds like you should fix the network rather than the curl code :)
