### ISSUE TITLE
Dedicated SentryHandler

### ISSUE THREAD

**Issue by pkruithof** [Seldaek/monolog#1298]
Since the sentry-php has just had a [big refactoring](https://github.com/getsentry/sentry-php/releases/tag/2.0.0), it seems time to integrate this into a new handler. The current one is the `RavenHandler`, and from what I can find, Raven is the legacy SDK for Sentry. So I'm proposing a new `SentryHandler` which is compliant with `sentry-php:^2`.

If this would be considered I could have a PR later today. Please let me know.

**Comment by alfredbez** [comment]
Take a look at #1273 and https://github.com/getsentry/sentry-php/issues/790

**Comment by pkruithof** [comment]
Thank you, I had not found these issues before. Closing this one then.
