### ISSUE TITLE
Is it use sentry's breadcrumbs?

### ISSUE THREAD

**Issue by eerison** [Seldaek/monolog#1301]
I'm trying to create a custom [breadcrumb](https://sentry.io/features/breadcrumbs/) But I have not seen any way to do this

**Comment by fmasa** [comment]
@eerison Monolog does not provide support for monolog breadcrumbs. You have two options:
- use https://github.com/getsentry/sentry-php/blob/1.10.0/lib/Raven/Breadcrumbs/MonologHandler.php with older Sentry SDK (worse option IMO, as newer version of SDK is straightforward to integrate)
- use new Sentry SDK and implement breadcrumbs yourself ([implementation example](https://github.com/getsentry/sentry-php/issues/790#issuecomment-509737779))

**Comment by B-Galati** [comment]
@eerison Hello!

I did one and try to contribute it -> getsentry/sentry-php#844 but it's been rejected for some reasons that you can see in my PR. Quite sad about it.

**Comment by B-Galati** [comment]
@eerison I released a dedicated Library if you are interested -> https://github.com/B-Galati/monolog-sentry-handler
