### ISSUE TITLE
Confusing [array] usage for a Record model

### ISSUE THREAD

**Issue by nitso** [Seldaek/monolog#1302]
Hi!

Using an array model for a Record (in internals) confuses me when working with monolog.
Adding a record interface will clean up method signatures and internal structure.

What do you think about refactoring? Is it worth a PR?
I suppose that changes must be either backwards compatible or cause a new major version.

**Comment by Seldaek** [comment]
Sorry that it's confusing you but I find it simpler and not necessary to have objects as records..

**Comment by stof** [comment]
and such change cannot be backward compatible (as both processors and handlers deal with the record, and they are both extension points)
