### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [Seldaek/monolog#1305]
Greetings, I'm here today to offer my services. As a graphic designer in development and an open source enthusiast, I wish to contribute to this wonderful project by making a logo for it, the process (of course) is totally free and we would be working together to create the design that fits best with your project. Of course, you can quit whenever you want. In case you agree, I would like to ask you a few simple questions about your project to have a better understanding of it and so deliver a better product, also you could share with me any preferences you may have about colors, shapes, etc.

Sorry for disturbing if this is not the proper channel, kind regards.

**Comment by Seldaek** [comment]
Hey, thanks for the offer but a logo isn't really a top priority and time is limited (as you can see from the delay responding to this..) so probably not worth wasting your time on this :)
