### ISSUE TITLE
Rocket Chat Support

### ISSUE THREAD

**Issue by lucassmacedo** [Seldaek/monolog#1310]
Hello. This package has suporte to Rocket Chat?

**Comment by lucassmacedo** [comment]
any?

**Comment by lucassmacedo** [comment]
?

**Comment by Seldaek** [comment]
Sorry for lack of details, but no we are not going to support it.. Feel free to create your own handler and publish it as an additional package though, see https://github.com/Seldaek/monolog/wiki/Third-Party-Packages for other examples
