### ISSUE TITLE
Unused variable `depth` in JsonFormatter

### ISSUE THREAD

**Issue by rdohms** [Seldaek/monolog#1317]
In the `formatException` method, the parameter `depth` is never used. Wondering if it should or if it can be removed completely.

https://github.com/Seldaek/monolog/blob/0ad73a526f4b5e67312e94fb7f60c1bdefc284b9/src/Monolog/Formatter/JsonFormatter.php#L167

**Comment by Seldaek** [comment]
Not sure what you mean, $depth is used below in that function.

**Comment by rdohms** [comment]
🤦‍♂ I think i was drunk and tired.
