### ISSUE TITLE
ZendMonitor TypeError

### ISSUE THREAD

**Issue by happydude** [Seldaek/monolog#1323]
Getting a TypeError in 2.0.0-beta1,

./vendor/monolog/monolog/src/Monolog/Handler/ZendMonitorHandler.php:68
zend_monitor_custom_event() expects parameter 1 to be string, integer given

Documentation at http://files.zend.com/help/Zend-Server/content/zendserverapi/zend_monitor-php_api.htm#function-zend_monitor_custom_event

Based on the zend server documentation
https://github.com/Seldaek/monolog/blob/ebb804e432e8fe0fe96828f30d89c45581d36d07/src/Monolog/Handler/ZendMonitorHandler.php#L68
 should be something like

```
zend_monitor_custom_event('',$message, $formatted, $level);
```

In addition the levelMap is not compatible with zend server monitor, they only support three log levels:
```
var_export(
[
	'ZEND_MONITOR_EVENT_SEVERITY_INFO' => \ZEND_MONITOR_EVENT_SEVERITY_INFO,
	'ZEND_MONITOR_EVENT_SEVERITY_WARNING' => \ZEND_MONITOR_EVENT_SEVERITY_WARNING,
	'ZEND_MONITOR_EVENT_SEVERITY_ERROR' => \ZEND_MONITOR_EVENT_SEVERITY_ERROR
]);
```
outputs
```
array (
  'ZEND_MONITOR_EVENT_SEVERITY_INFO' => -1,
  'ZEND_MONITOR_EVENT_SEVERITY_WARNING' => 0,
  'ZEND_MONITOR_EVENT_SEVERITY_ERROR' => 1,
)
```

**Comment by Seldaek** [comment]
If you have time to send a PR, the handler would ideally adjust its behavior based on the version of ZendServer present, I am not familiar enough with it to say how to detect that.. Please target the 1.x branch for a fix.

**Comment by happydude** [comment]
I did not find a way to detect zend server version, but the newer style should be compatible with zend server 6 (php 5.3) and newer.

I did not commit it, but the tests passed with declare(strict_types=1).
