### ISSUE TITLE
Wrong DocBlock annotation in ErrorHandler::register causes static analyses to fail (again)

### ISSUE THREAD

**Issue by Aerendir** [Seldaek/monolog#1324]
The full description of the problem is described at #1066 and was fixed by PR #1067 .

In [version `1.23.0`](https://github.com/Seldaek/monolog/compare/1.23.0...master#diff-157e26b619888e5e125fcb22b919ea41R56) the DOCblock is correct.

Also in the [version `1.24.0`](https://github.com/Seldaek/monolog/compare/1.24.0...master#diff-157e26b619888e5e125fcb22b919ea41R56) the code seems to be right.

**But downloading the code, the code is the old one, with the wrong DOCblock that causes issues with static analysis.**

This happen both downloading version `1.24.0` with composer or downloading it directly from GitHub.

Any feedback on this?

**Comment by xabbuh** [comment]
I don't see the line you mention on GitHub: https://github.com/Seldaek/monolog/blob/1.24.0/src/Monolog/ErrorHandler.php#L58

**Comment by Aerendir** [comment]
@xabbuh , you don't see the line? What does this means?

You should see this:

    @param  int|false       $fatalLevel     a LogLevel::* constant, or false to disable fatal error handling

while it should be:

    @param  string|null|false $fatalLevel        a LogLevel::* constant, null to use the default LogLevel::ALERT or false to disable fatal error handling

**Comment by xabbuh** [comment]
What I just mean is that even when you look at the code on GitHub for the 1.4.0 tag it still contains the old code. #1067 was merged into `master` which is for Monolog 2 and thus this was not part of the 1.4.0 release.

**Comment by Aerendir** [comment]
@xabbuh , ok, I missed this part: thank you for the clarification! So I need to wait for the version 2 of monolog... Any ideas about the release date?
