### ISSUE TITLE
Warning:  count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by arnolem** [Seldaek/monolog#1326]
https://github.com/Seldaek/monolog/blob/ebb804e432e8fe0fe96828f30d89c45581d36d07/src/Monolog/Handler/RotatingFileHandler.php#L138

> Warning: count(): Parameter must be an array or an object that implements Countable in [...]/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php on line 137
> 
> Call Stack:
>     0.8178   11272032   1. Monolog\Handler\RotatingFileHandler->__destruct() [...]/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php:0
>     0.8178   11272032   2. Monolog\Handler\RotatingFileHandler->close() [...]/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php:170
>     0.8178   11271560   3. Monolog\Handler\RotatingFileHandler->rotate() [...]/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php:65
>     0.8179   11271560   4. count() [...]/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php:137

I have :
`$this->filename = './logs/app/debug.log'`
But, the value of **\getcwd()** after **__destruct()** is **"/"**
https://stackoverflow.com/questions/14678947/why-does-getcwd-returns-in-destruct/14679008

glob() function don't find files with relative path on "/"

**Comment by Seldaek** [comment]
Interesting find.. So this doesn't work because of the relative filename. I guess doing a `$this->filename = realpath(pathinfo($filename)) . '/' . basename($filename)` in the constructor would fix it? Can you try and confirm that?

**Comment by arnolem** [comment]
Hello, yes, it works but it would be nice if it also works with relative paths
