### ISSUE TITLE
Send unsent errors in RavenHandler

### ISSUE THREAD

**Issue by s7anley** [Seldaek/monolog#1329]
Hi,

in 1.24.0 the reset method was introduced and it should be used to flush pending message in for example worker. `Raven_Client` could be configured to not send event immediately by property `store_errors_for_bulk_send`.  In that scenario, the messages/events will be flushed only when the worker is restarted.

Maybe we should send them when the logger is reset in RavenHandler? E.g. 

```php
public function reset()
{
    $this->ravenClient->sendUnsentErrors();

    parent::reset();
}
```

**Comment by Seldaek** [comment]
Sounds reasonable to me, feel free to send a pull request for the 1.x branch. The RavenHandler will be deprecated though as Sentry now ships their own handler, so I'd suggest making sure that one handles things correctly as well.

**Comment by s7anley** [comment]
Thanks, I will send MR soon.
