### ISSUE TITLE
Monolog Slack handler is not working

### ISSUE THREAD

**Issue by moda20** [Seldaek/monolog#1332]
hey !

I am trying to use slack handler in monolog but couldn't make it to work. 

I created an APi key and integrated the app in my channel and gave it writes to write in it via the slack Web interface.

and i am using this code to send the error : 
Note: this is a test code.

```
$slackHandler = new \Monolog\Handler\SlackHandler('xoxp********', '#debugerrors');
$slackHandler->setLevel(\Monolog\Logger::ERROR);
$slacklogger = new Monolog\Logger("debugerrors");
$slacklogger->pushHandler($slackHandler);
$Messages ="Logging";
$slacklogger->error($Messages);
```

I just ook that code straight from a tutorial, so I don't see where I could have gone wrong.

is this a recurring problem with slack ? emails and file saving do work.

**Comment by matthewpoer** [comment]
I had issues with `SlackHandler` but found the `SlackWebhookHandler` very easy to work with, e.g.:

```php
$this->log = new Monolog\Logger('log title');
$this->log->pushHandler(new Monolog\Handler\SlackWebhookHandler(
  SLACK_WEBHOOK_URL, // create URL in https://your-slack-app.slack.com/apps/A0F7XDUAZ-incoming-webhooks
  SLACK_CHANNEL, // e.g. #general
  'someUsername', // username, no @ prefix, can be made-up
  true, // use-attachment flag, affects formatting of message
  'red_circle', // iconEmoji flag, the avatar associated with the message, can be a custom icon
  false, // useShortAttachment flag, affects formatting of the message
  true, // includeContextAndExtra, how much of the context is sent into Slack channel
  Logger::WARNING // level of message to send in to Slack
));

```

**Comment by pnoeric** [comment]
Just to add - yeah, the SlackHandler seems out of date and non-functional, but SlackWebhookHandler works great and is very easy to set up/use.

**Comment by seferov** [comment]
I just integrated `Monolog\Handler\SlackHandler` and it works!

```php
$logger = new Logger('jira-ci');
$logger->pushHandler(new SlackHandler(
    getenv('SLACK_TOKEN'),
    getenv('SLACK_CHANNEL'),
    getenv('SLACK_USERNAME'),
    true,
    null,
    Logger::INFO
));
$logger->info('lorem ipsum');
```

**Comment by gmponos** [comment]
If you guys are interested I have also created a package like this: https://github.com/gmponos/monolog-slack/

**Comment by dinoluck** [comment]
Since Slack deprecated Incoming Webhooks, is there a way to get SlackHandler working?
