### ISSUE TITLE
How can I display PHP Parse errors in the monolog log file?

### ISSUE THREAD

**Issue by josephkang619** [Seldaek/monolog#1333]
I am going to use the monolog library to view all the php logs. In the case of PHP parse errors, only the www-error.log file is logged. Any subsequent code will not work. Can I use Monolog to display PHP Parse errors?

Thanks for reading.

I tried the following test code:

```php
// create a log channel
$logger = new Logger('test');
$handler = new RotatingFileHandler('../log/test.log', 0, Logger::DEBUG);

$handler->setFilenameFormat('{filename}-{date}', 'Ymd');

$error_log_handler = new \Monolog\Handler\ErrorLogHandler();

$logger->pushHandler($handler);
$logger->pushHandler($error_log_handler);

// ErrorHandler::register($logger);

$error_handler = new ErrorHandler($logger);
$error_handler->registerErrorHandler(array(), false);
$error_handler->registerExceptionHandler();
$error_handler->registerFatalHandler();

$logger->debug('------- test.php');

if $x==1 {
   echo "Hello World!";
}
```

I expected the logs shown in the **www-error.log** file to be displayed in the monolog log file as follows, but nothing was recorded, including '------- test.php'.

www-error.log Log output: [13-Jun-2019 08:56:53 UTC] PHP Parse error: syntax error, unexpected '$x' (T_VARIABLE), expecting '(' in /home/kinimall/m/test.php on line 70

**test-20190613.log (monolog) Log output is nothing.**

**Comment by Seldaek** [comment]
This should work but not if the parse error is in the same file as the file that sets up monolog, because in that case the monolog config won't ever be executed, php fails with a parse error before it even starts executing that file. If you split it in two files and move the broken if block to an `include 'broken.php';` I believe it should work.

**Comment by mdjaman** [comment]
Sorry i know it is a very old post but how to display the entries of log files?
