### ISSUE TITLE
Exception during flush BufferHandler

### ISSUE THREAD

**Issue by medinskiy** [Seldaek/monolog#1335]
I use ElasticSearchHandler with BufferHandler.
When the script is shut down and the \Monolog\Handler\BufferHandler::close method is called, if ElasticSearchHandler throws an exception, it will not be processed by exceptionHandler, which I set to setExceptionHandler

**Comment by Seldaek** [comment]
Indeed it's a problem if the logging process fails that's generally leading to poor results.. Not sure what can be done about this, except making sure logging code is as bulletproof as possible.
