### ISSUE TITLE
Require PHP 7.2 in Monolog 2.x

### ISSUE THREAD

**Issue by Seldaek** [Seldaek/monolog#1337]
As per the discussion at  https://github.com/symfony/symfony/pull/27905 - the question is whether it's a good idea to require PHP 7.2. I don't think it brings a ton to monolog itself but it makes integration slightly easier in this case.

If anyone has feedback/opinions on this I'm all ears /cc @lyrixx

**Comment by derrabus** [comment]
My case in favor of requiring php 7.2 would be:
* php 7.1 is officially EOL in five months from now.
* Monolog 1 will not cease to exist when Monolog 2 comes out, so people can still use it if they can't upgrade php.
* php 7.2 allows you to add type-hints to parameters without breaking user-land implementations of your interfaces which is great for maintenance.

The latter helps a lot when creating a version of Symfony's MonologBridge that supports Monolog 1 as well as Monolog 2.

**Comment by stof** [comment]
:+1: to benefit from the parameter widening feature of PHP 7.2

**Comment by Seldaek** [comment]
Ok let's do this then :)
