### ISSUE TITLE
JsonFormatter with stacktaces may cause fatal errors and reveal sensitive data

### ISSUE THREAD

**Issue by andrei-e-random** [Seldaek/monolog#1346]
I'd propose a PR, but I'm not very familiar with the code. Plus some of the stuff in the second part is rather debatable and it is probably better to discuss it first. 

PHP:  7.2.15
Monolog: 1.24.0 ( I realize this is a slightly older version but the code in master which is causing the issue looks the same). 

To verify the crash, one can use almost exactly the code from #772, but:

1. Put the closure into method of a class which has a namespace. 
2. Use JsonFormatter instead of NormalizerFormatter  because the latter has been actually fixed (see at the end) by 3e92b08956da82867774ca8a8edef2472ab743f9 (which  fixes #1138)

```php
<?php

namespace MyIterators;

use ArrayIterator;

class SomeIter extends ArrayIterator
{
    public function next()
    {
        // Imagine some logic attempted to evaluate
        // current element but failed and throws exception
        throw new \Exception('Something bad');
    }
}

namespace MyNamespace;

use Monolog\Formatter\JsonFormatter;
use Monolog\Handler\ErrorLogHandler;
use Monolog\Logger;
use MyIterators\SomeIter;

class MyClass {

    public function process() {
        $handler = new ErrorLogHandler();
        $formatter = new JsonFormatter();
        $formatter->includeStacktraces();
        $handler->setFormatter($formatter);

        $logger = new Logger('name');
        $logger->pushHandler($handler);

        $array = [
            new SomeIter([1]),
            new SomeIter([2]),
        ];

        $result = \array_filter($array, function ($iter) use ($logger) {
            try {
                foreach ($iter as $elem) {
                    // don't care
                }
            } catch (\Exception $e) {
                $logger->error('Failed iterating.', ['exception' => $e]);
            }
        });

    }
}

$myObject = new MyClass();
$myObject->process();

```

The above code will cause a fatal uncaught exception, instead of just logging an error.

The problem lies in the `JsonFormatter` class:

```php
          foreach ($trace as $frame) {
                if (isset($frame['file'])) {
                    $data['trace'][] = $frame['file'].':'.$frame['line'];
                } elseif (isset($frame['function']) && $frame['function'] === '{closure}') {
                    // We should again normalize the frames, because it might contain invalid items
                    $data['trace'][] = $frame['function'];
                } else {
                    // We should again normalize the frames, because it might contain invalid items
                    $data['trace'][] = $this->normalize($frame);
                }
            }
```

Here `$frame['function']` is not `{closure}` but `MyNamespace\{closure}`. This causes the final else path to be evaluated.

_Suggested Fix_

I think the initial approach checking for closure and just putting in `$frame['function']` when a closure is detected is fine, except for the fact that ` $frame['function'] === '{closure}'` is not the complete way to do it. (maybe using some sort of `endsWith` function could do it). 

**Revealing sensitive data**

However, once the closure detection is fine we're still left with the fact the stacktrace may contain functions which will also contain args. That is somewhat mitigated for NormalizerFormatter  in 3e92b08956da82867774ca8a8edef2472ab743f9 - but there are some problems I see with that commit, the most important beeing that it does not touch the JsonFormatter - so the problem still exists for this one (not sure if there are other formatters which should be touched.

Another potential problem is that it still leaks the class name or the arguments. I'm not sure how can that be relevant at any point, but the class name themselves could be seen as data in certain (exotic?) circumstances.

Another potential problem is that the `$frame['file'].':'.$frame['line']` structure of the stacktrace is being not being respected for functions. This means that whoever is parsing the stacktraces from log files (I know, not many people do), will have to account for different possible formats for elements on the same array, which is, in my opinion, not ideal. 

_Suggested Fix_

I believe functions should be handled exactly the same way as closures when it comes to stacktraces: no information about args should be logged. 

If one decides to display some information about args for functions, then it should probably display the same information for closures as well. Ideally though whether those args are displayed should be controlled by a flag.

Either way, the 2 formatters should have the same behavior.

**Comment by Seldaek** [comment]
This normalizer stuff is really hard to get right yeah, there are so many use cases and ways it can go wrong.

Anyway.. I would say normalizing to the same structure for closures and functions makes sense for sure. Most calls are being formatted as `file:line`, only oddball calls reach the other branch, and were previously formatted using `function` + `args` keys.

#1363 is changing this second case to now be `($frame['class'] ? $frame['class'].$frame['type'] : '').$frame['function']` - i.e. `function` alone or `class::function` or `class->function`. This is still slightly different to `file:line`, but as the info is not available I don't see what we can do really, at least it's all simple strings now. What do you think?

**Comment by andrei-e-random** [comment]
> #1363 is changing this second case to now be ($frame['class'] ? $frame['class'].$frame['type'] : '').$frame['function'] - i.e. function alone or class::function or class->function. 

First, thank you! What you did will work for my purposes - it fixes both the crash and the revealing of sensitive data - as far as I am able to test it/reason about it right now. It also looks cleaner.

> This is still slightly different to file:line, but as the info is not available I don't see what we can do really, at least it's all simple strings now. What do you think?

One thing we can do is skip this frame from the trace. I might be missing something (I likely am since this is the first time I'm pondering on the issue), but right now I'm not seeing the relevance of information from this frame. It appears to be either useless, or obvious - depending on who is looking at the trace. Here's why:

It appears to me that there's nearly always going to be always another frame, just before it, which will contain the exact file and line number from within the closure. So this frame only shows us that the previous file+line number was part of a closure - which seems to be quite obvious for whoever will actually look at the code and quite useless for whoever is only looking at the trace.

It appears to me that the only case in which there's not going to be another frame before this one, is when the exception is thrown within a closure. In that case, the file and line number are already available with `$e->getFile().':'.$e->getLine()` (which you're already putting in `$data` - so the important info is already there). So this frame will tell us that the exception was thrown in a closure, which is similarly obvious for whoever actually looks at the code, and similarly useless for whoever is only looking at the trace.

Does that make sense, or am I way off?

**Comment by Seldaek** [comment]
Yeah I think that might well make sense :) I am also not 100% sure what this is good for. I tried many permutations and could not really identify where this is useful so maybe best to simply remove the else block entirely. I'll update the PR and merge it when I get a minute.
