### ISSUE TITLE
SyslogUdpHandler doesn't respect TimeZone

### ISSUE THREAD

**Issue by Pierre-Lannoy** [Seldaek/monolog#1350]
Hello all contributors, and thanks for this wonderful tool!

While trying 2.0.0-beta2 I found SyslogUdpHandler doesn't respect the timezone set in Logger.
I think this line is not fully compliant with timezone ;)
`
protected function getDateTime(): string
    {
        return date($this->dateFormats[$this->rfc]);
    }
`
Do you know how to proceed to fix it? Should I contact the author? Should I submit a PR (and if so, what's your input on how to do it in regards with the fact that TZ is now set to Logger class)?

Thanks.

**Comment by yi-yang-github** [comment]
This fix actually doesn't work when the datetime is `DateTimeImmutable`, I'll create a new ticket.
