### ISSUE TITLE
prefix context fields ?

### ISSUE THREAD

**Issue by nathanblogs** [Seldaek/monolog#1353]
Hi,

This seems like it should exists but my google foo seems to be failing me, we have an issue were the same context field gets set with different types eg:
```
Log::info('Example', ['id' => '1']);
Log::info('Example', ['id' => [1,2,3]);
```
This causes an index conflict and elasticsearch rejects the logs which is annoying.

I was thinking the context fields could be prefixed with there type so instead of ctxt_id being written to the log it could be `ctxt_array_id` or `ctxt_string_id`.

Is this possible, has it already been done ?

**Comment by Seldaek** [comment]
No idea, sounds like something you could do with a processor though, or a custom handler I guess.. I doubt this is something we can tackle in core really.
