### ISSUE TITLE
Replace swiftmailer with symfony/mailer?

### ISSUE THREAD

**Issue by bmack** [Seldaek/monolog#1354]
Hey,

are you interested in switching from SwiftMailer to symfony/mailer as require-dev for v2.0.0? If so, I'd be willing to create a PR for it.

Thanks for a quick info.
Benni.

**Comment by Seldaek** [comment]
IMO this should be shipped as a new handler in the symfony/monolog-bridge instead than here. The SwiftMailerHandler should remain a SwiftMailerHandler.. although we eventually should deprecate it I guess. Leaving this open as a task to deprecate it eventually..
