### ISSUE TITLE
remove replaced context when using psrlogmessageprocessor

### ISSUE THREAD

**Issue by mlsshrzr** [Seldaek/monolog#1356]
as far as i know, the psrlogmessageprocessor-class is designed to replace placeholders in messages like
```php
$logger->debug('{foo}', ['foo' => 'bar']);
```
after processing the message, the output is 
```php
"bar {'foo':'bar'}"
```
the replaced context still exists, even though the element 'foo' was properly replaced. 
why not remove that context, but keep the context which could not be replaced?
i tried do achieve this goal and this is my solution: (class PsrLogMessageProcessor.php)
```php
public function __invoke(array $record)
...
$newContext = array();
foreach ($record['context'] as $key => $val) {
    ...
    if (false === strpos($record['message'], '{'.$key.'}')) {
        $newContext[$key] = $val;
    }
}
$record['context'] = $newContext;
...
```
if the user wants to keep the context in his message, you could make it an option by introducing a boolean parameter in the constructor. 
what do you think about?

**Comment by Seldaek** [comment]
There is already a `$removeUsedContextFields` option in the PsrLogMessageProcessor in Monolog 2.0 so closing.
