### ISSUE TITLE
Get severity level via Processor

### ISSUE THREAD

**Issue by LeftPinkie** [Seldaek/monolog#1365]
Is there a way to get the severity level via a processor?  I would like to create a custom processor where:
```
$entry[ 'extra' ][ 'severity' ] = [ DEBUG (100) | INFO (200) | NOTICE (250) | WARNING (300) | ERROR (400) | CRITICAL (500) | ALERT (550) | EMERGENCY (600) ]
```

**Comment by Seldaek** [comment]
The severity name is available as level_name on the record already. You can take it from there and put it in extra, or use %level_name% in LineFormatter to get it in the logs
