### ISSUE TITLE
Adding extra data in the records causes FatalError

### ISSUE THREAD

**Issue by szaqal83** [Seldaek/monolog#1369]
This code causes FatalError:
`$logger->info('Adding a new user', array('0' => 'Test'));`
this doesn't:
`$logger->info('Adding a new user', array('a' => 'Test'));`
for logger handler BrowserConsoleHandler.

**Comment by Seldaek** [comment]
What's the fatal error? It'd help a lot if you posted it..

**Comment by szaqal83** [comment]
`Fatal error: Uncaught TypeError: Argument 2 passed to Monolog\Logger::info() must be of the type array, object given, called in /var/www/html/test/ad/ad.php on line 110 and defined in /var/www/html/test/ad/vendor/monolog/monolog/src/Monolog/Logger.php:497 Stack trace: #0 /var/www/html/test/ad/ad.php(110): Monolog\Logger->info('User', Object(Adldap\Models\User)) #1 {main} thrown in /var/www/html/test/ad/vendor/monolog/monolog/src/Monolog/Logger.php on line 497`
