### ISSUE TITLE
Missing Sentry.io handler?

### ISSUE THREAD

**Issue by markushausammann** [Seldaek/monolog#1377]
In the latest state of the codebase (master) I'm not seeing neither a SentryHandler nor a RavenHandler. What am I missing?

**Comment by alexandrmazur96** [comment]
`<captain obvious mode>` SentryHandler nor a RavenHandler `</captain obvious mode>`

**Comment by stof** [comment]
this is because the latest version of the Sentry SDK ships the Monolog handler by itself: https://github.com/getsentry/sentry-php/blob/master/src/Monolog/Handler.php

So there is no handler anymore in Monolog itself to wrap the SDK.

**Comment by markushausammann** [comment]
> latest version of the Sentry SDK ships the Monolog handler

that's what I was missing!
