### ISSUE TITLE
Weird severity levels -  RFC 5424

### ISSUE THREAD

**Issue by theduke** [Seldaek/monolog#138]
How did you arrive at the weird numerical values for the logging levels?

RFC5424 still defines the values as 7 for debug to 0 for emergency.
Pretty much every system I know uses those values.

The priority according to 5424 is Facility*8 + severity, but you are obviously not using that either.

**Comment by EnoahNetzach** [comment]
@Seldaek interoperability, for starter.

I have to manage log levels that are given by my system through environment variables, following this weird standard, that is only remotely supposed to follow [RFC 5424](https://www.rfc-editor.org/rfc/rfc5424.txt).

Priorities are well defined (as @theduke was saying), and names are also well defined (you use `info`, lowercase, abbreviated; The standard is `Informational`).

I find also [this comment ("Logging levels from syslog protocol defined in RFC 5424")](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php#L90) to be very disorienting..
