### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by itsyub** [Seldaek/monolog#1380]
I am using Monolog  ^1.17

I am using google-php-apiclient in my project and this package uses monolog as dependancy. 

I am getting 
`Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) on Logger.php line no. 146`
`Message: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) on Logger.php line no. 33`

I'm getting error on php version: 7.1,7.2 and 7.3.

**Comment by xabbuh** [comment]
Looking at the error message I'd say that you are using Monolog 2 with PHP 5. Please double-check that Monolog 1 is installed (you can see the installed versions running `composer show`) and make sure that the PHP version used when this error occurs is actually PHP 7 (the version used on the CLI may differ from the one used by your web server).

**Comment by itsyub** [comment]
Thanks @xabbuh, I updated PHP 7.0 to 7.3 but I forgot to enable 7.3 module. Now it's working fine. Thanks.
