### ISSUE TITLE
Issue with close() ordering of FingersCrossedHandler and nested handlers. 

### ISSUE THREAD

**Issue by tapetersen** [Seldaek/monolog#1381]
I am using Monolog version 2

First of all thanks for the brilliance that FingersCrossedHandler is in keeping a relevant logging stream.

We've configured FingersCrossedhandler with an activation lavel of `warning` and a passthru level of `notice` to allow `notice`-level logs to go through but skip `info`-level one unless we have a warning. This generally works fins but in cases where the nested handler needs flushing and registers a call to `close()` at shutdown there is an ordering issue if the Nested Handlers `close()` is called before `FingersCrossed::close()` and we have `notice` records but haven't reached the activation level.

If FingersCrossedHandler have  buffered records it writes those to the nested handler on it's close but if the nested handler have already flushed it's records before that they are never sent as it's close method is not called again.

Checking #864 I see you don't like calling the close manually on the nested handlers and I can see that being a problem if close is not guaranteed to be callable more than once and it's even somewhat reasonable for a handler to not accept records after it's been called but this leaves an unintuitive hole to lose log records depending on registration order of shutdown functions.

We can solve it in our case by manually noticing this and flushing the affected handler but it's not really ideal and took a while to debug.

**Comment by tapetersen** [comment]
Ok thinking and debugging further I notice that actually no shutDown functions are registered at all and this is a case of the destructors being called in the wrong order (the nested handler is destructed before FingersCrossed even if there is a reference which is apparently something that happens in php for objects that are alive until request end with circular dependencies see https://stackoverflow.com/a/8565887/6160212. 

This is the case when using Symfony DI container here and so it's solved by calling close manually on FingersCrossed before complete shutdown. Not sure what to do about it more than noticing that relying on destructors in PHP (and all non RIAA structured languages) still has a lot of pitfalls and problems.

**Comment by Seldaek** [comment]
Thanks for the investigation. Typically calling $logger->reset() at the end of the request would be the right thing to do IMO, as this should trigger a cycling of all handlers, which is almost equivalent to close(). That's something which should be done in Symfony's MonologBundle though I guess.. Not really something Monolog can fix I am afraid, as it lacks application context.

**Comment by lyrixx** [comment]
I agree with @Seldaek here :+1: 
Let's move that call to symfony (for HTTP request, and CLI (regular command + worker on each message)

**Comment by tapetersen** [comment]
The problem here is not that the close handler is not guaranteed to be called as it is by the destructor more or less does that. The problem is that there is a dependency in some cases of the ordering on the calls to close where a buffering handler has to flush before the nested handler or else flush the nested handler again. Are you going to hardcode this dependency into the bundle or is there someway to determine and traverse this graph to flush handlers in the right order? 

If this is just a limitation of the current HandlerInterface and you don't want to complicate it (which I understand) and the option of calling close on nested handler after flush is not an option feel free to close it (unless you just find a solution I couldn't).

**Comment by Seldaek** [comment]
If we call reset() on the Logger instance, that should sort it out without having to call close(). reset() must be able to be called several times. And it will propagate down the handler chain from outer layers to the nested ones, so it calls them in the right order. close() will then be called right after during object destruction, but then it should have nothing left to flush, so that should be fine really.
