### ISSUE TITLE
Monolog-2: SlackRecord::generateAttachmentField() must be of the type string, integer given

### ISSUE THREAD

**Issue by pmochine** [Seldaek/monolog#1382]
I am using Monolog version 2 with Laravel 6.0. I opened an [issue here first](https://github.com/laravel/framework/issues/30068#issue-496787009), but was redirected here.

Since updating to Laravel 6.0 with Monolog 2.0.0, I get this error: 

> Failed asserting that exception of type "TypeError" matches expected exception "\Exception". Message was: "Argument 1 passed to Monolog\Handler\Slack\SlackRecord::generateAttachmentField() must be of the type string, integer given, called in /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php on line 328" at
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php:309
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php:328
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php:170
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/SlackWebhookHandler.php:94
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:42
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Logger.php:323
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/monolog/monolog/src/Monolog/Logger.php:551
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Log/Logger.php:176
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Log/Logger.php:75
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:493
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:239
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/app/Helpers/Sms/SmsNotifications.php:95
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/app/Helpers/Sms/SmsNotifications.php:25
/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/tests/Unit/Sms/SmsNotificationsTest.php:36
.

### Steps To Reproduce:
Call this function: `\Log::critical('Some text', ['somevalue']);` 

And before that add in logging.php

    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'slack'],
        ],

        'single' => [
            'driver' => 'single',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
        ],
        'slack' => [
            'driver' => 'slack',
            'url' => env('LOG_SLACK_WEBHOOK_URL'),
            'username' => 'Laravel Log',
            'emoji' => ':boom:',
            'level' => 'critical',
        ],
    ]

A temporary solution is:
`\Log::critical('Some text', ['a string key' => 'somevalue']);` 

[And could be temporarily fixed by adding `(string)`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/Slack/SlackRecord.php#L327)

    $fields[] = $this->generateAttachmentField((string) $key, $value);

**Comment by judahnator** [comment]
Same issue here. 

* PHP 7.3.8
* monolog/monolog@v2.0.0
* dependency of laravel/framework@v6.0.3
