### ISSUE TITLE
Monolog declaration failing for google api php7.3.9

### ISSUE THREAD

**Issue by sajjadsaleem** [Seldaek/monolog#1388]
Fatal error: Declaration of Monolog\Handler\ProcessableHandlerTrait::pushProcessor(callable $callback): Monolog\Handler\HandlerInterface must be compatible with Monolog\Handler\AbstractHandler::pushProcessor($callback) in /google-sheet/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php on line 22

**Comment by Seldaek** [comment]
Sorry I don't understand the error here, can you please give more details and steps to reproduce? Are you using stock Monolog or a custom handler? Which Monolog version is it? etc.
