### ISSUE TITLE
Monolog Crash on stringify

### ISSUE THREAD

**Issue by molanostephane** [Seldaek/monolog#1392]
We are using Monolog version 2.0.0 that comes with Laravel 6.2 and we are facing an error when monolog uses the function "stringify" on a trace containing non utf-8 characters (basically when one of the lines of the array "$fields", 1st parameter of the function stringify(), is identified as "binary" by laravel : see screenshot)

![chrome_NRXjkNZov7](https://user-images.githubusercontent.com/51644881/67672484-5640f480-f978-11e9-88d9-bcf6e6c9bd5b.png)

The error is the following and you'll find the full trace after (BUG.MONOLOG is an .html changed to .txt)

`'Return value of Monolog\Handler\Slack\SlackRecord::stringify() must be of the type string, boolean returned'`

[BUG MONOLOG.txt](https://github.com/Seldaek/monolog/files/3778345/BUG.MONOLOG.txt)

Funny that the error that monolog wanted to return is also affected by this UTF8 problem. This is not the topic, we solved it on our side, but the real problem is that : 

Here, we just would like Monolog to be able to log our errors.

Feel free to ask for more questions if you need,

**Comment by Seldaek** [comment]
I believe this is fixed but would be happy if you can verify this by requiring monolog `^2.0@dev`

**Comment by mmenozzi** [comment]
Hi @Seldaek,
isn't [this fix](https://github.com/Seldaek/monolog/commit/12a76ad61e5ac3770ed175579f990f365f66ffd9#diff-922580478defb36219c3dfdff68f7720) for 1.x a BC break? You removed the public method `\Monolog\Formatter\NormalizerFormatter::detectAndCleanUtf8`.

**Comment by Seldaek** [comment]
It had a `@private` annotation so I'd say it's fine..

**Comment by mmenozzi** [comment]
Ah ok @Seldaek didn't noticed the `@private` annotation. Also the IDE (PhpStorm) didn't highlighted as it does when using `@internal`. I think that `@internal` is the "standard" annotation to use in such cases (https://docs.phpdoc.org/references/phpdoc/tags/internal.html).

**Comment by Seldaek** [comment]
Ok good to know, too late to fix this one though :)

**Comment by mmenozzi** [comment]
Yes no problem man! 😉
