### ISSUE TITLE
Unneeded character escaping for Slack/SlackRecord

### ISSUE THREAD

**Issue by lptn** [Seldaek/monolog#1396]
The only one goal of using `json_encode`  to prepare `$record` to  send to slack is to  stringify some types for better perception. `json_encode` uses flash escaping by default that provides bad user experience, especially for URL:

![image](https://user-images.githubusercontent.com/5278175/68527624-fcd2b100-02f9-11ea-8ac6-4f1b58a7b0fc.png)

**Comment by Seldaek** [comment]
Thanks for the fix, but it kinda conflicted with other changes I did to fix broader json encoding issues so I had to reimplement it. In any case it should now be fixed in the latest release
