### ISSUE TITLE
ElasticaHandler is incompatible with Elastica 7

### ISSUE THREAD

**Issue by panychek** [Seldaek/monolog#1399]
Starting from version 7 (which is in a beta stage now), the `\Elastica\Type` class was removed (since specifying types in requests is deprecated in ES 7.x).

So the handler will result in:
`Call to undefined method Elastica\Document::setType`

I can cook up a PR if you want.

**Comment by Seldaek** [comment]
Please do send a PR yes, based on the `1.x` branch if relevant, or master if only relevant to `2.*` releases.

**Comment by panychek** [comment]
Well, the fix itself could be done by adding a simple check, but adjusting the existing test gets tricky.
In fact, it doesn't really pass at the moment, because [the integration part](https://github.com/Seldaek/monolog/blob/master/tests/Monolog/Handler/ElasticaHandlerTest.php#L166) is aimed for the old obsolete Elastica versions.
Also, [this patch](https://github.com/Seldaek/monolog/commit/9ef18f111f98f8a95411d83b09952f2eac45d6b9#diff-734241fe5a63e503672f0b5ed7dcfd85) broke it too, but I suppose it had gone unnoticed (because of always being skipped).

I can patch it up to pass with Elastica 6 and 7, and update the `require-dev` with these versions. What do you think?

And since `ElasticSearchHandler` became `ElasticaHandler` in `2.x`, I believe I should create two PRs, against both branches?

**Comment by Seldaek** [comment]
Rather just PR against 1.x and I'll try to adjust when merging 1.x to master, but if that fails then maybe a 2nd PR would be needed. Most likely it's fine though.

If you can adjust the test + require-dev to work with both v6 and 7 that would be ideal yes. Thanks
