### ISSUE TITLE
Composer constraints do not reflect conflict with Symfony < 5

### ISSUE THREAD

**Issue by YetiCGN** [Seldaek/monolog#1403]
Monolog version 2

I just `composer up`ed a project that's running on Symfony 3.4 LTS and requires `"symfony/monolog-bundle: "^3.0"` which today resulted in an upgrade of Monolog from `1.25.1` to `2.0.1`. Composer went through fine, but in the post-update-cmd Monolog complained:

```
In MonologExtension.php line 55:

  Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.
```

Why isn't Monolog 2 declaring a conflict with any Symfony version lower than 5 in the composer.json?

**Comment by xabbuh** [comment]
see symfony/monolog-bundle#330

**Comment by YetiCGN** [comment]
Yes, but I still don't understand why Monolog fails at runtime and doesn't declare this important conflict from the get-go. Is some sort of performance the reason for not declaring the conflict in Monolog itself?

**Comment by stof** [comment]
it is not monolog which is failing. It is MonologBundle.

**Comment by YetiCGN** [comment]
Fair enough, I misinterpreted the error message.
