### ISSUE TITLE
Duplicate files in vendor folder

### ISSUE THREAD

**Issue by UdyW** [Seldaek/monolog#1404]
Monolog version 1.12

Write your bug report here.
When I run composer update I get a list of warnings as Ambiguous class resolution.
When I check vendor folder there are 2 files of each class as Classname 2.php

`AbstractHandler 2.php			FilterHandler.php			LogglyHandler 2.php			RollbarHandler 2.php
AbstractHandler.php			FingersCrossed				LogglyHandler.php			RollbarHandler.php
AbstractProcessingHandler 2.php		FingersCrossedHandler 2.php		MailHandler 2.php			RotatingFileHandler 2.php
AbstractProcessingHandler.php		FingersCrossedHandler.php		MailHandler.php				RotatingFileHandler.php
AbstractSyslogHandler 2.php		FirePHPHandler 2.php			MandrillHandler 2.php			SamplingHandler 2.php
AbstractSyslogHandler.php		FirePHPHandler.php			MandrillHandler.php			SamplingHandler.php
AmqpHandler 2.php			FleepHookHandler 2.php			MissingExtensionException 2.php		Slack
AmqpHandler.php				FleepHookHandler.php			MissingExtensionException.php		SlackHandler 2.php
BrowserConsoleHandler 2.php		FlowdockHandler 2.php			MongoDBHandler 2.php			SlackHandler.php`

My Composer file is ;

> {
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.4",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "predis/predis": "^1.1"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },

Any idea why this is happening?

**Comment by stof** [comment]
where are these files in the vendor folder ?

**Comment by hamidrezabstn** [comment]
@UdyW 
@stof 
i've double check everything but i can't reproduce it !
are u sure that it was not temporarily or composer related ?
