### ISSUE TITLE
Proper ElasticsearchHandler exceptions

### ISSUE THREAD

**Issue by ninze** [Seldaek/monolog#1405]
If ElasticsearchHandler fails to insert documents, the thrown exception will look something like this:

`Error sending messages to Elasticsearch` => (previous) `Elasticsearch returned error for one of the records`.

Which is honestly quite useless and doesn't help to find the source of the error.

In the `bulkSend` method, the `$responses` array contains much more useful info about the errors. 

I am suggesting to convert data within $responses array into exceptions and throw that instead of very generic `Elasticsearch returned error for one of the records`. 

Unless of course there is a way to get elasticsearch php client to do that automatically, but I couldn't find such info in elasticsearch docs.

**Comment by Seldaek** [comment]
If you see a way to do this, feel free to send a PR.. I am not familiar enough with the elasticsearch lib
