### ISSUE TITLE
Assign custom name to handler to modify their settings on the fly

### ISSUE THREAD

**Issue by tolgaulas** [Seldaek/monolog#1408]
It would be beneficial to be able to select an handler by name for modifying their values after the construction. 
i.e
$logger->pushHandler(new StreamHandler($logFileName, $level, true /**bubble */, null /**filePermission */, false /**useLocking=false */, "foo"/**Optional name*/);

$logger->getHandlerByName("foo")->setLevel(200);

**Comment by Seldaek** [comment]
I don't really see this happening in Monolog itself. Configuration is a framework/app-specific concern.. monolog cascade or similar would be a better place.
