### ISSUE TITLE
ElasticsearchFormatter: Force record values to be strings

### ISSUE THREAD

**Issue by tomsommer** [Seldaek/monolog#1417]
Monolog version 2

ElasticsearchFormatter should force all records to be strings, since ElasticSearch will fail on field types mixing in an index.

It would also make sense to not allow deep arrays, basically flatten arrays and make them scalar.

**Comment by Seldaek** [comment]
I don't think we can really do that without breaking BC.. It just means that currently you have to manage your context data carefully yourself.. The data provided by Monolog itself is consistently typed AFAIK. IMO this fact makes ElasticSearch generally speaking a poor choice for log storage but I can't choose what people use..
