### ISSUE TITLE
GelfMessageFormatter::$logLevels should be protected

### ISSUE THREAD

**Issue by gander** [Seldaek/monolog#1420]
`\Monolog\Formatter\GelfMessageFormatter`:

```php
    /**
     * Translates Monolog log levels to Graylog2 log priorities.
     */
    private $logLevels = array(
        Logger::DEBUG     => 7,
        Logger::INFO      => 6,
        Logger::NOTICE    => 5,
        Logger::WARNING   => 4,
        Logger::ERROR     => 3,
        Logger::CRITICAL  => 2,
        Logger::ALERT     => 1,
        Logger::EMERGENCY => 0,
    );
```

I needed to change this mapping a bit, and I wanted to do it by extending the base class, but of course it won't work because this field is private. I would also have to overwrite the format method, which is huge. Lots of code to copy. If the author followed the KISS design pattern, it would be great. I would suggest adding a method to obtain the GELF level. Or divided the format method into smaller fragments. Or did it protected field.

**Comment by Seldaek** [comment]
Sounds good to me if you want to send a PR against the 1.x branch to allow better extensibility.
