### ISSUE TITLE
Breaking change in BufferHandler

### ISSUE THREAD

**Issue by mariusbuescher** [Seldaek/monolog#1428]
Monolog version 1 & 2

When using the `BufferHandler`, the `setFormatter` method is passed on to the handler. That unfortunately breaks a use case of the BufferHandler. What we use it for is formatting messages in the GELF format and afterwards streaming it to a file. From there we collect all logs.

The commit [4a70fb3353107bf1be596958d395ec29b32dbbec](https://github.com/Seldaek/monolog/commit/4a70fb3353107bf1be596958d395ec29b32dbbec) breaks this usage.

Unfortunately that breaking change was published in a patch version (1.25.2 and 2.0.2).

**Comment by mariusbuescher** [comment]
Did I just cunfigure it wrong, or is it really a breaking change? Just wonder if I made a mistake.

**Comment by Seldaek** [comment]
I don't quite see how this did anything for you before, as the formatter configured on the buffer handler was completely ignored as far as I can tell.. So setFormatter was a noop, and now it is configuring the formatter on the nested handler, which indeed might break things if you are overriding something else, but it sounds like it was misconfigured before?

**Comment by mariusbuescher** [comment]
Yes, I am totaly aware of that. It was definitely a misconfiguration on my behalf. I just forgot to delete something.

The case was, that I configured the formatter on the nested handler already, but calling `setFormatter` reconfigured it. That was breaking the setup.

**Comment by Seldaek** [comment]
Ok I see.. Then strictly speaking yes it was a breaking change for a broken config. Sorry about that, but I don't think we can do much besides moving on and hoping for less mistakes in the future :)

**Comment by mariusbuescher** [comment]
No problem. Thank you for the answer as well as your work on this, well, crucial component for many developers in the PHP community.
