### ISSUE TITLE
Issue with serialization SoapFault

### ISSUE THREAD

**Issue by yethee** [Seldaek/monolog#1431]
**Monolog version**: 2.0.2

Occurs an error during serialization `SoapFault`, when property `details` has value of complex type.

```
Error(code: 0): Object of class stdClass could not be converted to string at /app/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php:184
```

An example of SoapFault:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode>SOAP-ENV:Client</faultcode>
      <faultstring>Недостаточно баллов</faultstring>
      <detail>
        <ns3:FaultResponse xmlns:ns3="http://api.direct.yandex.com/v5/general">
          <requestId>2577205305276726399</requestId>
          <errorCode>152</errorCode>
          <errorDetail>Недостаточно баллов для выполнения операции</errorDetail>
        </ns3:FaultResponse>
      </detail>
     </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Commit 633bcd526 not fixes issue in this case, because `reset()` returns `stdClass{requestId, errorCode, errorDetail}`.

**Comment by covobo** [comment]
I have the same problem

**Comment by neclimdul** [comment]
I _was_ having the same problem but then as soon as I started trying to fix it my soap resource fixed itself and I couldn't dig in. 

I think the description of the problem with the assumptions in using reset are accurate though.

I was going to play with refactoring the if/ternary logic out and letting var_export or print_r just dump what ever was given. Replacing it with something like:
```php
            if (isset($e->detail)) {
                if  (is_string($e->detail)) {
                    $str .= ' detail: ' . $e->detail;
                }
                elseif (is_object($e->detail) || is_array($e->detail)) {
                    $str .= ' detail: ' . var_export($e->detail, true);
                }
            }
```

**Comment by covobo** [comment]
The problem here is that php claim detail property as string (you can look at the __construct method https://www.php.net/manual/en/class.soapfault.php ), but in fact it's not only string.

So if it mixed property we have to use some kind of serialization, var_export looks nice.

I use json_encode as ad-hoc solution, I think it is more friendly for logging systems.

**Comment by Seldaek** [comment]
Refs https://github.com/Seldaek/monolog/issues/1391

**Comment by Seldaek** [comment]
Fixed by https://github.com/Seldaek/monolog/pull/1462
