### ISSUE TITLE
Quotation error ( ` )

### ISSUE THREAD

**Issue by rickserrat** [Seldaek/monolog#1435]
Monolog version 1|2

Error:
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: preg_match() expects parameter 2 to be string, null given in /var/www/html/vendor/monolog/monolog/src/Monolog/Processor/GitProcessor.php:54

Remove: 

> ```$branches = `git branch -v --no-abbrev`;```

**Update:**` $branches = 'git branch -v --no-abbrev';`

**Comment by rickserrat** [comment]
@Seldaek Can I make a pull request?

**Comment by Seldaek** [comment]
This is not a quotation error, the backticks are executing the process https://www.php.net/manual/en/language.operators.execution.php. But I guess it should check that $branches is not null before calling preg_match. Feel free to PR that to 1.x branch.

**Comment by rickserrat** [comment]
Pull Request 1.x #1438
