### ISSUE TITLE
Handlers undefined offset

### ISSUE THREAD

**Issue by mirekratman** [Seldaek/monolog#1436]
Monolog version 1|2

If any of handlers can't handle error here:
https://github.com/Seldaek/monolog/blob/bec314a9c14ce8a40650cf13923f5941ef1bfe0a/src/Monolog/Logger.php#L323

this throw an Undefined offset: 1 here:
https://github.com/Seldaek/monolog/blob/bec314a9c14ce8a40650cf13923f5941ef1bfe0a/src/Monolog/Logger.php#L327

**Comment by Seldaek** [comment]
I don't understand what you mean by `Undefined offset: 1`.. next() can not fail this way as far as I can tell as it does not use offsets but just goes to the next array item if there is one..

https://3v4l.org/d7TQO
