### ISSUE TITLE
Monolog requires abandoned projects

### ISSUE THREAD

**Issue by sloanja** [Seldaek/monolog#1445]
monolog/monolog requires packages in composer.json which have been marked as abandonded by the author as of 20 days ago (March 15, 2020):
jakub-onderka/php-parallel-lint (see https://github.com/JakubOnderka/PHP-Parallel-Lint)
jakub-onderka/php-console-highlighter (see https://github.com/JakubOnderka/PHP-Console-Highlighter)

Recommended replacements:
https://github.com/php-parallel-lint/PHP-Parallel-Lint
https://github.com/php-parallel-lint/PHP-Console-Highlighter

I found this issue by loading up a new fresh copy of Laravel and it was complaining about the abandoned packages right away.

**Comment by janesmae** [comment]
+1

**Comment by hadjistasi** [comment]
Hello guys, any updates on this? 
 +1

**Comment by xabbuh** [comment]
Please note that the abandoned package won't be installed in your applications as it is only listed in the `require-dev` section. And since nobody made the change until today, maybe someone of you would like to create the needed pull request.

**Comment by hadjistasi** [comment]
Any updates?
+1

**Comment by xabbuh** [comment]
@hadjistasi If you are so curious about this change, I suggest to simply open a PR as I suggested before.
