### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by viksts** [Seldaek/monolog#1450]
Hi,
I am using monolog for logging purpose in of my private package as a dependency and it is giving error
`Notice: Array to string conversion in Handler/SocketHandler.php on line 313`
Monolog version :- ^1.13
Php version :- 7.4.4
How can i fix this error i can't find any thing in changelog.

**Comment by stof** [comment]
AFAICT, the only case where this can happen is if you instantiate your SocketHandler by passing an array in the `connectionString` argument instead of a string. That would mean that the bug is actually in the code instantiating the handler, not in monolog itself.

**Comment by viksts** [comment]
> AFAICT, the only case where this can happen is if you instantiate your SocketHandler by passing an array in the `connectionString` argument instead of a string. That would mean that the bug is actually in the code instantiating the handler, not in monolog itself.

Ok will check the code. Thanks for reply
