### ISSUE TITLE
Set date format in Logger

### ISSUE THREAD

**Issue by delrio-design** [Seldaek/monolog#1459]
Some background: I am using Fluent Bit as a log forwarder for a containerized PHP application with Monolog, and want to standardize date formats across my log streams.

Some formatters, such as LineFormatter and NormalizeFormatter allow this already. I am using JsonFormatter for structured logs, it inherits from NormalizeFormatter, but I don't believe I can set the date format without subclassing it and overriding the normalize method myself. I would like to be able to set the date format globally or consistently per formatter. Given that some streams require certain date formats for ingestion by third party services, it would be nice if each step from logger to handler to stream inherited the default or global date format unless explicitly set.

**Comment by Seldaek** [comment]
Indeed JsonFormatter relies on jsonSerialize's implementation on `Monolog\DateTimeImmutable`. 

I think fixing it to allow choosing a date format sounds possible and reasonable, but I am not sure about adding a default global date format option, that sounds like it's going to be a mess to handle.

**Comment by delrio-design** [comment]
> Indeed JsonFormatter relies on jsonSerialize's implementation on `Monolog\DateTimeImmutable`.
> 
> I think fixing it to allow choosing a date format sounds possible and reasonable, but I am not sure about adding a default global date format option, that sounds like it's going to be a mess to handle.

Thanks for the consideration! You're right about the global format, that's a broad request.

**Comment by Seldaek** [comment]
If you feel like sending a PR for adding this to JsonFormatter please do :)

**Comment by Shiva-Kandagatla** [comment]
I'm also stuck on the exact same problem. @delrio-design Can you please explain a bit more how you solved it.
