### ISSUE TITLE
Prevent Monolog from calling slack.com url

### ISSUE THREAD

**Issue by PCes83** [Seldaek/monolog#1460]
On a Symfony project, when I run cache:clear in CLI, Monolog bundle try to connect to ssl://slack.com:443 (SlackHandler.php:58)

On OVH web hosting, out-bounding connections on 443 are disabled 

So my cache:clear command crashes (even on manual run than on composer update command)

How can I prevent this ?

Thanks a lot

-----------------------------------
php bin/console cache:clear

 // Clearing the cache for the prod environment with debug false

In SocketHandler.php line 313:

  Failed connecting to ssl://slack.com:443 (111: Connection refused)

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by Seldaek** [comment]
I suggest you don't configure a SlackHandler if you are not able to use it?

**Comment by PCes83** [comment]
I'm not able to use it in CLI environment...

All works perfectly on the website and I do need it in this way 

So if you have a way to disable it in CLI only, all is great for me

**Comment by Seldaek** [comment]
I guess you have to see what it's trying to log when running cache:clear, if you can fix the error then it should stop logging to Slack I assume and stop causing issues in CLI.. But generally speaking I don't think it's possible to configure web-only monolog handlers in symfony.

An alternative is to use a handler of type `whatfailuregroup` which will suppress the errors from nested handlers.

Like:

```
suppress_errors:
    type: whatfailuregroup
    members: [your_slack_handler_name]
```

**Comment by PCes83** [comment]
Thanks for this way, I'm going to explore it

But here exactly the situation:
1/
When I manually empty cache dir and run cache:clear, all works fine and my cache warmup is ok
When I run again cache:clear, it try to log to slack and fail

2/
When Slack handler is not configured all is OK

3/
In all situations, I have a swift_mailer handler with debug level. So, if there was an error, as you supposed, I should receive error details by email
All looks like if there is no error to push to Slack but Monolog just try to connect (to check if handler and API credentials are well configured ?)

Actually, I don't run cache:clear manually. It's run by composer
So I found the following workaround: I created a composer script to empty cache folder. This script is ran by PHP to be crossplatform (Win/Linux) and use the composer env var to determine if it must empty prod or dev cache....

**Comment by Seldaek** [comment]
Can you share your complete monolog configuration?

The way I see it in the code it should not try to connect unless there is a log record written.. Maybe you could try using a stream handler to log to a file to see if anything gets logged? Not sure if your swift handler works from CLI or not..

**Comment by PCes83** [comment]
You're completely right
I have a Deprecated notice in log file

I can't understand why slack error is visible in console and swift silently fails....

Well, sorry for annoying you and thanks for your answers and advice with whatfailuregroup. I'll now be able to prevent my app from crashing if there is a problem in one handler

**Comment by beardedev** [comment]
Hi @PCes83, did you find a solution to this problem ?
