### ISSUE TITLE
ChromePHPHandler Charset

### ISSUE THREAD

**Issue by elvispdosreis** [Seldaek/monolog#1461]
Monolog version 2

I have a data output in a string encoded in utf-8, but in the log console I get a string with malformed characters

**Comment by Seldaek** [comment]
You got any more details here? This is completely unusable feedback sorry.

**Comment by Seldaek** [comment]
Might be fixed by https://github.com/Seldaek/monolog/commit/863670fa94d8038a23a05f2f1745891f7dc6ee77
