### ISSUE TITLE
Normalizer(Line)Formatter works with all the types, but the Logger sticks to the String

### ISSUE THREAD

**Issue by Daisuke-sama** [Seldaek/monolog#1463]
https://github.com/Seldaek/monolog/blob/438b8983b7e58f6342377b8cf5b9ab1ee91d518f/src/Monolog/Logger.php#L284

On this line, the `addRecord` function has the strictly typed `$message` variable to string. At the same time `Logger` uses internal `LineFormatter` that knows how to transform objects and arrays. What I am wondering about is the ability to handle this strict type in the source code. Now I am nesting from the class with duplicating the whole `addRecord` function and everything from the `LoggerInterface`, except type coercing to string.

Thank you

**Comment by Seldaek** [comment]
The message should be a string, this is not really up for discussion. If you have non-string data to pass in it belongs in $context. That will be normalized and formatted just fine.
