### ISSUE TITLE
Breaking change on v2.1.0

### ISSUE THREAD

**Issue by gmponos** [Seldaek/monolog#1464]
https://github.com/Seldaek/monolog/commit/eb84930e70d8b355cee2e96993011d8d8dced0d1#r39360045

Hi.. thought that it might be better to continue the discussion here...

Not sure if you want to address this though...  :)

**Comment by Seldaek** [comment]
Just seeing this now sorry but as I wrote on the commit no I don't really think it's worth addressing :)
