### ISSUE TITLE
How could I change monolog to another log components implements PSR-3?

### ISSUE THREAD

**Issue by nickppbd** [Seldaek/monolog#1465]
I don't use monolog yet, but I read monolog docs here.

Is it possible without changing my code to change monolog to another log components which implements PSR-3?

I think I should change my code if I change monolog to another.

Am I wrong?

**Comment by Seldaek** [comment]
The code which only relies on `Psr\Log\LoggerInterface` can receive any PSR-3 logger and log to it just fine. The code which configures Monolog or $otherLogger is specific to that library and will have to change if you want to use another library.
