### ISSUE TITLE
Private properties in MongoDBHandler

### ISSUE THREAD

**Issue by vstokarev** [Seldaek/monolog#1483]
I was wondering if there is a reason why all properties in MongoDBHandler are private. Checked other handlers and most of them are using protected properties.

I was trying to extend MongoDBHandler and add handleBatch() method (I'd like to use this handler in conjuction with BufferHandler), but I ended up just cloning the class.

Can you please make properties in this class protected instead of private?

**Comment by Seldaek** [comment]
You could also send a PR to add the handleBatch functionality so everyone benefits?
