### ISSUE TITLE
Monolog support for Laravel 5.8

### ISSUE THREAD

**Issue by MarceloPincheira** [Seldaek/monolog#1492]
Monolog version 1

Hi there! I've a project with Laravel 5.8 and I'm having the following issue at try to install monolog. I tried to install of multiple ways but I still getting the same error with laravel compatibility.

  Problem 1
    - **Conclusion: remove laravel/framework v5.8.38**
    - Conclusion: don't install laravel/framework v5.8.38
    - laravel/ui 2.x-dev requires illuminate/filesystem ^7.0|^8.0 -> satisfiable by illuminate/filesystem[7.x-dev, 8.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - laravel/ui v2.1.0 requires illuminate/filesystem ^7.0 -> satisfiable by illuminate/filesystem[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - laravel/ui v2.2.0 requires illuminate/filesystem ^7.0|^8.0 -> satisfiable by illuminate/filesystem[7.x-dev, 8.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/filesystem 7.x-dev|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.3|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.4|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.5|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.6|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.7|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.0.8|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.1.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.1.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.1.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.1.3|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.10.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.10.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.10.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.10.3|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.11.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.12.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.13.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.14.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.14.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.15.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.16.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.16.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.17.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.17.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.17.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.18.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.19.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.19.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.2.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.2.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.2.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.20.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.21.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.22.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.22.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.22.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.22.3|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.22.4|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.23.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.23.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.23.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.24.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.25.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.26.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.3.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.4.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.5.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.5.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.5.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.6.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.6.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.6.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.7.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.7.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.8.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.8.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.9.0|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.9.1|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem v7.9.2|don't install laravel/framework v5.8.38
    - don't install illuminate/filesystem 8.x-dev|don't install laravel/framework v5.8.38
    - Installation request for laravel/framework (locked at v5.8.38, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.38].
    - Installation request for laravel/ui ^2.1 -> satisfiable by laravel/ui[2.x-dev, v2.1.0, v2.2.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by Seldaek** [comment]
I don't see how this relates to monolog at all sorry. Maybe composer 2 will give you a better error message..
