### ISSUE TITLE
File name format

### ISSUE THREAD

**Issue by sujittiwari** [Seldaek/monolog#1493]
Only three formats are allowed FILE_PER_DAY('Y-m-d'), FILE_PER_MONTH('Y-m') and FILE_PER_YEAR('Y').

I want to generate a file name including month name eg. **2020-Sep.log** but I could only generate **2020-08**.

I think it should be allowed to pass custom file name format ('Y-M') to **$handler->setFilenameFormat()**.

![rotatingFileHandler](https://user-images.githubusercontent.com/6831020/91796970-105f5780-ec3f-11ea-90be-98d42c2374bf.PNG)

**Comment by Seldaek** [comment]
Nope sorry but we are not going to support random formats. If you want more complex configs you can use logrotate.
