### ISSUE TITLE
Can I get current file and current line by configuring handler?

### ISSUE THREAD

**Issue by huanghantao** [Seldaek/monolog#1494]
Monolog version 1|2

version is `1`.

Write your question here.

I want to record the current line and current file. The way I do it now:

```php
$this->logger->debug(
            'function call: in App\Model\Chat::getMessagesByPage',
            [
                'key' => $key,
                'param' => $param,
                'startIndex' => $startIndex,
                'endIndex' => $endIndex,
                'file' => __FILE__,
                'line' => __LINE__,
            ]
        );
```

However, I wish there was a better way to get the current file and the current line. Can I do this by configuring a Handler?

**Comment by mfn** [comment]
This sounds like a use case for `\Monolog\Processor\IntrospectionProcessor` to me.

In general for processors, see https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#processors
> IntrospectionProcessor: Adds the line/file/class/method from which the log call originated.

=> https://github.com/Seldaek/monolog/blob/master/src/Monolog/Processor/IntrospectionProcessor.php

HTH

**Comment by huanghantao** [comment]
> This sounds like a use case for `\Monolog\Processor\IntrospectionProcessor` to me.
> 
> In general for processors, see https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#processors
> 
> > IntrospectionProcessor: Adds the line/file/class/method from which the log call originated.
> 
> => https://github.com/Seldaek/monolog/blob/master/src/Monolog/Processor/IntrospectionProcessor.php
> 
> HTH

Thanks, I can get current file and current line. 

Can I output something similar to file:line? That way, my editor can jump straight to that line of code.

**Comment by codemedic** [comment]
@huanghantao You should be able to achieve that by configuring `LineFormatter` with `%extra.file%:%extra.line%` in which ever position (within the line) you fancy.
