### ISSUE TITLE
Allow empty braces "[] []" at end of log line to be suppressed.

### ISSUE THREAD

**Issue by fearless359** [Seldaek/monolog#1497]
I'm not using context, so that [] is empty and it is followed by another one that I can't determine what goes in it, and it is empty. My log output looks like this:
`2020-09-10T20:45:34.261675+02:00] siLog.DEBUG: index.php - module[auth] view[login] action[] id[] menu[1] [] []`
These just add noise to the log lines. Is there a way to suppress the "[] []" at the end of the line when empty?

**Comment by serkanerip** [comment]
This is a feature that already exists. Commit: efe572cb1074121f943320607ad9f448686f844c

LineFormatter has an **ignoreEmptyContextAndExtra** paramater but its default value is false. 
You should create a new LineFormatter and pass true to **ignoreEmptyContextAndExtra** paramater and it will ignore empty context and extra arrays. And dont forget to set the formatter to your handler.

**Constructor Method Signature OF LineFormatter:**
```php
public function __construct(?string $format = null, ?string $dateFormat = null, bool $allowInlineLineBreaks = false, bool $ignoreEmptyContextAndExtra = false)
    {
        $this->format = $format === null ? static::SIMPLE_FORMAT : $format;
        $this->allowInlineLineBreaks = $allowInlineLineBreaks;
        $this->ignoreEmptyContextAndExtra = $ignoreEmptyContextAndExtra;
        parent::__construct($dateFormat);
    }
```

**Example Usage:**
```php
$formatter = new LineFormatter(null, 'Y-m-d', false, true); 
$handler->setFormatter($formatter);
```

**Comment by Seldaek** [comment]
Closing as per @serkanerip's comment 👍🏻
