### ISSUE TITLE
Bug on PHP 8 - socket_create & is_resource

### ISSUE THREAD

**Issue by KangAdmin** [Seldaek/monolog#1519]
"monolog/monolog": "^2.0",
"version": "2.1.1"

```
<?php

$socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
if (!is_resource($socket)) {
	echo socket_strerror(socket_last_error($socket))."\n";
	echo "Not is_resource"."\n";
}

var_dump($socket);
```

If i run this on windows&Debian on PHP 7.4, I get this result :
**$ php socket.php**
resource(4) of type (Socket)

If i run the same script on windows&Debian on PHP 8.0, I get this result : 
**$ ../php-8.0.0-Win32-vs16-x64/php.exe socket.php**
Success
Not is_resource
object(Socket)#1 (0) {
}

I wrote this small PHP line because **is_resource** is use on **UdpSocket** :
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SyslogUdp/UdpSocket.php

**Comment by stof** [comment]
I think that all the `is_resource($this->socket)` in this class must become `is_resource($this->socket) || $this->socket instanceof \Socket` instead, to account from the fact that PHP 8.0 has migrated the socket extension from resources to objects.

**Comment by KangAdmin** [comment]
> I think that all the `is_resource($this->socket)` in this class must become `is_resource($this->socket) || $this->socket instanceof \Socket` instead, to account from the fact that PHP 8.0 has migrated the socket extension from resources to objects.

This works for me in PHP 7.4 & PHP 8.0

```

    public function close(): void
    {
        if ((is_resource($this->socket) || $this->socket instanceof \Socket)) {
            socket_close($this->socket);
            $this->socket = null;
        }
    }

    protected function send(string $chunk): void
    {
        if (!(is_resource($this->socket) || $this->socket instanceof \Socket)) {
            throw new \RuntimeException('The UdpSocket to '.$this->ip.':'.$this->port.' has been closed and can not be written to anymore');
        }
        socket_sendto($this->socket, $chunk, strlen($chunk), $flags = 0, $this->ip, $this->port);
    }

```

**Comment by stof** [comment]
even better solution: compare to `false` which is the error return value in all PHP versions

**Comment by Seldaek** [comment]
Fixed in https://github.com/Seldaek/monolog/commit/fd305da67bdbda519979e8de52599376788d57f1

**Comment by reedy** [comment]
It looks like there's a few other uses of `is_resource` scattered around (see https://github.com/Seldaek/monolog/search?q=is_resource). While not all resources have been migrated in 8.0, a longer term goal (maybe even in 8.1) is for that to be done - https://github.com/php/php-tasks/issues/6

**Comment by stof** [comment]
@reedy sure, but the file handle is not migrated to an object yet, so there is nothing to migrate yet. Monolog can adapt to the new PHP API only once it is defined.
