### ISSUE TITLE
Special characters  e.g. üö§ with Monolog+ Firephp + Chrome extension not working ??? 

### ISSUE THREAD

**Issue by wnedoe** [Seldaek/monolog#1521]
Monolog version 2

If i try  to log  user input including special characters  like "ÖüÄ§"   to the Firephp Handler, the complete chrome screen of the FIREPHP extension stays blank. 
If i remove those characters everythink works perfectly. 

Update: 
Using ONLY  the current class   
https://github.com/firephp/firephp-core
together with the firephp chrome extension  but WITHOUT MONOLOG 

everything works perfectly with all these unicode characters like  ÄÜÖ§
they are prperly displayed in the firephp console 

So most probably the FirePHPHandler has a bug. 

thanks
Alex

**Comment by Seldaek** [comment]
Can you perhaps show what the exact headers sent look like (both for FirePHPHandler and native firephp-core)? That might hint at why one works and the other not.

**Comment by Seldaek** [comment]
Ah  never mind, I suspect the issue is because we send unicode unescaped in the JSON. And that goes through headers, which is probably not a great idea.

Can you please try if `composer require monolog/monolog:^2.1@dev` fixes it for you?

**Comment by wnedoe** [comment]
THANK YOU!

Now it works

Ans yes the encoding of the http heders was  the problem…

Header from Chrome devtools below  now look similar and output is fine 😊



Outpout by Monolog  / FirePHPHandler

x-wf-1-1-1-5:
86|[{"Type":"INFO","File":"","Line":"","Label":"terraristik"},"\u00f6\u00fc\u00e4\u00a7"]|
1.  x-wf-1-1-1-6:
86|[{"Type":"INFO","File":"","Line":"","Label":"terraristik"},"\u00f6\u00fc\u00e4\u00a7"]|


Output by Firephpcore  has the identical encoding (shows more details like line but that is a completely different story ..)


  1.  x-wf-1-1-1-14:

191|[{"Type":"INFO","Label":"Uml\u00e4\u00fct Test!","File":"\/var\/www\/vhosts\/terraristik.com\/httpdocs\/tb\/test\/firephp\/index.php","Line":80},"Info message mit \u00d6O\u00dc\u00c4 \u00a7"]|



Von: Jordi Boggiano <notifications@github.com>
Gesendet: Donnerstag, 10. Dezember 2020 17:16
An: Seldaek/monolog <monolog@noreply.github.com>
Cc: Alexander Dobernig <office@terraristik.com>; Author <author@noreply.github.com>
Betreff: Re: [Seldaek/monolog] Special characters e.g. üö§ with Monolog+ Firephp + Chrome extension not working ??? (#1521)


Ah never mind, I suspect the issue is because we send unicode unescaped in the JSON. And that goes through headers, which is probably not a great idea.

Can you please try if composer require monolog/monolog:^2.1@dev fixes it for you?

**Comment by Seldaek** [comment]
Ok great, I'll try and get a release out soonish.
