### ISSUE TITLE
Deprecate SlackHandler / SlackWebhookHandler

### ISSUE THREAD

**Issue by Seldaek** [Seldaek/monolog#1522]
It might be good to just deprecate those two, and point people to https://github.com/gmponos/monolog-slack  - @gmponos is there anything your package does not support from those two handlers?

**Comment by Seldaek** [comment]
See also https://github.com/Seldaek/monolog/pull/1499 which triggered this..

**Comment by Seldaek** [comment]
@gmponos ping, are you still maintaining monolog-slack or not? If not I'd rather not remove them, but as I am preparing Monolog 3.0 in https://github.com/Seldaek/monolog/pull/1635 I am wondering what I should do here.

**Comment by gmponos** [comment]
I am in a weird spot this time around not able to contribute to OSS as much as I would wish. There is a high chance that this will change in the next weeks for various reasons related with changes inside my working environment. Can you give me a few days and ping me again?

**Comment by gmponos** [comment]
Hi I will continue to support the packages I have.. although I think the https://github.com/monolog-http/monolog-http is better to use.

**Comment by Seldaek** [comment]
OK thanks, I'll think about it some more..

**Comment by Seldaek** [comment]
Closing as keeping them is fairly low maintenance and removing will cause migration pains for no reason.
