### ISSUE TITLE
Can I put color on my stdout (file or terminal) ?

### ISSUE THREAD

**Issue by zak39** [Seldaek/monolog#1530]
Monolog version 2.1

Hello everyone :)

Can I put color on my stdout (file or terminal) ?

I would like to put color on my stdout, file or terminal, so that clearer to read.

Thank you :)

**Comment by Seldaek** [comment]
You can add [terminal color codes](https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html#colors) in the format of a LineFormatter for sure, it's just text.

**Comment by zak39** [comment]
Hi @Seldaek :)

Thanks for your answer :+1: 

It's true I can use terminal color codes, but I think it's heavy to manage this part it...

I found this library [monolog-colored-line-formatter](https://github.com/bramus/monolog-colored-line-formatter) and it uses your library.

What do you think of the monolog-colored-line-formatter library ?
Do you recommend it to me ?

**Comment by Seldaek** [comment]
Yeah that seems like what you were looking for so give it a shot, I haven't used it myself as there are hundreds of monolog extensions out there, so can't personally recommend, but I'm sure it'll be fine.

**Comment by zak39** [comment]
Okay, I didn't know that there were any other extensions of Monolog :)

It's very good for me :smiley: 

Thank you very much @Seldaek :+1:
