### ISSUE TITLE
Return type declarations in 1.X backport breaks PHP 5.* support

### ISSUE THREAD

**Issue by angusmcleod** [Seldaek/monolog#1537]
Monolog version 1 PHP 5.* support issue

> Monolog ^2.0 works with PHP 7.2 or above, use Monolog ^1.25 for PHP 5.3+ support.

I may be incorrect, but it seems that this [backport](https://github.com/Seldaek/monolog/commit/6d76eaaf7699d6bab1609b0a5abcc9d2326ad566) introduced return [type declarations](https://www.php.net/manual/en/language.types.declarations.php) into 1.X, which are not supported in PHP 5.*?

My PHP 5.6 syntax checker is complaining about Monolog 1.25 with this error when it reaches those four backported files

> PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{'

**Comment by stof** [comment]
IIRC, these interfaces are meant to allow writing code supporting Monolog 1 and 2 in parallel in libraries requiring PHP 7. Monolog itself does not use these interfaces in any classes in 1.x

**Comment by angusmcleod** [comment]
I see, I guess that makes sense, assuming the type declarations themselves are critical to the interface. There are some circumstances in which the mere presence of incompatible syntax is going to cause issues for older versions regardless of whether the file is used. But that's manageable (and also somewhat contextually specific), so yeah a decent trade off perhaps. Thanks.
