### ISSUE TITLE
TelegramBotHandler throws when Telegram API returns "message is too long" error

### ISSUE THREAD

**Issue by sergiks** [Seldaek/monolog#1542]
Monolog version 2.0.0

Telegram Bot API [sendMessage()][1] method has a message length limit of "4096 characters after entities parsing"

Added logging to my Telegram bot. Since stack trace might get long, Telegram API returns an error which is thrown unhandled by TelegramBotHandler:

    Fatal error: Uncaught RuntimeException: Telegram API error.
    Description: Bad Request: message is too long 
    in /var/www/prod/lumen/vendor/monolog/monolog/src/Monolog/Handler/TelegramBotHandler.php:96

Solution options:

* trim message length to 4096
* split long message into multiple messages
* attach long messages as a text file attachment to a message
* strip stack trace from message

[1]: https://core.telegram.org/bots/api#sendmessage

**Comment by alexandrmazur96** [comment]
Hi!

I have introduced PR some time ago. Before (**and if!**) it will be merged you can alternatively handle this by yourself:

Create a new `TelegramBotHandler` class in your project and extend it from `Monolog\TelegramBotHandler`, then override proper methods in your class (you can use code from my PR).

**Comment by Seldaek** [comment]
Fixed by #1616
