### ISSUE TITLE
Atomicity of logging to file

### ISSUE THREAD

**Issue by flaushi** [Seldaek/monolog#1555]
Monolog version 2

I guess the answer to the following question is "yes", but why exactly?

Is logging to a StreamHandler an atomic operation? Can I be sure that if 20 processes do use the same logfile, no lines get mixed up?

I am in a symfony setup, and any php process (or any concurrent request) might send log messages.
How can I be sure that those messages are not e.g. interleaved? In practice I have never encountered problems but I just don't understand why...

Thanks in advance, Olli

**Comment by stof** [comment]
It depends of the size of the log messages. PHP writes to files in chunks. So if your write logs messages that are bigger than the chunk size (8KiB by default if you don't change your php.ini), it will be split into multiple writes (see https://github.com/Seldaek/monolog/issues/1552 reporting that).

However, separate log messages can be interleaved

**Comment by flaushi** [comment]
Thanks for your quick answer! So, if not changing the default value and logging just an 80char line I can be sure to not get interleaving. Thanks!
