### ISSUE TITLE
LogstashFormatter does not allow to send no type and no host

### ISSUE THREAD

**Issue by nicolas-hernandez** [Seldaek/monolog#1562]
We have an ELK stack installation (using [filebeat](https://www.elastic.co/es/beats/filebeat)) that automatically fills in the type field if not present. This type is generated dinamically outside the application.

The [LogstashFormatter](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Formatter/LogstashFormatter.php#L80) always fills the `type` field (using either the `applicationName` or the `channel`) and the `host` field, but we would like to have the option of not doing it at all.

We would like to have a way to indicate to the formatter not to fill the `type` field. Could this be through a new parameter in the constructor or anything like this?

**Comment by Seldaek** [comment]
To be honest, if you have such custom requirements, I would recommend extending the class and overriding format(). It's easy enough. We can't have options for every possible field someone may want or not.
