### ISSUE TITLE
PHP 8 features introduced are breaking backward compatibility with PHP7.2++ 

### ISSUE THREAD

**Issue by juan-morales** [Seldaek/monolog#1567]
Monolog version 2

The function `preg_last_error_msg` was introduced in different files. This function is available in php8+.

The README states that Monolog requires php7.2+ in order to work, so this function is not backwards compatible with our minimum php version required.

The function is on this files:

Handler/BrowserConsoleHandler.php
Handler/ErrorLogHandler.php
Formatter/LineFormatter.php
Handler/SyslogUdpHandler.php
Utils.php

I am creating a Pull requests to provide a possible fix for this, please let me know in case I should adjust the pull request, I would really like to provide my first contribution to the project.
@Seldaek

**Comment by Seldaek** [comment]
Sorry about that, did not realize it was a new function. Thanks for the PR 👍🏻
