### ISSUE TITLE
DocBlocks do not match, phpstan issues

### ISSUE THREAD

**Issue by odan** [Seldaek/monolog#1582]
Monolog version 2

When I try to create a StreamHandler or RotatingFileHandler like this, ...
```php
$streamHandler = new \Monolog\Handler\StreamHandler('php://output', $level);
$rotatingFileHandler = new \Monolog\Handler\RotatingFileHandler($filename, 0, $level, true, 0777);
```

... then **phpstan** outputs the following errors:

```
 90     Parameter #3 $level of class Monolog\Handler\RotatingFileHandler  
         constructor expects 100|200|250|300|400|500|550|600|string, int   
         given.                                                            
 109    Parameter #2 $level of class Monolog\Handler\StreamHandler        
         constructor expects 100|200|250|300|400|500|550|600|string, int   
         given.     
```

It appears to be a bug in the DocBlocks of Monolog. See here:

* https://github.com/Seldaek/monolog/blob/2.3.2/src/Monolog/Handler/RotatingFileHandler.php#L46-L52
* https://github.com/Seldaek/monolog/blob/2.3.2/src/Monolog/Handler/StreamHandler.php#L43-L50

The DocBlock does not match with the actual constructor parameters. 

When I fix the DocBlock in RotatingFileHandler and StreamHandler manually, the phpstan errors are gone.

The RotatingFileHandler:

```php
/**
 * @param string $filename The filename
 * @param int $maxFiles The maximal amount of files to keep (0 means unlimited)
 * @param int|string $level The minimum logging level at which this handler will be triggered
 * @param bool $bubble Whether the messages that are handled can bubble up the stack or not
 * @param int|null $filePermission Optional file permissions (default (0644) are only for owner read/write)
 * @param bool $useLocking Try to lock log file before doing any writes
 */
public function __construct(string $filename, int $maxFiles = 0, $level = Logger::DEBUG, bool $bubble = true, ?int $filePermission = null, bool $useLocking = false)
```

The StreamHandler:

```php
/**
 * @param resource|string $stream If a missing path can't be created, an UnexpectedValueException will be thrown on first write
 * @param int|string $level The minimum logging level at which this handler will be triggered
 * @param bool $bubble Try to lock log file before doing any writes
 * @param int|null $filePermission Optional file permissions (default (0644) are only for owner read/write)
 * @param bool $useLocking Try to lock before doing any writes
 *
 * @throws \InvalidArgumentException If stream is not a resource or string
 */
public function __construct($stream, $level = Logger::DEBUG, bool $bubble = true, ?int $filePermission = null, bool $useLocking = false)

```

I would be able to create a PR to fix this DocBlocks.

**Comment by Seldaek** [comment]
The level is defined here https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/AbstractHandler.php#L40

Imported here https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/AbstractHandler.php#L23-L24

And the actual types are here:

https://github.com/Seldaek/monolog/blob/main/src/Monolog/Logger.php#L29-L30

Because yeah, we don't allow every int, so I thought it's kinda nice to exactly define what is allowed.

The ideal way would be for you to also import the type from Monolog\Logger and use it as param type, then it should resolve the phpstan errors.

**Comment by odan** [comment]
Unfortunately, that didn't work for me. This probably has to do with the fact that I additionally set the level from a settings array in the constructor.

```php
$this->level = (int)($settings['level'] ?? Logger::DEBUG);
```

I also define `int` and `null` in my method paramameter list for `$level`.

```php
public function addFileHandler(string $filename, int $level = null): self
```

```
Parameter #3 $level of class Monolog\Handler\RotatingFileHandler constructor expects
100|200|250|300|400|500|550|600|'ALERT'|'alert'|'CRITICAL'|'critical'|'DEBUG'|
'debug'|'EMERGENCY'|'emergency'|'ERROR'|'error'|'INFO'|'info'|'NOTICE'|'notice'|'WARNING'|'warning', int given.
```

I also don't want to declare "mixed" as datatype, because I prefer strict types. I just want to allow `int|null`.

As a quick fix I had to add `/** @phpstan-ignore-next-line */` everywhere I want to create a log handler.

**Comment by Seldaek** [comment]
Yeah you would need $this->level to be typed as a Level, and the param type you can define this using `@phpstan-param Level|null $level`. Then things should work IMO.
