### ISSUE TITLE
Inconsistent docblocks

### ISSUE THREAD

**Issue by FabianPiconeDev** [Seldaek/monolog#1586]
Monolog 2.3.2.

The docblock does not match with the params. I wanted to know more about the `$level` variable, but it is not described in the docblock.

https://github.com/Seldaek/monolog/blob/f2156cdd55f960432c332d4da1cd53c7fccf075f/src/Monolog/Handler/StreamHandler.php#L43-L51

**Comment by villfa** [comment]
The `$level` parameter is inherited from *AbstractHandler.php*:
https://github.com/Seldaek/monolog/blob/f2156cdd55f960432c332d4da1cd53c7fccf075f/src/Monolog/Handler/AbstractHandler.php#L36-L42

Take also a look at *Logger.php*:
https://github.com/Seldaek/monolog/blob/f2156cdd55f960432c332d4da1cd53c7fccf075f/src/Monolog/Logger.php#L29-L30

**Comment by Seldaek** [comment]
What @villfa said (thanks:)

**Comment by FabianPiconeDev** [comment]
I am not liking this approach. So I am forced to search for a description in parents, in other cases maybe in more levels of parants. Without an IDE, this would be even more difficult.
I would rather have more descriptive variables without docbocks, instead of less-descriptive variables with inconsistent docblocks.
Suggestion: `$loggingLevel` or `$minimumLoggingLevel` or `$minimumTriggeringLoggingLevel`
