### ISSUE TITLE
Syslog formatter

### ISSUE THREAD

**Issue by dkarlovi** [Seldaek/monolog#1594]
First of, I know the Syslog handler exists.

The suggestion here is to create a Syslog formatter, which would allow using it without messing around with PHP's settings.

Use case:
- formatter is created and Symfony enables it by default in dev mode
- the format of the log file is by default recognized by various logging helpers like https://lnav.org/ without any configuration, super-charging the logging information
- the user (developer) gets great DX by default, using standard best-of-kind apps

Syslog seems like the most obvious choice since it's very widely supported, if there's another alternative, that also works.

**Comment by Seldaek** [comment]
Closed by https://github.com/Seldaek/monolog/pull/1689

**Comment by dkarlovi** [comment]
Yay! \o/ Created a Symfony bundle issue here: https://github.com/symfony/monolog-bundle/issues/441
