### ISSUE TITLE
SlackHandler does not timeout

### ISSUE THREAD

**Issue by Flightfreak** [Seldaek/monolog#1602]
Monolog version 1.26.1

In a Laravel application we are using the SlackHandler for verbose logging. We see from our APM New Relic that certain logging processes are taking much longer than we allow them to. 

![image](https://user-images.githubusercontent.com/7059720/136364860-aee429d6-fd55-417d-8728-b58d5d65f73c.png)

```php
$handler = new SlackHandler($key, '#notices', 'username', true, null, Logger::NOTICE, false, false, true);
$handler->setConnectionTimeout(2);
$handler->setTimeout(4);
$monolog->pushHandler($handler);

$handler = new SlackHandler($key, '#warnings', 'username', true, null, Logger::WARNING, false, false, true);
$handler->setConnectionTimeout(2);
$handler->setTimeout(4);
$monolog->pushHandler($handler);

$handler = new SlackHandler($key, '#errors', 'username', true, null, Logger::ERROR, false, false, true);
$handler->setConnectionTimeout(2);
$handler->setTimeout(4);
$monolog->pushHandler($handler);
```
I'm looking for any advice on how to further analyze and control this.

**Comment by juan-morales** [comment]
Change is ready

**Comment by Flightfreak** [comment]
Thank you @juan-morales! I'm not familiar enough with the related stream functionalities but I will try to test this.

**Comment by juan-morales** [comment]
any updates on this one? :ok_man:
