### ISSUE TITLE
Why is includeStacktraces an option that cannot be set in constructor?

### ISSUE THREAD

**Issue by rajyan** [Seldaek/monolog#1603]
Monolog version 2

Thank you for this great logging tool!

I wanted to ask,

Why is includeStacktraces an option that cannot be set in constructor in LineFormatter and JsonFormatter?

because we have to call `includeStacktraces()` to enable stacktrace, we need to create an custom formatter just to enable stacktrace in some frameworks.

ex.

* using JsonFormatter with Laravel
  * Laravel default Lineformatter enables stacktrace like this, but no way to enable it in JsonFormatter by config.
  * https://github.com/laravel/framework/blob/b0ae2123b18b689b4bdd8f932f362ebc2531ed2c/src/Illuminate/Log/LogManager.php#L424-L426

* https://github.com/contributte/monolog

note.
* Symfony handles it it monolog-bundle and can configure it in config files.
  * https://github.com/symfony/monolog-bundle/blob/92bd02cc10c40605ff5b4cea88a2911e421aed6b/MonologBundle.php#L43-L52

If includeStacktraces could be set in constructor, we don't need to create a custom formatter class for these usages and configure it in framework config files.

**Comment by Seldaek** [comment]
I think it could be added. It would still implicitly force allowInlineLineBreaks  to true in LineFormatter but that can be documented (and possibly throw if allowInlineLineBreaks=false is passed with includeStacktraces=true)

**Comment by rajyan** [comment]
@Seldaek 
Thanks for your response and fixes!
