### ISSUE TITLE
How DeduplicationHandler works?

### ISSUE THREAD

**Issue by mkoske** [Seldaek/monolog#1608]
Hello! 

Have I understood correctly, that `DeducpliationHandler` lets all log messages through but deduplicates only messages that have level greater or equal to what has been set to `DeduplicationHandler::$deduplicationLevel`?

I.e. if I have set deduplication level to `error` and I have 10 `debug` messages and 10 `error` messages, all 10 `debug` messages are passed to wrapped handler and only 1 `error` message?

Br, Miika

**Comment by Seldaek** [comment]
Yeah the point is really to use this in combination with a FingersCrossedHandler IMO so that the dumping of debug info etc only happens when a deduplicated error reaches the FingersCrossedHandler. But this may depend on your use case.
