### ISSUE TITLE
swiftmailer is abandoned

### ISSUE THREAD

**Issue by BITWINGS-DE** [Seldaek/monolog#1611]
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.

**Comment by stof** [comment]
Well, Monolog has an optional feature allowing to use Swiftmailer to send logs by email. The `symfony/monolog-bridge` package already implements the equivalent feature using symfony/mailer.

**Comment by juan-morales** [comment]
But... Is this an issue?

**Comment by stof** [comment]
Well, to me, this should be closed. The fact that Swiftmailer is abandoned means that projects should probably stop using it, and so should stop using the SwiftmailerHandler of Monolog (migrating to one of the alternatives that already exist).

However, it does not mean that the SwiftmailerHandler should be removed from Monolog right now:
- it is a BC break, so it would require doing a new major version of Monolog (and if it is the only BC break, the impact on the ecosystem might not be worth it)
- the handler does not suddenly become broken, so if a project relies on it right now, it can still do it (but should plan a migration away from swiftmailer)

**Comment by juan-morales** [comment]
I also agree this should be close, and the handler should remain alive.

@BITWINGS-DE please consider these comments, and close the issue unless you encounter this event to represent an issue to the project.
