### ISSUE TITLE
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead

### ISSUE THREAD

**Issue by trianity** [Seldaek/monolog#1618]
**The swiftmailer/swiftmailer package is in the end of its life-cycle.**

The composer suggestion is:
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.

Since Laravel 8 also uses this package "monolog/monolog", the "monolog/monolog" must also switch in order for Laravel 8 to switch to the symfony/mailer package.

**Comment by juan-morales** [comment]
Sorry I Don't understand how this is affecting Laravel. 

I see that swiftmailer is under the "require-dev" Section of monolog's composer.json file... Not in "require".

Can you please explain better? 

Also... There is always a chance to write a custom Handler... In casé you wanted to refer to the SwiftmailerHandler. 

This is the second issue regarding this topic and I would like to know if We Are under a problem that we Don't see..... And that needs to be treated ASAP. 


Pd: even though that... Yes... This event should bé considered but also we Have to keep in mind that the SwiftmailerHandler SHOULD NOT bé deleted as there might be many systems still using it.


Thanks in Advance!

**Comment by stof** [comment]
please read the answers in https://github.com/Seldaek/monolog/issues/1611

To me, there is nothing to change in monolog. Monolog does not force you to use Swiftmailer at all. It _allows_ you to do so if you want.

**Comment by juan-morales** [comment]
@trianity any comment on this? If you agree with us, this issue can be closed, otherwise let us know.

**Comment by trianity** [comment]
@juan-morales @stof You are right. Thank you for the attention, and I am sorry that I missed the #1611 conversion. Ok, for close.
