### ISSUE TITLE
Implement a symfony/mailer handler

### ISSUE THREAD

**Issue by MaximilianKresse** [Seldaek/monolog#1621]
As swiftmailer is abandoned many of us are "forced" to search for an alternative. The recommended alternative is [symfony/mailer](https://github.com/symfony/mailer).

I'm not using the Symfony Framework but only the ```symfony/mailer```. I know there is an implementation inside the [monolog-bridge](https://github.com/symfony/monolog-bridge). But the ```monolog-bridge``` has some dependencies which I absolutely not need e.g. ```symfony/http-kernel```. So i don't want to require the ```monolog-bridge``` as I'm only missing the monolog handler. 

Is there a chance we could get an implementation directly inside the monolog package like with the swiftmailer handler?

**Comment by stof** [comment]
AFAIK the monolog package itself has stopped accepting handlers that rely on additional dependencies, as it makes it very hard to manage dependencies (the monolog package cannot require those dependencies, as it would annoy all projects not using that handler). That's also why the wiki has a [list of third-party packages](https://github.com/Seldaek/monolog/wiki/Third-Party-Packages) related to monolog.

**Comment by MaximilianKresse** [comment]
Ok thank you for your answer. That makes sense! I'll take a look at an alternative approach.

**Comment by Seldaek** [comment]
Yeah for this I think I may want to make an exception though as email support is kinda core IMO and just relying on mail() makes for a poor UX.

SwiftMailerHandler needs to be deprecated, and MandrillHandler also relies on SwiftMailer being present to build a message so this would need to be updated too.

**Comment by Seldaek** [comment]
If someone wants to help with this that'd be great btw.

**Comment by driesvints** [comment]
I'll answer @dmitry-ivanov's [question](https://github.com/Seldaek/monolog/issues/1638#issuecomment-1065085268) here. It's true that we don't use Symfony's Mailer directly, just the transports. It's because we already have our own Mailer class with its `send` method. Changing it would be a really big breaking change to our users. 

I'm not too familiar with Monolog's handlers or inner workings so I'm not sure I can answer what's needed to make this work on the Laravel side of things.

**Comment by raziel057** [comment]
Please note that with the current implementation of monolog-bridge there is an issue when using SmtpTransport related to the fact that Symfony Mailer use monolog to log in the ``stop`` method https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php

https://github.com/symfony/monolog-bundle/issues/405

**Comment by Seldaek** [comment]
See https://github.com/Seldaek/monolog/pull/1663
