### ISSUE TITLE
How do I output `level` as the level name instead of the constant value?

### ISSUE THREAD

**Issue by LeoAdamek** [Seldaek/monolog#1625]
How do I have my output (when using the `JSONFormatter`) output the level _name_  (e.g. info) in the `level` field, rather than the level constant value (e.g. 200)? My log management tools don't understand the numeric levels so don't display the logs properly.

I tried using a processor to copy the `level_name` value to `level` but this caused other handlers/formatters etc which used the level value to error.

**Comment by Seldaek** [comment]
I would say write your own formatter that does what you need.
