### ISSUE TITLE
New lines in context data do not output valid json. (Laravel)

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Seldaek/monolog#1629]
Monolog version 2

Noticed when using in a Laravel project and trying to ingest logs into ELK.

Something like this:
```
Log::debug('Testing new lines in log context.', ['yep' => "This\nhas\nNew Lines."]);
```

Outputs
```
[2022-01-25 09:53:22] local.DEBUG: Testing new lines in log context. {"yep":"This
has
New Lines."}
```

Expecting
```
[2022-01-25 09:53:22] local.DEBUG: Testing new lines in log context. {"yep":"This\\nhas\\nNew Lines."}
```

Just wonder if there is a setting I can alter to make it escape the new line characters as its invalid json.

Maybe related: https://github.com/Seldaek/monolog/issues/1185
https://stackoverflow.com/questions/70840461/new-lines-in-context-data-do-not-output-valid-json

**Comment by Seldaek** [comment]
If you need your log lines to be json, the best way is to use a JsonFormatter, then it's guaranteed json one line per log record.

If you're using a LineFormatter, by default it should have allowInlineLineBreaks set to false, which should also prevent that problem. See https://github.com/Seldaek/monolog/blob/6f233d2e2fc38378670db62640f630fdd7c8321f/src/Monolog/Formatter/LineFormatter.php#L43

Maybe check your config.
