### ISSUE TITLE
Deprecate SwiftMailerHandler in 2.x

### ISSUE THREAD

**Issue by Seldaek** [Seldaek/monolog#1638]
Perhaps add a new one based on symfony/mailer? Not sure if it is needed or if symfony's monolog-bridge covers that well enough already.

Also deprecate MandrillHandler's SwiftMessage arg

**Comment by dmitry-ivanov** [comment]
As far as I can see right now, the `symfony/monolog-bridge` provides a [handler](https://github.com/symfony/monolog-bridge/blob/5.4/Handler/MailerHandler.php), though we can't use it in Laravel projects.

If I'm not mistaken, Laravel doesn't use the `Symfony\Component\Mailer\Mailer` class directly. Thus, we don't have an instance of the `Symfony\Component\Mailer\MailerInterface` required by the [`symfony/monolog-bridge` handler](https://github.com/symfony/monolog-bridge/blob/4b56e17c443e7092895477f047f2a70f324f984c/Handler/MailerHandler.php#L35) as a first argument.

All we have in Laravel is `app('mailer')->getSymfonyTransport()` [which returns the `Symfony\Component\Mailer\Transport\TransportInterface`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailer.php#L561-L569) _(but, again - we can't use it in `symfony/monolog-bridge` handler)_.

I guess we need the `LaravelMailerHandler` as well? 🤔
@driesvints Could you please take a look at this?

Thank you!

**Comment by Seldaek** [comment]
Related issue for a mailer handler https://github.com/Seldaek/monolog/issues/1621 

This issue is really just about marking the SwiftMailerHandler as deprecated.

**Comment by Seldaek** [comment]
See https://github.com/Seldaek/monolog/pull/1663

**Comment by driesvints** [comment]
Heya, sorry I seem to have missed this. We indeed don't directly use the Mailer interface because it would collide with our own `send` method. We thought it wasn't necessary for our implementation. 

The PR by @Seldaek lgtm 👍
