### ISSUE TITLE
fastcgi error wraps around monolog logged messaages

### ISSUE THREAD

**Issue by duronrulez** [Seldaek/monolog#1642]
Monolog version 1.25.5

Some monolog messages get wrapped in a fastcgi error. We use the errorLog handler.
All error logs are configured to be stdout, both in the php-fpm.ini and php.ini configs.

An example call:
```
$logger->info('[TEST_ENTRY] ', [
    'field1' => "abc",    
    'field2' => "xyz"
]);
```

For the most part messages are logged like this, which is the expected result:
```
[2021-12-01 00:00:00] TEST_LOGGER.INFO: [TEST_ENTRY] {"field1":"abc","field2":"xyz"} []
```

But every so often some messages get wrapped by a fastcgi error:
```
2021/12/01 00:00:00 [error] 6626#6626: *309196 FastCGI sent in stderr: "PHP message: [2021-11-30 23:59:59] TEST_LOGGER.INFO: [TEST_ENTRY] {"field1":"abc","field2":"xyz"} []" while reading response header from upstream, client: xxxxx, server: xxxxx, request: "POST xxxxx HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "xxxxx"
```

Sometimes multiple monolog log entries get wrapped by 1 fastcgi error.

It seems that when php-fpm proccess errors out for whatever reason, fastcgi takes over all the logs (in the buffer?) from the php process. Any ideas how to prevent that from happening?

By looking at the errorlog handler that comes with Monolog, this very well may not be a monolog bug, but still worth a try if anyone had similar issue ...

Any ideas?

**Comment by Seldaek** [comment]
Not sure why it (nginx/?) reports fastcgi `stderr` output if you configured it to output on `stdout`. This seems odd. I don't really understand the setup/details fully tho.

**Comment by Seldaek** [comment]
Yeah I think logging to a file or syslog or similar would be the best option here.

**Comment by Seldaek** [comment]
Giving up or did you find a solution?

**Comment by duronrulez** [comment]
Sorry, should have explained probably.
Decided to go with the logging to a file approach, that way things are written as they happen. Even if the php proc crashes wont affect the log.
