### ISSUE TITLE
Will the 7.x incompatible code in AsMonologProcessor.php cause issues?

### ISSUE THREAD

**Issue by JReissmueller** [Seldaek/monolog#1645]
Monolog version 2.4.0

[monolog](https://github.com/Seldaek/monolog)/[src](https://github.com/Seldaek/monolog/tree/main/src)/[Monolog](https://github.com/Seldaek/monolog/tree/main/src/Monolog)/[Attribute](https://github.com/Seldaek/monolog/tree/main/src/Monolog/Attribute)/AsMonologProcessor.php  uses syntax incompatible with php 7.x.  Clearly you are aware of this because you have excluded it from linting
[monolog](https://github.com/Seldaek/monolog)/[.github](https://github.com/Seldaek/monolog/tree/main/.github)/[workflows](https://github.com/Seldaek/monolog/tree/main/.github/workflows)/lint.yml

Will this cause issues at runtime on php 7.x?

**Comment by stof** [comment]
AsMonologProcessor is meant to be used as an attribute. As attributes are a PHP 8.1+ feature, there is no reason to try loading this class on PHP 7.x

**Comment by JReissmueller** [comment]
Thanks for the info
