### ISSUE TITLE
Php linting

### ISSUE THREAD

**Issue by jcvignoli** [Seldaek/monolog#1646]
Hi,

I use the following php command-line function before git committing a project that includes monolog:

php -l

The latest monolog version introduced a parse error:

```
PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in vendor/lib/Monolog/Attribute/AsMonologProcessor.php on line 31
Errors parsing vendor/lib/Monolog/Attribute/AsMonologProcessor.php
Fix the error before commit.

```

Thanks!

**Comment by Seldaek** [comment]
Yes, that file is an attribute which is only compatible with PHP 8. Can you ignore it from  your linting (it won't be used unless you use it in your project)? I'd also recommend an upgrade to php8 :)

**Comment by jcvignoli** [comment]
Got it, will figure out how to make it work.
I'm still using PHP 7.4.x for development puproses, since many servers run it :)
Cheers, and thanks for you wonderful work.
