### ISSUE TITLE
RotatingFileHandler doesn't seem to support log level

### ISSUE THREAD

**Issue by dutchie027** [Seldaek/monolog#1649]
Monolog version 2.4

It seems that the RotatingFileHandler isn't respecting the log level being passed to it.

Using the following code:

``` php
<?php

declare(strict_types=1);

use Monolog\Handler\RotatingFileHandler;
use Monolog\Logger;

$logger = new Logger('test');
$logger->pushHandler(new RotatingFileHandler('/tmp/rfh.log', 300));
$logger->debug("Debug Message");
```

The $logger object actually puts the debug (100) message in the log even though the handler set it to 300.

If I do the same with the StreamHandler

``` php
<?php

declare(strict_types=1);

use Monolog\Handler\StreamHandler;
use Monolog\Logger;

$logger = new Logger('test');
$logger->pushHandler(new StreamHandler('/tmp/sh.log', 300));
$logger->debug("Debug Message");
```

It won't write the debug message to the log (as expected).

**Comment by dutchie027** [comment]
Looking more in to the handler for Rotating Logs, it seems that you mix the parameters. The second parameter in that handler is the number of logs to keep versus keeping consistency and having both second parameters be log level. Maybe something to change/add/refactor in the future for consistency as its definitely confusing, the jumbling of parameters.

**Comment by Seldaek** [comment]
Yeah the constructor param args are a bit of a mess because of organic evolution of things, that's just life. I don't think reordering them helps much as it'll only break third party code.

**Comment by dutchie027** [comment]
Maybe something for the next major release.

**Comment by stof** [comment]
@dutchie027 that would still be a mess for third-party code if they want to be compatible with 2 major versions

**Comment by dutchie027** [comment]
Yeah but for it to be a great package, consistency is key. It's not that hard to refactor the calls to the constructor if it means the construction is the same amongst all loggers. Doing it right doesn't mean it's easy.

**Comment by Seldaek** [comment]
The thing is it will never be the same amongst all handlers, as time passes we add new arguments again and those have to be added at the end and it's a mess again.

IMO the better solution to this problem is to use named parameters in php8+, `new FooHandler(level: $foo)` will work with all handlers.
