### ISSUE TITLE
Monolog version 2.4.0 incompatible with PHP versions <8

### ISSUE THREAD

**Issue by michdingpayc** [Seldaek/monolog#1651]
The file [src/Monolog/Attribute/AsMonologProcessor.php](https://github.com/Seldaek/monolog/blob/2.4.0/src/Monolog/Attribute/AsMonologProcessor.php) in monolog version 2.4.0 uses constructor property promotion (lines 31-33) which was introduced in PHP version 8.0. 

When used in PHP 7.4, one sees the following:
`PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in [...]/vendor/monolog/monolog/src/Monolog/Attribute/AsMonologProcessor.php on line 31`.

The issue here is the fact that the[ composer.json file](https://github.com/Seldaek/monolog/blob/2.4.0/composer.json) and therefore the [monolog/monlog packagist page](https://packagist.org/packages/monolog/monolog#2.4.0) lists the PHP version requirement as `">=7.2"`.

**Comment by michdingpayc** [comment]
I would love to see the constructor property promotion usage removed. The next best thing would be updating the `composer.json`. This is a backwards incompatible change. In keeping with semantic versioning, this should become version 3.0.0.

**Comment by Seldaek** [comment]
Attributes are a php8 feature so you cannot use this class on 7.4 anyway and I'm not sure what you are doing?

**Comment by wp-seopress** [comment]
Same issue here, VS Code returns an error.

Solution?

`public function __construct(?string $channel = null, ?string $handler = null, ?string $method = null) {`

**Comment by michdingpayc** [comment]
> Attributes are a php8 feature so you cannot use this class on 7.4 anyway and I'm not sure what you are doing?

Thank you for the quick response.

The attribute class isn't used in the PHP 7.4 project I'm referencing, but the monolog vendor directory is preloaded into opcache. This is done for performance purposes but with monolog version 2.4.0 that is also where this issue arises.

The file can be explicitly excluded from preloading, but I would like to hear your thoughts first.

**Comment by Seldaek** [comment]
Fixed in https://github.com/Seldaek/monolog/commit/508df120fac348c1e7ed6e590d83c549fa95434e - please upgrade to 2.5.0

**Comment by michdingpayc** [comment]
Thank you kindly!
