### ISSUE TITLE
GelfMethodFormatter uses deprecated methods

### ISSUE THREAD

**Issue by jortgies** [Seldaek/monolog#1659]
The file, level and facility fields are deprecated in gelf v1.1 (see [gelf spec](https://docs.graylog.org/v1/docs/gelf#gelf-payload-specification)). It is suggested to add those fields as "additional" instead. I've opened a pull request which uses the get/setAdditional [here](https://github.com/Seldaek/monolog/pull/1658).

I have discovered this after testing the v2.0.0-beta1 of graylog2/gelf-php, which deprecates support for gelf v1.0.

**Comment by Seldaek** [comment]
Fixed by https://github.com/Seldaek/monolog/pull/1664
