### ISSUE TITLE
Unable to send email with NativeMailerHandler in Laravel 8

### ISSUE THREAD

**Issue by julianphp** [Seldaek/monolog#1661]
Monolog version 2
Laravel 8.x
Php 7.4

Hi, I'm trying to use a laravel logging channel to send an email with the error, but I can't get anything to be sent, I'm trying with monolog and NativeMailerHandler but I still can't send anything, Laravel 8 and php 7.4:

config/logging.php
```        
'monolog' => [
            'driver' => 'monolog',
            'handler' =>\Monolog\Handler\NativeMailerHandler::class,
            'level' => 'debug',
            'with' => [
                'to' => 'to@to.com',
                'from' => 'noreplay@from.com',
                'subject' => 'test',
                'level' => 'debug'
            ],
],
```
Call from a controller
```
 Log::channel('monologmail')->debug('test');
```
In the .env i have the mails settings:
```
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=noreplay@from.com
MAIL_PASSWORD=password
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=noreplay@from.com
```
It simply does not send any message, nor does it give any error or anything...

**Comment by Seldaek** [comment]
I suspect the MAIL_* config from .env apply to the symfony/mailer. 

You can try with https://github.com/Seldaek/monolog/pull/1663 see if it helps, by passing it the mailer transport..

**Comment by Seldaek** [comment]
Yes the new SymfonyMailerHandler is the way to go IMO.
