### ISSUE TITLE
Monolog doesn't handle E_USER_ERROR as fatal error if registerErrorHandler is called with callPrevious === false

### ISSUE THREAD

**Issue by WoZ** [Seldaek/monolog#1669]
Monolog version 2.6

Example:

```
$logger = new Monolog\Logger('main');
$logger->pushHandler(new Monolog\Handler\StreamHandler('php://stderr', Monolog\Logger::DEBUG));
$errorHandler = new ErrorHandler($logger);
$errorHandler->registerErrorHandler([], false); // false is for callPrevious
$errorHandler->registerExceptionHandler();

trigger_error('Error', E_USER_ERROR);
```

Description:

1. `$errorHandler->registerErrorHandler` sets `$this->previousErrorHandler` to `null`.
2. `ErrorHandler::handleError()` doesn't log error, but sets trace into the `$this->lastFatalTrace`. `handleError` assumes that the  `handleFatalError()` will be called.
3. `callPrevious` option prevents `ErrorHandler::handleError()` to start chaining, default PHP's error logger will not be called, `handleError` returns true. This prevents PHP from setting "last error" structure internally.
4. `ErrorHandler::handleFatalError()` catches E_USER_ERROR and tries to receive `$lastError = error_get_last();`, but there's no last error.
5. Both functions ignores error logging.

Scenario. I use official docker php image with error_log == 'php://stderr'. Also, I want to use Monolog with StreamHandler and write logs to stderr. Monolog logs errors twice with default settings (first time default PHP logger writes logs to stderr, second time Monolog does the same).

**Comment by WoZ** [comment]
It's impossible to test shutdown functions with PHPUnit, so I tested this code with my hands. Results and tests in the comment https://github.com/Seldaek/monolog/pull/1670#issuecomment-1124067212

**Comment by Seldaek** [comment]
No need to port the patch I'll merge 2.x in main myself and fix anything that needs fixing.

**Comment by WoZ** [comment]
@Seldaek I accepted your change in #1670
