### ISSUE TITLE
Rename TestCase class to something else to improve developer experience

### ISSUE THREAD

**Issue by alexander-schranz** [Seldaek/monolog#1677]
I'm not sure why but PHPStorm begins to suggest me always the Monolog TestCase class instead of PHPUnit TestCase class. Was it in the past not part of the export? Not sure even strange that it begins now always be the first entry in the suggest list:

![Bildschirmfoto 2022-05-25 um 16 52 48](https://user-images.githubusercontent.com/1698337/170293363-b4e3cc11-0809-4678-9be6-2fd6cbb12769.png)

There was similar issue with PHPStan https://github.com/phpstan/phpstan-src/pull/634 where PHPStan decided to change the class for Developer Experience, maybe we can do the same here. Sadly it seems I'm little bit late as 3.0 was released shortly :/. But maybe we can already do some changes for a future 4.0 🤔.

**Comment by stof** [comment]
It is part of the package since 2.0

**Comment by alexander-schranz** [comment]
I see maybe was locked to monolog 1 until yet 🤔

**Comment by Seldaek** [comment]
Yeah I can see this sucks, but it seems more like a PHPStorm issue than something that can be fixed here.. Tons of packages expose a TestCase class/file, it should really prefer the PHPUnit one unless you have a local TestCase class in the project itself (which it already seems to prefer unless I'm mistaken).

Only thing I can think of is to mark it internal, which may help PHPStorm, but will also nag anyone relying on the class in third party extensions, which may be an ok trade-off. Can you try if adding `@internal` fixes it for you?

**Comment by mfn** [comment]
@alexander-schranz maybe also try on https://youtrack.jetbrains.com/ directly on the PhpStorm team

**Comment by stof** [comment]
> Tons of packages expose a TestCase class/file, it should really prefer the PHPUnit one unless you have a local TestCase class in the project itself (which it already seems to prefer unless I'm mistaken).

I don't think tons of package expose it. Many package have one in their testsuite. But as of Monolog 2, it is part of the package itself, not of the testsuite (and so not excluded from the archive). I think most packages exposing a reusable base testcase give it a name describing it.

**Comment by alexander-schranz** [comment]
@Seldaek Thank you!
