### ISSUE TITLE
Concurrency directory creation

### ISSUE THREAD

**Issue by Legion112** [Seldaek/monolog#1678]
Monolog version 2.4.0

We run test in parallel in sometimes we experience following behaviour:

```
 There is no existing directory at "/php-tests/report/logs/e2e/PathToTestDir" and it could not be cr  
  eated: File exists   
```
  
  This is from `\Monolog\Handler\StreamHandler::createDir`

**Comment by Seldaek** [comment]
Oh we did check for concurrency but I think there is a missing `clearstatcache()` in there to properly fix this issue. I'll fix this thanks for reporting 👍🏻

**Comment by Seldaek** [comment]
Hm no sorry.. PHP shouldn't cache the fact that a file is missing, so I don't quite see how this code can fail https://github.com/Seldaek/monolog/blob/60ad5183b5e5d6c9d4047e9f3072d36071dcc161/src/Monolog/Handler/StreamHandler.php#L193-L198

If mkdir failed, it checks for is_dir again and if the failure reason is `File exists` then it should definitely be there.

Is it possible that your concurrent test runs create the dir, log, and then delete the dir very quickly so you can run into a race condition where mkdir fails but is_dir still returns false as it was deleted already?

**Comment by Legion112** [comment]
Retry seem like a realy good option here @Seldaek.

**Comment by Seldaek** [comment]
@Legion112 I'm not sure this fixes anything in fact.. As per my comment on https://github.com/Seldaek/monolog/pull/1683#discussion_r893066866 - I believe you may then run into another race condition whereas the directory gets wiped by another process and then the file write fails. The only real solution if you do clear the directory after the test is to run tests in different directories IMO.

**Comment by Legion112** [comment]
@Seldaek well let's check if `$this->errorMessage === 'File exists'` and do not throw exception in that case? 
What do you think?

**Comment by Seldaek** [comment]
Maybe.. but if it exists why did is_dir() return false at line 196? Do you have a reliable way to reproduce the error so that we can try to inspect things further?

**Comment by Legion112** [comment]
https://github.com/Seldaek/monolog/pull/1685

**Comment by Legion112** [comment]
I don't know why `is_dir` returned false. 
I understand that is strange case. 
Maybe series of retry would prevent this issue. 
Like try to run `createDir ` body code 3 times only after 3 error throw exception.

**Comment by Seldaek** [comment]
These are all just band-aids though, not fixes. I would really like to understand what is going on before doing anything that hides the problem.

**Comment by Legion112** [comment]
We could try to look at [is_dir](https://www.php.net/manual/en/function.is-dir.php)
Several users have pointed that can return false in same cases.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/20613430/172837019-2e99e26a-3cd6-4162-88f9-c3c2433154e3.png">

**Comment by Seldaek** [comment]
What environment are you running this on? VM? virtual filesystem? etc?

**Comment by Seldaek** [comment]
The stat cache is only for true result, so if is_dir returns true it will cache it, if false it doesn't cache, so that can't be it.

k8s / docker yeah sounds like that shouldn't cause weird issues like VMs but who knows.
