### ISSUE TITLE
Level class is not added in composer package

### ISSUE THREAD

**Issue by David-Baron** [Seldaek/monolog#1679]
Monolog version 2.6

When install via composer require monolog/monolog
Installed => v 2.6 ( php 7.4) 

Monolog\Level::class is missing.

and is missing in the branch [2.x branch](https://github.com/Seldaek/monolog/tree/2.x/src/Monolog)

Or maybe the doc is wrong? 
Maybe something like that: $log->pushHandler(new StreamHandler('path/to/your.log', Logger::Warning)); ?

**Comment by Seldaek** [comment]
The docs are for the 3.x branch. See https://github.com/Seldaek/monolog/blob/2.x/doc/01-usage.md for 2.x docs. I guess I should add a warning on the 3.x docs so leaving this open for now as reminder.
