### ISSUE TITLE
How is the AMQPHandler supposed to work?

### ISSUE THREAD

**Issue by jerrac** [Seldaek/monolog#1687]
Monolog version 2

I'm pretty sure I'm just missing something, but I can't seem to get the AMQP handler to push logs onto my RabbitMQ queue.

I'm using `"php-amqplib/php-amqplib": "^3.2"` and `"monolog/monolog": "^2.7"` in my composer.json.

Here's my test code:

```php
<?php

use Monolog\Handler\AmqpHandler;
use Monolog\Logger;
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

require_once __DIR__ . '/vendor/autoload.php';

$logger = new Logger('App');
$queue = new AMQPStreamConnection(
  '127.0.0.1',
  (int)'9001',
  'guest',
  'guest'
);
$queue->channel()->queue_declare(
  'ac_logs',
  false,
  true,
  false,
  false,
  false
);

$amqpHandler = new AmqpHandler($queue->channel());
$logger->pushHandler($amqpHandler);
$logger->info("Started app."); // This line does NOT add anything to ac_logs.
$testMessage = new AMQPMessage("test message");
$queue->channel()->basic_publish($testMessage, '', 'ac_logs'); // This line DOES add the message to ac_logs.
```
I have RabbitMQ in a Docker container, hence the odd port number. When I exec into the container and run `rabbitmqctl list_queues` I can see the count of `ac_logs` only goes up by 1 after running my test.php file. It should go up by 2. 

What am I missing?

Thanks in advance!

**Comment by stof** [comment]
The routing key used by the handler is `$levelName.$loggerName` (in lowercase). So in your case, it would be `info.app`, not `ac_logs`.

You probably don't want to use a direct exchange for the log publication (unless you have separate queues for each combination of level and logging channel). The basic case would be a fanout exchange sending all messages to all queues. A more advanced case would allow queues to subscribes only to some messages.

**Comment by jerrac** [comment]
Thanks for the quick response!

So I have to set up a queue per logging level? I'm not seeing any `info.app` queue when I run `rabbitmqctl list_queues`.

I'd rather just override that and send the logs to a single queue. Is that possible?

FYI, my goal is to avoid file I/O slow downs in my app. A few years ago I seriously improved the speed of an app when I stopped logging to a file and started pushing to remote syslog. For this specific case, I'm planning on running a separate process to consume the logs and write them to a database.

> You probably don't want to use a direct exchange for the log publication (unless you have separate queues for each combination of level and logging channel). The basic case would be a fanout exchange sending all messages to all queues. A more advanced case would allow queues to subscribes only to some messages.
Um, so, I'm rather new to RabbitMQ, so I feel like I'm missing something obvious... Can you clarify that? I'm just not getting it... :\

**Comment by jerrac** [comment]
So I obviously did not read the RabbitMQ docs thoroughly enough... After doing a somewhat better job at that, I figured out what an exchange is and was able to get things working... 

Thanks.
