### ISSUE TITLE
PHP 8.2 - `utf8_encode` deprecated

### ISSUE THREAD

**Issue by systemsolutionweb** [Seldaek/monolog#1718]
Monolog version 1|2

**PHP 8.2** 
https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated

**Suggestion:**
```php
function_exists('mb_convert_encoding') ? mb_convert_encoding($json, 'UTF-8', mb_list_encodings()) : utf8_encode($json);
```

----

https://github.com/Seldaek/monolog/blob/d381140ca134f7ece43cd2c139d2207bb26dc329/src/Monolog/Utils.php#L203
https://github.com/Seldaek/monolog/blob/5579edf28aee1190a798bfa5be8bc16c563bd524/src/Monolog/Handler/ChromePHPHandler.php#L152
https://github.com/Seldaek/monolog/blob/5579edf28aee1190a798bfa5be8bc16c563bd524/src/Monolog/Handler/ChromePHPHandler.php#L167

**Comment by Seldaek** [comment]
Fixed by https://github.com/Seldaek/monolog/pull/1722
