### ISSUE TITLE
[v3] Grumphp fails on NullHandler construct $level initialization

### ISSUE THREAD

**Issue by soulcodex** [Seldaek/monolog#1727]
Hi guys,

Monolog v3

Check it out this issue on grumphp from monolog v3 package. Any idea?

https://github.com/phpro/grumphp/issues/1020

**Comment by stof** [comment]
And the level property is initialized in the constructor, so this error looks really weird.

**Comment by soulcodex** [comment]
Sorry @stof verifying the problem on source of grumphp i encountered the really source and is a bad or old implementation of monolog on https://github.com/gitonomy/gitlib repository, i will open a issue.

Thank you for your soon response, feel free to close the issue
