### ISSUE TITLE
JSONFormatter and normalizing of PHP objects

### ISSUE THREAD

**Issue by digilist** [Seldaek/monolog#1733]
Monolog version 2

Not sure if this is really a bug report or rather a feature request. But I noticed that some objects in the log context are not normalized like it is via the `NormalizerFormatter` and therefore disappear when using the `JsonFormatter`.

As an example, I am refering to the Symfony `AuthenticatorManager` that is writing a "Authenticator successful" log message after a successful authentication:

https://github.com/symfony/symfony/blob/25c2bb1c7c2f1d1f32955c5f0365ccbfcc447137/src/Symfony/Component/Security/Http/Authentication/AuthenticatorManager.php#L204

You can see there as well that the token is added to the log context (in my example it is an instance of `UsernamePasswordToken`).

On successful authentication and when using the `StreamHandler` with the default `NormalizerFormatter`, the output looks like this:

```
[2022-07-09T17:31:16.113589+02:00] security.INFO: Authenticator successful! {"token":{"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken":"UsernamePasswordToken(user=\"foo@bar.com\", roles=\"ROLE_USER\")"},"authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} {}
```

And when the `JsonFormatter` is used, it looks like this:
```
{"message":"Authenticator successful!","context":{"token":{},"authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"},"level":200,"level_name":"INFO","channel":"security","datetime":"2022-07-09T17:31:16.113589+02:00","extra":{}
```

As you can see, the token disappeared. I already did a bit of investigation and noticed that in the `NormalizerFormatter::normalize()` method contains some logic for objects:

https://github.com/Seldaek/monolog/blob/100d0f1625988be5cc8595aaf7429d0d9e96b9b8/src/Monolog/Formatter/NormalizerFormatter.php#L189-L207

The `JsonFormatter::normalize()` doesn't contain such logic.

My guess is that objects are not serialized, because json_encode is taking care of it. However, private fields in PHP are not part of the encoded JSON and therefore the information gets lost.

My suggestion for a fix would be to add a similar logic for the JSON normalizer if the objects implements `JSONSerializable` or has a `__toString()` method. What do you think about it? I can provide a PR if this proposal sounds reasonable to you.

**Comment by Seldaek** [comment]
JSONSerializable is already handled internally by json_encode, which is why there was no speical object treatment, but we need to add toString if it's present too.

**Comment by digilist** [comment]
Thank you! :blush:
