### ISSUE TITLE
Readme.md Link errors

### ISSUE THREAD

**Issue by mimmi20** [Seldaek/monolog#1734]
In an project which requires monolog and has some links copied from the readme.md the following links were reported broken:

- RotatingFileHandler: http://linuxcommand.org/man_pages/logrotate8.html
- CubeHandler: http://square.github.com/cube/
- PHPConsoleHandler: https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef

**Comment by Seldaek** [comment]
Thanks for the report, this actually lead me to deprecate two handlers 👍🏻
