### ISSUE TITLE
Cannot attach logs to errors in New Relic with Monolog 3

### ISSUE THREAD

**Issue by ostrolucky** [Seldaek/monolog#1735]
We have this Monolog processor
```php
final class NewrelicTraceProcessor implements ProcessorInterface
{
    public function __invoke(array $record): array
    {
        $metadata = newrelic_get_linking_metadata();

        $record['span.id']  = $metadata['span.id'] ?? null;
        $record['trace.id'] = $metadata['trace.id'] ?? null;

        return $record;
    }
}
```

It makes logs being sent to NR look like so:
```json
{
  "channel": "app",
  "context.alert.expired": "null",
  "context.alert.id": 12844,
  "context.alert.reached": 1657704118,
  "context.alert.type": "price",
  "context.handler": "Haushalt\\Bl\\DomainBundle\\Application\\Offer\\Handler\\DispatchPriceAlertReachedNotificationHandler",
  "context.offerId": 1007892303,
  "datetime": "2022-07-13T11:21:58.446984+02:00",
  "entity.guid": "MzIxODc4M3xFWFR8U0VSVklDRXwtODA3OTcwMzc0MDUwOTAyNjc3NQ",
  "entity.guids": "MzIxODc4M3xBUE18QVBQTElDQVRJT058NzQxMTE5ODE5|MzIxODc4M3xFWFR8U0VSVklDRXwtODA3OTcwMzc0MDUwOTAyNjc3NQ",
  "entity.name": "fe-bl-service",
  "entity.type": "SERVICE",
  "extra.uid": "2b4344d",
  "hostname": "h2-wrk1-p02",
  "index": 0,
  "level": 200,
  "level_name": "INFO",
  "Logfile": "/home/h2-fe-bl-service/deployer/current/var/log/prod.log",
  "message": "Dispatching Reached Alert",
  "newrelic.source": "api.logs",
  "service_name": "fe-bl-service",
  "span.id": "b4d0c933685c5c33",
  "timestamp": 1657704118000,
  "trace.id": "d3c0d394d1c78be8"
}
```

This is vital for eg. this button to work 
![image](https://user-images.githubusercontent.com/496233/178703077-b9e16e3b-679d-4b87-bc89-35bf91f79587.png)

because NR attempts to search through logs based on filter `trace.id:{traceId}`

If we move this to `context`, this will stop working, NR will not find any logs and button will be disabled. `\Monolog\LogRecord` allows custom info added only nested under `context` or `extra` keys, which is an issue here.

**Comment by Seldaek** [comment]
Yeah this should be in an extension/wrapper for the formatter used on your newrelic handler IMO. The processor was an abuse which admittedly worked well before :)

That said if this is standard newrelic functionality why not send a PR to add it by default in the newrelic handler? Or is it an optional thing? It could be made optional then..

**Comment by ostrolucky** [comment]
Because handler bundled with monolog doesn't use newrelic logs functionality, it just handles errors and even for that one how it works is that it marks current transaction as error. We log to file via stream handler and forward it to NR via fluentbit.

Yeah I guess there could be a custom formatter, but it wouldn't be straightforward. Why did you find it necessary to disallow adding this info outside of context/extra keys?

**Comment by Seldaek** [comment]
> Because handler bundled with monolog doesn't use newrelic logs functionality, it just handles errors and even for that one how it works is that it marks current transaction as error. We log to file via stream handler and forward it to NR via fluentbit.

OK sorry I am not super familiar with it and forgot that :) 

> Yeah I guess there could be a custom formatter, but it wouldn't be straightforward. Why did you find it necessary to disallow adding this info outside of context/extra keys?

Because PHP 8.1 finally made it reasonably possible to switch from arrays to more structured objects. This however means that it's not so possible to smash random data on the records anymore. It has to go in context or extra.

I think a custom formatter shouldn't be much more work than the processor tbh. I assume you do write a json formatted file right now? 

If so you could do smth like:

```
final class NewrelicTraceFormatter extends JsonFormatter
{
    protected function normalizeRecord(LogRecord $record): array
    {
        $normalized = parent::normalizeRecord($record);
        $metadata = newrelic_get_linking_metadata();

        $normalized['span.id']  = $metadata['span.id'] ?? null;
        $normalized['trace.id'] = $metadata['trace.id'] ?? null;

        return $normalized;
    }
}
```

**Comment by ostrolucky** [comment]
Indeed if it's as simple as that that might be good enough. I'll try it, thanks.

**Comment by bradjones1** [comment]
For SEO: The same situation exists for Google Cloud Logging/StackDriver. E.g. if you wish to include a trace ID with `logging.googleapis.com/trace` it is expected at the top-level.
