### ISSUE TITLE
Implement ElasticSearchFormatter

### ISSUE THREAD

**Issue by stunited-nhatnguyen** [Seldaek/monolog#1742]
For special case, i want to custom format of ElasticSearchFormater, but i can't extend or implement it. Why we do it for more flexible?

**Comment by Seldaek** [comment]
Why can't you extend ElasticsearchFormater and override getDocument to do what you need?

**Comment by stunited-nhatnguyen** [comment]
I try extended it but not work, in ElasticsearchHandler has condition formater instanceof ElasticsearchFormater in setFormatter function.

**Comment by Seldaek** [comment]
That shouldn't be a problem. A class extending it will still be an instance of the parent class.
