### ISSUE TITLE
Add support for updating context more easily 

### ISSUE THREAD

**Issue by lyrixx** [Seldaek/monolog#1750]
Hi

I'm updating our application to monolog V3, and I'm not super fan of the new LogRecord API.

I use many processors to "serialize" / "unwrap" the data. IE, In my application I log raw objects in the the context:

```php
$logger->error('something', ['crawl' => $crawl]);
```

and then I use a processor to "unwrap" / "serialize" the data.

```php
class ModelProcessor implements ProcessorInterface
{
    public function __invoke(array $record): array
    {
        foreach ($record['context'] as &$value) {
            if ($value instanceof Crawl) {
                $value = [
                    'id' => $value->getId(),
                ];
```

But now, the code is much harder to write 
```php
$record = $record->with(context: array_replace($record->context, [
    $k =>  [
        'id' => $value->getId(),
    ]
]));
```

It would be nice to have a simpler API

1. by removing the readonly on the context
2. by adding a `withContextKey` method
  ```
  $record = $record->withContextKey('user', ['id' => 1]);
  ```
3. Another idea ?

---

Not one may suggest I can snapshot the $context, alter it, and replace it at the end, but this mean I will create many clone of log, even if the context did not change. Since I write *a lot of* log, I prefer to avoid that!

**Comment by Seldaek** [comment]
Your option 2 here would also result in multiple log clones if I'm not mistaken?

Option 1 yes sure, we could. It was mutable in v1/2.. But IMO context data should not be modified after log record creation, only extra is meant to store stuff from processors.

Besides making the array mutable means that anything changed by one processor somewhere has an effect on the record no matter where it's stored, so with fingers crossed or buffer handlers keeping records in memory this could have weird side effects. Technically even extra should be readonly to be strict here.. But for BC this is difficult.

> Not one may suggest I can snapshot the $context, alter it, and replace it at the end, but this mean I will create many clone of log, even if the context did not change. Since I write a lot of log, I prefer to avoid that!

I don't see the point here, you could only ->with() if the context did change at the end?

**Comment by lyrixx** [comment]
> Option 1 yes sure, we could. It was mutable in v1/2.. But IMO context data should not be modified after log record creation, only extra is meant to store stuff from processors.

How could you achieve my use case? I really like this pattern, and IMHO the best place to transform the context (object to scalar) is in processors. But I may miss something, or it's stupid idea 😬.

BTW, I want this transformation to be applied everywhere (dev, prod, test // sentry, kibana, logfile)

> Your option 2 here would also result in multiple log clones if I'm not mistaken?

Yes, but It'll be encapsulated in monolog and reduce the number of LOC in my app

>I don't see the point here, you could only ->with() if the context did change at the end?

You are right, I badly anticipated an answer and I was not clever enough to think about this solution

**Comment by Seldaek** [comment]
So.. it still seems to me like calling with() just once at the end of your transforms is the best option? It's a little more code than in monolog 2 for you yes, but the most efficient way to implement this pattern I think.

The only better way I could think of would be to add a concept of context transformers to monolog itself, or as a way to hook into NormalizerFormatter at least.. but that would probably do it too late and end up doing it multiple times if you log to several locations. I see the pattern has some merit but I'm not sure it really is worth adding it natively for what little code it'd save you vs using a processor.

**Comment by lyrixx** [comment]
ok, so let's close this.

Thanks for the discussion
