### ISSUE TITLE
Better example to SocketHandler

### ISSUE THREAD

**Issue by csimpi** [Seldaek/monolog#1751]
Monolog version 1|2|3?
2. (in Laravel)

I can't make `SocketHandler` work at all.
Using the example throws an error the sock doesn't exist.
I guess in this case it is supposed to create the stream and post the logs there. 

I tried to create a socket but it doesn't work with `SocketHandler`.

Could somebody give me a 100% working example code both for the server and client side? I would really appreciate that.

**Comment by mimmi20** [comment]
> Could somebody give me a 100% working example code both for the server and client side? I would really appreciate that.

Why the client side? Monolog is working only on the server.
