### ISSUE TITLE
Cycle detection doesn't work well with fibers

### ISSUE THREAD

**Issue by kelunik** [Seldaek/monolog#1752]
[Cycle detection](https://github.com/Seldaek/monolog/blob/e68c00670e310e276da9624d75965f5d2f28aa80/src/Monolog/Logger.php#L324) is broken when using fibers, because it assumes that if the function is entered multiple times, it's a cycle. With fibers, the function might be entered multiple times in different fibers if one of them suspends somewhere within the function.

What are your thoughts to moving cycle detection to an interface? There could be a `NullCycleDetector` that doesn't detect cycles at all, a `CountingCycleDetector` and then a [`FiberLocal`](https://github.com/revoltphp/event-loop/blob/4e7455506d9ff61f3705b76a20a8f12ad4dc1552/src/EventLoop/FiberLocal.php) based implementation that keeps track of the depth for each fiber separately. I'm of course also fine with fibers being supported natively, but I don't think it's a good idea to put this logic into `Logger` itself in that case.

**Comment by Seldaek** [comment]
Given that concurrency isn't really the default model for PHP still, for now you'd need to call $logger->useLoggingLoopDetection(false)  (which was added for Swoole "support" https://github.com/Seldaek/monolog/commit/9c1566a971d42ff1acb4756708e8d9a5568bb194) - I'm not sure how the FiberLocal impl would look like, as I am not super familiar with fibers tbh. But I'm open to supporting that if possible as I am sure fibers will only see more usage with time.

**Comment by kelunik** [comment]
Fibers each have their own call stack. Fiber locals are basically variables bound to a specific fiber, so a bit like `static`, but per fiber. I can work on a PR. I guess `FiberLocal` doesn't have to be used directly, as clearing isn't required here, so support can be built-in.
