### ISSUE TITLE
[RotatingFileHandler] Is it possible to save logs in file per hour option?

### ISSUE THREAD

**Issue by piernik** [Seldaek/monolog#1769]
Monolog version 1

As in topic. Clients generate large files per day - even 3GB. Is it possible to have `file per hour` strategy?

**Comment by michaljusiega** [comment]
Maybe just look at these files and do minimize what information you saving. If you save information likes route matches, doctrine, php deprecations etc, you got an answer why you have 3GB logs per day :)

**Comment by Seldaek** [comment]
Nope, I suggest you use logrotate + a simple StreamHandler to have more flexibility here.
