### ISSUE TITLE
Telegram Handler

### ISSUE THREAD

**Issue by deulizealand** [Seldaek/monolog#1787]
Monolog version 2.8

How to send Telegram logs to private channel or private group instead of public channel ?

**Comment by deulizealand** [comment]
i found that we can use chat id of the private group or channel

**Comment by claudiu-cristea** [comment]
@deulizealand did you prefix with "@"? What about the dash in front of the ID?

**Comment by chimit** [comment]
Using a chat ID like `-1654567890` doesn't work for me: `RuntimeException  Telegram API error. Description: Bad Request: chat not found.`

@alexandrmazur96 is there any way to support private chats/channels?
