### ISSUE TITLE
"Object of class Monolog\Level could not be converted to int" 

### ISSUE THREAD

**Issue by NavyCoat** [Seldaek/monolog#1789]
Monolog version 3.2

I'm experiencing strange behavior from Monolog when using any logging method.

> ErrorException: Warning: Object of class Monolog\Level could not be converted to int
#12 /vendor/monolog/monolog/src/Monolog/Logger.php(314): Monolog\Logger::addRecord
#11 /vendor/monolog/monolog/src/Monolog/Logger.php(614): Monolog\Logger::error
#10 /src/MyFile.php(107): Service\MyFile::foobar

Inside foobar method I'm just executing
`        $this->logger->error('lorem ipsum');`

I am still trying to understand why this is happening.
I tried to reproduce the steps in 3v4l.org and on my local env, but this only happens on my prod env.

Can this be related to this package, or is this something with opcache, maybe? Any idea how to fix this?

**Comment by stof** [comment]
`addRecord` has an argument type being `int|Level`, so PHP should not try to convert the argument to `int`

**Comment by Seldaek** [comment]
Seems like an issue on your end but I can't imagine what would cause this. Perhaps incorrect version installed? Or like two versions in parallel from different pieces of software you run?

**Comment by Seldaek** [comment]
I mean opcache could be a thing if you don't clear it on deploy and you have some old or new Logger class in there, but it sounds weird even then..

**Comment by sakarikl** [comment]
This same thing happens to us. And affects only servers where Instana is installed (instana.io)

**Comment by sakarikl** [comment]
I bet that for us Instana hooks into monolog in PHP process and now does it using old interface.

**Comment by NavyCoat** [comment]
@sakarikl Thanks for a clue! I'm not using Instana, but maybe I have another tool that is doing something like it.

**Comment by NavyCoat** [comment]
>  Lol, that was Instana, indeed. :joy: Thanks!

**Comment by NavyCoat** [comment]
> I bet that for us Instana hooks into monolog in PHP process and now does it using old interface.

Lol, that was Instana, indeed. :joy: Thanks @sakarikl !

**Comment by sakarikl** [comment]
I got a patch file from instana support that basically just changed enum usages to integers. And no timeline when actual fix would be available. :)

**Comment by matt-horwood-mayden** [comment]
Hello,
We are running instana and have also hit this issue, Instana have provided a patch that should fix the issue. But they seem to think its a Monolog issue.

Here is the patch if you need it, not sure if this should land as a PR also

```
--- vendor/monolog/monolog/src/Monolog/Logger.php.orig	2022-07-24 05:00:55.000000000 -0700
+++ vendor/monolog/monolog/src/Monolog/Logger.php	2022-11-07 08:57:00.953341669 -0800
@@ -559,7 +559,8 @@
      */
     public function debug(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Debug, (string) $message, $context);
+        //$this->addRecord(Level::Debug, (string) $message, $context);
+        $this->addRecord(7, (string) $message, $context);
     }
 
     /**
@@ -572,7 +573,8 @@
      */
     public function info(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Info, (string) $message, $context);
+        //$this->addRecord(Level::Info, (string) $message, $context);
+        $this->addRecord(6, (string) $message, $context);
     }
 
     /**
@@ -585,7 +587,8 @@
      */
     public function notice(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Notice, (string) $message, $context);
+        //$this->addRecord(Level::Notice, (string) $message, $context);
+        $this->addRecord(5, (string) $message, $context);
     }
 
     /**
@@ -598,7 +601,8 @@
      */
     public function warning(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Warning, (string) $message, $context);
+        //$this->addRecord(Level::Warning, (string) $message, $context);
+        $this->addRecord(4, (string) $message, $context);
     }
 
     /**
@@ -611,7 +615,8 @@
      */
     public function error(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Error, (string) $message, $context);
+        //$this->addRecord(Level::Error, (string) $message, $context);
+        $this->addRecord(3, (string) $message, $context);
     }
 
     /**
@@ -624,7 +629,8 @@
      */
     public function critical(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Critical, (string) $message, $context);
+        //$this->addRecord(Level::Critical, (string) $message, $context);
+        $this->addRecord(2, (string) $message, $context);
     }
 
     /**
@@ -637,7 +643,8 @@
      */
     public function alert(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Alert, (string) $message, $context);
+        //$this->addRecord(Level::Alert, (string) $message, $context);
+        $this->addRecord(1, (string) $message, $context);
     }
 
     /**
@@ -650,7 +657,8 @@
      */
     public function emergency(string|\Stringable $message, array $context = []): void
     {
-        $this->addRecord(Level::Emergency, (string) $message, $context);
+        //$this->addRecord(Level::Emergency, (string) $message, $context);
+        $this->addRecord(0, (string) $message, $context);
     }
 
     /**
```

**Comment by Seldaek** [comment]
Yeah sorry but we are not going to patch this like that, it makes no sense. They should make sure to update their support to include Monolog 3.

**Comment by sakarikl** [comment]
We ended up dumping Instana altogether mainly because of this.

**Comment by bkuschel** [comment]
We are looking at the issue and investigating a possible fix for the Instana PHP Tracer.

**Comment by ltrk2** [comment]
@NavyCoat @sakarikl @Seldaek

We fixed the behaviour identified in this issue by rolling out general support for Monolog 3 with Instana PHP Tracer 3.0.0.

**Comment by matt-horwood-mayden** [comment]
Morning @ltrk2 

Do you have a planed release data for that?

**Comment by ltrk2** [comment]
@matt-horwood-mayden it's already out. It was rolled out across the board yesterday (February 26).
