### ISSUE TITLE
`SyslogUdpHandler` `autoclose` option

### ISSUE THREAD

**Issue by boesing** [Seldaek/monolog#1795]
Hey there,

we do have some longrunning processes using `pcntl_fork` which do log stuff via `SyslogUdpHandler` to our syslog.
Due to the fact that it is a longrunning process, the UDP socket is never closed and therefore stays open until the process is restarted.
I wonder if it would make sense to have an option available in the `SyslogUdpHandler` which allows projects to configure some `socketAutoClose` option so that the socket is being closed after message is being sent.

I am open for other suggestions as well (i.e. some `CloseAfterProcessHandler` which decorates another processor).
Thanks for your time.

Max

**Comment by Seldaek** [comment]
If you're using Monolog 3, you can call $logger->close() as well as $logger->reset() in between "jobs" or whatever you have as a good point to do this where it makes sense, that would then be reopened whenever something needs to be written again.

https://github.com/Seldaek/monolog/blob/d3d495b742cacf9c0af87867bf87dab2fc591e68/src/Monolog/Logger.php#L401-L416

**Comment by boesing** [comment]
I do not have a strong need in closing all handlers. Some do not need to be closed as they do not keep ports open, that seems only being the case for the udp socket here 🤔

I have no handler doing http requests but I dont think that curl keeps TCP ports open which were used to send HTTP requests?

**Comment by Seldaek** [comment]
You can also close the UDP handler directly of course, if that's more appropriate, but IMO closing/resetting everything between jobs in long running worker processes is a good approach.
