### ISSUE TITLE
How to set other field into the LogRecord for V3

### ISSUE THREAD

**Issue by yankewei** [Seldaek/monolog#1798]
Monolog version 1|2|3?
3
Write your question here.
In Monolog version 2, we could kindly call the `pushProcessor` method to add our custom processor, which gracefully adds some fields to the log. However, in version 3, the processor's callable has to respectfully accept a LogRecord object, and the `LogRecord` can only have seven keys - "message", "context", "level", "channel", "datetime", and "extra". We cannot set other fields in the LogRecord object. May I kindly ask if you provide an alternative method that allows us to elegantly customize the `LogRecord` content?

**Comment by Seldaek** [comment]
processors were always meant to store data in the extra array, which is still available in monolog 3.
