### ISSUE TITLE
Can I transform final Monolog request to curl string and log it somewhere?

### ISSUE THREAD

**Issue by zeyser** [Seldaek/monolog#1809]
Monolog 2

Hi. I'm trying to understand - Why I can't receive request from Monolog on my server(everything fine from local machine). 
Because of that I want to transform Monolog request into cUrl string and execute it directly from server machine (I think that such request can be blocked on server side by firewall or something like that)

For initialisation I'm using next code
```
protected function init()
    {
        parent::init();

        $config = Factory::getInstance()->getConfigurationForInstallation('monolog');
        $host = $config->getHost();
        $port = $config->getPort();

        $handler = new SyslogUdpHandler($host, $port);
        $formatter = new LogstashFormatter('portal-log');
        $handler->setFormatter($formatter);

        $this->log = new Logger('portal-logger');
        $this->log->pushHandler($handler);
    }
```
and call with  `$this->log->addRecord(Logger::ERROR, '[PORTAL] ' . $message, []);`

How can I catch final result of such request and reproduce it on server?

P.S. I will be grateful for any other recommendation for my situation (server not send but local machine - OK)

**Comment by stof** [comment]
I don't think curl supports the Syslog UDP protocol.
