### ISSUE TITLE
why datetime is UTC?

### ISSUE THREAD

**Issue by kukudeliu** [Seldaek/monolog#1810]
`
		
	$logger = new Logger('TEST');
        $logger->setTimezone(new \DateTimeZone('Asia/Shanghai'));
        $client  = new MongoDB\Client('mongodb://127.0.0.1/');
        $handler = new MongoDBHandler($client, 'logs', 'prod');
        $logger->pushHandler($handler);
        $logger->info('666', [1213213]);
        echo 'success';`

![image](https://github.com/Seldaek/monolog/assets/16948472/af4dcae2-fdcb-4702-b386-09f520569a18)

**Comment by kukudeliu** [comment]
2023-06-07 10:15:23.555 is right

**Comment by HenriqueAmrl** [comment]
As per the information provided in the MongoDB documentation (source: https://www.mongodb.com/docs/v4.4/tutorial/model-time-data/#:~:text=Time%2DSeries%20Data-,Overview,time%20representations%20into%20this%20form), timestamps are stored in UTC by default.
