### ISSUE TITLE
setting log level at runtime

### ISSUE THREAD

**Issue by LiamFry** [Seldaek/monolog#1821]
Monolog version 3
Per #1418, I see that there is no [longer the] concept of "get level" in Monolog.
Does this mean there's no way to change the log level at runtime?

**Comment by Seldaek** [comment]
Not sure what you mean, changing the minimum level handled?  You can do it via the FilterHandler (then nest your handler in it, and make sure the nested one accepts everything), that one has setAcceptedLevels
