### ISSUE TITLE
Monolog\Level (enum) against Constants

### ISSUE THREAD

**Issue by sumedia** [Seldaek/monolog#1830]
Hi,

i'm currently not understand why removing the level constants from Monolog, which has a proper and changeable definition of the right level for monolog.
Instead i should use a enum Monolog\Level, which does in the end exactly the same.
Give a valid Errorlevel.
I'm forced to, now!
What are the advantages of this?
I can only consider it as usefull to convert invalid Levels inside the application.
It's a deprecated world :D

Regards

Sven

**Comment by sumedia** [comment]
Yes i understand, but consider the way:

myFunction($var) {
    $code = ENUM::get($var);
}

What's about this?

**Comment by stof** [comment]
I don't understand what you code snippet is about

**Comment by Seldaek** [comment]
You mean Level::from($var)? Have you looked how enum work in php?  See https://www.php.net/manual/en/language.enumerations.backed.php

**Comment by Seldaek** [comment]
Level instances also have convenient ways to get other standard level types from them this is something you couldn't do with constants https://github.com/Seldaek/monolog/blob/main/src/Monolog/Level.php#L150-L187

**Comment by sumedia** [comment]
Why was it a bad idea?
I have first to review the reason why i wrote this, it's some time ago.
