### ISSUE TITLE
Fatal error: method_exists(): The script tried to execute a method or access a property of an incomplete object.

### ISSUE THREAD

**Issue by koekaverna** [Seldaek/monolog#1834]
Monolog version 2|3

When `NormalizeFormatter` use `method_exists` on [incomplete object](https://www.php.net/manual/en/function.unserialize.php) it cause fatal error.

I found the problem in logs without any stacktrace information. It can happen when `unserialize` wrong response from service or `unserialize` outdated data from session. Anyway NormalizeFormatter should not make fatal error even on corrupted data.

I made PR with fix. Please check it out. https://github.com/Seldaek/monolog/pull/1833

**Comment by koekaverna** [comment]
@Seldaek Hi, it's not fixed in 2.9.2 JsonFormatter. There is normalize method override NormalizerFormatter::normalize and have same problem...

**Comment by Seldaek** [comment]
@koekaverna https://github.com/Seldaek/monolog/commit/884aa47a055ea3e8e351ceaf4dfc67f52fff44c0 should take care of this for JsonFormatter at last.
