### ISSUE TITLE
LogglyHandler - incorrect records comparison. 

### ISSUE THREAD

**Issue by dimasvas** [Seldaek/monolog#1838]
Monolog version 3.4.0

Loggly does not receive all logs. The reason is an incorrect records comparison in LogglyHandler. 

[Source reference](https://github.com/Seldaek/monolog/blob/9546d94bdc212214e23aa7ea5a3734417e33e5e1/src/Monolog/Handler/LogglyHandler.php#L129)

Now the code is: 

   `return ($record->level >= $level);`

    
It looks like should be:
    
`return ($record->level->value >= $level->value);`

We should compare values properties of records.

**Comment by omerimzali** [comment]
Hi @dimasvas, I crated a pr for this one.
 https://github.com/Seldaek/monolog/pull/1841

**Comment by dimasvas** [comment]
Hi[omerimzali](https://github.com/omerimzali)! Thank you very much!!!! 
I have just decorated the handler and created a temporary kludge until new version of the monolog package with the fix will be released. Thank you again!
