### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 102863464 bytes) *** monolog/src/Monolog/Formatter/HtmlFormatter.php on line 64

### ISSUE THREAD

**Issue by clemask** [Seldaek/monolog#1839]
Monolog version 1|2|3?
3

Write your bug report here.
I inherited the abstract class MailHandler and implemented the send method for sending emails. When triggering emails to be sent at a specified error level, a severe out of memory error occurred.

Error log：
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 102863464 bytes) in /project/vendor/monolog/monolog/src/Monolog/Formatter/HtmlFormatter.php on line 64
```

**Comment by Seldaek** [comment]
That looks like you had one row with 100MB of data, could be a gigant stack trace or you dumped a huge dataset in context? In any case not really something monolog can prevent.. Gotta make sure you keep things within reason or increase your memory limit.
