### ISSUE TITLE
OpenObserve Handler

### ISSUE THREAD

**Issue by homersimpsons** [Seldaek/monolog#1844]
OpenObserve (https://openobserve.ai/) is a platform to ingest logs.

It would be great to have a Monolog handler for it.

This should be doable with https://openobserve.ai/docs/ingestion/logs/curl/ and this should be rather easy to test using their docker image https://openobserve.ai/docs/quickstart/#self-hosted-installation.

**Comment by Seldaek** [comment]
Feel free to publish your own handler as a third party package and then list it at https://github.com/Seldaek/monolog/wiki/Third-Party-Packages - I'm not adding new handlers for specific services like that anymore to keep maintenance reasonable.
