### ISSUE TITLE
Brevo mail api handler

### ISSUE THREAD

**Issue by Rogtaz** [Seldaek/monolog#1846]
Brevo is a platform for communicating via email.
https://developers.brevo.com/docs/getting-started
It would be nice to have the Brevo api to send an email.
I wrote the handler but I cannot make a pull request which is reserved for collaborators.

**Comment by stof** [comment]
This can already be supported via the SymfonyMailerHandler.
If you have an alternate implementation, maybe it should be maintained in a dedicated package maintained by you.

> I wrote the handler but I cannot make a pull request which is reserved for collaborators.

Making a pull request is not reserved for collaborators at all. **Merging** them is. That's the whole point of pull requests.

**Comment by Seldaek** [comment]
Yes please publish this as an individual package and add it to https://github.com/Seldaek/monolog/wiki/Third-Party-Packages - I don't want to maintain even more handlers which are provider specific.
