### ISSUE TITLE
Could a new release be considered to remove the 0.7MB logo from the package ?

### ISSUE THREAD

**Issue by tigitz** [Seldaek/monolog#1870]
Hello, packaging my [Castor](https://github.com/jolicode/castor) app as a Phar I've tried to reduce the size as much as I could but the main culprit remains the packaged logo in this lib.

Representing 11% of the total phar archive.

![image](https://github.com/Seldaek/monolog/assets/1524501/dc02be10-e9ec-447b-83d4-adfd5339f8f8)

[I've seen the commit fixing this issue ](https://github.com/Seldaek/monolog/commit/479c936d2c230d8c467bdb3882afab45a6e6b8ad) but it hasn't been released yet.

So before implementing a workaround on my side that would become obsolete in the next release, I was just wondering if a new release is / could be considered soon ?

Thanks

**Comment by Seldaek** [comment]
https://github.com/Seldaek/monolog/releases/tag/3.6.0 is now out sorry for the delay
