### ISSUE TITLE
Truncated JsonFormatter logs at 8191 characters

### ISSUE THREAD

**Issue by Mad4T** [Seldaek/monolog#1890]
**version**
Monolog version: 3.0
Laravel: 10.0

**Issue Description:**
We're encountering log truncation at 8191 characters within our Laravel application deployed on AWS ECS. CloudWatch logs from this specific app are affected, while logs from other apps function normally.
We suspect a potential limitation within Monolog (version 3.0) might be causing this behavior.

**Expected Behavior:**
We expect CloudWatch logs from our Laravel app to be captured in their entirety without truncation.

**Code Snippet (relevant part of logger.php):**
`'stderr' => [
            'driver' => 'monolog',
            'handler' => StreamHandler::class,
            'formatter' => env('LOG_STDERR_FORMATTER'),
            'with' => [
                'stream' => 'php://stderr',
            ],
 ]`

**Comment by Seldaek** [comment]
AFAIK there is no such limit in Monolog itself, but I am not very familiar with ECS and there might be something else there.

**Comment by Seldaek** [comment]
Yeah sorry but that's something you'll have to debug yourself I am afraid.. There is too much environment specific stuff at play here for me to help much.

**Comment by Seldaek** [comment]
If you figure it out please share here, it may help someone else one day

**Comment by sc0rp10** [comment]
@Mad4T please take a look to [log_limit](https://www.php.net/manual/en/install.fpm.configuration.php#log-limit) setting of php-fpm: it was the key to solving a similar problem in my case (I'm writing this mostly for folks from google).

**Comment by Seldaek** [comment]
Feel free to send a PR if you have a good understanding of the problem because I have zero context here so it'll take me much more effort and probably not get done..
