### ISSUE TITLE
DeduplicationHandler in a read only container

### ISSUE THREAD

**Issue by ervinBLU** [Seldaek/monolog#1893]
Monolog version 3

Is there a way for DeduplicationHandler to save into database, redis for example, instead of file system? I'm using a read only container and it tries to write on file system, I can't find anything to configure it to use something else instead of file system, Thanks :)

**Comment by Seldaek** [comment]
Nope sorry this is really a hackish handler built to avoid spamming mailboxes when doing mail handler stuff.. But in general IMO it is best to log everything and handle filtering on the log viewer.

**Comment by Seldaek** [comment]
That said, the DeduplicationHandler accepts a file path, so using stream wrappers you might be able to build a redis backed store for it 🤷🏻 I don't know if it's worth the hassle though.

**Comment by ervinBLU** [comment]
Thank you for answering :)
