### ISSUE TITLE
Adding postParams in ERROR notice for HTTP 405 code

### ISSUE THREAD

**Issue by sdespont** [Seldaek/monolog#1898]
Monolog version 3

Hello, I use HtmlFormatter to receive logs by email. 

In the case of an ERROR notification for an HTTP 405 error code, there is no postParams data provided, but postParams are present in the next INFO notification if present for a deprecated notification.

How can I include postParams directly in the ERROR notification?

**Comment by Seldaek** [comment]
The best way to do email logging IMO is to combine it with a FingersCrossedHandler => BufferHandler => MailerHandler. That way you get the full request logs in the email, not just the ERROR.
