### ISSUE TITLE
`HandlerInterface::isHandling` could have better naming

### ISSUE THREAD

**Issue by ghost** [Seldaek/monolog#1900]
Hi, I have a little problem with HandlerInterface::isHandling method naming and I'm often mislead by it.

For me `isHandling` means (the first is my default, the second is alternative understanding)
1. this handler is handling a log record **at the moment**.
OR
2. this handler is handling a log record but not in a sense that in does it at the moment but in a sense that this log record belongs **only** to this handler. 

However what it really does is that this handler **supports** (i.e. will log) this log record. 
I know the doc block on the method gives some explaination but one can't remember all the doc blocks and it's the class API (e.g. method naming) what a developer works with daily so better method naming should be our priority.

I hope I've described my POV understandable.

I know the naming change would be a big BC break so I'm not forcing to change it right away. It's more like a question for maintainers whether they agree with my POV and maybe in some future major release this could be done.

**Comment by Seldaek** [comment]
Probably not going to change this no..
