### ISSUE TITLE
Parse error: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /usr/share/php/Symfony/Component/Console/Application.php on line 238

### ISSUE THREAD

**Issue by emergingcoders16** [Seldaek/monolog#1910]
I am using multiple versions of php and now I want to composer install in my project but I am getting this error. how to solve this?

**Comment by stof** [comment]
which version of composer and PHP are you using when getting this error ?

**Comment by stof** [comment]
Btw, the location of the error `/usr/share/php/Symfony/Component/Console/Application.php` does not appear to be part of a composer phar.

**Comment by emergingcoders16** [comment]
I ran command composer -V but it did not show the composer version and got the same error.

**Comment by stof** [comment]
how did you install composer ?

**Comment by Batraz2004** [comment]
did you manage to solve the problem? i have the same error when i switch from php 8.3.6 to 7

**Comment by Seldaek** [comment]
@Batraz2004 if you downgrade the php version you need to downgrade monolog as well to a version that supports your PHP version..
