### ISSUE TITLE
ErrorHandler::register not working as expected

### ISSUE THREAD

**Issue by kaihendry** [Seldaek/monolog#1915]
Monolog version 3.7

https://gist.github.com/kaihendry/6ad32ed135e3d679e6dd896365b252cb

The error handler is not working as expected, it shows:

      {"level":"info","ts":1726946030.4808884,"msg":"capture me monolog","syslog_level":"notice"}

**Comment by stof** [comment]
what do you mean by "it is not working as expected" ?

**Comment by kaihendry** [comment]
I expected monolog to hook into `error_log`

**Comment by stof** [comment]
PHP's `error_log` function does not report its messages to the PHP error handler system. It directly sends it to the PHP system logger, which is not hookable in userland.

**Comment by Seldaek** [comment]
Right the way to trigger it is to call trigger_error().. But really if you wanna trigger the logger, please call the logger :)
