### ISSUE TITLE
Override the source attribute in v3?

### ISSUE THREAD

**Issue by hcker2000** [Seldaek/monolog#1922]
Monolog v3

We used to be able to use a source processor to override the source and host options but can no longer do this. This was required as the default source and host options inside docker are useless for logging across multiple servers as they all have the same ip and host name.

Here is the old processor code:

```php
class SourceProcessor implements ProcessorInterface
{
    public function __invoke(array $record): array
    {
        $record['source'] = 'ops.' . $_ENV['ENVIRONMENT'];
        $record['host'] = 'ops.' . $_ENV['ENVIRONMENT'];

        return $record;
    }
}
```

**How can we do this same thing with v3?**

**Comment by stof** [comment]
which source and host options are you talking about ? there is no such options in Monolog.

**Comment by Seldaek** [comment]
You'd need to write those in context or ideally extra data from the Processor, then use a custom formatter that moves the extra data into top level keys (or even just use a formatter to set the keys and skip the processor entirely).

For v3 since records are objects you cannot write arbitrary data on them.

**Comment by hcker2000** [comment]
Thanks the custom formatter does the trick.

```php
<?php

namespace App\Monolog\Formatter;
 
use Monolog\Formatter\FormatterInterface;
use Monolog\LogRecord;
use stdClass;

class JsonFormatter implements FormatterInterface
{
    public function format(LogRecord $record)
    {
        $output = new stdClass;
        $output->source = 'subdomainhere.' . $_ENV['ENVIRONMENT'];
        $output->host = 'subdomainhere.' . $_ENV['ENVIRONMENT'];
        $output->context = $record['context'];
        $output->message = $record['message'];
        $output->timestamp = date(DATE_ISO8601);

        return json_encode($output).PHP_EOL;
    }
 
    public function formatBatch(array $records)
    {
        foreach ($records as $key => $record) {
            $records[$key] = $this->format($record);
        }
 
        return $records;
    }
}```
