### ISSUE TITLE
Rename `Monolog\DateTimeImmutable` to something else, e.g. `JsonSerializableDateTimeImmutable` 

### ISSUE THREAD

**Issue by ruudk** [Seldaek/monolog#1926]
First of all, thanks for this amazing package 💙 

So this is something that I'm bothered by for a long time. Every time I want to import `DateTimeImmutable`, PHPStorm asks me which one I want to import:

![Screenshot 2024-11-21 at 12 14 13@2x](https://github.com/user-attachments/assets/1db5f8ae-25e0-4b9e-9319-448c0b09d7d4)

Even though the version of Monolog is namespaced, it's still annoying to think which one to pick.

I want to propose the following:

* Rename `Monolog\DateTimeImmutable` to something different, for example: `Monolog\JsonSerializableDateTimeImmutable`
* Keep the old `Monolog\DateTimeImmutable` as an alias for `Monolog\JsonSerializableDateTimeImmutable`, and mark it as deprecated.
* In the next major, remove `Monolog\DateTimeImmutable`

Or if there is a better way to do this, I'm all ears. I would be happy to create the PR.

/cc @Seldaek

**Comment by Seldaek** [comment]
Yeah i wonder if marking it internal would help? Can you try that locally maybe? There's a minor use case of passing it directly to addRecord but i dont think many people do that..

Renaming would be cleaner but a longer term solution. 

Not sure what else is possible.

**Comment by Seldaek** [comment]
And did you try if an alias helps? Because I'm guessing it would also still suggest the alias, if so that'd only be fixed in 4.0

**Comment by ruudk** [comment]
The alias won't hide it :( 

So it will be a long time before I can enjoy it, but I still think it's good to prepare this for 4.0, so I created the PR:
- https://github.com/Seldaek/monolog/pull/1928
