### ISSUE TITLE
Add an AnsiHandler

### ISSUE THREAD

**Issue by evert** [Seldaek/monolog#212]
I would like to contribute a log handler for output to a terminal (stdout/stderr), and specifically: colorize the output a bit to make every developer's day slightly more cheerful.

I wanted to check first if this is a feature you'd accept in monolog, if I were to create it, and if so, if you have any special requirements.

**Comment by Seldaek** [comment]
@bramus looks good except one minor thing I would remove the blink from EMERGENCY because while it highlights it well, it makes reading the message quite hard :) Maybe the %level% could be blinking in the EMERGENCY case but I wouldn't blink the whole line.

**Comment by Seldaek** [comment]
OK I added it to https://github.com/Seldaek/monolog/wiki/Third-Party-Packages - I am closing this.
