### ISSUE TITLE
No easy/No obvious way to get detailed logging information via Email

### ISSUE THREAD

**Issue by tback** [Seldaek/monolog#237]
The most common use-case for MailHandlers (NativeMailerHandler and SwiftMailerHandler.php) is to send detailed information about errors/exceptions to developers.
Developers need context to solve errors, so they ask for a stacktrace and a useragent and maybe more.
The documentation doesn't offer an easy way to configure or implement this behaviour.

I understand that this can be achieved by providing a custom formatter, but I think this should be as easy as it can be.

**Comment by tzookb** [comment]
I am in a need of implementing a new feature, what exactly would like to be created here? 
just user agent? I could simply attach "HTTP_USER_AGENT" to the web processor.

Stack trace? it could be added with a new processor... is that what you mean?

**Comment by Seldaek** [comment]
Well I think this has been somewhat solved by the HtmlFormatter that you can combine with email handler now to get nicely formatted and clear emails.

Regarding configuration, https://github.com/theorchard/monolog-cascade now lets you do this a bit nicer than just raw monolog usage.

**Comment by tzookb** [comment]
mmm so it can be closed...

any features needed to implement? not something to big or tiny...?

**Comment by Seldaek** [comment]
I guess it can be closed yes. Not many things to do ATM I think, apart from monolog 2.0 but I need some time to review open PRs before piling more up makes any sense.
