### ISSUE TITLE
Some more guidance on using the logging context properly would be helpful

### ISSUE THREAD

**Issue by mpdude** [Seldaek/monolog#249]
The logging context is briefly mentioned in the [usage.md](https://github.com/Seldaek/monolog/blob/master/doc/usage.md#using-the-logging-context), but I would like to get some additional guidance on how to best leverage it. 

So which is the best way to send log messages?
1. `$logger->info(sprintf("Will have %s for %s", $food, $meal))`
2. `$logger->info(sprintf("Will have %s for %s", $food, $meal), array('food' => $food, 'meal' => $meal))`
3. `$logger->info("Food chosen", array('food' => $food, 'meal' => $meal))`

That is, should I try to keep log messages as "fixed" as possible and add all varying info into the context? Or should the message itself be as clear as possible?

When it comes to 1.) or 2.) above, wouldn't it be handy for the Formatter to expand %var% from the context as well?

Thanks!

**Comment by charlydagos** [comment]
To add to this, I normally will write "static" lines as the first argument, and variable data as the second one. This makes it easier to grep if you're logging to files.

Example

     $this->logger->info("Generated url for user", array('url' => $url->toString(), 'user_id' => $user->getID()));

I thought that was the intended use to begin with :smile:

**Comment by Seldaek** [comment]
@charlydagos it is definitely the initial intended use, but there are other options too like described above.

**Comment by adjenks** [comment]
@carlosdagos That's how I use it. Then I stuff the array into my db as a json. I can parse the json if I have some consistently used fields.

**Comment by juan-morales** [comment]
@mpdude - OK old issue, but .... **"It depends"** is the right answer.

Because the logging context is the data-entry point for processors, etc.

Is not about how you build up the log message .... **only**.

So ... if you have a processor (for example) that is suppose to expect certain value in the context to do its job ... well ... put it there :slightly_smiling_face:

I think this issue can be close.

**Comment by mpdude** [comment]
Over the past years, I mostly followed the approach outlined in https://github.com/Seldaek/monolog/issues/249#issuecomment-26150242. That leaves it up to the configuration of your handler stack and/or processors and is also easy to write in code.

**Comment by vukanac** [comment]
Hey guys, @mpdude, can you share your experience with logging events to eg. New Relic?

Logging events is expected to have event name and params.
```
$logger->info('Log and send event', ['food' => $food, 'meal' => $meal, 'type' => 'event']);
```
I am considering to have one log line in the code like you described above, but to use two handlers.

One for normal logging eg. stdout and the other for sending to some external services or agents like New Relic.
```
$log->pushHandler(new StreamHandler('php://stdout', Logger::INFO));
// custom handler to cover use of newrelic_record_custom_event($name, $attributes)
$log->pushHandler(new CustomNewRelicHandler(Logger::INFO, $triggerByContext['type' => 'event']));
```
Somehow it looks cumbersome to add `'type'=>'event'` every time.
The other option more verbose is to introduce and inject additional logger for events only.

What are your thoughts?
