### ISSUE TITLE
Update the GELF handler/formatter

### ISSUE THREAD

**Issue by bzikarsky** [Seldaek/monolog#285]
Last summer I wrote a php-gelf library with multiple goals:
- Possibility to use as standalone PSR-3 logger
- Higher flexibility for transports besides UDP
- Test-coverage
- PSR[0-3] compatibility

The result can be found at https://github.com/bzikarsky/gelf-php and is based upon f @lennartkoopmann's original Graylog2/gelf-php. 

I'd be happy to also provide an updated GelfHandler/GelfFormatter for monolog if there is interest/use for it. It would be a one-time dependency break since IMessagePublisher and Message don't exist in the updated version.

**Comment by tomzx** [comment]
Isn't this done already? Can this issue be closed?

**Comment by Seldaek** [comment]
Yup I missed this, thanks
