### ISSUE TITLE
AmqpHandler should not enforce exchange name

### ISSUE THREAD

**Issue by jcart** [Seldaek/monolog#355]
When creating an AmqpHandler, it's enforced in constructor to provide an exchange_name as part of configuration.

This is something that should be done outside of the scope of AmqpHandler and done as part of AmqpExchange DI configuration (via setter injection).

Enforcing this as part of AmqpHandler forces an already configured AmqpExchange to duplicate configuration which is error prone.

**Comment by Seldaek** [comment]
After digging into this a bit, it seems only PhpAmqpLib was actually needing/using that $exchange argument, but it seems optional at the PhpAmqpLib level. So I made it default to null and it's also not used at all anymore for the amqp extension users. 

I hope this approach makes sense. Ping @postalservice14 and @nubeiro in case you have an opinion here that'd be great.
