### ISSUE TITLE
elastica 1.*

### ISSUE THREAD

**Issue by leahaense** [Seldaek/monolog#364]
is there a plan to upgrade to elastica 1.*?

**Comment by mablae** [comment]
I am using ElasticsearchHandler with ES 1.7, working good

**Comment by acostasg** [comment]
They can be formed:

```
'number_of_shards' => 4, 
'number_of_replicas' => 1, 
```

from ElasticSearchHandler instance?

**Comment by mablae** [comment]
@acostasg The elasticsearch handler makes no assumptions about the index mapping and settings. 
It just does bulk indexing, nothing more. 

I just use an elasticsearch index template that matches the indexes written by the monolog handler. In that template I defined the whole mapping and analysis and it is possible to override set the settings of shards and replicas, too: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html
