### ISSUE TITLE
stream handler does not reopen file if pipe gets closed

### ISSUE THREAD

**Issue by gggeek** [Seldaek/monolog#368]
I might be missing something, but it seems that the stream handler is optimistic about the pipe never getting closed while it is in action.
This is fine as long as the logger is used by web pages, but not so if it is used by long running processes.
Example scenario: php daemon starts, logrotate kicks in at midnight and removes the open file under its nose. The php daemon should be able to keep on logging without the need for a restart

**Comment by kamilsk** [comment]
Any solution available here? Workaround for me https://github.com/kamilsk/common/blob/master/src/Monolog/Handler/BulletproofStreamHandler.php (https://github.com/kamilsk/common/blob/master/src/Tests/Monolog/Handler/BulletproofStreamHandlerTest.php#L33-L44), but I don't really like it.

> Maybe your daemon could call $handler->close() after every thing is processed to make sure it gets reopened?

Log rotating is not such a frequent event, so it is better to check for the file to perform the additional work.

**Comment by Seldaek** [comment]
@kamilsk actually to properly test this at https://github.com/kamilsk/common/blob/master/src/Tests/Monolog/Handler/BulletproofStreamHandlerTest.php#L39 you should do `exec('rm '.shellescapearg($this->getStream()));`. If you do it with an unlink() call it will remove the file from the php stat cache, but if it's done by an external process the php stat cache won't know of the file's disappearance and file_exists() will still return true.

**Comment by kamilsk** [comment]
@Seldaek, thanks! [Fixed](https://github.com/kamilsk/common/blob/master/src/Tests/Monolog/Handler/BulletproofStreamHandlerTest.php#L52-L63).
Incompatibility, which now comes to mind is [write to moved file](https://github.com/kamilsk/common/blob/master/src/Tests/Monolog/Handler/BulletproofStreamHandlerTest.php#L33-L47), but in my case it is not critical.

**Comment by Seldaek** [comment]
Yes but that means your fix doesn't really fix the problem does it? I still think the best way is to close the handler periodically if you have long running processes and need this level of safety.

**Comment by kamilsk** [comment]
> Yes but that means your fix doesn't really fix the problem does it?

Yes, the solution is not complete.

@gggeek, if you use `delaycompress`, all works fine.

> __delaycompress__
> It  can be used when some program can not be told to close its logfile and thus might continue writing to the  previous log file for some time.

`logrotate` uses `mv` in rotation. [The test](https://github.com/kamilsk/common/blob/master/src/Tests/Monolog/Handler/BulletproofStreamHandlerTest.php#L33-L47) shows that in this scenario, nothing is lost.

**Comment by Seldaek** [comment]
Closing as I don't see a possible fix.

**Comment by Kirzilla** [comment]
In case when log files are deleted by `logrotator` then it is possible to use `copytruncate` option. When this option is declared, logrotator copies log file and truncates original file, so all pipes are still valid and logging works as expected.

**Comment by freecorvette** [comment]
After experimenting with several implementations, I managed to overcome this problem by adding, in the long running script, from time to time, the following line:

`$logger->close();`

This closes the file handlers and, with the next write call, the file handlers are automatically recreated. If you add the `delaycompress` rotating option, as suggested by other commenters, you can achieve the desired result: not missing any log line, while allowing old logs to get rotated.

When the log rotator runs with the `delaycompress` option, it will rename the current log file and leave it untouched until the next rotation cycle. Your script will continue to log to this renamed file, until you issue the next `$logger->close();` command. After that, it will create (if needed) and log to the original file name again. When the log rotator runs its next cycle, it will rotate the old, renamed file. Rotation cycles are usually daily or less frequently, so ensuring that you run `$logger->close();` every few hours in your script should be good enough and also add minimal overhead.

**Comment by STotev** [comment]
Thanks @Kirzilla. Totally missed the fact that I could adjust logrotate instead of my app.

One other potential solution could be by using `postrotate/endscript` to kill the long running process. In my case I have systemd units under a target and I guess, on postrotate, I could execute something like `systemctl restart all-my-units.target`. 

I haven't tried it but I don't see a reason why it wouldn't work.
