### ISSUE TITLE
Add php-console handler

### ISSUE THREAD

**Issue by barbushin** [Seldaek/monolog#416]
Hi

There is a Google Chrome extension - PHP Console https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef with ~60k active, server side library https://github.com/barbushin/php-console, and having integration modules with Symfony, Yii, Silex, Laravel and Drupal frameworks.

Is it possible to develop monolog handler for php-console? I can do my best to help you with it.

Thank you!

**Comment by barbushin** [comment]
@Seldaek Hi, Jordi. I submitted pull request https://github.com/Seldaek/monolog/pull/533 with `PHPConsoleHandler` and `PHPConsoleHandlerTest`. I'm very worried that after 3 weeks there is no reaction from you.

I now you're very busy, but please just tell me if it's everything okay with https://github.com/Seldaek/monolog/pull/533 or there is something I can improve? 

Thank you

**Comment by stof** [comment]
this should be closed as #533 got merged.
