### ISSUE TITLE
Add a CallbackFilterHandler

### ISSUE THREAD

**Issue by Seldaek** [Seldaek/monolog#423]
see https://github.com/llaville/phpunit-LoggerTestListener/blob/master/extra/AdvancedFilterHandler.php and #411 

Needs to be evaluated.

**Comment by llaville** [comment]
I've closed the PR, because I've put a improved version in my own repo.
See https://github.com/llaville/monolog-callbackfilterhandler

I plan to release it soon a 1.0.0 version in my own vendor namespace `bartlett` on Packagist https://packagist.org/packages/bartlett/

**Comment by Seldaek** [comment]
Ok great. You're welcome to add it to https://github.com/Seldaek/monolog/wiki/Third-Party-Packages as well.

**Comment by llaville** [comment]
Added to the Wiki !
