### ISSUE TITLE
Fix the "datetime" field/add "timestamp" field

### ISSUE THREAD

**Issue by giannello** [Seldaek/monolog#438]
As per current implementation, monolog is not able to provide high-resolution timestamps for logs, because of the use of the DateTime object. Also - despite what the v1.3.0 changelog states (Support for millisecond in timestamps) - the feature is actually not more than a mock and the test case itself is not optimal, as it tests an edge case.
Right now, the only way to make sure logs coming out from monolog are accurate is to rely on the output sequence of the messages. While this case is acceptable when using file/stdout output, it's not valid anymore when outputting to an AMQP broker for later consumption.
In this case, as AMQP does not guarantee an ordered delivery, any indexer (InfluxDB, in our current implementation) will need a higher-resolution timestamp to make sure the log messages can be indexed/viewed in the correct order.
As log messages are not more than description of events in time, the best solution would be to just store the unix timestamp with microseconds, and let the presentation layer convert them to the appropriate date/time format the user needs.

**Comment by Seldaek** [comment]
As far as I can tell this was fixed by https://github.com/Seldaek/monolog/pull/793 - in 2.0 if you enable microsecond precision then json-serialized datetime objects will have full precision.
