### ISSUE TITLE
Proposal for inclusion of Handler/Formatter for logging to Gitter chat rooms.

### ISSUE THREAD

**Issue by nackjicholson** [Seldaek/monolog#442]
Don't know if you're familiar with [gitter.im](https://gitter.im) but it is a chat/irc app which is very integrated with github organizations, users and repos. I don't know, maybe there is a #monolog/monolog chat room on gitter, I'll check.

I've written a handler/formatter combination which sends logs via the Gitter REST api to a targeted chat room. I've made it into a composer package, although right now it's only available via "dev-master", I just haven't tagged it yet. 
###### https://github.com/nackjicholson/monolog-gitter-im

There is a picture in the readme of what the logs end up looking like. Gitter makes it possible to use github emoji, so I formatted log lines with a little emoji iconography. `EMERGENCY` gets :boom: for instance.

Just let me know if you'd like this as a contribution, and I will begin the pull request process.

If not, I'll keep it available as a composer package, and I'll stamp a version on it.

Thanks for a great library! Cheers! (thanks for composer too :smiley:)

**Comment by Seldaek** [comment]
Added https://github.com/Seldaek/monolog/blob/master/README.mdown#third-party-packages and a wiki page
