### ISSUE TITLE
Prohibit sending passwords to logs

### ISSUE THREAD

**Issue by lewyx** [Seldaek/monolog#457]
**Abstract**: I have tried to locate a feature that could be used to erase passwords from log messages. They can get there by accident, or because the modular structure of a system. Because in some setups these logs are used to alert personnel in the first tiers it could breach security to leak them passwords.
**Proposal**: If the feature does not exist then I propose a formatter-wrapper which replaces known passwords (which should look garbage) in every string of the record structure. The search could employ simple text matching or simple text matching for opening+closing sequence or a regEx pattern (for those who feel the need to suffer).
**Effects**: Of course this would only be useful if the passwords employed in an application do not collide with text or normally logged data. In case of system passwords this can easily be achieved by setting up passwords including a variety of special characters. In case of user-picked passwords it is a good practice to salt the value as soon as possible; if this salt happens to be non-colliding prefix/suffix then they can also be easily filtered for.

If you welcome the idea or have a better suggestion, I'd love to hear it. I'd also happily contribute with the above solution.

**Comment by cordoval** [comment]
The problem for hipaa compliant applications is that it is not only passwords but any identifiable information, so for instance if you ran into a disconnection from your db and there is an exception and monolog logs the trace or such then in there it could appear a name or a diagnostic, this in itself would already be a leak. I am also thinking in writing a custom processor but it won't be as easy as a regexp. Some more information must be passed to make the scrambler processor effective.
