### ISSUE TITLE
Streaming handler + json

### ISSUE THREAD

**Issue by mbrevda** [Seldaek/monolog#479]
When using the streaming handler with the json format, it seems that is necessary to close the stream to flush the buffer or something. Otherwise, json message come in in large groups and cause a parsing error when trying to parse them.

Perhaps this is an error with my setup or is it something else?

**Comment by mbrevda** [comment]
Im going to reopen this. Even if I close the stream at my end, it seems the SocketHandler will hang on `!feof()` because of how the stream was closed. I would propose having the SocketHandler close the socket after every write to ensure the each json object is received individually. Thoughts?

**Comment by staabm** [comment]
> I would propose having the SocketHandler close the socket after every write to ensure the each json object is received individually

closing and re-opening the socket on each write sounds like a bad idea performance wise.

**Comment by mbrevda** [comment]
It is, but its better than waiting 30 seconds for php to time out every time! I'm not proposing making it the default, just an options. For my dev environment, the performance penalty is really, really small.

I'm also open to other ideas on how to get the json objects send as individual messages to a remote server? The only way I can get it working is by closing the connection after every write...

**Comment by Seldaek** [comment]
@mbrevda maybe you could try to call SocketHandler::setTimeout(0.1) or something that fits your network model so that writes go through and do not block for 30seconds?

**Comment by mbrevda** [comment]
Great @Seldaek, I missed that. Thanks!

**Comment by Seldaek** [comment]
I think the remote is kinda borked if it can't read line by line.. so adding an option like that sounds a bit nasty, especially as it's so inefficient to close and reopen on every write. Would you mind sharing the code you have on the receiving end?

**Comment by mbrevda** [comment]
[This](https://github.com/mbrevda/monolog-log-streamer/blob/master/src/Server.php#L30-L43) is the gist of it. I agree closing the connection isn't very performant, but I don't see another way.

**Comment by Seldaek** [comment]
Closing as not sure what to do about this, sorry.
