### ISSUE TITLE
Processors should implement a ProcessorInterface

### ISSUE THREAD

**Issue by ahmadnazir** [Seldaek/monolog#486]
Hi,

I was wondering what is that reason to rely on the magic __invoke method inside the processors. I would expect that the processors should implement a ProcessorInterface with at least the following methods:

```
public function process(array $record);
public function setData(array $data); // Data that will be added to the record
public function setKey($key); // If we want to add data to key other than 'extra'
```

What are your thoughts? If it makes sense, I am interested in working on it and sending a pull request.

**Comment by zored** [comment]
@Seldaek however sometimes interfaces can be useful in OOP-based projects.

For example, in Symfony [it's required](https://symfony.com/doc/current/logging.html#using-a-logger-inside-a-service) to put `monolog.processor` tag on processor services. But if there was `ProcessorInterface`, I could [map it](https://symfony.com/doc/current/service_container/tags.html#autoconfiguring-tags) on tag and avoid explicit tags.
