### ISSUE TITLE
HtmlFormatter dies not include document type and <html> tag

### ISSUE THREAD

**Issue by danijoo** [Seldaek/monolog#488]
At the moment, the html formatter returns the plain html table starting with the  ```<table>``` tag. This is fine for most email programms.

Unfortunatly there are also some programs that wont render this correctly. Android's gmail app, for example, will show an empty mail with a file attachment named something like "-38". Its not possible to display that file as html at all on a phone. 

To change that, proper html declaration must be given I think. The table should be wrapped with something like this:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">     
<html xmlns="http://www.w3.org/1999/xhtml">    
    <head>     
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />     
        <title>some text</title>     
    </head>     
    <body>     
        PUT CONTENT HERE     
    </body>     
</html>```

**Comment by Seldaek** [comment]
Unfortunately the problem is records are formatted individually, so this would have to be done at a higher level in the handler itself before sending the email.
