### ISSUE TITLE
Hipchat has more detailed logs then Slack?

### ISSUE THREAD

**Issue by peric** [Seldaek/monolog#493]
Is it possible to have more detailed logs on Slack?

On Hipchat, I get where request was sent and then completely detailed critical error/exception. 
On Slack, I get just where exception has happened, without any details about request.

**Comment by Seldaek** [comment]
I guess this is due to the fact Slack doesn't include context info and includes extra only optionally. You could try to enable the $includeExtra param in the constructor, and then possibly we should fix the handler to include context also when includeExtra is on.

**Comment by peric** [comment]
Thanks for the answer. Hopefully I will have time to check it and maybe even contribute.

**Comment by Seldaek** [comment]
I think this has been resolved by #507
