### ISSUE TITLE
Use a more parsable output in LineFormatter

### ISSUE THREAD

**Issue by marcioAlmada** [Seldaek/monolog#494]
Sometimes, depending on what's being logged, it's difficult (perhaps impossible) to parse log lines written by `LineFormatter` because there is no delimiting between `message`, `context` and `extra` nodes:

```
"[%datetime%] %channel%.%level_name%: %message% %context% %extra%\n"
                                               ↑         ↑
```

My suggestion is to use some delimiter between the cited log entry nodes so logs written with default `LineFormatter` configuration would become more parsable.

**Comment by marcioAlmada** [comment]
**If** it's viable to change default `LineFormatter` format on next major version of Monolog, my first suggestion would be to use an unicode information separator character: [`\u1F`].(http://www.fileformat.info/info/unicode/char/1f/index.htm)

**Comment by Seldaek** [comment]
I would only change the default in 2.0, but yes it's a good idea, and you can already use it by configuring the formatter of course.

But by the way if you want parseability using JsonFormatter or the like is usually a better option.

**Comment by marcioAlmada** [comment]
> But by the way if you want parseability using JsonFormatter or the like is usually a better option.

Sure, 100% agreed with that. It's just that it wouldn't hurt to make the log lines feasible to automated  analysis in case it's really needed.

Is v2.0 code base already on a branch? I could send a pull request if you wish.

**Comment by Seldaek** [comment]
Nope I have not yet started work on 2.0, just collecting ideas.

**Comment by Seldaek** [comment]
@marcioAlmada thinking about this again now that master is targetting 2.0, I'm not sure what to use.. `\u{001F}` can potentially trip up a bunch of things to think it's binary. It sure does the job for PHPUnit, and I can imagine other text utils would also freak out. Not sure if we should care about that or not.

**Comment by marcioAlmada** [comment]
> I'm not sure what to use.. \u{001F} can potentially trip up a bunch of things to think it's binary

Closing this. That seems to have a high potential to be disappointing for the majority of the user base while being useful only on very exceptional cases.

Cheers!
