### ISSUE TITLE
Logging should be idempotent and not affect application state

### ISSUE THREAD

**Issue by paracycle** [Seldaek/monolog#500]
I have just ran into a problem with Monolog and file permissions. While I realize that I do need to solve the file permission problem on its own; the behaviour of Monolog in this situation really surprised me.

I would expect a logging library to work in an idempotent manner and not affect the state of the application as a whole. However, Monolog (`StreamHandler` more specifically) intentionally chooses to throw an `UnexpectedValueException` if the output stream can't be opened. This, I find, is not acceptable in a logging framework. If the stream is not writable then all I'd be willing to lose is a few logs, not my whole application state.

Such behaviour _could_ make sense in a debug setting where one would like to be alerted of such problems and raising an exception could be made into a global or per handler flags that could be turned **on** (ie OFF by default).

If the author(s) of this library agree with me, I'd be willing to send a PR to this effect.

**Comment by Seldaek** [comment]
I don't really agree we should silently suppress such errors. It's a clear misconfiguration and if we don't let you know the day you will need your logs they won't be there.

If you really want to you can easily create a `Monolog\Logger` wrapper that implements the `Psr\Log\LoggerInterface` and wraps the monolog call in a try/catch to suppress all errors or convert them to softer errors/php error_log.

**Comment by paracycle** [comment]
It actually makes me sad to see this reply. I *do* understand that not being able to log is a problem and might lead to lost logs down the line. However, do you really believe that the right way to notify the application is to actually crash it by throwing an error. That might lead to lost application data which IMHO is much much more important than any logs.

I realize that I can wrap logging and others have done so, eg #426, but if throwing an exception was an option that people could turn on if they need/want it, wouldn't it make Monolog a better library? After all, throwing/catching exceptions is more wasteful than not throwing them in the first place.

I realize that at the end of the day, this is your codebase and the choice is yours but I really would like you to reconsider this point. Thank you.

**Comment by fprochazka** [comment]
I would be really pissed if I found out after weeks my application hasn't been logging. So :+1: to @Seldaek

**Comment by chriseskow** [comment]
:-1: for this request. In some situations, logging may be a critical requirement of the application (e.g. for auditing), and even if it isn't, failing silently by default will cause confusion by hiding real problems.

That said, perhaps the exceptions should be better documented (e.g. in docblocks) and/or converted to custom exception classes.

**Comment by Seldaek** [comment]
I am sorry I replied a bit hastly and forgot to mention that you don't even have to implement your own wrapper, you can use a [WhatFailureGroupHandler](https://github.com/Seldaek/monolog#wrappers--special-handlers) to suppress errors of any potentially failing handler. I see you have found that though.

It boils down to a question of philosophy at this point I am afraid. You think it should be resilient by default and then have optional exceptions. I think it should not allow misconfigurations for such a critical thing as logging, unless you know what you are doing and wrap the handlers to avoid intermittent failures.

One thing that could be improved though in the case you refer to is to do a is_writable check in the constructor of the StreamHandler, and throw there if it's not. That way we ensure the error crops up while monolog is bootstrapped and not later on when you are in the process of logging something. This should make it a lot harder to end up in a state where it actually fails only in certain cases (when you log) leading to data loss. What do you think about that?

**Comment by paracycle** [comment]
@Seldaek Thank you for the time you are spending on this. Your proposed solution sounds very good and would definitely solve my original problem. I actually like the idea of failing fast and the proposed exception at initialization would provide even faster failure. In my opinion, an application that fails to start due to a misconfiguration is much better than an application that thinks everything is hunky dory until it later finds out it has to stop because it can't log.

For people who have more critical logging requirements, we could still have an optional flag to raise errors at logging time as well, if that's something that is highly desirable.

In the very least, @chriseskow has a very good point about better documentation on the fact that, by default, Monolog handlers _might_ be throwing exceptions if misconfigured.

**Comment by nirradian** [comment]
I have to agree with @paracycle - I'd much rather find out that I'm not logging anything for three days than to find out I'm not servicing my clients for 10 minutes. 

I'm trying to imagine in what situation anyone would feel the opposite. 

Also - we have devops who would feel immediately if logs aren't being written (we've also collected warnings and info from monolog to new-relic), even on holidays.

**Comment by Wirone** [comment]
Thanks @Seldaek, `WhatFailureGroupHandler` solved my problem with `GelfHandler` which is not critical for us and should not stop application on failure.

**Comment by Seldaek** [comment]
#1012 introduces a way to set a custom exception handler so that lets you deal with exceptions in a centralized manner and do what you want with them. Just in case someone's still looking for a solution here.
