### ISSUE TITLE
Add PHPMailerHandler (?)

### ISSUE THREAD

**Issue by SpazzMarticus** [Seldaek/monolog#502]
I am currently working on an `PHPMailerHandler` and since this is close to the `SwiftMailerHandler`  I wanted to know, if it should implement the feature @iltar suggested in his pull-request #497 or if I should better head in the direction @johnkary has implemented on his fork (branch: LazySwiftMailerHandler) ?

**Comment by fprochazka** [comment]
@SpazzMarticus I was under the impression, that new handlers should be implemented as standalone packages, that can be included into the app using composer :)

**Comment by SpazzMarticus** [comment]
Either way, which implementation would be more satisfying?
Callback on `send`, callback on `__construct`, or an option to choose which callback is used?

**Comment by iltar** [comment]
@SpazzMarticus I think that if you want to return "message" objects, you're better off using a proper factory pattern. The swift handler has a similar way by using the `call_user_func`, but is hard to implement.

If my PR gets merged, I will make a follow up PR to add lazy loading to the swift handler, which would make @johnkary's PR no longer required. This will prevent duplication and confusion within the handlers.

**Comment by Seldaek** [comment]
As we already have Swift and native mail() support I would say yes please keep it as a separate package especially since it depends on another package.
