### ISSUE TITLE
Temporarily disable handler and removing handlers

### ISSUE THREAD

**Issue by agentile** [Seldaek/monolog#506]
I have a use case where particular error handlers should not trigger if they have already already seen the same error in the last X time frame. I have the rate limiting in code in place, but what would be useful is to be able to toggle the handling of a handler to allow for this use case. e.g.

```php
foreach ($logger->getHandlers() as $handler) {
    if (get_class($handler) == 'Monolog\Handler\HipChatHandler') {
        $handler->toggleHandling();
        // or
        $handler->disableHandling();
        $handler->enableHandling();
    }
}
```

Perhaps this could be easily achieved by temporarily setting $this->level to > 600

Another possible solution for this use case that doesn't seem easily achievable in the codebase is to remove a specific handler from the stack, there is pop and push but, if say I wanted to remove all hipchat handlers, doesn't seem like there is a good way to do this. Maybe I am just missing it completely.

I can create some pull requests for these, but wanted to get your thoughts if you've purposely left this functionality out. Thanks.

**Comment by Seldaek** [comment]
The cleanest way would be to use a wrapping handler like GroupHandler or FilterHandler but with a custom implementation that disables forwarding to wrapped handlers if the message was already seen.
