### ISSUE TITLE
Accessing the $loggers array in Monolog\Registry

### ISSUE THREAD

**Issue by rantonmattei** [Seldaek/monolog#508]
@Seldaek 

```php
class Registry
{
    /**
     * List of all loggers in the registry (ba named indexes)
     *
     * @var Logger[]
     */
    private static $loggers = array();

    //...
}
```
Code is at https://github.com/Seldaek/monolog/blob/master/src/Monolog/Registry.php#L45

My initial goal was to be able to know if a logger existed in the registry. Currently, we can only achieve that by wrapping the `getInstance()` method in a `try...catch` block and catch the `InvalidArgumentException` thrown by that method. Not very elegant.

So, my suggestion would be to either
 * add a `loggerExists($name)` method

  or
 * make the `$loggers` array protected.

My preference goes to the former. I'd be happy to make a PR for that if you'd like to include such change. 

Thanks.

**Comment by Seldaek** [comment]
I'd be ok with a PR but please call it `hasLogger()` I think it fits better with the other method names.

**Comment by rantonmattei** [comment]
@Seldaek 
Thanks. It looks like @theravel took a stab at it before I did. Just reviewed his code on his fork.
Feel free to add to my comments or wait for the actual PR.

**Comment by theravel** [comment]
I guess this can be resolved
