### ISSUE TITLE
Use Monolog with Slack

### ISSUE THREAD

**Issue by thangngoc89** [Seldaek/monolog#514]
I am using Laravel 5 and I have some issues with Slack Handler integration.
I set up a ChromePHP Handler and It works perfectly so I assume there is no problems with Laravel.

This is the way I set up Slack Handler

```php
$monolog = Log::getMonolog();

$monolog->pushHandler($chromeHandler = new \Monolog\Handler\ChromePHPHandler());
$chromeHandler->setFormatter(new \Monolog\Formatter\ChromePHPFormatter());

$slackHandler = new \Monolog\Handler\SlackHandler('my-api-token', 'general');
$monolog->pushHandler($slackHandler);
$slackHandler->setFormatter(new \Monolog\Formatter\LineFormatter());
```

I get my api token from https://api.slack.com/web#auth. 
Is there anything wrong with my config? 
At the same time, ChromePHP works and Slack doesn't work.
I really can't make Monolog work with Slack.

**Comment by Seldaek** [comment]
Seems correct, but note that by default it logs only CRITICAL messages and above, so maybe you want to call `->setLevel` on the handler as well to lower that to `\Monolog\Logger::ERROR` or something. That could explain why you don't get any messages on it.

**Comment by wodCZ** [comment]
channel name must include the hashtag, so in your case: 
`$slackHandler = new \Monolog\Handler\SlackHandler('my-api-token', '#general');`

**Comment by thangngoc89** [comment]
@wodCZ I tried that, and setLevel to 100 / debug .... I gave up

**Comment by wodCZ** [comment]
@thangngoc89 try putting `echo fread($this->resource, 1000);` in Monolog/Handler/SocketHandler at line 243 end of method `writeToSocket` - this way I got response from Slack - that was that about nonexisting channel.

**Comment by thangngoc89** [comment]
@wodCZ Thanks you. Let's me try it

**Comment by thangngoc89** [comment]
@wodCZ now it work. I have no idea why is it?

**Comment by wodCZ** [comment]
@thangngoc89  maybe some cache or whatever :)

**Comment by thangngoc89** [comment]
@wodCZ Yeah. Maybe. But anyway. Yeah

**Comment by mprandot** [comment]
where is 'api-key'? i can't find! :-1:

**Comment by fhusquinet** [comment]
@mprandot 
Info about authentication is here: https://api.slack.com/web
