### ISSUE TITLE
Formatting of infinity and NAN

### ISSUE THREAD

**Issue by EdeMeijer** [Seldaek/monolog#523]
When formatting a record that contains INF, -INF or NAN values, the containing data structure is not output. The reason is that `json_encode` can't encode those values, and that is being used in the LineFormatter.

```
$record = array(
    'message' => 'Watch it',
    'context' => [
        'a' => 10,
        'b' => INF,
        'c' => [
            'd' => NAN,
            'e' => null,
            'f' => -INF
        ]
    ],
    'level' => 100,
    'level_name' => 'DEBUG',
    'channel' => 'test',
    'datetime' => new DateTime(),
    'extra' => array(),
);

$formatter = new \Monolog\Formatter\LineFormatter();
echo $formatter->format($record);
```
Gives the output
```
[2015-03-04 11:08:07] test.DEBUG: Watch it []
```

This  can be fixed by taking these values into account while normalizing, for example in the `Monolog\Formatter\NormalizeFormatter`.

```
    protected function normalize($data)
    {
        if (null === $data || is_scalar($data)) {
//++++++
            if (is_float($data)) {
                if (is_infinite($data)) {
                    return '[' . ($data > 0 ? '' : '-') . 'INF]';
                }
                if (is_nan($data)) {
                    return '[NaN]';
                }
            }
//+++++++
            return $data;
        }

        if (is_array($data) || $data instanceof \Traversable) {
```

When this fix applied, the test code now outputs
```
[2015-03-04 11:10:44] test.DEBUG: Watch it {"a":10,"b":"[INF]","c":{"d":"[NaN]","e":null,"f":"[-INF]"}} []
```

Maybe still not perfect, but something like this would be nice to have. I spent quite some time debugging something involving INF, and I would have noticed the issue much quicker if I would've been able to see the logging context properly.

Thanks.

**Comment by Seldaek** [comment]
Thanks, I applied your patch minus the `[` and `]` wrapping

**Comment by EdeMeijer** [comment]
Awesome
