### ISSUE TITLE
Exceptions are converted to string before they can be normalized

### ISSUE THREAD

**Issue by InstanceOfMichael** [Seldaek/monolog#528]
I was wondering why Exceptions are always logged as ugly truncated string blobs, so I looked into it:

I checked here, then I found that they are already strings before they reach 
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php#L94
```
return $this->normalizeException($data);
```

So it looks like this code is converting it to string prematurely:
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php#L252

```
        $record = array(
            'message' => (string) $message,
            'context' => $context,
            'level' => $level,
            'level_name' => $levelName,
            'channel' => $this->name,
            'datetime' => \DateTime::createFromFormat('U.u', sprintf('%.6F', microtime(true)), static::$timezone)->setTimezone(static::$timezone),
            'extra' => array(),
        );
```

So now I'm at a total loss what I'm suppose to do...

**Comment by InstanceOfMichael** [comment]
OK, upon further work-arounding, I found this interesting niche.

While having only tested using the LogStashFormatter, I found that:

```
// This will silently fail to write any log
// and continue execution as if nothing happened
->addRecord('error',$exception->getMessage(),['exception'=>$exception]);
```
but:
```
// This will write the log as expected
// and $exception will be parsed through normalizeException
->addRecord('error',$exception->getMessage(),['anything'=>$exception]);
```

It appears that if I use the ``$context[$key]`` like ``$context['exception']``, it will discard the entire log entry without telling me.

**Comment by Seldaek** [comment]
This might be related to #545 if your exception contained invalid unicode strings. I can't really see what would make it handle the 'exception' key differently than 'anything' though in LogstashFormatter or NormalizerFormatter. Which handler are you using?

**Comment by InstanceOfMichael** [comment]
I hope this answers your question:

```
    $handler = new Monolog\Handler\StreamHandler($stream, $level);
```

**Comment by Seldaek** [comment]
Ok so stream handler.. nothing exception specific either here, I don't quite get why you had a difference between those two behaviors. If you can't build up a reproducible scenario it's gonna be hard for me to look into.

**Comment by jchamberlain** [comment]
Regarding the original post, is there a reason the exception is converted to a string prematurely? I'm dealing with the same problem right now. I'm seeing a couple confusing things.

First, `NormalizerFormatter::normalize()` has logic to normalize exceptions which is exactly what I want to run. Unfortunately, it's only called by `NormalizerFormatter::format()` which only accepts an `array`:

```php
public function format(array $record)
{
    return $this->normalize($record);
}
// ...

protected function normalize($data)
{
// ...
    if (is_object($data)) {
            if ($data instanceof Exception) {
                return $this->normalizeException($data);
            }
// ...
}
```

The whole `if(is_object())` block will never run because `format()` is always passing in an array. So I figured I'd just extend `NormalizerFormatter` to get around that. However...

Second, as mentioned by @InstanceOfMichael, the exception is explicitly cast to a string before it even gets to the formatter, so this is kind of a moot point.

What is the correct way to 1) pass the exception object all the way to the formatter, and 2) get `NormalizerFormatter::normalizeException()` to fire?

**Comment by jchamberlain** [comment]
To respond to my own post, I believe my problem is actually with Laravel. By default, Laravel passes the exception as the first argument to `Logger::error()`, so I assumed that method was designed to handle exceptions that way. It looks like it's not, but that exceptions should instead be passed in via `$context`. Am I correct?

**Comment by Seldaek** [comment]
The standard way to log exceptions as per PSR-3 is to use `['exception'=>$exceptionObject]` as `$context`. The message can be anything but ideally should be meaningful. If you do it like that they will be serialized as they should, and not just cast to string

**Comment by jchamberlain** [comment]
That makes so much sense. Thanks for pointing me to the PSR.
