### ISSUE TITLE
Monolog sends every message twice in my logs

### ISSUE THREAD

**Issue by ligne13** [Seldaek/monolog#530]
Hi,
I'm using Monolog for the first time.
My first issue : a simple push to a StreamHandler sends the message twice. As a result my log file displays 2 lines but I called it only once.
Same behavior if I use the SwiftMailer handler : mails are sent twice !

What am I doing wrong ?

the code :

`$log = new Logger( 'mytestlogger' );`
`$log->pushHandler( new StreamHandler( APPPATH . 'logs/your.log', Logger::DEBUG) );`
`$log->addInfo( 'Foo' );`

the log file :
`[2015-03-20 12:09:43] mytestlogger.INFO: Foo [] []`
`[2015-03-20 12:09:44] mytestlogger.INFO: Foo [] []`

**Comment by Bilge** [comment]
>What am I doing wrong ?
@ligne13 Posting a support request in GitHub issues appears to be your biggest mistake.

**Comment by mirahost** [comment]
This seems like a fair place to make a support request, unless you have a specific suggestion to an alternate venue?

Regarding the original question, I noticed this same behavior in our app and tracked the issue to Chrome making a second call to the page in search of a favicon.

**Comment by Seldaek** [comment]
You might have more luck on stackoverflow for support requests, but anyway I am fairly sure this isn't a monolog issue so I'll close this.

It sounds like somethiing is running the code twice, but with the info given it's kinda hard to tell.
