### ISSUE TITLE
Violation of psr-3 standards in relation to the '"log" method.

### ISSUE THREAD

**Issue by avplab** [Seldaek/monolog#543]
The "log" method does not support arbitrary level because of the public method "getLevelName" throws an exception.

**Comment by stof** [comment]
This is not a violation of PSR-3 at all. See https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#11-basics

**Comment by avplab** [comment]
I'm sorry, missed this.
Thanks
