### ISSUE TITLE
PHPConsoleHandler doesn't support log levels above 200

### ISSUE THREAD

**Issue by SourceCode** [Seldaek/monolog#549]
I'm currently working on some logging items and when trying to log a critical item the PHPConsoleHandler throws the following exception:

'Undefined index: code' in vendor\monolog\monolog\src\Monolog\Handler\PHPConsoleHandler.php:205

Upon inspection it seems that any code above 200 throws this exception with the latest build of monolog (dev branch).

The code I am using is:
```php
        $monolog = new Logger('sysLog');
        $monolog->pushHandler(new StreamHandler($filePath . DS . $logStorage . 'error' . '-' . FD . '.log', Logger::CRITICAL));
        $monolog->pushHandler(new StreamHandler($filePath . DS . $logStorage . 'sys' . '-' . FD . '.log', Logger::CRITICAL));
        if ($debugMode == true)
        {
            if ($debugLoggly == true) $monolog->pushHandler(new LogglyHandler($logglyToken . '/tag/appName', Logger::CRITICAL));
            $monolog->pushHandler(new FirePHPHandler());
            $monolog->pushHandler(new PHPConsoleHandler());    
        }
```
Things make it to loggly and the fire php but die at php console for everything above level 200

I also attempted the following manual configuration
```php
$monolog->pushHandler(new PHPConsoleHandler(array(), \PhpConsole\Connector::getInstance(),Logger::NOTICE)); 
```

Which still resulted in the same error.

**Comment by Seldaek** [comment]
Fixed in https://github.com/Seldaek/monolog/commit/5202b35099e880183e9bcbacdb01dc4346622800 as far as I can tell. Ping @barbushin maybe you want to double check.

**Comment by barbushin** [comment]
My fault, sorry. I thought `code` index is required for all errors records. @Seldaek fix looks 100% correct. Thank you.

**Comment by SourceCode** [comment]
Thank you both for your help - it's much appreciated!
