### ISSUE TITLE
Creating Handler with path to non-existing folder

### ISSUE THREAD

**Issue by alexeyegorov** [Seldaek/monolog#555]
While trying out Monolog, I've tried giving it a path to a folder (e.g. "/logs/logging") and has got following exception thrown:
```
 The stream or file ".../logs/logging-2015-04-29" could not be opened: failed to open stream: No such file or directory
```
I replaced the irrelevant part of the path with `...`.

Should I just create the folder path by myself? Or should I add such a pull request with creation of the folders on the given path?

Cheers,
Alexey

**Comment by Seldaek** [comment]
The log directory should exist yes, it will create files in there but that's it. As the stream handler supports streams which can be many things, I don't think we should take it as a responsibility to create folders as this might not play well with some of the streams.
