### ISSUE TITLE
Support for JsonSerializable

### ISSUE THREAD

**Issue by UlrichEckhardt** [Seldaek/monolog#560]
I'd like to see support for objects that implement the JsonSerializable interface. At the moment, I have code like this:
```
class Example implements \JsonSerializable
{
    public function jsonSerialize()
    {
        return array('data' => 'structure');
    }
}

$logger->info('mapped', array('bar' => new Example));
$logger->info('array', array(new Example));
```
The resulting output is this:
```
[2015-05-06 15:54:30] log.INFO: mapped {"bar":"[object] (Example: {\"data\":\"structure\"})"} []
[2015-05-06 15:54:32] log.INFO: array ["[object] (Example: {\"data\":\"structure\"})"] []
```
This isn't really readable due to the backslash-escaped double quotes. With a small change, you can get this output though:
```
[2015-05-06 15:56:05] log.INFO: mapped {"bar":{"data":"structure"}} []
[2015-05-06 15:56:05] log.INFO: array [{"data":"structure"}] []
```
All that you need to do is to check for the JsonSerializable interface in the normalize() function of class NormalizerFormatter (code based on 1.13.1):
```
    ....
    if (is_object($data)) {
        if ($data instanceof Exception) {
            return $this->normalizeException($data);
        }
        if ($data instanceof \JsonSerializable) {
            return $this->normalize($data->jsonSerialize());
        }
        return sprintf("[object] (%s: %s)", get_class($data), $this->toJson($data, true));
    }
    ...
```

I haven't tested this thoroughly, so please don't just apply that change. I just wanted to ask whether that was a worthwhile approach at all or for any other remarks.

**Comment by Seldaek** [comment]
Your workaround removes the details about which class the object was though so I am not so sure this is a plus. IMO if you want this stuff to be readable you anyway need to consume it in a better format than the LineFormatter.

**Comment by UlrichEckhardt** [comment]
That's a valid concern. How about splitting the info into two fields "type" and "data" then? For example like this:
```
    if ($data instanceof \JsonSerializable) {
        return $this->normalize(
            array(
                'type' => get_class($data),
                'data' => $data->jsonSerialize(),
            )
        );
    }
```
That would give output like
```
[2015-07-13 10:06:25] log.INFO: mapped {"bar":{"type":"Example", "data":{"data":"structure"}}} []
[2015-07-13 10:06:25] log.INFO: array [{"type":"Example", "data":{"data":"structure"}}] []
```
The main advantage is that the class controls what is logged and that it uses JSON all the way through. BTW: I'd like to have something similar for exceptions, too, where I sometimes have additional info that should be logged but which is neither inside the "regular" fields nor inside the message.

I'm not sure what you mean with the advise to "consume it in a better format". I personally don't have any problems with the JSON context data (though maybe it's just my bioware that is adjusted to this).

**Comment by Seldaek** [comment]
Reopening as it should be considered for 2.0
