### ISSUE TITLE
Can we please supply complete $record to Handler::isHandling?

### ISSUE THREAD

**Issue by rpkamp** [Seldaek/monolog#569]
Logger::addRecord() on line 241 now reads

```
if ($handler->isHandling(array('level' => $level))) {
// ....
}
```

while this used to be

```
if ($handler->isHandling($record)) {
// ....
}
```

In our current setup we check if a handler needs to be handling a message based on some value in `$record['context']` but obviously we can't check this anymore because of this change.

Could this change be reverted and pass the full `$record` again to `Handler::isHandling`?

**Comment by Seldaek** [comment]
The idea was to do a very slim check before calling anything, but you can just return true there based on level and then ignore records that you don't want in handle() it should be harmless. See https://github.com/Seldaek/monolog/blob/556c56483f687517c62cda1b74f792ecc1e7de9b/src/Monolog/Handler/HandlerInterface.php#L24-30 for details.

Actually this makes me think we should skip the isHandling() call entirely if there are no global processors present.

**Comment by Seldaek** [comment]
Moreover we added a Logger::isHandling($level) that couldn't do its job properly anymore if we sent a full record to HandlerInterface::isHandling so I'm afraid it was a one way trip :)
