### ISSUE TITLE
Logger - Array to String conversion error

### ISSUE THREAD

**Issue by Whyounes** [Seldaek/monolog#573]
When you try to log an array like:

```php
$logger->info(["item 1", "Item 2"]);
```
The Logger shouldn't be responsible for converting messages to string, I think this is the Formater job. We should be able to pass any type of object as long as the formater can handle it correctly.

```php
// \Monolog\Logger.php:252
'message' => (string) $message,
```
am I missing something?

**Comment by stof** [comment]
The first argument of ``->info`` **MUST** be a string. See the phpdoc of the method and the PSR-3 spec. Using the method with anything else is using it in a broken way.

**Comment by Whyounes** [comment]
I understand, Thanks
