### ISSUE TITLE
create logdir if not exists

### ISSUE THREAD

**Issue by dominikzogg** [Seldaek/monolog#581]
Hello @Seldaek

Would be cool if the StreamHandler or another handler would be able to create the log directory (if its a path, not a stream), if it not exists.

see: https://github.com/silexphp/Silex/pull/1183

If you like the idea i would prepare a pullrequest.

Regards @dominikzogg

**Comment by Seldaek** [comment]
See #555 - but if you can provide a safe implementation I am not really against it..

**Comment by dominikzogg** [comment]
@Seldaek well a resource definition is a string, which has :// within, or a resource itself, isn't it?

**Comment by Seldaek** [comment]
'foo.log' is valid, 'file://foo.log' is valid but has ://, ftp://foo.log is valid but should perhaps not get mkdir called on it (well I guess with ftp it works but not necessarily with other streams). I think doing a is_dir+mkdir check for file:// or no-protocol paths is probably safe.

**Comment by dominikzogg** [comment]
@Seldaek You mean only paths with file:// should get considered? Would be a compromise i could live with, should be in documentation as well. Should i prepare a pull request which works like this?

**Comment by Seldaek** [comment]
No I mean paths with file:// and those that don't have a protocol defined, like "foo.log" has no `XXX://` and as such you know php defaults to the file:// stream. And yes if you like to send a PR please go ahead :)
