### ISSUE TITLE
Error with composer due to 1.14.0 TAG

### ISSUE THREAD

**Issue by idciconsulting** [Seldaek/monolog#582]
Could not load package monolog/monolog in http://packagist.org: [UnexpectedValueException] Could not parse version constraint >=0.90 <3.0: Invalid version string "0.90 <3.0"

changes in composer.json l23:
```yml
...
"ruflin/elastica": ">=0.90 <3.0",
...
```
To
```yml
...
"ruflin/elastica": ">=0.90,<3.0",
...
```

**Comment by Gnucki** [comment]
composer self-update

**Comment by idciconsulting** [comment]
Thx !
