### ISSUE TITLE
Error during composer update

### ISSUE THREAD

**Issue by 4string** [Seldaek/monolog#587]
When I run composer update, I'm getting the following error:

 [RuntimeException]
 Could not load package monolog/monolog in http://packagist.org: [Unexpected
 ValueException] Could not parse version constraint >=0.90 <3.0: Invalid ver
 sion string "0.90 <3.0"

 [UnexpectedValueException]
 Could not parse version constraint >=0.90 <3.0: Invalid version string "0.9
 0 <3.0"

This seems to match line 23 of monolog/composer.json:
"ruflin/elastica": ">=0.90 <3.0",

**Comment by Seldaek** [comment]
Your composer is outdated, run `composer self-update`

**Comment by 4string** [comment]
Thanks. I'm an idiot. Sorry to waste your time.

**Comment by Seldaek** [comment]
It's alright, quite a few people have been caught off guard by this :)
