### ISSUE TITLE
Logstashformatter level_name used for level

### ISSUE THREAD

**Issue by Tschebel** [Seldaek/monolog#589]
In v1 the field level contains level_name instead of the numeric representation
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LogstashFormatter.php#L147

Is this a desired behavior or an oversight/bug?

**Comment by Seldaek** [comment]
The point is that those names are more readable and constant over time, while the numeric values might well change and don't convey so much information to someone that is not familiar with monolog.

**Comment by Tschebel** [comment]
Thanks for the explanation.
 i'll migrate my kibana filters to use the name.
