### ISSUE TITLE
ErrorHandler: non-zero exit code for exception handler

### ISSUE THREAD

**Issue by pavelsmolka** [Seldaek/monolog#592]
As far as I am aware, ErrorHandler is able to handle all errors, uncaught exceptions or fatals. When any of these happens, the problem is logged by the provided Logger object. 

The shutdown function (i.e. fatal handler) does not affect the exit code. Therefore, if for example a non-existing function is called, the problem is logged by `ErrorHandler::handleFatalError`, and the process ends with exit code 255.

However, if an exception is thrown and not handled on the application level, the `ErrorHandler::handleException` logs it and by default returns a zero exit code. I believe that's not the expected (intuitive) behavior. Without the error handler, an uncaught exception results in exit code 255, so that the environment knows the specific PHP process failed. 

In my view Monolog should be responsible for logging the issue, but not hiding the exit status. I realize it's possible to work-around this by setting a custom exception_handler calling `exit(255)` prior to registering the Monolog handler, which is called after the problem has been logged. Despite that, I believe Monolog should do that by default. What do you think?

**Comment by Seldaek** [comment]
Makes sense to me. I'll look into fixing that.

**Comment by jian-wu** [comment]
@pavelsmolka @Seldaek I disagree with the addition of the explicit call to the `exit` function.  Uncaught exceptions lead to poor UX so when I write any applications, I make sure to catch any possible exceptions and log them with stack trace.  This `handleException` does exactly that but with the call to `exit` function, it still breaks my application.  Why would you still break your application(s) when you are able to handle the exceptions/errors?
I'm using the `RavenHandler` to send stack trace to Sentry but with this explicit exit call, I'm forced to use the native `Raven_Client` and its own `handleException` function, which does NOT call `exit`.  I like monolog for its flexibility of having all sorts of logger support with it's counter productive/intuitive for me and others to have to write extra code to do what needed to be done.
Please reconsider.  Thanks.

**Comment by Seldaek** [comment]
@jian-wu this has been added 3years ago and since monolog 1.15 - the exception handler is a helper thing, if you don't want to use it it's pretty easy to replace, only a few lines of code, and it isn't really part of the core monolog functionality.

**Comment by jian-wu** [comment]
It didn't matter to me initially but it's becoming more and more apparent and necessary to gracefully handle the exceptions, at least in my case that is.

I can see your point and it seems everyone out there who's using this function either doesn't care if their application breaks since it already breaks and relies on that or does what I do - workaround.

However, IMHO the purpose of this function is to handle uncaught exceptions.  Since it successfully handles them, why should it behave the same way exceptions do?

In any case, I have my workaround and moved on but just thought I should drop by and express my opinion on this.

Thanks.

**Comment by Seldaek** [comment]
The point is to log the exceptions, not suppress them. Hence why it behaves the same way exceptions do by default.
