### ISSUE TITLE
[UnexpectedValueException] Could not parse version constraint >=0.90 <3.0: Invalid version string "0.90 <3.0"

### ISSUE THREAD

**Issue by kekcius** [Seldaek/monolog#593]
Hi!
A little while ago faced with problem installing the package via composer:

```
[RuntimeException]
Could not load package monolog/monolog in http://packagist.org: [UnexpectedValueException] Could not parse version constraint >=0.90 <3.0: Invalid version string "0.90 <3.0"
```

**Comment by kamilsk** [comment]
What version of composer are you using?
In https://github.com/composer/composer/blob/master/CHANGELOG.md

> Added support for npm-style semver operators (`^` and `-` ranges, ` ` = AND, `||` = OR)

after 2015-04-14. Try to `composer self-update`.

**Comment by kamilsk** [comment]
@Seldaek, what do you think about depending on the composer inside composer.json? :) Not the first time I've seen similar bug reports.

**Comment by Seldaek** [comment]
That wouldn't help.. And yeah many people still use outdated composer versions which is a shame, but not much we can do except tell them to upgrade.

**Comment by staabm** [comment]
> That wouldn't help.. And yeah many people still use outdated composer versions which is a shame, but not much we can do except tell them to upgrade.

Maybe there could be a "harder" error then the current warning (which appears after 30days) after e.g. 100days?

**Comment by kamilsk** [comment]
> That wouldn't help..

In this case, users would see a message about outdated dependencies (for example, when you specify php >= 5.5), and not the parsing error (UnexpectedValueException).

**Comment by kekcius** [comment]
Updating the Composer resolved that problem, thanks!

**Comment by stof** [comment]
> Maybe there could be a "harder" error then the current warning (which appears after 30days) after e.g. 100days?

this would only help for people having a version of composer created after we add this new warning. It won't help for people not upgrading

**Comment by stof** [comment]
@kamilsk no. the error happens when composer is loading the monolog metadata from packagist. There is nothing we can change in monolog requirements (which are part of the metadata) to impact the fact that old versions of composer will be unable to read these metadata because their version does not support features used in them.
