### ISSUE TITLE
about NativeMailerHandler

### ISSUE THREAD

**Issue by cerebrumgit** [Seldaek/monolog#596]
Hello .. Good Night

I'm testing the following process but is not firing e-mail

How should I proceed?

---

use Monolog\Logger;
use Monolog\Handler\StreamHandler;

// create a log channel
$log = new Logger('name');

// 

$from = "x@gmail.com";
$to = "y@gmail.com";
$subject = "Logger \Monolog\Handler\NativeMailerHandler";
$body = 'body';

$nativeMailerHandler = new \Monolog\Handler\NativeMailerHandler($to, $subject, $from);
$log->pushHandler($nativeMailerHandler);

// add records to the log
$log->addWarning($body);

---

**Comment by Seldaek** [comment]
By default the mailer handler uses the ERROR level to avoid sending to much emails for nothing, you can change that with `$nativeMailerHandler = new \Monolog\Handler\NativeMailerHandler($to, $subject, $from, Logger::DEBUG);` if you like.
