### ISSUE TITLE
about FlowdockHandler

### ISSUE THREAD

**Issue by cerebrumgit** [Seldaek/monolog#597]
Hello .. Good Night

I'm testing the following process, but is being generated the following error

Warning: Illegal string offset 'flowdock' in /vendor/monolog/monolog/src/Monolog/Handler/FlowdockHandler.php on line 84

How should I proceed?

use Monolog\Logger;
use Monolog\Handler\StreamHandler;

// create a log channel
$log = new Logger('name');

//
$token = "??";
$flowdockHandler = new \Monolog\Handler\FlowdockHandler($token);
$formatter = new \Monolog\Formatter\LineFormatter();
$flowdockHandler->setFormatter($formatter);
$logger->pushHandler($flowdockHandler);

// add records to the log
$log->addWarning($body);

**Comment by xabbuh** [comment]
From reading the docblock of the `FlowdockHandler` class, it seems that the formatter must be an instance of [FlowdockFormatter](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/FlowdockFormatter.php).

**Comment by Seldaek** [comment]
Indeed, we should probably error out if it isn't.
