### ISSUE TITLE
error ssL certificate

### ISSUE THREAD

**Issue by joestick** [Seldaek/monolog#598]
After update monolog to version: 1.14.0

****
Error in exception handler: Curl error (code 60): SSL certificate problem: self signed certificate in certificate chain in C:\xampp\htdocs\imob-io\vendor\monolog\monolog\src\Monolog\Handler\LogglyHandler.php:96
*****

**Comment by xabbuh** [comment]
Since 56dcd1a668a60b2c25df2dd078e1745d890ca60d, the handler throws an exception when the `curl_exec()` call fails. It looks like the handler didn't work for you before, but you didn't notice as it fell silently.

**Comment by Seldaek** [comment]
Indeed, you might need to fix your curl.cafile setting in php.ini, make sure you have an up to date ca file
