### ISSUE TITLE
1.15 changelog is missing

### ISSUE THREAD

**Issue by mnapoli** [Seldaek/monolog#613]
The 1.15.0 version doesn't come with any changelog: https://github.com/Seldaek/monolog/releases/tag/1.15.0 Looking at the commits (https://github.com/Seldaek/monolog/compare/1.14.0...1.15.0) it doesn't seem to contain major features right? (just want to be sure I'm not missing a small internal BC break, or small new feature)

Thanks!

**Comment by Seldaek** [comment]
Yeah I just forgot to update that.. but note that I also maintain it in https://github.com/Seldaek/monolog/blob/master/CHANGELOG.mdown

**Comment by mnapoli** [comment]
Oh thanks, I don't know how I missed that ;)
