### ISSUE TITLE
Bad syntax in composer.json for ruflin/elastica depedency

### ISSUE THREAD

**Issue by mbertin** [Seldaek/monolog#620]
Hello, 
I have noticed that you have a mistake in your composer.json,

"ruflin/elastica": ">=0.90 <3.0", should be "ruflin/elastica": ">=0.90, <3.0" (add missing coma)

I have this problem updating monolog to dev-master =>
 
Could not load package monolog/monolog in http://packagist.org: [UnexpectedValueException] Could not parse version constraint >=0.90 <3.0: Invalid version string "0.90 <3.0"  

Could not parse version constraint >=0.90 <3.0: Invalid version string "0.90 <3.0"

**Comment by stof** [comment]
This is not a bad syntax. It is supported in Composer since December 2014. Just use an uptodate version of Composer

**Comment by mbertin** [comment]
Ok i changed my version of composer and it's working. 
Thank you I close my issue.
