### ISSUE TITLE
handleError and handleFatalError log the same error twice

### ISSUE THREAD

**Issue by sminnee** [Seldaek/monolog#622]
I've noticed that handleError and handleFatalError will log the same error twice, with the default configuration of `Monolog\ErrorHandler::register()`. Here's a simple example:

## Code

	require_once('vendor/autoload.php');

	$logger = new Monolog\Logger('test');
	$logger->pushHandler(new Monolog\Handler\StreamHandler(STDOUT, Monolog\Logger::DEBUG));

	Monolog\ErrorHandler::register($logger);
	user_error('test', E_USER_ERROR);

## Output

	[2015-08-05 11:31:02] test.ERROR: E_USER_ERROR: test {"code":256,"message":"test","file":"/Users/sminnee/Sites/ss4/test.php","line":9} []
	PHP Fatal error:  test in /Users/sminnee/Sites/ss4/test.php on line 9
	PHP Stack trace:
	PHP   1. {main}() /Users/sminnee/Sites/ss4/test.php:0
	PHP   2. user_error() /Users/sminnee/Sites/ss4/test.php:9

	Fatal error: test in /Users/sminnee/Sites/ss4/test.php on line 9

	Call Stack:
	    0.0002     226800   1. {main}() /Users/sminnee/Sites/ss4/test.php:0
	    0.0034     674416   2. user_error() /Users/sminnee/Sites/ss4/test.php:9

	[2015-08-05 11:31:02] test.ALERT: Fatal Error (E_USER_ERROR): test {"code":256,"message":"test","file":"/Users/sminnee/Sites/ss4/test.php","line":9} []

**Comment by camspiers** [comment]
I'm pretty sure that's why I added this when I was deep in the weeds of error logging:

https://github.com/camspiers/silverstripe-loggerbridge/blob/master/src/Camspiers/LoggerBridge/LoggerBridge.php#L465

**Comment by sminnee** [comment]
OK @camspiers are you recommending that after a fatal error is handled by `handleError()`, we call `exit(1)` explicitly?

An alternative fix would be keep track of the last error handled by `handleError()` and only log in `handleFatalError()` if the error returned by `error_get_last()` was something different.

**Comment by Seldaek** [comment]
Pushed a fix which I believe will be sufficient, at least it seems to work fine in my small tests.
