### ISSUE TITLE
Question: is there an easy way to prepend all log messages with specific text?

### ISSUE THREAD

**Issue by jbruni** [Seldaek/monolog#628]
I want to prepend all log results with the return value of a specific function. (I'm using Laravel.)

How to "extend" or "override" or "format" all log messages, so I can include this string before the messages provided by calls to the logger?

**Comment by jbruni** [comment]
@Seldaek - I'm pretty sure it is easy. I just don't know. Please point it for me. Thank you!

**Comment by Seldaek** [comment]
Use the processor feature, like this for example:

```php
$logger->addProcessor(function ($record) {
    $record['message'] = 'PREFIX: ' . $record['message'];
    return $record;
});
```

**Comment by nicholaswright** [comment]
The above should be `$logger->pushProcessor()`.

**Comment by GinoPane** [comment]
The above does not work:
```[16-Jan-2024 11:16:56 Europe/London] PHP Fatal error:  Uncaught LogicException: Unsupported operation: setting message in /var/www/html/vendor/monolog/monolog/src/Monolog/LogRecord.php:60```

**Comment by Seldaek** [comment]
@GinoPane sorry I'm late here but for Monolog 3.x you need to do `$record->with(message: "...")` and return the new object that with() returns.

**Comment by pthreat** [comment]
> @GinoPane sorry I'm late here but for Monolog 3.x you need to do `$record->with(message: "...")` and return the new object that with() returns.

      "message" => "Named parameter $datetime overwrites previous argument"
