### ISSUE TITLE
Request for HipChat formatter

### ISSUE THREAD

**Issue by snapshotpl** [Seldaek/monolog#629]
HipChat api has 1000 signs limit for message length. When I try to log longer message nothing happend: I don't receive error and message doesn't appear in my Hipchat.

Via https://www.hipchat.com/docs/apiv2/method/send_message

**Comment by Seldaek** [comment]
I guess the max length from https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/HipChatHandler.php#L49 has been downgraded to 1000? cc @rdohms

**Comment by rdohms** [comment]
That limitation was added afterwards by @leevigraham maybe he has some more insight? I have not used HipChat for 2 years now.

**Comment by snapshotpl** [comment]
I'm not sure but I think that this feature should be in formater. What about case when I use HtmlFormatter and it make message longer than limit in HipChat?

**Comment by rdohms** [comment]
Actually i think it needs to be in the adapter. Cause its the adapter's responsibility to know "how" to send the message. Which in this case means splitting a 3K char message in 3x1K messages.

**Comment by snapshotpl** [comment]
Ok, good idea, but what about case when you cut html message inside html tag?

**Comment by leevigraham** [comment]
@snapshotpl @Seldaek The limit has indeed been reduced: 

V1: https://www.hipchat.com/docs/api/method/rooms/message
V2: https://www.hipchat.com/docs/apiv2/method/send_message

**Comment by Seldaek** [comment]
If anyone feels like doing a pull request to fix this that'd be great. I don't have any hipchat access so I can patch up the code but not check it works.

**Comment by snapshotpl** [comment]
I have investigate this issue more and now I can say that limit is 10k. Why?
* we have use send room notification https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/HipChatHandler.php#L168
* it has 10k limit https://www.hipchat.com/docs/apiv2/method/send_room_notification

I think we should split hipchat handler to v1 and v2 to ease code.

**Comment by Seldaek** [comment]
So it seems the limit is indeed 10000 and not 1000. @snapshotpl with which version of the API were you having issues? v1 or v2? Can you please contact hipchat if you're on v2, because it seems the endpoint we are using allows up to 10000chars and we limit to 9500 which should be safe.

**Comment by snapshotpl** [comment]
v2. But I have written about this above

**Comment by shehi** [comment]
@Seldaek , I came here for the same issue: the limit of 10k is there, but Monolog doesn't really respect that: ```HipChatHandler::write()``` method doesn't check for the limits and just writes the content. I just tried an exception-trace message weighing 15k+ bytes, and Monolog didn't return any errors. However, Hipchat returns the following result: 

```{"error":{"code":400,"type":"Bad Request","message":"Message must be 10000 characters or less."}}```

Could you please add actual length checks into ```HipChatHandler::write()``` ?

**Comment by shehi** [comment]
@Seldaek , additionally, I'd recommend adding unit-tests checking the exception situations, especially where length-limits are passed.

**Comment by shehi** [comment]
I think adding the third parameter to ```fwrite()``` function at:

https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SocketHandler.php#L227

equal to the max length of handler would solve the issue.
