### ISSUE TITLE
Error found in ExecutableFinder.php while creating monolog?

### ISSUE THREAD

**Issue by 572** [Seldaek/monolog#632]
I found errors when creating logs, I'm not very sure if the mono-log is the root of the problem so I posed my whole code :

		<?php
			//Setup~~
			$php_path = '/etc/php5/apache2/';
			$index_path = '/var/www/html/deja_vu/';
			require $php_path.'vendor/autoload.php';

			//Using XPDF, following the tutorial here : https://php-xpdf.readthedocs.org/en/latest/
			use Monolog\Logger;
			use Monolog\Handler\NullHandler;
			use XPDF\PdfToText;
			// Create a logger
			$logger = new Logger('MyLogger');
			$logger->pushHandler(new NullHandler());

			// You have to pass a Monolog logger
			// This logger provides some usefull infos about what's happening
			$pdfToText = PdfToText::load($logger);

			// open PDF
			$pdfToText->open($index_path.'a.pdf');

			// PDF text is now in the $text variable
			$text = $pdfToText->getText();
			$pdfToText->close();
			
			echo $text;
		?>

I use browser to check the errors, here's the output :

		Warning: file_exists() expects parameter 1 to be a valid path, object given in /etc/php5/apache2/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php on line 150

		Catchable fatal error: Object of class Monolog\Logger could not be converted to string in /etc/php5/apache2/vendor/symfony/process/ExecutableFinder.php on line 81

It is pretty confusing to find what's wrong, I would be very thankful if the issue is solved

**Comment by Seldaek** [comment]
The source for this PdfToText::load() call is here https://github.com/alchemy-fr/BinaryDriver/blob/master/src/Alchemy/BinaryDriver/AbstractBinary.php#L143 and it appears it needs something else before the logger.

The XPDF docs also indicate you should use ::create to initialize it before open, and not load, so I am guessing this tutorial you follow is outdated: https://github.com/alchemy-fr/PHP-XPDF#driver-initialization /cc @romainneutron

Anyway nothing to do with monolog so I am closing this.

**Comment by 572** [comment]
Thank you very much!
