### ISSUE TITLE
Unserialize logs

### ISSUE THREAD

**Issue by garygreen** [Seldaek/monolog#633]
Monolog primary purpose seems to be writing / send logs, but what about unserializing existing, formatted logs? It would seem logical that each formatter has the ability to unserialize the format it wrote back into an array `record` object.

It would be extremely useful in cases for creating some kind of log viewer, or scraping the data for statistics etc.

**Comment by Seldaek** [comment]
IMO for log viewing there are already plenty of great solutions (heka, logstash, and a boatloat of paid services). Those generally have standard inputs, existing formatters, or can even parse any kind of json output. I don't really see the value in adding more code to achieve the same.
