### ISSUE TITLE
Slack logging doesn't work

### ISSUE THREAD

**Issue by lucian303** [Seldaek/monolog#638]
I tried the following:

```
$logEntriesHandler = new SlackHandler($slackToken, 'general');
$handlers[] = $logEntriesHandler;
return new Logger('api', $handlers);
```

There are no errors related to the handler and the other handlers (stream, rotating file, and Logentries) are all working, so I can only assume the Slack handler no longer works.

**Comment by Seldaek** [comment]
The default log level for slack is CRITICAL, that might be your issue, if you want to log more than that you should set it up with a lower level. i.e. add `$logEntriesHandler->setLevel(Logger::DEBUG);`
