### ISSUE TITLE
composer install Failure.

### ISSUE THREAD

**Issue by wkii** [Seldaek/monolog#639]
composer require "monolog/monolog" "1.16.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package monolog/monolog could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by prisis** [comment]
try without quotation marks: composer require monolog/monolog 1.16.0.

**Comment by stof** [comment]
do you have an existing composer.json ? If yes, please paste it to help debugging the issue

Btw, I suggest you to avoid requiring a specific version explicitly. Use a range constraint instead, allowing you to receive bug fixes

**Comment by wkii** [comment]
I think it is a network problem.
The tragedy is that I was in China.
