### ISSUE TITLE
LineFormatter leaves trailing spaces

### ISSUE THREAD

**Issue by clphillips** [Seldaek/monolog#645]
If `$ignoreEmptyContextAndExtra` is set to true, LineFormatter will leave tailing white space.

```php
use Monolog\Logger;
use Monolog\Handler\RotatingFileHandler;
use Monolog\Formatter\LineFormatter;

$handler = new RotatingFileHandler('my.log', 5);
$handler->setFormatter(new LineFormatter(null, null, false, true));

$log = new Logger('general');
$log->pushHandler($handler);

$log->info('No trailing spaces please!');
```

Output (note trailing spaces, yuck!):

```
[2015-09-15 21:54:22] general.INFO: No trailing spaces please!  

```

With `$ignoreEmptyContextAndExtra` set to false, output becomes:

```
[2015-09-15 21:54:22] general.INFO: No trailing spaces please! [] []

```

**Comment by Seldaek** [comment]
Yes, this is true, and there is no real way to fix it unless we trim but how do we know we can trim those characters safely? We don't, so there is no trimming. I don't think it's such a big problem..

**Comment by clphillips** [comment]
I see a simple fix that doesn't involve trim. I'll see if I can find the time to hammer it out.

I agree it isn't a big problem, but trailing white space is evil.

**Comment by timkelty** [comment]
Agreed this is a bit annoying – I don't even mind the trailing WS so much, as the instance where you have `%extra%`  but no `%context%, you'll end up with an extra space.
