### ISSUE TITLE
Allow level range in handlers

### ISSUE THREAD

**Issue by dzubchik** [Seldaek/monolog#649]
Hi, I would like to propose level range in handlers. In this way it will allow to send messages with levels [debug, info, warning] to one handler, errors to other and critical to another, for ex. Currently such logging scheme can not be implemented, because handlers check only lower level limit, but there are no check about upper level limit. Would this feature be usable or it is just me?

**Comment by Seldaek** [comment]
You can implement it with the FilterHandler actually, configure the inner handler as accepting DEBUG (and above) and then pick exactly which levels you want to let through to it using FilterHandler.

**Comment by dzubchik** [comment]
@Seldaek , thank you! Monolog is great!
