### ISSUE TITLE
StreamHandler and LogglyHandler?

### ISSUE THREAD

**Issue by BardiaAfshin** [Seldaek/monolog#653]
Why do you need to have a stream handler when you have a loggly handler? Does the log get written temporary to disk before being pushed to loggly?

**Comment by stof** [comment]
Well, the StreamHandler is for cases where you want to log things in a file. Not everyone is using loggly.

**Comment by BardiaAfshin** [comment]
Closing issue. I might post a gist link later on. The article Loggly introduces you with is more confusion than helpful.
