### ISSUE TITLE
Microsecond timestamps cost milliseconds of runtime with heavy log usage

### ISSUE THREAD

**Issue by bd808** [Seldaek/monolog#657]
The use of `DateTime::createFromFormat` to create timestamps with microsecond resolution can incur milliseconds of runtime overhead when handling a request which generates a significant number of logging events. This cost is paid even if the events are eventually discarded as the `$record['datetime']` member for each event is populated even if no handlers are interested in recording the event durably.

This simplistic benchmark shows the relative costs of collecting microsecond level timing data:

```php
<?php
$limit = 1000;
$tz = new DateTimeZone('UTC');

$start = microtime(true);
for ($i = 0; $i < $limit; $i++) {
        $dt = DateTime::createFromFormat('U.u', sprintf('%.6F', microtime(true)), $tz)->
                setTimezone($tz);
}
echo 'createFromFormat: ', microtime(true) - $start, "\n";

$start = microtime(true);
for ($i = 0; $i < $limit; $i++) {
        $dt = new DateTime(null, $tz);
}
echo 'DateTime:         ', microtime(true) - $start, "\n";
```

```sh
$ php benchmark.php
createFromFormat: 0.010702133178711
DateTime:         0.0037209987640381
```

Use of `DateTime::createFromFormat` was introduced in 61a4945 replacing a simple usage of `new DateTime`. In a application that generates a few dozens or even hundreds of log events per request the runtime cost difference of `DateTime::createFromFormat` is probably not noticeable. The costs add up however on a heavily loaded system handling hundreds of requests per second with hundreds or even thousands of log events generated per request. Under any conditions the benefit of having microsecond resolution for timestamps verses millisecond level resolution is debatable. When having this level of granularity requires milliseconds of wall clock time to compute, the benefit is even more tenuous.

The easy fix for this issue would be to simply replace `\DateTime::createFromFormat('U.u', sprintf('%.6F', microtime(true)), static::$timezone)->setTimezone(static::$timezone)` with `'datetime' => new \DateTime(null, static::$timezone)` in `Monolog\Logger`. A more complicated approach would be to introduce a feature flag that allows control of millisecond/microsecond timestamp resolution. If I was the benevolent dictator for this project I would chose the simple solution under the basic assumption that logging should seek to be as low impact as possible, especially for `debug` events that are likely to be discarded anyway.

**Comment by Seldaek** [comment]
The reason this was introduced is that without that  hack, you don't get microsecond precision indeed, but you also don't get millisecond precision. `(new \DateTime(null, new \DateTimeZone('UTC')))->format('U.u')` outputs `1444931680.000000`.

That said, I definitely see that this isn't for everyone.. And given on the use case I guess yes it might be too much overhead. I think adding a way to configure it is probably the best, and possibly changing the default in 2.0 to be disabled by default.
