### ISSUE TITLE
Request for a Dbal / Mysql handler

### ISSUE THREAD

**Issue by ClementGautier** [Seldaek/monolog#665]
Hello :)

I guess that the topic have already been discussed but I would like to know if any handler for `doctrine/dbal` or PDO exists. 

If not, is it ok if I submit a PR for this ? 

What do you think will be the most popular ? dbal or pdo ? I think that if I use `Doctrine\Dbal\Connection::insert` it could cover MySql and PostgreSQL at the same time but include a dependency to doctrine/dbal.

**Comment by Seldaek** [comment]
I don't think logging to DB is very smart as it tends to be too slow for any kind of loaded site. However there is https://github.com/waza-ari/monolog-mysql that exists if you are interested.

**Comment by ClementGautier** [comment]
@Seldaek Thanks. 

I know that it's not a smart idea regarding all possible kind of logs. In our application we are planning to use monolog to notify users (like flash messages in Symfony2 for example) using the LoggerInterface as it is compliant with our needs. Some clients of ours could use a SlackHandler or an HipChatHandler, but, for the other, we need to persist the notifications in order to display them on the app.
