### ISSUE TITLE
ErrorHandler and injected logger

### ISSUE THREAD

**Issue by snapshotpl** [Seldaek/monolog#666]
`Monolog\ErrorHandler` gets `Psr\Log\LoggerInterface` in constructor. In my application I created simple implementation of `Psr\Log\LoggerInterface` and injected it to error handler. After fatal error I get another one:

```
Fatal error: Call to undefined method CatchableLoggerHandler::getHandlers() in Monolog/ErrorHandler.php on line 177
```

In line 177 logger use method `getHandlers()` which doesn't exist in `LoggerInterface` (exists in `Monolog\Logger`).

**Comment by Seldaek** [comment]
Sorry about that, silly mistake.

**Comment by Seldaek** [comment]
1.17.2 is out with the fix

**Comment by snapshotpl** [comment]
Thank you!
