### ISSUE TITLE
Why forcing $context to be an array ?

### ISSUE THREAD

**Issue by dmidz** [Seldaek/monolog#675]
I am wondering why forcing $context to be an array, because such, even writing a custom handler, it forces to record an array, and then eventually transform the data in the handler.
For example I wrote my own browser handler, which write javascript console.* and important, use JMSSerializer, so it respect entities' properties exposure, like :
```php
// BrowserHandler
$serializer->serialize($record['context'], 'json');
// Controller
$logger->debug('anyentity', $entity);
```
But I am forced to do like :
```php
// Controller
$logger->debug('anyentity', [$entity]);// wrap the context in an array
// BrowerHandler
$arr = $record['context'];
if(count($arr) === 1) $arr = $arr[0];// extract the first index if array contains only one element
$serializer->serialize($arr, 'json');
```
So now it outputs well 
```javascript
console.log("anyentity", {"exposedproperty":"foo","exposedproperty2":"bar"});
```

**Comment by Seldaek** [comment]
There are a few reason: standardization and to make sure we can always access it as an array, it just builds common assumptions that make it a bit easier to write code. Plus it is required by the PSR-3 interface as well so it's unlikely we'll change that. And finally IMO it helps you write more readable logs if you are forced to name things and not just pass values without names (like you are doing, I would prefer passing it like `['entityName' => $entity]`, then maybe you can loop over all the context data and pass any object from the `Foo\Entity\..` namespace into the serializer and let the rest be serialized using the usual monolog NormalizerFormatter::normalize?).

**Comment by dmidz** [comment]
Thank you for the clarification, I thought well it was about standardization, and then because it is used by a so wide variety of output possibilities, so it is more easy and less code everywhere when always expecting the input as array. Yes I could parse first level of context and check if instance of Entity and so pass to serializer, code in the handler is not a problem, it is more where I use the logger, I had to bypass in each place for wrapping the context in an array, but well...I could also extends the logger or insert a service in between and bypass there if I acually need it...
Anyway, Monolog is so usefull !
