### ISSUE TITLE
CloudWatch handler

### ISSUE THREAD

**Issue by veewee** [Seldaek/monolog#678]
Hello,

I can't seem to find any information about using Monolog in combination with Amazon CloudWatch. 
That is why I have some questions about the integration:

- Has cloudwatch been discussed before? 
- Are there any 3rd party handlers available or under construction?
- Is there another / better way of integrating logs with CloudWatch like for example logging to a file and syncing it?
- Are there any plans of adding a CloudWatch handler?

Thanks!

**Comment by tegansnyder** [comment]
You can log to a file and pick that up in AWS logs.
```php
$logger = new Monolog('mylogger');
$logger->pushHandler(new \Monolog\Handler\ErrorLogHandler());
$logger->pushHandler(new \Monolog\Handler\StreamHandler("/my_application/errors.log"));
```
Then install the agent for cloud watch on your Amazon servers. Finally setup the config file: /etc/awslogs/awslogs.conf
```
[ /my_application/errors.log]
datetime_format = %b %d %H:%M:%S
file = /my_application/errors.log
buffer_duration = 5000
log_stream_name = MyAppLogStream
initial_position = start_of_file
log_group_name = ApplicationLogs
```

**Comment by veewee** [comment]
Thanks @tegansnyder.
We also found 2 other possible solutions when logging inside a Docker container:

- Log to the `php://stdout` or `php://stderr` stream with the StreamHandler.
- Log to the errorlog with the ErrorLogHandler. Not that this will require a link from the error-log file to /dev/stdout

Next you will need to configure the Amazon CloudWatch Logs logging driver:
http://docs.docker.com/engine/reference/logging/awslogs/

However it might still be handy to create a CloudwatchHandler in Monolog based on the aws-sdk library: https://github.com/aws/aws-sdk-php

This way the logs don't need to be passed by an agent or a logs-driver.

**Comment by Seldaek** [comment]
I think a CloudWatch-specific handler might be a good thing if it helps smooth the setup process, but if it depends on AWS SDK it definitely belongs in its own package/repository. You can then link it in the wiki page of [third party handlers](https://github.com/Seldaek/monolog/wiki/Third-Party-Packages).

**Comment by maxbanton** [comment]
Just created CloudWatch Monolog Handler https://github.com/maxbanton/cwh
