### ISSUE TITLE
Read log files with monolog?

### ISSUE THREAD

**Issue by JHGitty** [Seldaek/monolog#689]
Is it possible to read log files which are written with monolog?
If not: Is there any PHP library which is working on this?

I like to add a "view logs" page to our administration interface.

**Comment by quantumpacket** [comment]
You can save the log files as JSON using the `JsonFormatter`. You then basically do the following:

```php
$logDetails = json_decode(file_get_contents(...));
```

Keep in mind the size of the log files as this basic example would load it all into memory. You'd want to cache what you want, or rotate logs when they reach an acceptable max size.

There are also options to save log records to a database. This would be easier for retrieval, but depending on how many records are being logged for each request based on your application it *may* impact performance.

You should just check out the [documentation](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md) to find what suits your needs.

**Comment by Seldaek** [comment]
There is no way and IMO it's out of scope for monolog, there are many existing solutions (although not in PHP that I know of), from Logstash to Heka to a zillion third party services that monolog supports logging to.
