### ISSUE TITLE
Extending/custom processors

### ISSUE THREAD

**Issue by rreynier** [Seldaek/monolog#694]
There only seems to be documentation regarding creating your own handlers, but how about processors?  My use case is that I need to add some information regarding the connected database.  Just like webprocessor adds information regarding the web request, this processor would add information regarding the connected database (primarily database name). (single tenancy.. ugh I know ;)).

Anyway, is there a recommended way to do custom processors? We dont seem to be extending an interface or anything along those lines.

**Comment by staabm** [comment]
A processor is just a callable nothing more, e.g. a class implementing `__invoke()` or just a lambda function
