### ISSUE TITLE
Integrate with Google Analytics

### ISSUE THREAD

**Issue by wernight** [Seldaek/monolog#696]
Google Analytics supports [exception tracking via Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#exception) and that could be called from PHP.

Some events can also be tracked real-time, other have a short delay which may for some users provide a good experience that is also easier to deploy than using Raven/Sentry.

**Comment by Seldaek** [comment]
I think this would belong more in a third party handler package as I guess it'll depend on a google analytics sdk lib of some sort.

**Comment by wernight** [comment]
You can just send an HTTP request like:

    https://www.google-analytics.com/collect?v=1&tid=UA-XXXXXX-Y&cid=555&t=exception&exd=my-exception-description&exf=1

See [exception hit type](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#exception) for details about the fields.

So it should be pretty simple, just urlencode each argument.

**Comment by Seldaek** [comment]
Ok that's good but still I think I would rather have it as a third party 
package just because it's not exactly a mainstream logging target and I 
am trying to limit the maintenance burden of this repo :)
