### ISSUE TITLE
Handler for Logging via consuming an API

### ISSUE THREAD

**Issue by paragdakle** [Seldaek/monolog#699]
Hello,

I have been using Monolog with Laravel 5.1 and I really like the simplicity of the logger.

However, in my project we had a central logging server which exposed an API for logging. I failed to find any Logging Handler for the same purpose.

I think such kind of an handler will be useful as it will provide the developer the flexibility to consume any API for logging.

Cheers,

**Comment by xabbuh** [comment]
Are you sure that a handler in Monolog is the best solution? I mean the actual API endpoints will probably differ with each use case and you can quite easily implement a custom handler in your application using the [cURL Util class](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/Curl/Util.php).

**Comment by paragdakle** [comment]
Yes. I agree, that actual API endpoints will differ, but if we have a generic basic Handler which does the task and will work for majority of the cases, from a developers perspective, writing a new handler is always more tedious then adding a few tweaks to an existing one. I have added a basic generic handler and pull request for the same also has been initiated.

**Comment by Seldaek** [comment]
Closing as per https://github.com/Seldaek/monolog/pull/700#issuecomment-190781061
