### ISSUE TITLE
Is there JsonFormatter example or tutorial?

### ISSUE THREAD

**Issue by setkyar** [Seldaek/monolog#708]
I want to use JsonFormatter and json_decode. Is there any example or tutorials?

**Comment by xabbuh** [comment]
@setkyar Can you explain what exact problems you have with using the formatter?

**Comment by setkyar** [comment]
@xabbuh I try to use json formatter and want to try to get those logs json from `file_get_content` method. And want to encode to json. The following was my code

	use Monolog\Logger;
	use Monolog\Handler\StreamHandler;
	use Monolog\Formatter\LineFormatter;
	use Monolog\Formatter\JsonFormatter;

	Route::get('/test', function() {

		$user_info = ['ip' => '192.168.1.0', 'OS' => 'Window'];

		$file = storage_path() . '/user-info/info-' . date('Y-m-d') . '.log';

		// finally, create a formatter
		$formatter = new JsonFormatter();

		// Create a handler
		$stream = new StreamHandler($file, Logger::INFO);
		$stream->setFormatter($formatter);

		// bind it to a logger object
		$securityLogger = new Logger('View Info');
		$securityLogger->pushHandler($stream);
		$securityLogger->addInfo('info', $user_info);
	});

And the following is my logs

	{"message":"info","context":{"ip":"192.168.1.0","OS":"Window"},"level":200,"level_name":"INFO","channel":"View Info","datetime":{"date":"2015-12-23 16:51:06.934494","timezone_type":3,"timezone":"Asia\/Rangoon"},"extra":[]}
	{"message":"info","context":{"ip":"192.168.1.0","OS":"Window"},"level":200,"level_name":"INFO","channel":"View Info","datetime":{"date":"2015-12-23 16:52:30.977059","timezone_type":3,"timezone":"Asia\/Rangoon"},"extra":[]}

But, when I try to `json_decode` that result. I always get empty result. Is that because my log format was wrong?

**Comment by quantumpacket** [comment]
@setkyar that is a JSON object PER LINE. So you gotta pass each line through to `json_decode()`

**Comment by setkyar** [comment]
It's there a way to make JSON object collection? @quantumpacket

**Comment by quantumpacket** [comment]
@setkyar just use https://secure.php.net/manual/en/function.file.php it will load the file with each array element being a JSON object. Then do whatever you want with it. :)

**Comment by setkyar** [comment]
@quantumpacket that is what I want. Thanks you very much @quantumpacket
