### ISSUE TITLE
File rotate failed due to error 'No such file or directory'

### ISSUE THREAD

**Issue by atulatri** [Seldaek/monolog#709]
We experienced following exception while using RotatingFileHandler
```
unlink(/opt/__data/logs/queue-2015-12-13.log): No such file or directory in /__src/thirdparty/Monolog/Handler/RotatingFileHandler.php on line 118
#0 [internal function]: Whoops\Run->handleError(2, 'unlink(/opt/...', '/opt/releases/...', 118, Array)
#1 /__src/thirdparty/Monolog/Handler/RotatingFileHandler.php(118): unlink('/opt/__...')
#2 /__src/thirdparty/Monolog/Handler/RotatingFileHandler.php(61): Monolog\Handler\RotatingFileHandler->rotate()
#3 /__src/thirdparty/Monolog/Handler/RotatingFileHandler.php(85): Monolog\Handler\RotatingFileHandler->close()
#4 /__src/thirdparty/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#5 /__src/thirdparty/Monolog/Logger.php(263): Monolog\Handler\AbstractProcessingHandler->handle(Array)
```

I am not exactly sure why this error occurred.  However upon looking method RotatingFileHandler::rotate(). I think there is a possibility of such exceptions. 

```
/**
 * Rotates the files.
 */
protected function rotate()
{
    // update filename
    $this->url = $this->getTimedFilename();
    $this->nextRotation = new \DateTime('tomorrow');

    // skip GC of old logs if files are unlimited
    if (0 === $this->maxFiles) {
        return;
    }

    $logFiles = glob($this->getGlobPattern());
    if ($this->maxFiles >= count($logFiles)) {
        // no files to remove
        return;
    }

    // Sorting the files by name to remove the older ones
    usort($logFiles, function ($a, $b) {
        return strcmp($b, $a);
    });

    foreach (array_slice($logFiles, $this->maxFiles) as $file) {
        if (is_writable($file)) {
            unlink($file);
        }
    }
}
```

Here unlink is protected by is_writable check. But is_writable result is cached (http://php.net/manual/en/function.clearstatcache.php). So if log file is removed by another process (may be log rotate event in another process), unlink may fail. To solve this issue we should clearstatcache for log file before using check is_writable. Happening of this case is rare but I think is a real possibility.

I am also looking for other explanations for such exception.  Your help is much appreciated.

**Comment by Seldaek** [comment]
The analysis sounds legit. However even clearstatcache won't necessarily fix it as it could still have a race condition between is_writable and unlink, so I think the only way here is to ignore errors when calling unlink. I'll do a fix.
