### ISSUE TITLE
Allow to use different LogHandler with the same LogLevel

### ISSUE THREAD

**Issue by xhallix** [Seldaek/monolog#716]
Let's say I have a use case in which I use the ```SyslogUdpHandler``` as my standard logger.
This logger has the Loglevel ```Debug``` by default.
When I have a special usecase, where I want to log specific data into a file using ```StreamHandler``` with LogLevel ```Debug``` this is not possible because I have another handler already set for this level.

### Proposal

```Logger::addRecord()``` exits early which is pretty good actually. 
But maybe it could be some improvement, to add some extra check if the handlers with the same loglevel are handlers of the same type, so that they would not interfere each other?

Not sure if this is suppressed by purpose, but if so, please let me know.

Cheers

**Comment by xabbuh** [comment]
Isn't the [GroupHandler](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#wrappers--special-handlers) what you are looking for?

**Comment by xhallix** [comment]
Thanks a lot! 
I did not see this. Seems that could be what I'm looking for.
