### ISSUE TITLE
PHP7 compatibility fixes required

### ISSUE THREAD

**Issue by kowalk** [Seldaek/monolog#718]
Please replace Exception with Throwable or just remove "Exception":

monolog/src/Monolog/Formatter/LineFormatter.php:177
monolog/src/Monolog/Formatter/NormalizerFormatter.php:93
monolog/src/Monolog/Formatter/NormalizerFormatter.php:115

**Comment by Seb35** [comment]
According to the PHP documentation for the [interface Throwable](https://secure.php.net/manual/en/class.throwable.php), Throwable is not implementable by PHP users, it’s only an internal interface for Exception and Error (I tested to be sure, and PHP really says "PHP Fatal error:  Interface 'Throwable' not found").

Is this issue still valid given this fact? What was the initial goal?

**Comment by staabm** [comment]
The suggested changes would break compat with all php5 versions

**Comment by Seldaek** [comment]
Fixed in 1.x by https://github.com/Seldaek/monolog/commit/481fc4cfa17808581d113673e7dd002b06dcc100

**Comment by kowalk** [comment]
Nice! Thanks :)
