### ISSUE TITLE
recursion of exception normalization should be configurable

### ISSUE THREAD

**Issue by rolfvreijdenberger** [Seldaek/monolog#726]
Hi,
we're using Monolog in our application and we find that we want to limit the normalization level for nested exceptions.

I've made an adjustment in the NormalizerFormatter that makes the level of recursion configurable with a sensible default to remain backwards compatible.

Can I submit it as a pull request?

**Comment by Seldaek** [comment]
You can always submit pull requests, feel free to do so without asking, then we can discuss in the pull request when looking at the code it's often easier :)

I'll close this issue but please open a pull request yes.
