### ISSUE TITLE
[Question] Handler stop the log stack execution

### ISSUE THREAD

**Issue by tiagobrito** [Seldaek/monolog#732]
Imagine that LogEntries have a problem with their servers and they keep the connection open for a long time (1 minute), could this make our site slow? What can I do to avoid this?

Related to #733

**Comment by Seldaek** [comment]
Yes that could be a problem, and yes your other issue sounds like a good solution

**Comment by vaidas-lungis** [comment]
Or wrap it into `WhatFailureGroupHandler` ?
