### ISSUE TITLE
Allow custom connection_timeout to LogEntries handler

### ISSUE THREAD

**Issue by tiagobrito** [Seldaek/monolog#733]
It would be great to set the connection_timeout configuration from parameters instead of getting it from php.ini configuration

**Comment by Seldaek** [comment]
I think this applies to most handlers doing network stuff really.. maybe we could think of a global solution to this.

**Comment by spawn-guy** [comment]
I am currently experiencing this issue, with logEntries in particular.

I try to log inside a long-running Console script. Everything works nicely until i get a _next_ long-running request to a 3rd party.
After that script crashes with 
`exception 'RuntimeException' with message 'End-of-file reached, probably we got disconnected (sent 0 of 2128)' in /var/app/current/vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php:281`

timelapse is the following
```
[2016-04-06 11:36:01] production.INFO: got ...stripped for security....
[2016-04-06 11:37:54] production.ERROR: exception 'RuntimeException' with message 'End-of-file reached, probably we got disconnected (sent 0 of 2128)' in /var/app/current/vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php:281
```
this happens with the (already) increased `default_socket_timeout=6000`

Can someone advise me the steps to fix it?

**Comment by holtkamp** [comment]
Maybe I am missing the point of this issue, but one can use [```setConnectionTimeout()```](https://github.com/Seldaek/monolog/blob/58544af7ff9d0c54ef36bc0e4e79330cda751b0e/src/Monolog/Handler/SocketHandler.php#L103-L107) for this, right?

**Comment by Seldaek** [comment]
Yeah I think I'm gonna close this. Doesn't seem really worth having global configuration (at least not more than php.ini stuff) for this. Can be done at the handler level.
