### ISSUE TITLE
BrowserConsoleHandler no longer gives any output with monolog 1.18.0

### ISSUE THREAD

**Issue by johnhunt** [Seldaek/monolog#737]
Background:

`composer require monolog/monolog` installs v1.18. Therefore lots of people will use this version.

Steps to re-produce:

1. Install monolog 1.18
2. Try using the BrowserConsoleHandler
3. Notice that it no longer adds any HTML or javascript to the page
4. Try 1.17.2
5. Notice this works as expected.

Test code:

> <?php
> use Monolog\Logger;
> use Monolog\Handler\BrowserConsoleHandler;
> require_once('vendor/autoload.php');
> $logger = new Logger('xyz');
> $logger->pushHandler(new BrowserConsoleHandler());
> $logger->addWarning('Hello world');

**Comment by Seldaek** [comment]
I guess https://github.com/Seldaek/monolog/commit/1048aa4a5932db4c6471fecbb22eb19e56e47e74 broke it then, but.. why? I think maybe because before we defaulted to html unless you send a content-type header with something else than html. Does your app send content-type for html pages?

**Comment by johnhunt** [comment]
Hi Seldaek, I've not spent a lot of time investigating but I can tell you that setting the content type to html does cause the <script> tags to be injected into the page, but no javascript within them.

**Comment by johnhunt** [comment]
haha, fixed it.. PR coming through :)

**Comment by Seldaek** [comment]
Yeah I just saw the commas as well :/ Silly echo statement from before.

**Comment by Seldaek** [comment]
Please PR against 1.x branch btw

**Comment by Seldaek** [comment]
It's now available in 1.x if you `composer require monolog/monolog:^1.18@dev` you'll get the fixed version.

**Comment by johnhunt** [comment]
Thanks, sorry I realised I'd requested it to be merged into the wrong thing after I'd left the office - thanks for merging it anyway, this makes a big difference to our team :+1:
