### ISSUE TITLE
Newrelic transaction name - setNewRelicTransactionName()

### ISSUE THREAD

**Issue by Azuka** [Seldaek/monolog#739]
Should [setNewRelicTransactionName](https://github.com/Seldaek/monolog/blob/3d30ba5ecc301dc0e7d61480c7a163cfcf1458fc/src/Monolog/Handler/NewRelicHandler.php#L174) also set

```php
$this->transactionName = $transactionName;
```
otherwise subsequent calls to `getTransactionName()` would be invalid.

**Comment by Seldaek** [comment]
I don't think so no, as setNewRelicTransactionName is protected.. the $this->transactionName is just a default value that you can configure in constructor and used as default if context has on message.
