### ISSUE TITLE
NullHandler doesn't bubble

### ISSUE THREAD

**Issue by apflieger** [Seldaek/monolog#749]
The current implementation of NullHandler doesn't allow the handler to bubble, it doesn't care about the `bubble` attrbute at all.

Here's a use case of having the NullHandler to bubble : 

I'm using MonologBundle and I configure it to have the same handlers for all symfony's environments. I still need to disable some handlers so I simply override the type to "null" in config_*.yml and expect them to be noop and bubble.

Anyway, it's weird that it behaves differently from all other handlers (I suppose all, I didn't check)

Let me know what you think about it :)

**Comment by Seldaek** [comment]
The point of the null handler is to suppress all log records, so if it bubbled it would just become a noop and might as well not be there. You could use a type group or something instead if you want a noop.
