### ISSUE TITLE
How to log multi line logs to stdout

### ISSUE THREAD

**Issue by mbrevda** [Seldaek/monolog#752]
How can I log multiple errors (such as stack traces) to stdout? I have tried many different combinations of  ErrorFileLog and StreamLogger (to stdout) with the line formater but was unsuccessful. Do you have an example of how this might work?

**Comment by Seldaek** [comment]
Did you call `$lineFormatter->allowInlineLineBreaks()` and `$lineFormatter->includeStacktraces()` on your formatter?

**Comment by mbrevda** [comment]
I passed true for that option to the constructor.

**Comment by magnetik** [comment]
It seems that `allowInlineLineBreaks()` does not work because everything is passed through `json_encode` which is ruining it. Check : https://3v4l.org/C0P79

```
php > $variable="This\nIs\nA\nMultiline\nInput";
php > echo $variable;
This
Is
A
Multiline
Input
php > echo json_encode($variable);
"This\nIs\nA\nMultiline\nInput"
php > echo json_encode($variable, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
"This\nIs\nA\nMultiline\nInput"
```
