### ISSUE TITLE
Greedy Glob File Matching

### ISSUE THREAD

**Issue by mathiasgrimm** [Seldaek/monolog#753]
I had a problem, not sure if that is documented and expected but I had problems when using files starting with the same name.

I use Laravel which create files in the format laravel-2016-03-24.log and I also have one laravel package which uses laravel-log-keeper-2016-03-24.log

This is deleting some unexpected files.

I changed this and it worked...

```php
// Monolog/Handler/RotatingFileHandler.php

protected function getGlobPattern()
    {
        $fileInfo = pathinfo($this->filename);

        $glob = str_replace(
            array('{filename}', '{date}'),
            array($fileInfo['filename'], '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'), // changed here from * to this pattern
            $fileInfo['dirname'] . '/' . $this->filenameFormat
        );
        if (!empty($fileInfo['extension'])) {
            $glob .= '.'.$fileInfo['extension'];
        }

        return $glob;
    }
```

this way only files with the prefix will be rotated

Is this correct?
I can submit a PR if that is case

**Comment by Seldaek** [comment]
Unfortunately no that won't work, it only works with the default dateFormat, but that's configurable via setFilenameFormat().
