### ISSUE TITLE
Pass in 'extra'

### ISSUE THREAD

**Issue by mbrevda** [Seldaek/monolog#754]
When passing around a message (i.e. logging it from somewhere other than where it occurred), the 'extra' data will not be populated correctly, even if using `IntrospectionProcessor`. Additionally, it would seem there is no way to set this extra data. Would it be feasible to allow the extra data to be passed in? Alternatively, would it make sense to pass a backtrace to `IntrospectionProcessor` (perhaps as part of the context) so that it can inspect from the proper point?

My use case is catching an exception in the Domain, but actually logging it in the infrastructure side of the code. I would like to specify the correct class/file/line/method.

**Comment by stof** [comment]
``extra`` is meant to be filled by processors, not by the caller of the logger (the context is there for callers).

**Comment by mbrevda** [comment]
In this case, the processor doesn't have enough information to make an
educated guess. How would you suggest argumenting it so that it know what
data to read?

**Comment by mbrevda** [comment]
For now I "fixed" this by adding the infrastructure classes to `$skipClassesPartials`. I'm just concerned about what happens if an exception is thrown in those classes, it would seem that the trace would be messed up.

**Comment by stof** [comment]
@mbrevda if you want to pass the file and line from the outside, put them in the context.

**Comment by mbrevda** [comment]
It would be nice if IntrospectionProcessor would respect that (I.e. look for a value in the context and set extra to that instead of lookt through a backtrace). For now though, I think there is enough to work with so km closing this issue.
