### ISSUE TITLE
PHP7 Raven Handler

### ISSUE THREAD

**Issue by bassrock** [Seldaek/monolog#759]
I just recently switched to PHP 7 and I began to notice that errors are no longer being sent to Sentry with the Raven Handler. Nothing in the Raven configuration changed, and I am able to log messages by hand with the Raven Client. 

Is the Monolog Raven Handler and PHP 7 known to work?

**Comment by Seldaek** [comment]
There isn't much code in https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php so if anything I'd guess it's the RavenPHP code but their test suite seems to pass on php7 so I don't know.. Best talk to them I think. Ping @dcramer @msabramo

**Comment by mitsuhiko** [comment]
We're seeing various reports that the monolog handler no longer sends stacktraces in laravel. I did some testing myself and I can't see anything passing in the stacktrace.  It now appears to be part of the message.

**Comment by mitsuhiko** [comment]
(That to the best of my knowledge is not an issue with PHP 7)

**Comment by Seldaek** [comment]
So it's not PHP7.. but it is laravel specific? As far as I can tell in https://github.com/Seldaek/monolog/blob/1.x/src/Monolog/Handler/RavenHandler.php#L184 we pass the exception object directly if it is given to us in a standard way (i.e. exception key in the record's context data, which follows PSR-3 standard). If it is only laravel it could be they changed the way they log exceptions to monolog? cc @taylorotwell

**Comment by antoniofrignani** [comment]
We have this exact problem on a Laravel 4 application running on php 5.6. The stack trace is passed to the raven client as expected, but it gets displayed as a full text log in the additional data section of the Sentry application. The Raven php sdk version is at 0.12, but the same (tested) issue arise with the latest 0.13

**Comment by Seldaek** [comment]
Anyone figured this one out? Sorry but it's a bit too involved for me to try and reproduce.

**Comment by cryode** [comment]
I'm fairly certain this is mostly on Sentry's end. See: https://github.com/getsentry/sentry-php/issues/312

**Comment by Seldaek** [comment]
#834 might be fixing this.. Let me know if it works with the latest `1.x-dev` installed.
