### ISSUE TITLE
[Tech debt] Distributed batch proccesing

### ISSUE THREAD

**Issue by ese** [Seldaek/monolog#760]
We have now huge tasks like occupation feeds running in batch at once, This means they need a big amount of RAM to store objects while are proccesing which can have impact in the server performance.
This also avoid the possibility of distribute the load across different servers.

The thing should be divide the task in individual jobs that they can be queued and have differents process (workers) that can consume its

**Comment by xabbuh** [comment]
Can you explain a bit how your problem is related to Monolog (which is a logging library)?

**Comment by ese** [comment]
oops sorry, I opened the issue in the wrong repository :(
