### ISSUE TITLE
Log object - normalization

### ISSUE THREAD

**Issue by slava-basko** [Seldaek/monolog#767]
Hi!

Create Logger with StreamHandler and NormalizerFormatter (i expect that object will be converted by calling jsonSerialize() from NormalizerFormatter::toJson() - json_encode())
Call $logger->log($object) and receive error.

The problem is here: https://github.com/Seldaek/monolog/commit/c1675c59d8dbf50e16fa776917030eb03efa6206#diff-dce565f403e044caa5e6a0d988339430

$record = array(
    'message' => (string) $message,
...

Cast to string before calling formatter - is this a normal behaviour?

If i remove cast to string all it ok. $record goes to NormalizerFormatter and transform to string.
Or maybe i don't understand something.

So, what should i do? Transform object to string myself and then call $logger->log($message)? If yes - what for NormalizerFormatter?

**Comment by Seldaek** [comment]
The message should be a string as per PSR-3. $context is an array that can contain any kind of metadata, and should be used for passing more complex types (which are then handled by the NormalizerFormatter in most cases yes).
