### ISSUE TITLE
Invalid assumption about date sorting in RotatingFileHandler

### ISSUE THREAD

**Issue by rpkamp** [Seldaek/monolog#771]
I was looking at the `RotatingFileHandler` and in lines 111-114 there is the following code:

```php
// Sorting the files by name to remove the older ones
usort($logFiles, function ($a, $b) {
    return strcmp($b, $a);
});
```

The problem with this code is that it makes the assumption that the chronological order of dates is the same as the lexicographical order of the textual representation of those dates, which is indeed the case for the default date format of the class, `Y-m-d`, but is certainly not true for all date formats.
For example here in the Netherlands the default date format is `m-d-Y`. Using that format and assuming we still have some files from the end of last month and some files from the beginning of this month, when rotating the class would keep the files from last month and throw away the files from this month, which is certainly not what you'd want.

Combining this with https://github.com/Seldaek/monolog/issues/753 (which is why I was looking at the file in the first place) it may be worth it to ask people if they actually use the class with a different date format than the default. If not, it would remove a lot of complexity from the class if `Y-m-d` could be set as a hard coded default.

Alternatively, if you don't want to force a default on people, they should be able to supply their own sorting algorithm for the lines given above so they can inject a sorting algorithm for their custom date format.
Inspecting the date format and generating a sorted specifically tailored for that sounds like a framework on its own :)

**Comment by stof** [comment]
The idea of making the format configurable was to allow rotating per month instead of rotating per day for instance. So removing the feature entirely may cause issues.

But I agree that we could provide a simpler feature for that rather than making the format configurable, which would simplify solving #753 too

**Comment by rpkamp** [comment]
Okay, so maybe we could solve it like so:

1) Stop exposing the dateFormat to the outside world (remove parameter from `setFilenameFormat` method), but instead introduce a "rotation strategy" that can be set to "days", "months" or "years", using class constants.

```
const ROTATE_DAYS = 'days';
const ROTATE_MONTHS = 'months';
const ROTATE_YEARS = 'years';
```

2) Add a method `setRotateStrategy` that allows one of the constants above and sets the internal $dateFormat according to the chosen strategy.

3, optional) Make $dateFormat private so people can't override it in subclasses and fall in the same traps described in this ticket.

How does that sound?

NB. The 'years' option is probably overkill

**Comment by rpkamp** [comment]
Come to think of it I think the naming `ROTATE_*` in my earlier comment is quite bad and would instead suggest an interface like

```
setFilenameFormat($filename, RotatingFileHandler::FILE_PER_DAY);
setFilenameFormat($filename, RotatingFileHandler::FILE_PER_MONTH);
setFilenameFormat($filename, RotatingFileHandler::FILE_PER_YEAR);
```

where
 - FILE_PER_DAY='Y-m-d'
 - FILE_PER_MONTH='Y-m'
 - FILE_PER_YEAR='Y'

So the class basically stays the same as it is right now, but the input for the `$dateFormat` parameter of the `setFilenameFormat` method is limited to just these three options, resolving this issue, and making it so that https://github.com/Seldaek/monolog/issues/753 can be solved easily as well because it just needs a dateFormat=>glob mapping for these three values.

**Comment by stof** [comment]
This looks good.
We can even keep accepting any format in 1.x but triggering a deprecation notice if it is not one of these patterns (and keeping the existing flawed logic rather than a glob in such case)

**Comment by rpkamp** [comment]
Okay. I'll see if I can create a PR tonight [CET].

**Comment by rpkamp** [comment]
Two PRs are open for this issue:

Deprecate in 1.x: https://github.com/Seldaek/monolog/pull/774
Remove in 2.x: https://github.com/Seldaek/monolog/pull/773

**Comment by eusonlito** [comment]
Previously to this change I had this rotate configuration:

```php
private static function getLogger($name, $buffer = 0)
{
    $handler = (new RotatingFileHandler(storage_path().'/logs/esignal/'.$name.'.log'));

    $handler->setFilenameFormat('{date}/{filename}', 'Y/m-d');
    $handler->setFormatter(new LineFormatter(self::$line."\n"));

    if ($buffer) {
        $handler = new BufferHandler($handler, $buffer, Logger::INFO, true, true);
    }

    return (new Logger($name))->pushHandler($handler);
}
```

I have a problem because on day change, last buffer stored is lost, but is not relevant.

Anyway I want this configuration because I need to create a year container to logs and avoid large contents on logs folder.

There are any way to do it again?

Thanks :)

**Comment by Seldaek** [comment]
I guess we could accept anything that has Ymd with optional separators in between. I'll reopen for now.

**Comment by eusonlito** [comment]
:+1:

**Comment by rpkamp** [comment]
@Seldaek I've created a PR that fixes this for 2.x: https://github.com/Seldaek/monolog/pull/821

If you like it I could write one for 1.x as well.
