### ISSUE TITLE
Add Parent Logger to Monolog

### ISSUE THREAD

**Issue by PhiloEpisteme** [Seldaek/monolog#778]
## Overview
I have put up an example how one might implement this in #777 

Developers may find parent loggers useful when a service wants to have a defined logging behavior across all of its parts; however, a developer may also want individual parts of this service to have some additional behavior. For example:

The service may have the following handlers, in order.
**_NonBubblingServiceEmergencyHandler, BubblingServiceInfoHandler_**

A class used by the service may want, in addition to the above, to use the following.
**_NonBubblingFooWarningHandler, BubblingFooDebugHandler_**

The desired behavior would be that all messages logged in Foo would be first processed by Foo's handlers, and then by the parents. So, for example.
```php
// In Foo.php
$this->logger->warn('Something strange happened');
```
The above code would be handled by the NonBubblingFooWarningHandler AND the BubblingServiceInfoHandler. A stack of handlers would cause this message to get blocked by the NonBubblingFooWarningHandler.

In this way, one can set up parent loggers which are used across a service to ensure that the entire service logs in an expected way without limiting developer control over where or how their classes (which make up the service) log.

### Code Example

```php
class Foo
{
    protected $logger;

    public function __construct(Logger $parent_logger = null){
        // We want our logger to always log to the injected logger
        // If we have a warning level log, lets do something special with it.
        $special_handler = new MySpecialHandler(Logger::WARN, false);
        // If we don't have a warning level log, lets do something boring.
        $boring_handler = new MyBoringHandler(Logger::DEBUG);

        $logger = new Logger(__CLASS__);
        $logger->setHandlers(array($special_handler, $boring_handler));

        // Lets always log to our parent logger
        $logger->setParent($parent_logger);
        $this->logger = $logger;
    }
}
```
We may use Foo in two difference areas of our code. 

routine_1.php
```php
$handler = new StreamHandler('/var/log/my_log.log');
$logger = new Logger('routine_1');
$logger->pushHandler($handler);

// No matter how Foo logs, I always want it to log to my stream handler from above.
$foo = new Foo($logger);
```
routine_2.php
```php
// Lets have most logs to to email
$email_handler = new SwiftMailHandler(
    $this->mailer,
    'my_message',
    Logger::INFO, 
    true); // bubble = true
// Lets have all Critical level logs to to HipChat instead of email.
$hip_chat_handler = new HipChatHandler(
    'my_token',
    'my_room',
    'Monolog',
    false,
    Logger::CRITICAL,
    false); // bubble = false
$logger = new Logger('routine_2');
$logger->pushHandler($email_handler);
$logger->pushHandler($hip_chat_handler);

// No matter how Foo logs, I need all my CRITICAL level logs to go to HipChat for routine_2
$foo = new Foo($logger);
```

### Unsuccessful Work Around
There are many cases where one could attempt to use a GroupHandler to combing several handlers together. Perhaps one might propose to write Foo as follows.

```php
// Foo.php

class Foo
{
    protected $logger;

    public function __construct(Logger $parent_logger = null){
        $handlers = array();
        // We want our logger to always log to the injected logger
        // If we have a warning level log, lets do something special with it.
        handlers[] = new MySpecialHandler(Logger::WARN, false);
        // If we don't have a warning level log, lets do something boring.
        handlers[] = new MyBoringHandler(Logger::DEBUG);
        $foo_group_handler = new GroupHandler($handlers);
        $handlers = array($foo_group_handler);

        if ($parent_logger !== null) {
            $group_handler = new GroupHandler($parent_logger->getHandlers());
            foreach (array_reverse($parent_logger->getProcessors) as $processors) {
                // We must add the processors as well.
                $group_handler->pushProcessor($processor);
            }
            $handlers[] = $group_handler;
        }

        $logger = new Logger(__CLASS__);
        $logger->setHandlers($handlers);
        $this->logger = $logger;
    }
}
```
The above code will unfortunately not achieve the desired result. If we issue the following message.
```php
// In Foo.php
$this->logger->warn('Something strange happened');
```
The above log will get handled by **ALL** of the loggers in Foo AND from the parent logger. This is because the GroupHandler **ignores handler bubble**.

I feel it is more difficult to determine the behavior of the above code and is more complicated than adding a parent logger.

### BC
Per the tests run against the PR linked here, this feature would not involve breaking Backward Compatibility.

**Comment by Seldaek** [comment]
I still don't really get the purpose I am sorry. Anyone else sees the point here? Any thoughts @stof? The way I see it this can easily be done by extending the Logger so if it doesn't have a wide appeal I'd rather it be done in a third party package providing this extended logger.
