### ISSUE TITLE
Is it possible to better format logs with "big" context arrays ?

### ISSUE THREAD

**Issue by bgaillard** [Seldaek/monolog#784]
Hi, for a very critical peace of code I have to output logs associated to "big" context arrays. 

Here is a sample. 
```php
$this->logger->info(
    'Sample log {ctxParam1} ... {ctxParam2} ...',
    [
        'ctxParam1' => "value1",
        'ctxParam2' => "value2",
        'ctxParam3' => "value3",
        'ctxParam4' => "value4",
        'ctxParam5' => "value5",
        'ctxParam6' => "value6",
    ]
```

The output is the following.
```
[2016-05-11 16:38:13] LoggerName.INFO: Sample log value1 ... value2 .... {"ctxParam1":"value1","ctxParam2":"value2","ctxParam3":"value3","ctxParam4":"value4","ctxParam5":"value5","ctxParam6":"value6"} []
```

So everything is displayed on a single line which is not really easy to read. Instead I would like to change the display to something like that.

```
[2016-05-11 16:38:13] LoggerName.INFO: Sample log value1 ... value2 .... 
{
    "ctxParam1" : "value1",
    "ctxParam2" : "value2",
    "ctxParam3" : "value3",
    "ctxParam4" : "value4",
    "ctxParam5" : "value5",
    "ctxParam6" : "value6"
}
```

Is it possible ? How can I do it ?

**Comment by Seldaek** [comment]
It's not possible by default, but you could implement your own formatter that extends the LineFormatter and replaces \n with real new lines for example. TBH we already have too many options on it I have to say so I am quite reluctant to add even more.
