### ISSUE TITLE
Add an HTML LineFormatter

### ISSUE THREAD

**Issue by Aerendir** [Seldaek/monolog#787]
I know there is an HTMLFormatter, but it uses tables that makes the logs very long. So I edited it and make it more slim.

You can find it here: https://github.com/Aerendir/MonologColorfulHtmlLineFormatter

It is really really simple.

My question: is it possible to add it to the formatter provided with the package?

How can I do this? Is a simple PR sufficient?

**Comment by Seldaek** [comment]
IMO it's ok to have it as a third party package like this. I added it to https://github.com/Seldaek/monolog/wiki/Third-Party-Packages#formatters
