### ISSUE TITLE
raven-php is DEPRECATED: Please switch to the sentry-php package.

### ISSUE THREAD

**Issue by ifduyue** [Seldaek/monolog#791]
According to https://github.com/getsentry/raven-php REAMDE, raven-php is DEPRECATED.

![c05064b9-56e0-4648-b5dc-86bdfca03046](https://cloud.githubusercontent.com/assets/568900/15284839/609ceade-1b86-11e6-80d3-c25a36b86a31.png)

Please consider switching to sentry-php https://github.com/getsentry/sentry-php

**Comment by xabbuh** [comment]
see #786

**Comment by ifduyue** [comment]
@xabbuh Sorry, searched issues but not PRs, going to close this.
