### ISSUE TITLE
RotatingFileHandler fails to call rotate() when used in a short-lived process

### ISSUE THREAD

**Issue by mberkowski** [Seldaek/monolog#794]
When integrating Monolog into a Drupal site on Apache/mod_php, we found that RotatingFileHandler fails to call `rotate()` in its GC routine.  New date-stamped logfiles are created, but old ones never disposed. This seems due to the fact that `RotatingFileHandler::$nextRotation` is initialized to tomorrow's date, and later compared less than the logged item's date stamp.

In a short-lived process like an HTTP request under mod_php the initialized `nextRotation` will always be greater than the logged item's timestamp preventing `RotatingFileHandler::close()` and consequently `RotatingFileHandler::rotate()` from being called when depending on this implicit call to `close()`.

In `RotatingFileHandlerTest::testRotation()`, an explicit call is made to `$handler->close()` causing the garbage collection to take place and test to pass.  An explicit call to `RotatingFileHandler::close()` is therefore a possible workaround.

https://github.com/Seldaek/monolog/blob/6d2cfa63c9d7c03abd1284c2c4e8a9b310cd5062/src/Monolog/Handler/RotatingFileHandler.php#L47-L53
```php
public function __construct($filename, $maxFiles = 0, $level = Logger::DEBUG, $bubble = true, $filePermission = null, $useLocking = false)
{
    $this->filename = $filename;
    $this->maxFiles = (int) $maxFiles;

    // nextRotation is always tomorrow's date
    $this->nextRotation = new \DateTime('tomorrow');
    $this->filenameFormat = '{filename}-{date}';
```

https://github.com/Seldaek/monolog/blob/6d2cfa63c9d7c03abd1284c2c4e8a9b310cd5062/src/Monolog/Handler/RotatingFileHandler.php#L100-L103

```php
// This condition is probably never true
if ($this->nextRotation < $record['datetime']) {
    $this->mustRotate = true;
    $this->close();
}
```

**Comment by Seldaek** [comment]
Normally all handler's close method is called by __destruct, so I am not sure why you don't get a rotation triggered?

**Comment by mberkowski** [comment]
Yes, I see that way up in `Monolog\Handler\Handler`. I wonder if an exception is being eaten. I did find that I could cause the test to fail if I commented out the explicit `close()`.
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/Handler.php#L42-L43

**Comment by mberkowski** [comment]
Yes, I see that way up in `Monolog\Handler\Handler::__destruct()`.  My guess is that since it's inside Drupal, any number of things could be interfering with normal shutdown & GC to prevent `__destruct()` executing. I find that if I comment out the explicit `close()` in the test but still explicitly `unset($handler)` the test passes because `__destruct()` cleans up. So Monolog is probably working as intended.

**Comment by Seldaek** [comment]
Yup I am pretty sure this works, but I'm quite curious to see what interferes with that in Drupal..

**Comment by mberkowski** [comment]
This turned out to be due to a strange set of local circumstances and a faulty directory ACL I might have discovered sooner had I noticed the base class `__destruct()` calling `close()`.  Apologies for the noise.

**Comment by attisan** [comment]
sorry for excavating this issue, but I'm experiencing a very similar behaviour with monolog and drupal 8 using RotatingFileHandler. Although `close()` gets called, `$this->mustRotate` is either `NULL` or `FALSE` for the same reasons as @mberkowski described.

As a result the check `if (true === $this->mustRotate) {` in `close()` gates off `$this->rotate();`.
