### ISSUE TITLE
Filename "0"

### ISSUE THREAD

**Issue by noplanman** [Seldaek/monolog#796]
When trying to log to a file called `0` I get the following:
`Fatal error: Uncaught exception 'LogicException' with message 'Missing stream url, the stream can not be opened. This may be caused by a premature call to close().'`

This happens because the string `"0"` is regarded as `false` here:
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L84

**Comment by Seldaek** [comment]
Curious why you'd call a log file '0' but anyway I'll push a fix as it's quite an easy one.
