### ISSUE TITLE
Logging Level for HandlerWrapper and GroupHandler

### ISSUE THREAD

**Issue by Bob4ever** [Seldaek/monolog#802]
Is it possible to add a logging level for the HandlerWrapper and/or the GroupHandler? And if not is there a special reason for this?

e.g.  
```php
$log = new Logger('name');
$fileHandler = new StreamHandler('path/to/your.log', Logger::DEBUG);
$log->pushHandler(new HandlerWrapper($fileHandler, Logger::WARNING));
```

**Comment by Seldaek** [comment]
What would that do? Those handlers are just proxying stuff so they shouldn't filter anything. There is a FilterHandler if you want to filter records by level before it reaches another handler.

**Comment by Bob4ever** [comment]
Ohhh ^^ Thank you. I just didn't seen it.
