### ISSUE TITLE
ErrorHandler: $this->uncaughtExceptionLevel is an array and causes subsequent errors

### ISSUE THREAD

**Issue by Aerendir** [Seldaek/monolog#803]
I'm using `ErrorHandler` to handle errors and it seems there is a problem at line 127:

https://github.com/Seldaek/monolog/blob/1.x/src/Monolog/ErrorHandler.php#L125-L138

The property `$this->uncaughtExceptionLevel` may happen is an `array` and this cause subsequent errors.

In fact, debugging the trace, also the method [`Logger::getLevelName()`](https://github.com/Seldaek/monolog/blob/1.x/src/Monolog/Logger.php#L461) produces a notice as there is an `array` to `string` conversion in the message of the throwing exception.

Here is a screenshot:

![screenshot 2016-06-03 13 41 53](https://cloud.githubusercontent.com/assets/1968622/15777673/78822f92-2991-11e6-9a62-a5c6b30008d8.png)

These are the messages I receive as errors:

<img width="1671" alt="schermata 2016-06-03 alle 13 49 47" src="https://cloud.githubusercontent.com/assets/1968622/15777755/10eefd46-2992-11e6-81c5-36f71ef707f6.png">

I think you need other information. This message is only to open the discussion and to understand which is the better way to proceed to solve the problem... In the meantime I'll disable the error handler...

**Comment by xabbuh** [comment]
This looks odd to me. How did you end up with `$uncaughtExceptionLevel` being an array? Can you show some example code to reproduce your issue?

**Comment by Seldaek** [comment]
If you call ErrorHandler::registerExceptionHandler (or register) and pass an array, there are no type checks in place so it might cause it to be in a corrupt state. That'd be on your side though. In monolog itself I don't see how it's possible without bad user input.

**Comment by Aerendir** [comment]
@Seldaek , I'm using this code to activate register the `ErrorHandler`:

    ErrorHandler::register($logger, [], [], LogLevel::DEBUG);

@xabbuh No, I cannot provide code as the error is the result of a lot of code and is impossible to me to provide some samples.

But the error comes from the [`OptionResolver` Symfony's Component](http://symfony.com/doc/current/components/options_resolver.html) with a code similar to this:

        $resolver = new OptionsResolver();

        // Set the mandatory options
        $resolver->setRequired([
            // Options to find the right Connector
            'debug',
            'param1',
            'param2',
            'param3',
            // 'arrayParam' // <-- This produced the error if not present
        ]);

        // Set allowed types and defaults
        $resolver->setAllowedTypes('debug', 'bool')
        $resolver->setAllowedTypes('param1', 'string');
        $resolver->setAllowedTypes('param2', 'string');
        $resolver->setAllowedTypes('param3', 'string');
        // $resolver->setAllowedTypes('arrayParam', 'array')
        //     ->setDefault('arrayParam', []);

        // ... HERE OTHER CODE TO CONFIG THE RESOLVER

        return $resolver->resolve($options);

Now, if i pass the `arrayParam` without setting it in the `OptionResovler` the error were produced. Once set in the `OptionResolver`, the error disappeared.

I hope this will help...

**Comment by Seldaek** [comment]
OK so if you look at the function signature:

```
     * @param  LoggerInterface $logger
     * @param  array|false     $errorLevelMap  an array of E_* constant to LogLevel::* constant mapping, or false to disable error handling
     * @param  int|false       $exceptionLevel a LogLevel::* constant, or false to disable exception handling
     * @param  int|false       $fatalLevel     a LogLevel::* constant, or false to disable fatal error handling
     * @return ErrorHandler
     */
    public static function register(LoggerInterface $logger, $errorLevelMap = array(), $exceptionLevel = null, $fatalLevel = null)
```

Logger, array, int, int. You pass it Logger, array, array, int. That's why it blows up with an array to string conversion.

Just fix it to be `ErrorHandler::register($logger, [], null, LogLevel::DEBUG);` if you want to use the default value.

**Comment by Aerendir** [comment]
-.-' Ooops, thank you and excuse me :)
