### ISSUE TITLE
SlackHandler is ignoring log level parameter

### ISSUE THREAD

**Issue by jaschweder** [Seldaek/monolog#806]
The SlackHandler is totally ignoring the log level parameter and forcing CRITICAL level

**Comment by Seldaek** [comment]
The way I see it in the code, it's not ignoring it, it just has a default of CRITICAL while many other handlers have a default of DEBUG. Not sure I see the problem here.

**Comment by jaschweder** [comment]
thanks for check, I'll see the problem here, because I set the log level to INFO and when I try call info() method, nothing happing :disappointed:
