### ISSUE TITLE
Throw exception in StreamHandler upon constructing, not writing

### ISSUE THREAD

**Issue by sbol-coolblue** [Seldaek/monolog#812]
Currently when using the StreamHandler with a non-writable file location, the exception indicating this is only thrown during the write() operation. During object construction the writability of the stream could already be verified, which would help in making logging a non-breaking aspect of the application. Making this a non-breaking issue currently requires us to wrap all writes in a Try-block.

**Comment by Seldaek** [comment]
The problem then is that we always open the stream even though in most cases the request won't need to if you only log errors. I'd rather not change that, but you could pass in a resource instead of a stream url by doing the fopen() yourself and that way you catch the failure at instantiation time.

**Comment by Seldaek** [comment]
Also alternatively note that you can use https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/WhatFailureGroupHandler.php to wrap all your handlers if you want to make sure logging never throws.
