### ISSUE TITLE
GroupHandler skips processors in handleBatch()

### ISSUE THREAD

**Issue by UlrichEckhardt** [Seldaek/monolog#814]
Problem: In GroupHandler, the processors added with pushProcessor() are not forwarded to the contained handlers, therefore processing must happen locally before forwarding records to the individual handlers. This works correctly in handle(), where first the processors are applied and then the handlers are invoked. In handleBatch(), this doesn't work though, because there, the records are directly forwarded to the individual handlers.

Solution: Remove the handleBatch() override in that class, the baseclass does the correct thing by repeatedly calling handle().

Improvement: Process the records locally to allow still using handleBatch() in the individual handlers.

Just wondering, is this even used? It seems strange to me that this never happened to anyone...

**Comment by Seldaek** [comment]
Processors aren't widely used I guess, or usually placed on the Logger instance or on specific handlers. Anyway should be an easy enough fix.
