### ISSUE TITLE
Is PHP 5.3 still supported?

### ISSUE THREAD

**Issue by daigo75** [Seldaek/monolog#830]
I was looking through the code, and I noticed that the Logger class uses the short array syntax. Example:

`public function __construct(string $name, array $handlers = [], array $processors = [], DateTimeZone $timezone = null)`

As far as I know, such syntanx is not supported in PHP 5.3, it was introduced in 5.4.

**Comment by stof** [comment]
@daigo75 in the 1.x branch, yes. the master branch is the development branch of Monolog 2.x, which requires PHP 7 (and the composer.json contains this info)

**Comment by daigo75** [comment]
You're right, I was looking at the master branch out of habit (in our internal workflow, the master branch is always the production one, while new versions have their own branch).

Good to know about the requirements in 2.0. Considering how "late adopter" is the PHP community, I reckon it will take a while before it will be possible to switch to PHP 7 (I can't believe how many hosts still run 5.2).
