### ISSUE TITLE
NormalizerFormatter fatal errors when logging generators

### ISSUE THREAD

**Issue by Odalrick** [Seldaek/monolog#838]
I kept getting "Fatal error: Cannot resume an already running generator in" when running some test code. I finally figured out that it was `NormalizerFormatter` choking on a `debug_backtrace()`. This made me realise that maybe logging the output of `debug_backtrace()` isn't the best thing.

However, I don't think logging a spent generator should crash horribly.

**Comment by Seldaek** [comment]
I don't quite get how to reproduce this, and thus can't even try to fix it.. most likely it's choking in this loop https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php#L150 but well, I'd need more details.

**Comment by Odalrick** [comment]
Sorry, I should have attatched a minimal example:

`<?php

$logger = new \Monolog\Logger('test');

function aGeneratorFunction() {
	yield 1;
	yield 2;
}

$gen = aGeneratorFunction();
foreach ($gen as $i) {
	// Consume generator...
}

// Crash because normalizer cant handle spent generators.
$logger->debug('Log a spent generator', ['gen' => $gen,]);
`
It's actually this loop that crashes: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php#L86 .

_My_ problem was that I was logging stuff that I shouldn't log, it would just have been nice if the logger didn't crash just because I did.

**Comment by Seldaek** [comment]
Thanks that helps a lot :)
