### ISSUE TITLE
Usage of warn and err methods

### ISSUE THREAD

**Issue by catalinux** [Seldaek/monolog#839]
This methods are not defined in LoggerInterface. Usage of these methods without notice makes it hard when you changer your logger to other LoggerInterface implementation.

Shouldn't we remove these methods?

**Comment by stof** [comment]
Well, in the master branch (which is the dev version of Monolog 2), they are already removed.
They cannot be removed in 1.x for BC reasons

**Comment by catalinux** [comment]
Ok. I did not notice that. Tx
