### ISSUE TITLE
SyslogUdpHandler priority format bug?

### ISSUE THREAD

**Issue by codeb2cc** [Seldaek/monolog#842]
```
    protected function makeCommonSyslogHeader($severity)
    {
        $priority = $severity + $this->facility;
        return "<$priority>1 ";
    }
```

Why there's a `1` after priority? RFC5424 defines:

```
HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                        SP APP-NAME SP PROCID SP MSGID
PRI             = "<" PRIVAL ">"
```

**Comment by Seldaek** [comment]
It's the version I believe. As per https://tools.ietf.org/html/rfc5424#section-6.2.2 - and https://tools.ietf.org/html/rfc5424#section-6.5 also shows this `<prio>1` scheme in examples, so it seems fine to me.
