### ISSUE TITLE
Unicode characters escaping in $context

### ISSUE THREAD

**Issue by mityukov** [Seldaek/monolog#845]
Hello from Russia,

I'm using pretty default setup of Monolog, here's the example:
```
    function getLogger()
    {
        if ( is_null($this->logger) ) {
            $this->logger = new Logger('amo_sms');
            $handler = new StreamHandler( $this->getLogFilename(), Logger::DEBUG);
            $this->logger->pushHandler( $handler );
        }

        return $this->logger;
    }

// ... client code:
$this->getLogger()->addDebug('Событие отправлено в AmoWorker', $ins_data);
```

The result it gives:

```
[2016-09-05 19:48:44] amo_sms.DEBUG: Событие отправлено в AmoWorker 
{"subdomain":"sampledomain","created":1473094124,"api_path":"/notes/set","request_body":"{\"request\":{\"notes\":{\"add\":[{\"element_id\":\"1111111111\",\"element_type\":2,\"note_type\":4,\"text\":\"\\n\\u0421\\u043e\\u043e\\u0431\\u0449\\u0435\\u043d\\u0438\\u0435 ... \"}]}}}","uid":"201636-1000098-103"}
```

As you can see, the `$message` part is unescaped and is readable. The `$context` part, however, is not as pretty (see after `\"text\":`). How can I make the `$context` readable as well? Maybe, there's already a formatter or processor for this?

**Comment by Seldaek** [comment]
If you are on php 5.4+ it should encode with JSON_UNESCAPED_UNICODE, which should avoid this sort of ugly output.

**Comment by mityukov** [comment]
I was getting this issue on PHP 5.6.5, actually..

**Comment by Seldaek** [comment]
Then we need more details to be able to reproduce and maybe fix it..

**Comment by ThomasLandauer** [comment]
Just encountered a similar issue, and in my case it was due to the `json` data type of the `context` column in the database.
