### ISSUE TITLE
Issue with MongoDb Formatter when using new MongoDb Driver

### ISSUE THREAD

**Issue by haridarshan** [Seldaek/monolog#847]
When using the current stable release of monolog for writting logs in MongoDb. It gets break at line 103 in MongoDbFormatter.php where its using older MongoDate class. So everytime when we update the libraries via composer I need to manually change the MongoDBFormatter.php. 

Kindly add support for both new and old MongoDb Driver classes. so it won't break for new and older classes. We're using this in our production server.

**Comment by moderndeveloperllc** [comment]
Can you please provide the versions of software you are using? PHP, monolog, MongoDB, mongo/mongodb extension, etc? 

The `master` branch is for PHP 7 and new `mongodb` driver. The old `MongoDate` class does not exist in the new `mongodb` extension and has been replaced by `MongoDB\BSON\UTCDateTime`. The 1.x branch is still compatible with the old `mongo` extension. There would be an issue if you are using the new `mongodb` extension, but have not moved to PHP 7 yet, but I don't see how any of the code would be working in that case as there is lots of PHP 7-specific code in `master`.

**Comment by haridarshan** [comment]
PHP 7.0.9
Monolog 1.21.0
MongoDb 3.2
mongodb php extension 1.1.7

I've noticed 1.x branch is not fully compatible with php 7, so is it possible to pre-release alpha or beta version with php 7 compatiblity. As currently we're using this in production server.

**Comment by moderndeveloperllc** [comment]
@haridarshan You should probably look into using the `master` branch. The `master` branch is designed for PHP 7 (Throwables, etc) and the new mongodb extension. @Seldaek is one of the best open source maintainers in regards to making sure that commits to the `master` branch do not break anything. That being said, as this is a production system I would test the latest build and then [tie your composer config to that commit ID](https://getcomposer.org/doc/04-schema.md#package-links) to avoid future BC-breaking issues.

**Comment by Seldaek** [comment]
Thanks for the vote of confidence, but do note that aspects of the API may and most likely *will* break still in master before we reach 2.0 stable :) So be very careful with updates if you want to use it.

**Comment by Seldaek** [comment]
Anyway regarding the initial issue here, yeah sorry but 1.x is not going to support the new Mongo PHP7 stuff, it's a pain to backport, but you can use monolog master for now, just beware that when updating it you might have breaking changes (at some point we are likely to change the constructor of most handlers, which will break application configuration). The rest should be fairly stable.
