### ISSUE TITLE
SlackHandler: do not send username and icon

### ISSUE THREAD

**Issue by greeny** [Seldaek/monolog#849]
Is there a way to use SlackHandler without sending username and icon? We have our bot configured in Slack administration and it is used by more services, so we want to remove duplicated username and icon definitions.

**Comment by Seldaek** [comment]
#846 should take care of this I believe.

**Comment by greeny** [comment]
Nice, thanks!

**Comment by Seldaek** [comment]
And btw I'm looking for slack users to give the new handlers in that PR a go, so if you have time and can try that branch and give feedback that'd be cool :)

**Comment by greeny** [comment]
Okay, I will do it later today :)
