### ISSUE TITLE
RollbarHandler: Critical message reduced to error when exception included

### ISSUE THREAD

**Issue by AlexStansfield** [Seldaek/monolog#852]
When there is an exception in the record context the RollbarHandler uses `RollbarNotifier:: report_exception` to log the error.

The problem is this doesn't pass on the level of the message to rollbar (there is no level argument on `report_exception`). The RollbarNotifier then sets it at a default level of `error`. 

This means no matter what level you log the exception at it will always show up as level `error` in rollbar.

Symfony's own ExceptionListener logs exceptions as `critical` when they are not instances of `HttpExceptionInterface` or have a status code great than or equal to 500.

A quick solution (I think) to this would be to add:

```
$payload['level'] = strtolower($record['level_name']);
```

prior to calling the `report_exception` method ([line 70](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RollbarHandler.php#L70))

**Comment by Seldaek** [comment]
So I looked into the RollbarHandler and found out that it was kinda suboptimal, so I did some tweaking in there and you should now get the level and some other stuff in the context data, no matter if logging an exception or a regular message. Let me know if it helps.
