### ISSUE TITLE
Monolog require-dev on elastica?

### ISSUE THREAD

**Issue by laszlof** [Seldaek/monolog#857]
Hello,

Is there a particular reason there is a require-dev on elastica? My understanding is that require-dev is used for development tools. Elastica perhaps belongs as a "suggest" as you have it, but I do not believe it should be a require-dev. This is causing issues with one of our packages currently.  (See composer issue: https://github.com/composer/composer/issues/5727)

Thanks.

**Comment by stof** [comment]
well, it is necessary to have elastica during development to run the testsuite fully. It probably *also* belongs to suggestions.

``require-dev`` is a root-only property. So it cannot cause any issue in your package. It is totally ignored anywhere else than when working on monolog itself.

**Comment by laszlof** [comment]
We commit our lock file, and the require-dev is for elastica is ending up in our root level composer.lock file.

**Comment by laszlof** [comment]
This appears to be an unrelated issue. Closing.

**Comment by nickel715** [comment]
@laszlof try `composer update --no-dev`
