### ISSUE TITLE
unsupported strict type

### ISSUE THREAD

**Issue by shorif2000** [Seldaek/monolog#859]
I am using php5.4 and i get following error

`Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/SP/oiadm/docroot/vendor/monolog/Logger.php on line 152`

**Comment by stof** [comment]
Use the 1.x version of Monolog. The master is the dev version of Monolog 2, which requires PHP 7+

**Comment by radiusplay** [comment]
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/SP/oiadm/docroot/vendor/monolog/Logger.php on line 152

**Comment by Seldaek** [comment]
@radiusplay Require monolog  `1.*` and not `2.*` if you are not running php7..
