### ISSUE TITLE
WhatFailureGroupHandler

### ISSUE THREAD

**Issue by sukki19** [Seldaek/monolog#860]
'WhatFailureGroupHandler' ignores the exception thrown by each child handler. Is there any way by which I can know what exceptions were ignored as I want to 'log' the ignored exceptions.?

**Comment by Seldaek** [comment]
This is not possible, but would be a good addition if you like to send a pull request. I think it could indeed store the exception, or even optionally log them but then you have to be careful to ignore further exceptions that occur while logging an exception, otherwise you are likely to end up in a recursion loop.

**Comment by sukki19** [comment]
Thanks for the reply.
Apart from this, how can i access the instance of logger class (that I created in my controller) in the 'WhatFailureGroupHandler' class.? Because if I am able to do that, then I can log all the exceptions that were ignored in my log file.

**Comment by Seldaek** [comment]
You can't access the logger from there no, you could pass it in the constructor, or allow passing a set of handlers that are "safer" and less likely to fail and should be used for logging handler failures?

**Comment by holtkamp** [comment]
Encountered this as well, the current implementation of the WhatFailureGroupHandler just discards exceptions, which could/will lead to serious puzzling when:

- users **are** reporting problems
- entries do **not** appear in logs typically used for investigation (like LogEntries)

Maybe an initial pragmatic approach would be to simply use [```error_log()```](http://php.net/manual/en/function.error-log.php) to at least inform the system of:

- the message that was attempted to be logged
- the caught exception (why did logging the message fail, for socket handlers useful information about connection timeouts, etc could help at pinpointing the source of problems...

just my 2 cents 😄

**Comment by Seldaek** [comment]
Closing as https://github.com/Seldaek/monolog/pull/1012 allows you to do more advanced error handling
