### ISSUE TITLE
Stupid question

### ISSUE THREAD

**Issue by XecuteFire** [Seldaek/monolog#862]
If I don't want to do:
```
require __DIR__ . '/../vendor/autoload.php';

use Monolog\Logger;
$logger = new Logger('my_logger');
```
And want to do:
```
require __DIR__ . '/../vendor/autoload.php';

$logger = new Monolog\Logger('my_logger');
```
Why doesn't it work?
` Fatal error: Uncaught Error: Class 'Logger' not found`

**Comment by Seldaek** [comment]
It should work, if you do `new \Monolog\Logger`, or `new Monolog\Logger` but then you need to be in the global namespace. Your second code block works fine for me..

**Comment by XecuteFire** [comment]
I know this should work, that's why I'm pulling my hair one by one since so many hours! :P 
Could it be my composer.json that is not set correctly?
```
{
    "require": {
        "monolog/monolog": "^1.21"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    }
}
```
When I look in composer/autoload_namespaces.php, the array is empty but when I look in composer/autoload_psr4, I have this:
`'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog')`

So technically, if I do `$log = new Monolog\Logger('APP');` it should work.

I'm really confused.

**Comment by stof** [comment]
@XecuteFire `` new Monolog\Logger('APP')`` works only if your file is in the global namespace. If your file has a namespace declared, this relative class name means you are trying to use `` new <current namespace>\Monolog\Logger('APP')``, which likely does not exist (the rule is not different for the global namespace, but applying this rule gives the right class)

This looks to me like a misunderstanding of how PHP namespaces are working

**Comment by XecuteFire** [comment]
@stof I admit that I am new with namespaces in PHP.

So if my structure goes like this:
```
app/
config/
    bootstrap.php
public/
    index.php
vendor/
composer.json
```
And that my front-controller `public/index.php` require `config/bootstrap.php`, and the bootstrap looks like this:
```
<?php
/*
 *---------------------------------------------------------------
 * COMPOSER AUTOLOADER
 *---------------------------------------------------------------
 */

    require __DIR__ . '/../vendor/autoload.php';

/*
 *---------------------------------------------------------------
 * APPLICATION LOGGER [MONOLOG/MONOLOG]
 *---------------------------------------------------------------
 */
    
    $log = new Monolog\Logger('APP');
    
    $log->pushHandler(new Monolog\Handler\StreamHandler(__DIR__ . '/../app/logs/app.log', Logger::DEBUG));
    $log->pushHandler(new Monolog\Handler\FirePHPHandler());
```

What should I do exactly to be able to call `$log = new Monolog\Logger('APP');` without the need of `use Monolog\Loger;`?
Even with `$log = new \Monolog\Logger('APP');`, I still get the `Fatal error: Uncaught Error: Class 'Logger' not found in D:\Documents\Documents\DaPHPCode.dev\config\bootstrap.php on line 16`

**Comment by XecuteFire** [comment]
I am so dumb, it's unbelievable.

Guys, the problem was a missing namespace on ` $log->pushHandler(new Monolog\Handler\StreamHandler(__DIR__ . '/../app/logs/app.log', Logger::DEBUG));` where `Logger::DEBUG` need to be `Monolog\Logger::DEBUG`

Problem solved, and a night wasted. :3
