### ISSUE TITLE
how to make a handler working in laravel ?

### ISSUE THREAD

**Issue by moeinrahimi** [Seldaek/monolog#863]
hi
i had written a custom handler and i want to use it in laravel, any idea how accomplish that ?
and also i want to make it as a package so other folks can use it

**Comment by stof** [comment]
Well, the way to make it work in laravel should be asked in the laravel community, not here, because it depends of how laravel lets you customize the logger they are configuring

**Comment by moeinrahimi** [comment]
oh ok, thank you for fast response.
