### ISSUE TITLE
<no message value> when logging to sentry

### ISSUE THREAD

**Issue by letr0n** [Seldaek/monolog#867]
I'm logging to sentry using monolog and I'm getting ```<no message value>``` in sentry when logging:

```php
$ravenClient = new Raven_Client('...');

$ravenHandler = new RavenHandler($ravenClient);

$ravenHandler->setFormatter(new LineFormatter("%message% %context% %extra%\n"));

$monolog->pushHandler($ravenHandler);
```

```php
$monolog->error($exception, ['exception' => $exception]);
```

I have no idea if the bug is in the monolog ```RavenHandler``` or the sentry ```Client``` class but it makes sentry logging useless.

Are the parameters passed to ```Client::captureException()```correct? ([RavenHandler.php#L185](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php#L185)
) Not easy to tell since the parameters are so poorly documented ([Client.php#L412](https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Client.php#L412)).

_Reference: getsentry/sentry-php#364_

**Comment by stof** [comment]
I cannot tell for the RavenHandler, but the argument you are passing to monolog are wrong. the first argument of ``->error()`` is a string

**Comment by letr0n** [comment]
Exceptions get casted to strings in ```Logger::addRecord()``` so it shouldn't make a difference. Changing it to this doesn't make a difference:

$monolog->error($exception->getMessage(), ['exception' => $exception]);

**Comment by letr0n** [comment]
Turns out we had forgotten to upgrade our Sentry install.
