### ISSUE TITLE
Buffer repeated messages

### ISSUE THREAD

**Issue by helix** [Seldaek/monolog#87]
It would be nice to have some kind of buffer which group same messages together with counting.

For example, on a production webserver, if the homepage generates an error, and the mail handler is being used. The operation team would receive as many emails as requests.

It should be nice to receive only 1 mail of the same error every N occurrences the error.

It is different from the BufferHandler because of the BufferHandler actually outputs every message log, even if they're identical, and this results in a HUGE mail, too much noise. I only need the relevant information once, not repeated N times.

**Comment by Seldaek** [comment]
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/DeduplicationHandler.php fixes it

**Comment by maraspin** [comment]
Thank you, @Seldaek
