### ISSUE TITLE
Laravel FirePHPHandler encoding problem

### ISSUE THREAD

**Issue by Sogl** [Seldaek/monolog#875]
Hello!

Monolog library is used in Laravel framework by default. I did settings to integrate it with FirePHP console.
Docs:
https://laravel.com/docs/5.3/errors#custom-monolog-configuration

Lines from my `bootstrap/app.php`:

``` php
//my monolog configuration
$app->configureMonologUsing(function($monolog) {
    $monolog->setHandlers([new \Monolog\Handler\FirePHPHandler()]);

   //this line also works
   //$monolog->pushHandler(new \Monolog\Handler\FirePHPHandler());
});
```

My `laravel.log` becomes clear with this code.

OK. Let's send something:

``` php
Log::info("Something");
```

Output:
![image](https://cloud.githubusercontent.com/assets/7556290/19714707/063013f0-9b9c-11e6-847f-0b5e2f441c63.png)

Works great.
But what happened if we put some Russian letters and other unicode symbols?

``` php
Log::info("Что-то");
Log::info("Odómetro");
```

Output:
![image](https://cloud.githubusercontent.com/assets/7556290/19714954/bafe3c16-9b9d-11e6-8369-e1c4a2f20ca5.png)

Something wrong. 

OK, disable our FirePHPHandler and refresh our page.
Output in `laravel.log`:

```
[2016-10-26 17:08:55] local.INFO: Что-то  
[2016-10-26 17:08:55] local.INFO: Odómetro  
```

Works as it should be.

What's wrong with FirePHPHandler?

Env:
Windows 7 x64
Firefox 49.0.2
Monolog 1.21.0

**Comment by Seldaek** [comment]
I would guess:

- either your page encoding is not set correctly (you should have a `Content-Type: text/html; charset=utf8` header)
- or you have the wrong encoding set in your php file calling Log::info
- or it's a bug in firebug.. 

The Firebug handler doesn't do anything special with the input so I am not sure what to say.

**Comment by Sogl** [comment]
>either your page encoding is not set correctly (you should have a Content-Type: text/html; charset=utf8 header)

I have HTML5 `<meta charset="UTF-8">`, also tried with `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`. 
`AddDefaultCharset UTF-8` in `.htacccess` to be sure :laughing: 

>or you have the wrong encoding set in your php file calling Log::info

Set correctly. UTF8 without BOM.

>or it's a bug in firebug..

Or in FirePHP. Issue created:
https://github.com/firephp/firephp/issues/16
