### ISSUE TITLE
fsockopen in SocketHandler/SlackHandler with proxy

### ISSUE THREAD

**Issue by mg-totemic** [Seldaek/monolog#877]
Hi,

Recently I wanted to implement the 'SlackHandler' to log critical error messages to Slack, however I've come across an issue as I'm behind a proxy.

There doesn't seem to be any way to configure this handler to use a proxy as it uses fsockopen and there's no way to pass it any options or anything.

Any advice/thoughts would be appreciated.

Thanks

**Comment by Seldaek** [comment]
That is indeed something we do not support, although it's an issue across the board really.. Should be considered for 2.0.

**Comment by lightswitch05** [comment]
libcurl supports proxy configurations via environment variables such as `https_proxy`. Full documentation: https://curl.haxx.se/libcurl/c/libcurl-env.html

The one catch is that `SlackHandler` does not use curl, but `SlackWebhookHandler` does.
