### ISSUE TITLE
LineFormatter throws TypeError when json_encode fails

### ISSUE THREAD

**Issue by Giuseppe-Mazzapica** [Seldaek/monolog#878]
When [`LineFormatter::convertToString()`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php#L139) is called with non scalar data, it ends up calling [`NormalizerFormatter::toJson()`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php#L187) with second param, `$ignoreErrors`,  [set to `true`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php#L149).

It means that `NormalizerFormatter::toJson()` does just [`return @$this->jsonEncode($data);`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php#L191) that on its turn calls [`json_encode`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/NormalizerFormatter.php#L209).

The issue here is that with some inputs `json_encode` returns `false` and so, up to the stack, in those cases `LineFormatter::convertToString()` return `false` as well.

This is causing a Monolog-based library I've written to log `TypeError` throwable caused by Monolog, because I was (reasonably, IMO) expecting `LineFormatter::convertToString()` to return a string.

This could just be solved changing 

```php
return $this->toJson($data, true);
```

to 

```php
return (string) $this->toJson($data, true);
```

in `LineFormatter::convertToString()`.

I'm glad to send a PR if you agree.

**Comment by Seldaek** [comment]
Thanks for the detailed report and indeed that sounds like a valid solution, I'll do it as it's such an easy change.
