### ISSUE TITLE
[Feature] MongoDBFormatter - Format Persistable objects?

### ISSUE THREAD

**Issue by moderndeveloperllc** [Seldaek/monolog#888]
@Seldaek I was wondering if you would be open to a PR that would modify `MongoDBHandler::write()` to accept either an array, or an object that utilizes the [`MongoDb\BSON\Persistable`](https://docs.mongodb.com/php-library/master/reference/bson/#persistable-classes) interface. Basically, it allows you to insert an object directly into `insertOne()` or `insert()` and let the driver handle the serialization of MongoDB-native objects. Inserting a `Persistable` object is particularly useful as deserialization is also handled when querying the logs.

It shouldn't be a BC break, but it would change the signature of `MongoDBHandler::write()` to be non type-hinted to be able to take something other than a `$record` array - which all other handlers use.

**Comment by Seldaek** [comment]
Are you (ab)using the monolog handler as a way to push random data into mongo though? Or why would write() be called with anything else than a log record array?

**Comment by moderndeveloperllc** [comment]
Sorry, I was misremembering the data flow. This is more of a Formatter proposal, not a Handler.

The idea is to insert the log event as a [`Persistable`-interfaced object](https://docs.mongodb.com/php-library/master/reference/bson/#persistable-classes) into MongoDB instead of a generic object. When retrieved, the results in the `Cursor` are automatically instantiated as that class instead of the generic `BSONDocument`. It would also allow for the record to be "massaged" in a more custom way before being inserted, or upon retrieval. This could either be an optional parameter on the existing formatter, or a new formatter.

Modify Existing Formatter:
```
public function __construct(int $maxNestingLevel = 3, bool $exceptionTraceAsString = true, string $persistableClass = null)
    {
        $this->maxNestingLevel = max($maxNestingLevel, 0);
        $this->exceptionTraceAsString = $exceptionTraceAsString;
        $this->persistableClass = $persistableClass;
        $this->isLegacyMongoExt = version_compare(phpversion('mongodb'), '1.1.9', '<=');
    }
    /**
     * {@inheritDoc}
     */
    public function format(array $record): array
    {
        if ($this->persistableClass){
            return new $this->persistableClass($record);
        }
        return $this->formatArray($record);
    }
```

New Formatter:
```
class MongoDBPersistableFormatter implements FormatterInterface
{
    private $persistableClass;

    public function __construct(string $persistableClass)
    {
        $this->persistableClass = $persistableClass;
    }
    /**
     * {@inheritDoc}
     */
    public function format(array $record): Persistable
    {
        return new $this->persistableClass($record);
    }
    /**
     * {@inheritDoc}
     */
    public function formatBatch(array $records): array
    {
        foreach ($records as $key => $record) {
            $records[$key] = $this->format($record);
        }
        return $records;
    }
}
```
