### ISSUE TITLE
Elastica vs Elasticsearch api?

### ISSUE THREAD

**Issue by rohdef** [Seldaek/monolog#901]
First of thanks for this logger, I am very grateful for having such a useful logger available to me :)

I'm wondering why Monolog is not using the [Elasticsearch php API](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/index.html) for the Elastic logger? In stead of a 3rd party API that may or may not be up to date and may or may not stay so.

Are there deeper reasons for the choice that I'm not aware of? If not may I suggest using the official API (e.g., as that was the logical search for me was actually that) to integrate with Elasticsearch?

No matter what I would suggest updating the documentation for the handler, for instance referring to the API to use :)

**Comment by Seldaek** [comment]
AFAIK Elastica has been the option of choice for a long time, and was started in 2010 while the official client only dates 2013.. That said at this point both might be equally good options. It probably would be possible to update the ElasticSearchHandler to accept either an Elastica client or one instance of the official one, if you are interested in using that one feel free to send a PR for that.

**Comment by akalongman** [comment]
@Seldaek PR is ready :smile:
