### ISSUE TITLE
Raven_Client#user_context() no longer accepts null as of 1.6.0

### ISSUE THREAD

**Issue by ianfp** [Seldaek/monolog#904]
[This change](https://github.com/getsentry/sentry-php/commit/8a5bff2caacd9eaf850b1d49159a1ff31e49bbac) in sentry-php 1.6.0 means that `Raven_Client#user_context()` no longer accepts `null` as the first argument. Passing `null` now generates a PHP Warning because the null value is passed to `array_merge()`.

I've filed the issue against sentry-php [here](https://github.com/getsentry/sentry-php/issues/388) because it's a backward-compatibility break, but perhaps we should consider only passing arrays to that method from now on. The problematic line in `RavenHander` is [here](https://github.com/Seldaek/monolog/blob/1.22.0/src/Monolog/Handler/RavenHandler.php#L190).

**Comment by Seldaek** [comment]
Been fixed in 1.6.1 of sentry I believe so closing this.
