### ISSUE TITLE
Recent versions of Raven/PHP cause error with RavenHandler

### ISSUE THREAD

**Issue by tremby** [Seldaek/monolog#905]
I posted something similar over at sentry-php at https://github.com/getsentry/sentry-php/issues/389.

I'm not sure whether this is a bug their end or yours, but `user_context` now [merges by default](https://github.com/getsentry/sentry-php/pull/387) since 1.6.0, which causes a problem when `$previousUserContext` has been set to `null` (which it gets, in the case of my app, from `$this->ravenClient->context->user` [here](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php#L170)).

It leads to a `array_merge(): Argument #2 is not an array` error when trying to replace the data later in the handler (https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php#L192).

Perhaps `$previousUserContext` could be `null` by default rather than `false`, and then tested against `null` rather than boolean to work around this? Or perhaps `false` could be passed for the `$merge` argument to `user_context` (but this is new in 1.6.0, so 1.6.0 would then need to be required). Or is this a sentry-php bug?

**Comment by dcramer** [comment]
Fixed in sentry/sentry 1.6.1

**Comment by tremby** [comment]
Thanks!
