### ISSUE TITLE
PHP Fatal error:  Allowed memory size error while try to use the logger in a loop

### ISSUE THREAD

**Issue by reypm** [Seldaek/monolog#907]
I have the following code to read the content of a CSV file and process it. The file has 1000 lines (rows). There is no duplicates so in this case `$line_of_text === $unique_rows`.

```
    $file_handle = fopen($new_path, 'r');

    while (($result = fgetcsv($file_handle)) !== false) {
        if (array(null) !== $result) { // ignore blank lines
            $line_of_text[] = $result;
        }
    }

    $unique_rows = array_unique($line_of_text, SORT_REGULAR);
    fclose($file_handle);

    try {
        $logger = new Logger('admin_console_charge_types_logger');
        $logger->pushHandler(new StreamHandler('/var/www/log', Logger::DEBUG));
    } catch (Exception $e) {
        $data['error'][] = $e->getMessage();
    }

   foreach ($unique_rows as $key => $row) {
       $array_key = $row[0].'-'.$row[2];
       ....
       $logger->addDebug('Procesing file: ', ['array_key' => $array_key]);
   }
```
I am trying to log the value of `$array_key` as shown above but I am ending with the following error:

> PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 139797905659824 bytes) in Unknown on line 0, referer: http://localhost/adminconsole-charge-types

Why? What's wrong here? The values for memory at php.ini are:

    memory_limit: 512M
    max_execution_time: 0

Important all this code is running inside a Docker container. Any ideas other than increase the memory limit?

**Comment by Seldaek** [comment]
This `tried to allocated 139797905659824` is usually due to a bug in opcache I think.. Try updating php to latest version to make sure. Anyway I doubt it's a monolog issue per se.

**Comment by reypm** [comment]
@Seldaek yeah, you're right was another issue on the code that I've fixed and Monolog started working, thx anyway
