### ISSUE TITLE
json formatter stringify

### ISSUE THREAD

**Issue by nikitadhiman** [Seldaek/monolog#910]
I would like my log to be recorded like this:

message{
a="something";
b="something else"
}
instead of:

message{a="something";b="something else"}

Hence, I am not able to use Stringify property unlike JSON.stringify in json formatter

**Comment by Seldaek** [comment]
That's not supported right now, but you can build your own formatter, or use a more rich output format and something else to import/view the logs, because text files are not really the easiest way to see rich log data.
