### ISSUE TITLE
RotatingFileHandler - nextRotation

### ISSUE THREAD

**Issue by mmucklo** [Seldaek/monolog#921]
Does it make sense that nextRotation is stays set to 'tomorrow' (and gets reset as such) in RotatingFileHandler even if the dateFormat changes to FILE_PER_YEAR or FILE_PER_MONTH?

**Comment by Seldaek** [comment]
It probably could be optimized to rotate only at 'next year' and 'next month' instead of 'tomorrow' yes.. then again checking once a day if we need to rotate isn't exactly CPU heavy.

**Comment by mmucklo** [comment]
So if someone chooses FILE_PER_YEAR, or FILE_PER_MONTH, should a rotation really get triggered daily?

Shouldn't it be triggered Monthly, or Yearly?

**Comment by Seldaek** [comment]
Well right now it rotates every day but it's going to rotate to the same file so it basically doesn't do anything except at end of month/year. I don't think it's a big bug, but it could be fixed to only rotate at the end of the month/year by changing the DateTime initialization value for the next rotation.

**Comment by mmucklo** [comment]
Ok.

It would also be nice to be able to specify a FILE_PER_HOUR for exceptionally busy sites, for example - so you can see where I'm going with this (although that request could be a separately filed issue if you want)...

**Comment by Seldaek** [comment]
Closing as this doesn't seem that important and hasn't drawn any interest yet.
