### ISSUE TITLE
LineFormatter outputs \n instead of new line

### ISSUE THREAD

**Issue by j4m3s** [Seldaek/monolog#925]
Monolog v1.22.0 on php PHP 7.0.8-0ubuntu0.16.04.3

Not sure where I'm going wrong.  Even the simplest case of running the following in the `php -a` CLI interpreter:

```php
function throwException(\Monolog\Logger $logger)
{
    $e = new Exception("test exception");
    $logger->error("exception logged", [$e]);
}

$logger = new \Monolog\Logger("Default");
$handler = new \Monolog\Handler\StreamHandler("php://stdout", \Monolog\Logger::DEBUG);
$formatter = new \Monolog\Formatter\LineFormatter();
$formatter->includeStacktraces(true);
$handler->setFormatter($formatter);
$logger->pushHandler($handler);

throwException($logger);
```

outputs everything on one line as follows:
```
[2017-02-16 16:58:49] Default.ERROR: exception logged ["[object] (Exception(code: 0): test exception at php shell code:3)\n[stacktrace]\n#0 php shell code(1): throwException(Object(Monolog\\Logger))\n#1 {main}"] []
```

**Comment by j4m3s** [comment]
Hi @Seldaek thanks for the backport/fix but it doesn't seem to have resolved the problem.  

I'm now on the version the fix is tagged-against (1.22.1) (the below from composer.lock):
```
            "name": "monolog/monolog",
            "version": "1.22.1",
            "source": {
                "type": "git",
                "url": "https://github.com/Seldaek/monolog.git",
                "reference": "1e044bc4b34e91743943479f1be7a1d5eb93add0"
            },
```
but running the code in the ticket still outputs everything on the same line.

**Comment by Seldaek** [comment]
Ah yeah sorry I forgot to clarify here, but Really you shouldn't just pass `[$e]` as context info.. If you pass `['exception' => $e]` you follow PSR-3 standards, and a lot of handlers and stuff will work better, and it outputs a json object as opposed to a json array, in which case the fix kicks in and converts the new lines.

**Comment by j4m3s** [comment]
Ah excellent, thank you.  I haven't read the PSR-3 standards - I'll go and do that now :)

(and you're right, the code above works fine once I've updated as you suggest!).

**Comment by Seldaek** [comment]
PSR-3 doesn't do a whole lot, but standardizing the exception key is a good thing IMO, as it allows all the tooling to know where to expect exceptions, and generally speaking it's a good idea to "name" your context data to have more context as to how to read the context data.. :)

**Comment by j4m3s** [comment]
You're spot-on - and I do it for the others, just not Exceptions (I guess because the class names are normally suffixed Exception).  I got away with it using log4php because the PSR-3 wrapper checked each context arg to see if it was an instanceof Exception.  

For those finding this ticket, PSR-3 is indeed [very explicit](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#13-context):
> If an Exception object is passed in the context data, it MUST be in the 'exception' key.
