### ISSUE TITLE
LineFormatter class breaks with php 7.2 builds

### ISSUE THREAD

**Issue by nawarian** [Seldaek/monolog#927]
I've notice a [previous PR](https://github.com/Seldaek/monolog/pull/926) of mine, which has nothing to do with LineFormatter, is breaking at travis CI for PHP 7.2 -dev because of the signature of method `LineFormatter::format()`.

That's because LineFormatter extends NormalizerFormatter. And `LineFormatter::format()` returns a string, and `NormalizerFormatter::format()` aims to return an array. And still, `FormatterInterface::format()` doesn't specify any return type.

Probably PHP 7.2 has something breaking at this point, since php has never done method overloading, but overriding.

I'm curious about it because master branch is passing...

**Comment by stof** [comment]
``FormatterInterface::format()`` is meant to return a mixed value. If PHP 7.2 does not support this anymore, it is a major bug in PHP 7.2. Please report this to PHP instead.

**Comment by Seldaek** [comment]
Can't confirm if this is still the case as at the moment the nightly build segfaults when installing dependencies.. But yeah sounds like a bug in php either way so closing.
