### ISSUE TITLE
Does NormalizeFormatter->normalize() ever receive anything other than an array?

### ISSUE THREAD

**Issue by rosshettel** [Seldaek/monolog#944]
Trying to fix up our app's logging set up, and wanted to set up Exceptions to be formatted nicely in Slack. I'm having trouble understanding how to do so though.

So if I do `$log->error($e);`, the Exception gets cast to a string [here](https://github.com/Seldaek/monolog/blob/1e044bc4b34e91743943479f1be7a1d5eb93add0/src/Monolog/Logger.php#L323), which makes sense.

Or if I try `$log->error('Exception happened', $e);`, I get an error because context is expected to be an array [here](https://github.com/Seldaek/monolog/blob/1e044bc4b34e91743943479f1be7a1d5eb93add0/src/Monolog/Logger.php#L614).

But I noticed in NormalizerFormatter that it has a [special case to normalize an Exception](https://github.com/Seldaek/monolog/blob/1e044bc4b34e91743943479f1be7a1d5eb93add0/src/Monolog/Formatter/NormalizerFormatter.php#L92), which sounds great. But as far as I can tell and with my testing, it will only ever get passed an array - so how do I properly log an exception so that it does so?

**Comment by Seldaek** [comment]
Logging exceptions, as per [PSR-3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md), should be done as `$logger->error('Something something', ['exception' => $e]);`

Generally speaking, context information should be an array with meaningful keys and their associated data I would say.
