### ISSUE TITLE
SlackHandler drops the first 2048b of response into oblivion.

### ISSUE THREAD

**Issue by Craige** [Seldaek/monolog#945]
See here for details: https://github.com/Seldaek/monolog/commit/5085630fd606c50d9b09efa0f93c0bdd83603d24#L149

This works, but it limits the ability to extend this method. The child class has now lost the ability to read the response in it's entirety. 

Furthermore, it `write()` closes the socket connection so you can't easily get the response if you wanted to.

**Comment by Seldaek** [comment]
Added a method to ease extensibility. I hope that works for you.
