### ISSUE TITLE
Consider dedicated exception classes

### ISSUE THREAD

**Issue by SpacePossum** [Seldaek/monolog#951]
Hi!

I was wondering if you would welcome dedicated exception classes to be used in the handlers.
My case for it is that I listen for (uncaught) exceptions and try to figure out where to log those and than figure out what path to take based on the exception.
The case I think dedicated exceptions will help is for example when I try to log an exception to Slack but Slack cannot be reached for whatever reason. In this case the handler will throw a Spl exception `UnexpectedValueException` when trying to create the socket. In the error handler is hard to figure out that the exception originates from the handler, which is of use for me because I would like to take a diff. action (log to file and continue) on this exception than I normally would do (log to file, server error page with 500 status).

**Comment by Seldaek** [comment]
You can use the WhatFailureGroupHandler to gobble up any exception happening in handlers. If you have the group handler containing your SlackHandler followed by a StreamHandler then it will always log to the file and your app won't realize when Slack logging fails.

**Comment by SpacePossum** [comment]
Thanks for the details how to deal with this @Seldaek :)
I'll give it a try soon!
