### ISSUE TITLE
laravel hipchat

### ISSUE THREAD

**Issue by MKR-KANI** [Seldaek/monolog#952]
how to use monolog & HipchatHandler from laravel.?
Can we send message to the hipchat room..?

**Comment by martijncalker** [comment]
Settings up the (Laravel-) Monologger depends on your Laravel version. 

In the error documentation you can find a way of configuring the default Laravel Logger.
https://laravel.com/docs/5.4/errors#custom-monolog-configuration

```php
$app->configureMonologUsing(function ($monolog) {
    $monolog->pushHandler(
        new HipChatHandler(.....)
    );
});
```

**Comment by MKR-KANI** [comment]
Based on your suggestion, I configured in the app.php file. Now how can i use Log::error('testing') and send log error to hipchat by above code..?

**Comment by martijncalker** [comment]
Based on the [docs](https://laravel.com/docs/5.4/errors#logging) you can use the Log [Facade](https://laravel.com/docs/5.4/facades#facade-class-reference).

```php
use Illuminate\Support\Facades\Log;

Log::info('testing');
```

**Comment by MKR-KANI** [comment]
Thanks for your help.
Success...!!!

**Comment by MKR-KANI** [comment]
Can i maintain the log file and as well as hipchat configuration at the same time..?
If i put Log::info(); means, it is need to create a log file and put that message into hipchat room.
