### ISSUE TITLE
Error at line number -1

### ISSUE THREAD

**Issue by Sharatheywa** [Seldaek/monolog#959]
I'm using Laravel 5.4, I'm getting error logs, but showing line number is -1, like:

Fatal error: Class undefined: App\\Http\\Controllers\XXXX in XXXX/XXXXController.php on line -1

Hoping to get some help on this.
Thanks.

**Comment by Seldaek** [comment]
That has nothing to do with Monolog sorry but we're not a php helpdesk.. Seems like you are just using the wrong class name or something though.

**Comment by Sharatheywa** [comment]
Thanks for your valuable time.
