### ISSUE TITLE
Possible to use colours in the log?

### ISSUE THREAD

**Issue by HawkonDK** [Seldaek/monolog#964]
is it possible to use colours in the log? I have seen some use `"\033[41;30mblack on red\033[40;37m` but can't get that to work

**Comment by moderndeveloperllc** [comment]
That has more to do with what _reads_ the log than software like this that just _creates_ the log. Are you have problems with escaping characters perhaps? What is your Monolog pipeline? (Processors->Formatter->Handler) It's possible one of these is mishandling the `\033`.

**Comment by HawkonDK** [comment]
First of all I run on macOS and using the default build in console to read the `.log` file

```
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

// create a log channel
$log = new Logger('signup');
$log->pushHandler(new StreamHandler($app['app']."/logs/signup.html", Logger::DEBUG));
```

And then I use:
` $log->error('\033[41;30mblack on red\033[40;37m');`

**Comment by Seldaek** [comment]
If you want `\033` to be output properly you need single quotes like `$log->error("\033[41;30mblack on red\033[40;37m");`
