### ISSUE TITLE
SlackWebhookHandler - not sending logs

### ISSUE THREAD

**Issue by vertisan** [Seldaek/monolog#968]
Hi,
I want to implement loggin via Slack, so i do in **AppServiceProvider**:
```
    public function boot() {
        $monolog = Log::getMonolog();
        $slackHandler = new SlackWebhookHandler( 'https://hooks.slack.com/services/xxx/xxx/xxxxxxxxxxxxxxxxxxxx', '#general', 'Monolog', true, null, Logger::DEBUG );
        $monolog->pushHandler( $slackHandler );
    }
```
but I'm not getting messages (webhook URI is working) - why, where is a bad?

**Comment by martijncalker** [comment]
You're using Laravel, right? Than you need to configure the logger in the [bootstrap/app.php](https://laravel.com/docs/5.4/errors#custom-monolog-configuration).

**Comment by vertisan** [comment]
I added to this file:
```
$app->configureMonologUsing(function ($monolog) {
    $monolog->pushHandler( new Monolog\Handler\SlackWebhookHandler( 'https://hooks.slack.com/services/XXXX/XXXXX/XXXXXXXXX', '#general', 'Monolog', true, null, Monolog\Logger::DEBUG ) );
});
```
but still nothing

**Comment by martijncalker** [comment]
How do log inside your Laravel application? Via the [Log Facade](https://laravel.com/docs/5.4/errors#logging)?
