### ISSUE TITLE
LineFormatter::includeStacktraces overriding allowInlineLineBreaks

### ISSUE THREAD

**Issue by tbureck** [Seldaek/monolog#971]
Hey there,

so I'm using Monolog in my project and I'm configuring it using theorchard's Cascade library. As you might know it can configure options in two ways: constructor arguments and extra options handler. The `LineFormatter` for example gets its `allowInlineLineBreaks` option via constructor, while `includeStacktraces` is set via an optionHandler, calling `LineFormatter`'s `includeStacktraces` method.

In my case, I need the whole message to be on one line, because I'm parsing each line for a log viewer. This has worked fine until the most recent patch 1.22.1, in which the string `\n` is replaced with an actual new line character.

So, the actual problem is, that `allowInlineLineBreaks` is set in the very beginning, when the formatter is constructed. When the Cascade configurator calls `includeStacktraces()` later on, however, the option is overridden.

![monologlineformatter](https://cloud.githubusercontent.com/assets/755057/24951778/deccf72a-1f75-11e7-9aa1-e187ca8f483a.png)

I would much prefer `includeStacktraces()` to not change any other options than the actual `includeStacktraces` option and thus leave this decision to the developer.

Best regards

**Comment by Seldaek** [comment]
In this case you really should call `...->includeStacktraces(true);` then `...->allowInlineLineBreaks(false)`. Having stack traces in a single line is usually quite messy as it results in long lines so this is just monolog trying to have the right defaults..  Maybe this could be fixed in Cascade directly /cc @rantonmattei
