### ISSUE TITLE
Capture E_USER_DEPRECATED

### ISSUE THREAD

**Issue by hackzilla** [Seldaek/monolog#974]
I can see ```E_USER_DEPRECATED``` is mapped to notice level for logging.

but is there a way to extract only the ```E_USER_DEPRECATED``` messages, so that I can save them to ```deprecated.log```?

**Comment by Seldaek** [comment]
You can quite easily write your own error_handler that filters those and sends them to a logger.. the ErrorHandler we provide offers decent defaults but not a ton of customization, so it's ok to roll your own if needed.
