### ISSUE TITLE
Introduce new TransparentHandler

### ISSUE THREAD

**Issue by Wirone** [Seldaek/monolog#985]
I would like to propose creating new handler, draft name could be `TransparentHandler`. Its purpose would be handling all records without doing anything AND, as opposite to `NullHandler` DO NOT break the handlers loop in `Logger::addRecord()`, ever.

**Use case:**

We have handler for Logstash registered dynamically, based on parameters. If `gelf_hostname` is set, we register `GelfHandler`, otherwise we've been using `NullHandler`. Today I realized the latter breaks all other handlers since we add `NullHandler` with `ContainerBuilder::prependExtensionConfig()` - `NullHandler::handle()` returns `true` and it escapes `Logger::addRecord()` loop over handlers stack, so none other handler gets log messages.

It **is** possible to get it work as expected with `NullHandler` with very high `level` (so `handle()` always returns `false`), but this is not intuitive.

Do you agree it could be helpful to introduce easier to use handler for it? I can make PR for it, but if you are not willing to add it it would be pointless, so here's question first.

**Comment by Seldaek** [comment]
You can use an empty GroupHandler I think that will do exactly what you mean :)
