### ISSUE TITLE
How do I add other fields to records like user IP address or browser info while logging to Elasticsearch?

### ISSUE THREAD

**Issue by 2DCodeBlocks** [Seldaek/monolog#987]
I am using the ElasticsearchHandler with Elastica client to log user info to Elasticsearch. I can't seem to find a way to add more fields other than the ones automatically set by Monolog. How do I add custom fields to it?

**Comment by Seldaek** [comment]
According to ElasticaFormatter the Elastica\Document has setData called with the entire record, so if you add a monolog processor that adds the IP for example to the `$record['extra']['ip'] = ...` then it should be in there as far as I can tell.
