### ISSUE TITLE
ErrorHandler and script context

### ISSUE THREAD

**Issue by JamesAlday** [Seldaek/monolog#990]
We're using php-redis to connect to redis. It returns various errors (E_WARNING, E_USER_ERROR, etc). We want to track these, but only really need to know what servers are having issues and how often.

The solution we're using is to log these failures to InfluxDB so we can do a nice graph of error rates. I wrote a handler (too custom (ie, hacked together) for sharing just yet) for sending these errors to Influx, but since it's an extension library that sends them, I have to catch them through an error handler - so I opted to use Monolog\ErrorHandler instead of reinventing the wheel.

The problem is, I need to know context from the script (primarily redis server ip) for the data I'm logging.  Monolog\ErrorHandler ignores context in handleError (other than to pass it along).  I overrode ErrorHandler to write my own version that injects the context so that my InfluxDB handler can extract the stuff it needs.

The problem is ErrorHandler doesn't really like to be overridden, and that seems to be by design. But I basically have to make overridden copies of $logger, and the defaultErrorLevelMap() and codeToString() methods in order for it to work.  I think this is still better than rolling my own, since it'd basically be the same thing anyway, but...

Why is overriding ErrorHandler so verboten? Could those private things be protected to make them friendlier to custom error handlers? Or, could handleError have some option to send along more context data?

I've tried finding a way to do this without the ErrorHandler with various Processors and whatnot, but since this lib is directly throwing errors, I don't think there's a good way to inject that data without doing it this way.  But maybe I'm missing something obvious?

**Comment by Seldaek** [comment]
Why not add the context data using a processor? You could pass a custom Logger instance to the ErrorHandler that is fitted with extra processors for this purpose.
