### ISSUE TITLE
HandlerWrapper isHandling() does not match Logger call to method.

### ISSUE THREAD

**Issue by nesl247** [Seldaek/monolog#991]
In `Logger::addRecord()` (https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php#L285) it calls `HandlerInterface::isHandling()` with only the level, not the record. While `HandlerInterface` does state this is correct, which is unfortunate, `HandlerWrapper` seems to be oblivious to this.

See https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/HandlerWrapper.php#L21 in which it states you can make different checks against the record. Unfortunately, since it's only the level, `HandlerWrapper` seems pretty useless according to it's documentation. It looks like `handle()` needs to actually be overwritten in order to make that determination.

**Comment by Seldaek** [comment]
Soo... override handle then if you have to override handle? I mean I agree the example is a bit silly but it's just an example, the class can be used to override any method.
