### ISSUE TITLE
Swift_Mime_SimpleMessage class "setDate" method requires DateTimeInterface

### ISSUE THREAD

**Issue by bo-brainlabs** [Seldaek/monolog#992]
Trying to use the SwiftMailerHandler results in an error...
It's because the Swift Message class type checks the input to set date which is currently a timestamp.
Instead of a timestamp, it needs to be:
```php
->setDate(new DateTimeImmutable())
```

**Comment by Pierstoval** [comment]
It's a problem with Swiftmailer 6.0 compatibility, I proposed #1001 to fix this because #993 was not enough flexible with BC.

Hope this will be accepted & merged, because we're stuck using Swiftmailer 5 until a fix comes up in Monolog 😕

**Comment by Seldaek** [comment]
Fixed by #1001
