### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by jens1o** [Seldaek/monolog#994]
Hi,

first of all: Very useful lib, love it!

Personally, I would like an handler which pings me in the discord client.

When I'm doing a pr, what do I have to watch out?

Regards,
Jens

**Comment by Seldaek** [comment]
The best thing to do is to publish it as a standalone package and add it to https://github.com/seldaek/monolog/wiki/Third-Party-Packages IMO as I am trying to avoid adding too many new handlers into the core at this point..

**Comment by Seldaek** [comment]
Otherwise, not much to watch out for I think :) I can have a quick glance when you're done if you post it here..

**Comment by jens1o** [comment]
Okay, I'll take a look, but so far I didn't worked with their api.

**Comment by lefuturiste** [comment]
You can use this third party package: https://github.com/lefuturiste/monolog-discord-handler
